<?php

$sid = $_GET['sid'];
if ($sid == "UbrsEWkM0bAs")
{
    echo "\n"; 
    echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n"; 
    echo "<html><head>\n"; 
    echo "<title>WiMAX Mobile Station</title>\n"; 
    echo "<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
    echo "<script type=\"text/javascript\" src=\"jquery-1.3.2.min.js\"></script>\n"; 
    echo "<script type=\"text/javascript\" src=\"top.js\"></script>\n"; 
    echo "\n"; 
    echo "<script type=\"text/javascript\">\n"; 
    echo "<!--\n"; 
    echo "\n"; 
    echo "function init()\n"; 
    echo "{\n"; 
    echo "	var page = GetCookie('page');\n"; 
    echo "	if(page == \"login.php\")\n"; 
    echo "		top.location.href = page;\n"; 
    echo "	else\n"; 
    echo "	{\n"; 
    echo "		var IE6value = document.getElementById(\"ie6\").value;\n"; 
    echo "		if (IE6value == \"1\") ie6flag = true;\n"; 
    echo "\n"; 
    echo "		init_top_obj();\n"; 
    echo "		ajax_get_sub_menu_list((page != null && page != \"\")?page:\"status_wimax.php\");\n"; 
    echo "	}\n"; 
    echo "	setInterval('ajax_get_ether_signals()',2000);\n"; 
    echo "}\n"; 
    echo "//-->\n"; 
    echo "</script>\n"; 
    echo "</head>\n"; 
    echo "\n"; 
    echo "<body onload=\"init();\">\n"; 
    echo "<img src=\"sub_menu.png\" style=\"display:none;\">\n"; 
    echo "<img src=\"sub_menu2.png\" style=\"display:none;\">\n"; 
    echo "<img src=\"progress.png\" style=\"display:none;\">\n"; 
    echo "\n"; 
    echo "<input id=\"ie6\" value=\"0\" type=\"hidden\">\n"; 
    echo "<div id=\"top_div\" class=\"top_div\">\n"; 
    echo "<table class=\"main_tbl\">\n"; 
    echo "<tbody><tr><td height=\"37\"></td></tr>\n"; 
    echo "<tr><td height=\"110\">\n"; 
    echo "	<!--<div  style=\"margin-left:150px;margin-top:75px;></div>//-->\n"; 
    echo "	<table style=\"margin-left:152px;margin-top:75px;width:630px;height:30px\">\n"; 
    echo "		<tbody><tr>\n"; 
    echo "			<td style=\"background-image: url(&quot;main_menu2.png&quot;); cursor: default; font-weight: bold; font-style: oblique;\" id=\"main_menu_0\" class=\"main_menu\" width=\"126\">Status</td>\n"; 
    echo "			<td style=\"background-image: url(&quot;main_menu.png&quot;); cursor: pointer; font-weight: normal; font-style: normal;\" id=\"main_menu_1\" class=\"main_menu\" width=\"126\">Personalization</td>\n"; 
    echo "\n"; 
    echo "			<td style=\"background-image: url(&quot;main_menu.png&quot;); cursor: pointer; font-weight: normal; font-style: normal;\" id=\"main_menu_2\" class=\"main_menu\" width=\"126\">WiMAX</td>\n"; 
    echo "			<td style=\"background-image: url(&quot;main_menu.png&quot;); cursor: pointer; font-weight: normal; font-style: normal;\" id=\"main_menu_3\" class=\"main_menu\" width=\"126\">Networking</td>\n"; 
    echo "\n"; 
    echo "			<td style=\"background-image: url(&quot;main_menu.png&quot;); cursor: pointer; font-style: normal;\" id=\"main_menu_4\" class=\"main_menu\" width=\"126\">Management</td>\n"; 
    echo "			<td id=\"main_menu_Engineering\" class=\"main_menu\" style=\"visibility:hidden;\" height=\"33%\"></td>\n"; 
    echo "		</tr>\n"; 
    echo "	</tbody></table>\n"; 
    echo "</td></tr>\n"; 
    echo "<tr><td style=\"background-image:url('bgL.png');background-repeat:no-repeat;\" height=\"426\">\n"; 
    echo "	<div id=\"subMenu_div\" style=\"position:relative;\"><div style=\"top: 70px; z-index: 600;\" class=\"s_menu\" id=\"div_sMenu_img_status_wimax.php\"><img id=\"img_text_1\" src=\"sub_menu2.png\"></div><div style=\"top: 67px;\" class=\"s_text\" id=\"div_sMenu_text_status_wimax.php\"><table style=\"color: rgb(0, 0, 0); cursor: default;\" onclick=\"if(loading == 1) return;change_page(&quot;status_wimax.php&quot;)\" onmouseover=\"change_focus_over(&quot;div_sMenu_img_status_wimax.php&quot;)\" onmouseout=\"change_focus_out()\" height=\"30px\" width=\"120px\"><tbody><tr><td>WiMAX Status</td></tr></tbody></table></div><div style=\"top: 104px; z-index: 498;\" class=\"s_menu\" id=\"div_sMenu_img_status_networking.php\"><img id=\"img_text_3\" src=\"sub_menu.png\"></div><div style=\"top: 101px;\" class=\"s_text\" id=\"div_sMenu_text_status_networking.php\"><table style=\"color: rgb(255, 255, 255); cursor: pointer;\" onclick=\"if(loading == 1) return;change_page(&quot;status_networking.php&quot;)\" onmouseover=\"change_focus_over(&quot;div_sMenu_img_status_networking.php&quot;)\" onmouseout=\"change_focus_out()\" height=\"30px\" width=\"120px\"><tbody><tr><td>Network Status</td></tr></tbody></table></div><div style=\"top: 138px; z-index: 497;\" class=\"s_menu\" id=\"div_sMenu_img_status_device.php\"><img id=\"img_text_5\" src=\"sub_menu.png\"></div><div style=\"top: 135px;\" class=\"s_text\" id=\"div_sMenu_text_status_device.php\"><table style=\"color: rgb(255, 255, 255); cursor: pointer;\" onclick=\"if(loading == 1) return;change_page(&quot;status_device.php&quot;)\" onmouseover=\"change_focus_over(&quot;div_sMenu_img_status_device.php&quot;)\" onmouseout=\"change_focus_out()\" height=\"30px\" width=\"120px\"><tbody><tr><td>Device Status</td></tr></tbody></table></div><div style=\"top: 172px; z-index: 496;\" class=\"s_menu\" id=\"div_sMenu_img_status_voip.php\"><img id=\"img_text_7\" src=\"sub_menu.png\"></div><div style=\"top: 169px;\" class=\"s_text\" id=\"div_sMenu_text_status_voip.php\"><table style=\"color: rgb(255, 255, 255); cursor: pointer;\" onclick=\"if(loading == 1) return;change_page(&quot;status_voip.php&quot;)\" onmouseover=\"change_focus_over(&quot;div_sMenu_img_status_voip.php&quot;)\" onmouseout=\"change_focus_out()\" height=\"30px\" width=\"120px\"><tbody><tr><td>VoIP</td></tr></tbody></table></div></div>\n"; 
    echo "	<div style=\"margin-left:140px\"><iframe id=\"main_frame\" src=\"\" frameborder=\"0\" height=\"426px\" scrolling=\"no\" width=\"640px\"></iframe></div>\n"; 
    echo "</td></tr>\n"; 
    echo "</tbody></table>\n"; 
    echo "<div class=\"version\" id=\"version\" align=\"right\">Firmware version:<br>v2.8.8.1-g1.4.2-gp</div><div class=\"sp\"><img src=\"Logo2.png\"></div><div class=\"cpe\"><img src=\"cpe_IDU.png\"></div><div style=\"width: 0px;\" class=\"signals\" id=\"DIV_SIGNAL\"><img src=\"signal.png\"></div><div style=\"z-index: -1;\" class=\"check\" id=\"DIV_CHECK\"><img src=\"check.png\"></div><div style=\"z-index: 1000;\" class=\"check\" id=\"DIV_UNCHECK\"><img src=\"uncheck.png\"></div><div style=\"z-index: -1;\" class=\"ethercheck\" id=\"DIV_EtherCHECK\"><img src=\"ether_check.png\"></div><div style=\"z-index: -1;\" class=\"ethersignal\" id=\"DIV_EtherSIGNAL\"><img src=\"ether_signal.png\"></div><div style=\"position: absolute; margin-left: 661px; top: 42px;\" id=\"DIV_LOGOUT\"><img src=\"logout.png\" title=\"Logout\" onclick=\"top.window.location.replace(&quot;login.php&quot;)\" onmouseover=\"fFCP(this);this.src='logout2.png'\" onmouseout=\"fFCD(this);this.src='logout.png'\"></div><div style=\"position: absolute; margin-left: 710px; top: 42px;\" id=\"DIV_REBOOT\"><img src=\"reboot.png\" title=\"Reboot\" onclick=\"dialog(&quot;Reboot?&quot;, &quot;Reboot()&quot;)\" onmouseover=\"fFCP(this);this.src='reboot2.png'\" onmouseout=\"fFCD(this);this.src='reboot.png'\"></div><div class=\"buttonbg\" id=\"DIV_BUTTONBG\"><img src=\"buttonbackground_5.png\"></div></div>\n"; 
    echo "\n"; 
    echo "\n"; 
    echo "\n"; 
    echo "</body><!--[if lte IE 6]>\n"; 
    echo "<script type=\"text/javascript\">\n"; 
    echo "	document.getElementById(\"ie6\").value = 1; \n"; 
    echo "</script>\n"; 
    echo "<![endif]--></html>\n";
}
else
{
    echo "\n"; 
    echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n"; 
    echo "<html>\n"; 
    echo "<head>\n"; 
    echo "<title></title>\n"; 
    echo "<link type=\"text/css\" rel=\"stylesheet\" href=\"style.css\">\n"; 
    echo "\n"; 
    echo "<!-- Include AJAX Framework -->\n"; 
    echo "<script src=\"ajax/ajax_framework.js\" language=\"javascript\"></script>\n"; 
    echo "\n"; 
    echo "<script type=\"text/javascript\">\n"; 
    echo "<!--\n"; 
    echo "function init()\n"; 
    echo "{\n"; 
    echo "	document.cookie = \"page=;path=/\";\n"; 
    echo "}\n"; 
    echo "function fFOB(o)\n"; 
    echo "{\n"; 
    echo "        o.style.fontStyle = 'oblique';\n"; 
    echo "        o.style.fontWeight = 'bolder';\n"; 
    echo "}\n"; 
    echo "\n"; 
    echo "function fFNN(o)\n"; 
    echo "{\n"; 
    echo "        o.style.fontStyle = 'normal';\n"; 
    echo "        o.style.fontWeight = 'normal';\n"; 
    echo "}\n"; 
    echo "\n"; 
    echo "function fFNB(o)\n"; 
    echo "{\n"; 
    echo "	o.style.fontStyle = 'normal';\n"; 
    echo "	o.style.fontWeight = 'bolder';\n"; 
    echo "}\n"; 
    echo "//-->\n"; 
    echo "</script>\n"; 
    echo "</head>\n"; 
    echo "\n"; 
    echo "<body onload=\"init()\" style=\"font-size:12pt\">\n"; 
    echo "<div id=\"img_bg\" style=\"background-image: url('login.png');background-repeat:no-repeat;margin-right:auto;margin-left:auto;width:780px;height:585px;\">\n"; 
    echo "<div style=\"position:absolute;width:54px;height:20px;top:468px;margin-left:551px;cursor:pointer;color:#FFFFFF;\" onmouseover=\"fFOB(this)\" onmouseout=\"fFNN(this)\" onclick=\"document.forms[0].submit();\">Login</div>\n"; 
    echo "<div style=\"position:absolute;width:54px;height:20px;top:468px;margin-left:654px;cursor:pointer;color:#FFFFFF;\" onmouseover=\"fFOB(this)\" onmouseout=\"fFNN(this)\" onclick=\"document.forms[0].reset();\">Reset</div>\n"; 
    echo "\n"; 
    echo "<!-- Show Message for AJAX response -->\n"; 
    echo "<div id=\"login_response\"></div>\n"; 
    echo "\n"; 
    echo "<div>\n"; 
    echo "<table>\n"; 
    echo "	<tr><td>\n"; 
    echo "		<!--<form method=\"post\" action=\"ajax.php?action=login\">-->\n"; 
    echo "		<form action=\"javascript:login()\" method=\"post\">\n"; 
    echo "			<div style=\"position:absolute;top:-1500px;\"><input type=\"submit\" value=\"sub\"></div>\n"; 
    echo "			<input id=\"UI_ADMIN_USERNAME\" size=\"22\" maxlength=\"31\" style=\"background:Transparent;border:none;position:absolute;top:381px;margin-left:540px;\"><br><br>\n"; 
    echo "			<input type=\"password\" id=\"UI_ADMIN_PASSWORD\" size=\"22\" maxlength=\"31\" style=\"background:Transparent;border:none;position:absolute;top:426px;margin-left:540px;\">\n"; 
    echo "		</form>\n"; 
    echo "	</td></tr>\n"; 
    echo "</table>\n"; 
    echo "</div>\n"; 
    echo "</div>\n"; 
    echo "</body>\n"; 
    echo "<!--[if lte IE 6]>\n"; 
    echo "<script type=\"text/javascript\">\n"; 
    echo "	document.getElementById(\"img_bg\").style.backgroundImage=\"url('blank.gif')\";\n"; 
    echo "	document.getElementById(\"img_bg\").style.filter=\"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='login.png',sizingMethod='crop')\";\n"; 
    echo "	document.getElementById(\"img_bg\").style.zIndex=-1;\n"; 
    echo "</script>	\n"; 
    echo "<![endif]-->\n"; 
    echo "</html>\n"; 
    echo "\n";
}
?>