<?php
echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "<title></title>\n"; 
echo "<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "<script type=\"text/javascript\" src=\"comm.js\"></script>\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "<!--\n"; 
echo "\n"; 
echo "function Validate (passForm) {\n"; 
echo "	return true;\n"; 
echo "}\n"; 
echo "\n"; 
echo "function InitDisplay()\n"; 
echo "{\n"; 
echo "	tr_display(\"WebUpgrade\");\n"; 
echo "	InitValue(document.forms[0]);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function InitValue(passForm) {\n"; 
echo "	if(!pri_a(uitems[inner_url][\"WebUpgrade\"]))\n"; 
echo "	{\n"; 
echo "		passForm.file.disabled =  true;\n"; 
echo "		passForm.Browse.disabled = true;\n"; 
echo "		passForm.Web_Upgrade_button.disabled = true;\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	top.loading = 0;\n"; 
echo "	setInterval('ajax_get_signals()',2000);\n"; 
echo "}\n"; 
echo "//-->\n"; 
echo "\n"; 
echo "</script>\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body onload=\"init_obj();InitDisplay();\">\n"; 
echo "<div id=\"main_div\">\n"; 
echo "	<div id=\"container\">\n"; 
echo "		<form method=\"POST\" enctype=\"multipart/form-data\" action=\"ajax.php?action=manage_upgrade\">\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>Web Upgrade</legend>\n"; 
echo "				<input type=\"hidden\" name=\"web_upgrade\" value=\"1\">\n"; 
echo "				<table>\n"; 
echo "					<tr id=\"TR_WebUpgrade\" style=\"display:none;\"><td>Firmware image file</td><td>\n"; 
echo "						<span><input type=\"file\" name=\"file\" size=\"30\" onChange=\"this.form.vfile.value=this.value;\" style=\"position:relative; top:11px; left:7px; opacity:0; filter:alpha(opacity=0); -moz-opacity:0; z-index: 90;\"></span><br/>\n"; 
echo "						<input type=\"text\" name=\"vfile\" size=\"30\" readOnly=\"true\" style=\"position:relative; top:-12px; z-index:91;\">\n"; 
echo "						<input type=\"button\" name=\"Browse\" value=\"Browse...\" style=\"position:relative; top:-12px; width:60px;\" onClick=\"this.form.upgrade_file_name.click();\">\n"; 
echo "						<input type=\"submit\" value=\"Upload\" name=\"Web_Upgrade_button\" onClick=\"return (this.form.file.value!='');\" style=\"position:relative; top:-12px; width:60px;\">\n"; 
echo "					</td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "		</form>\n"; 
echo "	</div>\n"; 
echo "</div>\n"; 
echo "</body>\n"; 
echo "</html>\n"; 
echo "\n";
?>