<?php
echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "<title></title>\n"; 
echo "<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "<script type=\"text/javascript\" src=\"comm.js\"></script>\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "<!--\n"; 
echo "var DM_ENABLE,DM_SERVER_URL,DM_SERVER_PORT,DM_SERVER_AUTH,DM_SERVER_ID,DM_SERVER_PW,\n"; 
echo "    DM_CLIENT_AUTH,DM_CLIENT_ID,DM_CLIENT_PW,DM_INTERVAL_ENABLE,DM_INTERVAL;\n"; 
echo "\n"; 
echo "function Validate (passForm) {\n"; 
echo "        passForm.sid.value = sid;\n"; 
echo "        passForm.submit();\n"; 
echo "}\n"; 
echo "\n"; 
echo "function InitDisplay(response)\n"; 
echo "{\n"; 
echo "        var token = response.split(\";\");\n"; 
echo "\n"; 
echo "        DM_ENABLE = token[0];\n"; 
echo "        DM_SERVER_URL = token[1];\n"; 
echo "        DM_SERVER_PORT = token[2];\n"; 
echo "        DM_SERVER_AUTH = token[3];\n"; 
echo "        DM_SERVER_ID = token[4];\n"; 
echo "        DM_SERVER_PW = token[5];\n"; 
echo "        DM_CLIENT_AUTH = token[6];\n"; 
echo "        DM_CLIENT_ID = token[7];\n"; 
echo "	DM_CLIENT_PW = token[8];\n"; 
echo "	DM_INTERVAL_ENABLE = token[9];\n"; 
echo "	DM_INTERVAL = token[10];\n"; 
echo "\n"; 
echo "\n"; 
echo "        tr_display(\"DM_ENABLE\");\n"; 
echo "        tr_display(\"DM_SERVER_URL\");\n"; 
echo "        tr_display(\"DM_SERVER_PORT\");\n"; 
echo "        tr_display(\"DM_SERVER_AUTH\");\n"; 
echo "        tr_display(\"DM_SERVER_ID\");\n"; 
echo "        tr_display(\"DM_SERVER_PW\");\n"; 
echo "        tr_display(\"DM_CLIENT_AUTH\");\n"; 
echo "        tr_display(\"DM_CLIENT_ID\");\n"; 
echo "        tr_display(\"DM_CLIENT_PW\");\n"; 
echo "        tr_display(\"DM_INTERVAL_ENABLE\");\n"; 
echo "	tr_display(\"DM_INTERVAL\");\n"; 
echo " \n"; 
echo "\n"; 
echo "        obj_readonly(\"DM_ENABLE\");\n"; 
echo "        obj_readonly(\"DM_SERVER_URL\");\n"; 
echo "        obj_readonly(\"DM_SERVER_PORT\");\n"; 
echo "        obj_readonly(\"DM_SERVER_AUTH\");\n"; 
echo "        obj_readonly(\"DM_SERVER_ID\");\n"; 
echo "        obj_readonly(\"DM_SERVER_PW\");\n"; 
echo "        obj_readonly(\"DM_CLIENT_AUTH\");\n"; 
echo "        obj_readonly(\"DM_CLIENT_ID\");\n"; 
echo "        obj_readonly(\"DM_CLIENT_PW\");\n"; 
echo "        obj_readonly(\"DM_INTERVAL_ENABLE\");\n"; 
echo "	obj_readonly(\"DM_INTERVAL\");\n"; 
echo "\n"; 
echo "        InitValue(document.forms[0]);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function InitValue(passForm) {\n"; 
echo "        passForm.DM_ENABLE.value = DM_ENABLE;\n"; 
echo "        passForm.DM_SERVER_URL.value = DM_SERVER_URL;\n"; 
echo "        passForm.DM_SERVER_PORT.value = DM_SERVER_PORT;\n"; 
echo "        passForm.DM_SERVER_AUTH.value = DM_SERVER_AUTH;\n"; 
echo "        passForm.DM_SERVER_ID.value = DM_SERVER_ID;\n"; 
echo "        passForm.DM_SERVER_PW.value = DM_SERVER_PW;\n"; 
echo "        passForm.DM_CLIENT_AUTH.value = DM_CLIENT_AUTH;\n"; 
echo "        passForm.DM_CLIENT_ID.value = DM_CLIENT_ID;\n"; 
echo "	passForm.DM_CLIENT_PW.value = DM_CLIENT_PW;\n"; 
echo "	passForm.DM_INTERVAL_ENABLE.value = DM_INTERVAL_ENABLE;\n"; 
echo "	passForm.DM_INTERVAL.value = DM_INTERVAL;\n"; 
echo "\n"; 
echo "        top.loading = 0;\n"; 
echo "        setInterval('ajax_get_signals()',2000);\n"; 
echo "}\n"; 
echo "\n"; 
echo "//-->\n"; 
echo "</script>\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body onload=\"init_obj();setTimeout('ajax_get_key()',500);\">\n"; 
echo "<div id=\"main_div\">\n"; 
echo "	<div id=\"container\">\n"; 
echo "		<form method=\"POST\" action=\"ajax.php?action=manage_omadm\">\n"; 
echo "			<input type=\"hidden\" name=\"sid\" id=\"sid\">\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>OMA-DM Configuration</legend>\n"; 
echo "				<table>\n"; 
echo "					<tr id=\"TR_DM_ENABLE\" style=\"display:none\"><td>OMA-DM Active Flag</td><td>\n"; 
echo "						<select id=\"DM_ENABLE\" name=\"DM_ENABLE\">\n"; 
echo "							<option value=\"0\">disable</option>\n"; 
echo "							<option value=\"1\">enable</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_DM_SERVER_URL\" style=\"display:none\"><td>Server URL</td><td>\n"; 
echo "						<input type=\"text\" id=\"DM_SERVER_URL\" name=\"DM_SERVER_URL\" size=\"24\" maxlength=\"256\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_DM_SERVER_PORT\" style=\"display:none\"><td>Server Port</td><td>\n"; 
echo "						<input type=\"text\" id=\"DM_SERVER_PORT\" name=\"DM_SERVER_PORT\" size=\"24\" maxlength=\"32\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_DM_SERVER_AUTH\" style=\"display:none\"><td>Server Auth Type</td><td>\n"; 
echo "						<select id=\"DM_SERVER_AUTH\" name=\"DM_SERVER_AUTH\">\n"; 
echo "							<option value=\"NONE\">NONE</option>\n"; 
echo "							<option value=\"BASIC\">BASIC</option>\n"; 
echo "							<option value=\"MD5\">MD5</option>\n"; 
echo "							<option value=\"HMAC\">HMAC</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_DM_SERVER_ID\" style=\"display:none\"><td>Server ID</td><td>\n"; 
echo "						<input type=\"text\" id=\"DM_SERVER_ID\" name=\"DM_SERVER_ID\" size=\"24\" maxlength=\"32\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_DM_SERVER_PW\" style=\"display:none\"><td>Server Password</td><td>\n"; 
echo "						<input type=\"password\" id =\"DM_SERVER_PW\" name=\"DM_SERVER_PW\" size=\"24\" maxlength=\"32\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_DM_CLIENT_AUTH\" style=\"display:none\"><td>Client Auth Type</td><td>\n"; 
echo "						<select id=\"DM_CLIENT_AUTH\" name=\"DM_CLIENT_AUTH\">\n"; 
echo "							<option value=\"NONE\">NONE</option>\n"; 
echo "							<option value=\"BASIC\">BASIC</option>\n"; 
echo "							<option value=\"MD5\">MD5</option>\n"; 
echo "							<option value=\"HMAC\">HMAC</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_DM_CLIENT_ID\" style=\"display:none\"><td>Client ID</td><td>\n"; 
echo "						<input type=\"text\" id=\"DM_CLIENT_ID\" name=\"DM_CLIENT_ID\" size=\"24\" maxlength=\"32\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_DM_CLIENT_PW\" style=\"display:none\"><td>Client Password</td><td>\n"; 
echo "						<input type=\"password\" id =\"DM_CLIENT_PW\" name=\"DM_CLIENT_PW\" size=\"24\" maxlength=\"32\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_DM_INTERVAL_ENABLE\" style=\"display:none\"><td>Periodical Client-initiated Enable</td><td>\n"; 
echo "						<select id=\"DM_INTERVAL_ENABLE\" name=\"DM_INTERVAL_ENABLE\">\n"; 
echo "							<option value=\"0\">disable</option>\n"; 
echo "							<option value=\"1\">enable</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_DM_INTERVAL\" style=\"display:none\"><td>Periodical Client-initiated Interval</td><td>\n"; 
echo "						<input type=\"text\" id=\"DM_INTERVAL\" name=\"DM_INTERVAL\" size=\"24\" maxlength=\"32\">\n"; 
echo "					</td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "		</form>\n"; 
echo "	</div>\n"; 
echo "	<div>\n"; 
echo "		<table style=\"width:600px;height:25px;text-align:center\">\n"; 
echo "			<tr>\n"; 
echo "				<td width=\"210\"></td>\n"; 
echo "				<td id=\"clear_btn\" class=\"td_btn\" onclick=\"location.reload()\">Undo</td>\n"; 
echo "				<td width=\"30\"></td>\n"; 
echo "				<td id=\"submit_btn\" class=\"td_btn\" onclick=\"Validate(document.forms[0])\">Apply</td>\n"; 
echo "				<td width=\"210\"></td>\n"; 
echo "			</tr>\n"; 
echo "		</table>\n"; 
echo "	</div>\n"; 
echo "</div>\n"; 
echo "</body>\n"; 
echo "</html>\n"; 
echo "\n";
?>