<?php
echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "<title></title>\n"; 
echo "<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "<script type=\"text/javascript\" src=\"comm.js\"></script>\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "<!--\n"; 
echo "var TR_ENABLE,TR_ACS_URL,TR_ACS_USER,TR_ACS_PASS,TR_INFORM_ENABLE,TR_INFORM_INTERVAL,TR_CR_USER,TR_CR_PASS;\n"; 
echo "\n"; 
echo "function Validate (passForm) {\n"; 
echo "	if(!CheckValue(passForm.TR_INFORM_INTERVAL, \"3600\", \"86400\"))\n"; 
echo "		return;\n"; 
echo "\n"; 
echo "	passForm.sid.value = sid;\n"; 
echo "	passForm.submit();\n"; 
echo "}\n"; 
echo "\n"; 
echo "\n"; 
echo "function InitDisplay(response)\n"; 
echo "{\n"; 
echo "	var token = response.split(\";\");\n"; 
echo "\n"; 
echo "	TR_ENABLE = token[0];\n"; 
echo "	TR_ACS_URL = token[1];\n"; 
echo "	TR_ACS_USER = token[2];\n"; 
echo "	TR_ACS_PASS = token[3];\n"; 
echo "	TR_INFORM_ENABLE = token[4];\n"; 
echo "	TR_INFORM_INTERVAL = token[5];\n"; 
echo "	TR_CR_USER = token[6];\n"; 
echo "	TR_CR_PASS = token[7];\n"; 
echo "\n"; 
echo "	if(token[8] == \"1\")\n"; 
echo "		GO(\"showCA\").style.display = \"\";\n"; 
echo "	if(token[9] == \"1\")\n"; 
echo "		GO(\"showUSER\").style.display = \"\";\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "	tr_display(\"TR_ENABLE\");\n"; 
echo "	tr_display(\"TR_ACS_URL\");\n"; 
echo "	tr_display(\"TR_ACS_USER\");\n"; 
echo "	tr_display(\"TR_ACS_PASS\");\n"; 
echo "	tr_display(\"TR_INFORM_ENABLE\");\n"; 
echo "	tr_display(\"TR_INFORM_INTERVAL\");\n"; 
echo "	tr_display(\"TR_CR_USER\");\n"; 
echo "	tr_display(\"TR_CR_PASS\");\n"; 
echo "	tr_display(\"TR_CA_CERT\");\n"; 
echo "	tr_display(\"TR_CLI_CERT\");\n"; 
echo "\n"; 
echo "	if(pri_d(uitems[inner_url][\"TR_CA_CERT\"]))\n"; 
echo "		GO(\"TR_TR_CA_CERT_SHOW\").style.display = \"\";\n"; 
echo "\n"; 
echo "	if(pri_d(uitems[inner_url][\"TR_CLI_CERT\"]))\n"; 
echo "		GO(\"TR_TR_CLI_CERT_SHOW\").style.display = \"\";\n"; 
echo "\n"; 
echo "\n"; 
echo "	obj_readonly(\"TR_ENABLE\");\n"; 
echo "	obj_readonly(\"TR_ACS_URL\");\n"; 
echo "	obj_readonly(\"TR_ACS_USER\");\n"; 
echo "	obj_readonly(\"TR_ACS_PASS\");\n"; 
echo "	obj_readonly(\"TR_INFORM_ENABLE\");\n"; 
echo "	obj_readonly(\"TR_INFORM_INTERVAL\");\n"; 
echo "	obj_readonly(\"TR_CR_USER\");\n"; 
echo "	obj_readonly(\"TR_CR_PASS\");\n"; 
echo "	obj_readonly(\"TR_CA_CERT\");\n"; 
echo "	obj_readonly(\"TR_CLI_CERT\");\n"; 
echo "\n"; 
echo "	InitValue(document.forms[0]);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function InitValue(passForm) {\n"; 
echo "	passForm.TR_ENABLE.value = TR_ENABLE;\n"; 
echo "	passForm.TR_ACS_URL.value = TR_ACS_URL;\n"; 
echo "	passForm.TR_ACS_USER.value = TR_ACS_USER;\n"; 
echo "	passForm.TR_ACS_PASS.value = TR_ACS_PASS;\n"; 
echo "	passForm.TR_INFORM_ENABLE.value = TR_INFORM_ENABLE;\n"; 
echo "	passForm.TR_INFORM_INTERVAL.value = TR_INFORM_INTERVAL;\n"; 
echo "	passForm.TR_CR_USER.value = TR_CR_USER;\n"; 
echo "	passForm.TR_CR_PASS.value = TR_CR_PASS;\n"; 
echo "\n"; 
echo "	top.loading = 0;\n"; 
echo "	setInterval('ajax_get_signals()',2000);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function file_upload(obj)\n"; 
echo "{\n"; 
echo "	if(obj.form.file.value!='');\n"; 
echo "	obj.form.vfile.disabled = true;\n"; 
echo "	obj.form.submit();\n"; 
echo "}\n"; 
echo "\n"; 
echo "//-->\n"; 
echo "</script>\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body onload=\"init_obj();setTimeout('ajax_get_key()',500);\">\n"; 
echo "<div id=\"main_div\">\n"; 
echo "	<div id=\"container\">\n"; 
echo "		<form method=\"POST\" action=\"ajax.php?action=manage_tr069\">\n"; 
echo "			<input type=\"hidden\" name=\"sid\" id=\"sid\">\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>TR-069 Configuration</legend>\n"; 
echo "				<table>\n"; 
echo "					<tr id=\"TR_TR_ENABLE\" style=\"display:none\"><td>TR-069 Active Flag</td><td>\n"; 
echo "						<select id=\"TR_ENABLE\" name=\"TR_ENABLE\">\n"; 
echo "							<option value=\"0\">disable</option>\n"; 
echo "							<option value=\"1\">enable</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_TR_ACS_URL\" style=\"display:none\"><td>ACS Server URL</td><td>\n"; 
echo "						<input type=\"text\" id=\"TR_ACS_URL\" name=\"TR_ACS_URL\" size=\"24\" maxlength=\"256\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_TR_ACS_USER\" style=\"display:none\"><td>ACS Username</td><td>\n"; 
echo "						<input type=\"text\" id=\"TR_ACS_USER\" name=\"TR_ACS_USER\" size=\"24\" maxlength=\"32\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_TR_ACS_PASS\" style=\"display:none\"><td>ACS Password</td><td>\n"; 
echo "						<input type=\"password\" id =\"TR_ACS_PASS\" name=\"TR_ACS_PASS\" size=\"24\" maxlength=\"32\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_TR_INFORM_ENABLE\" style=\"display:none\"><td>Inform Enable</td><td>\n"; 
echo "						<select id=\"TR_INFORM_ENABLE\" name=\"TR_INFORM_ENABLE\">\n"; 
echo "							<option value=\"0\">disable</option>\n"; 
echo "							<option value=\"1\">enable</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_TR_INFORM_INTERVAL\" style=\"display:none\"><td>Inform Interval<br/>(3600 ~ 86400 Seconds)</td><td>\n"; 
echo "						<input type=\"text\" id=\"TR_INFORM_INTERVAL\" name=\"TR_INFORM_INTERVAL\" size=\"5\" maxlength=\"5\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_TR_CR_USER\" style=\"display:none\"><td>Connection Request Username<br/>(The ACS server login to CPE)</td><td>\n"; 
echo "						<input type=\"text\" id=\"TR_CR_USER\" name=\"TR_CR_USER\" size=\"24\" maxlength=\"32\">\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "					<tr id=\"TR_TR_CR_PASS\" style=\"display:none\"><td>Connection Request Password<br/>(The ACS server login to CPE)</td><td>\n"; 
echo "						<input type=\"password\" id=\"TR_CR_PASS\" name=\"TR_CR_PASS\" size=\"24\" maxlength=\"32\">\n"; 
echo "					</td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "		</form>\n"; 
echo "		<form method=\"POST\" enctype=\"multipart/form-data\" action=\"ajax.php?action=tr069_ca_cert\">\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>TR-069 Certificate File Upload</legend>\n"; 
echo "				<table>\n"; 
echo "					<tr id=\"TR_TR_CA_CERT\" style=\"display:none\"><td align=\"right\">CA Certificate</td><td>\n"; 
echo "						<span><input type=\"file\" id=\"TR_CA_CERT\" name=\"file\" size=\"30\" onChange=\"this.form.vfile.value=this.value;\" style=\"position:relative; top:11px; left:7px; opacity:0; filter:alpha(opacity=0); -moz-opacity:0; z-index: 90;\"></span><br/>\n"; 
echo "						<input type=\"text\" name=\"vfile\" size=\"30\" readOnly=\"true\" style=\"position:relative; top:-12px; z-index:91;\">\n"; 
echo "						<input type=\"button\" name=\"Browse\" value=\"Browse...\" style=\"position:relative; top:-12px; width:60px;\" onClick=\"this.form.tr069_cert_file_name.click();\">\n"; 
echo "						<input type=\"button\" value=\"Upload\" name=\"TR069_Cert_Upload_button\" onClick=\"file_upload(this)\" style=\"position:relative; top:-12px; width:60px;\">\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "					<tr id=\"TR_TR_CA_CERT_SHOW\" style=\"display:none\">\n"; 
echo "					<td colspan=\"2\" id=\"showCA\" style=\"display:none\">\n"; 
echo "					<input type=\"button\" value=\"View CA certificate\" \n"; 
echo "					onclick=\"window.open('tr_cert_ca1.php','_blank','height=400, width=500, resizable=1,	scrollbars=1,location=0, menubar=0, directories=0, status=0, titlebar=0')\">\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "		</form>\n"; 
echo "\n"; 
echo "\n"; 
echo "		<form method=\"POST\" enctype=\"multipart/form-data\" action=\"ajax.php?action=tr069_client_cert\">\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>TR-069 Certificate File Upload</legend>\n"; 
echo "				<table>\n"; 
echo "					<tr id=\"TR_TR_CLI_CERT\" style=\"display:none\"><td align=\"right\">Client Certificate</td><td>\n"; 
echo "						<span><input type=\"file\" id=\"TR_CLI_CERT\" name=\"file\" size=\"30\" onChange=\"this.form.vfile.value=this.value;\" style=\"position:relative; top:11px; left:7px; opacity:0; filter:alpha(opacity=0); -moz-opacity:0; z-index: 90;\"></span><br/>\n"; 
echo "						<input type=\"text\" name=\"vfile\" size=\"30\" readOnly=\"true\" style=\"position:relative; top:-12px; z-index:91;\">\n"; 
echo "						<input type=\"button\" name=\"Browse\" value=\"Browse...\" style=\"position:relative; top:-12px; width:60px;\" onClick=\"this.form.tr069_cert_file_name.click();\">\n"; 
echo "						<input type=\"button\" value=\"Upload\" name=\"TR069_Cert_Upload_button\" onClick=\"file_upload(this)\" style=\"position:relative; top:-12px; width:60px;\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_TR_CLI_CERT_SHOW\" style=\"display:none\">\n"; 
echo "					<td colspan=\"2\" id=\"showUSER\" style=\"display:none\">\n"; 
echo "					<input type=\"button\" value=\"View User certificate\" \n"; 
echo "					onclick=\"window.open('tr_cert_user1.php','_blank','height=400, width=500, resizable=1,	scrollbars=1,location=0, menubar=0, directories=0, status=0, titlebar=0')\">\n"; 
echo "					</td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "		</form>\n"; 
echo "	</div>\n"; 
echo "	<div>\n"; 
echo "		<table style=\"width:600px;height:25px;text-align:center\">\n"; 
echo "			<tr>\n"; 
echo "				<td width=\"210\"></td>\n"; 
echo "				<td id=\"clear_btn\" class=\"td_btn\" onclick=\"location.reload()\">Undo</td>\n"; 
echo "				<td width=\"30\"></td>\n"; 
echo "				<td id=\"submit_btn\" class=\"td_btn\" onclick=\"Validate(document.forms[0])\">Apply</td>\n"; 
echo "				<td width=\"210\"></td>\n"; 
echo "			</tr>\n"; 
echo "		</table>\n"; 
echo "	</div>\n"; 
echo "</div>\n"; 
echo "</body>\n"; 
echo "</html>\n"; 
echo "\n";
?>