<?php
echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "<title></title>\n"; 
echo "<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "<script type=\"text/javascript\" src=\"comm.js\"></script>\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "<!--\n"; 
echo "function ajax_get_logMsg()\n"; 
echo "{\n"; 
echo "	top.$.ajax(\n"; 
echo "		{\n"; 
echo "			url:\"ajax.php\",\n"; 
echo "			data:{\n"; 
echo "				action:\"tag_LogMsg\",\n"; 
echo "				cache:false,\n"; 
echo "				time:(new Date()).getTime()\n"; 
echo "			},\n"; 
echo "			success:function(response){\n"; 
echo "				GO(\"logMessage\").innerHTML = \"<pre>\" + response + \"</pre>\";\n"; 
echo "			},\n"; 
echo "			error:function(xhr)\n"; 
echo "			{\n"; 
echo "				location.reload();\n"; 
echo "			}\n"; 
echo "		}\n"; 
echo "	);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function InitDisplay()\n"; 
echo "{\n"; 
echo "	if(pri_d(uitems[inner_url][\"Log\"]))\n"; 
echo "		ajax_get_logMsg();\n"; 
echo "\n"; 
echo "	top.loading = 0;\n"; 
echo "	setInterval('ajax_get_signals()',2000);\n"; 
echo "}\n"; 
echo "\n"; 
echo "-->\n"; 
echo "</script>\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body onload=\"init_obj();InitDisplay();\">\n"; 
echo "<div id=\"main_div\">\n"; 
echo "	<div id=\"container\">\n"; 
echo "	<div id=\"logMessage\" style=\"font-family:Courier New,Fixedsys,Arial; font-size:8pt;\"></div>\n"; 
echo "	</div>\n"; 
echo "	<div>\n"; 
echo "		<table style=\"width:600px;height:25px;text-align:center\">\n"; 
echo "			<tr>\n"; 
echo "				<td width=\"265\"></td>\n"; 
echo "				<td id=\"submit_btn\" class=\"td_btn\" onclick=\"ajax_get_logMsg()\">Refresh</td>\n"; 
echo "				<td width=\"265\"></td>\n"; 
echo "			</tr>\n"; 
echo "		</table>\n"; 
echo "	</div>\n"; 
echo "</div>\n"; 
echo "</body>\n"; 
echo "</html>\n"; 
echo "\n";
?>