<?php
echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "<title></title>\n"; 
echo "<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "<script type=\"text/javascript\" src=\"comm.js\"></script>\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "<!--\n"; 
echo "\n"; 
echo "var index;\n"; 
echo "var token;\n"; 
echo "\n"; 
echo "\n"; 
echo "/*function sleep(milliseconds) {\n"; 
echo "  var start = new Date().getTime();\n"; 
echo "\n"; 
echo "    while ((new Date().getTime() - start) < milliseconds){\n"; 
echo "      \n"; 
echo "    }\n"; 
echo "  	return;\n"; 
echo "}*/\n"; 
echo "\n"; 
echo "function show() {\n"; 
echo "	if(token.length -1 < index) return;\n"; 
echo "	GO(\"ipPing\").innerHTML += \"<pre>\" + token[index] + \"</pre>\"; \n"; 
echo "	index++;\n"; 
echo "	setTimeout(\"show()\",1000);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function ajax_get_dpingFile()\n"; 
echo "{\n"; 
echo "	var ip = document.getElementById(\"ip\").value;\n"; 
echo "	//var expr1 = new RegExp(\"([a-zA-Z0-9\.-]\.)*[a-zA-Z0-9\.-]+\");\n"; 
echo "\n"; 
echo "	if (!ip || ip.match(/^([a-zA-Z0-9\.-]\.)*[a-zA-Z0-9\.-]+$/g)==null)\n"; 
echo "	{\n"; 
echo "		alert(\"Invalid IP address, please input correct IP address!\");\n"; 
echo "		return;\n"; 
echo "	}\n"; 
echo "	top.$.ajax(\n"; 
echo "                {\n"; 
echo "                        url:\"ajax.php\",\n"; 
echo "                        data:{\n"; 
echo "                                action:\"tag_ipPing\",\n"; 
echo "                                pip:ip,\n"; 
echo "				cache:false,\n"; 
echo "                                time:(new Date()).getTime()\n"; 
echo "                        },\n"; 
echo "                        success:function(response){\n"; 
echo "				token = response.split(\"\n\");\n"; 
echo "				index=0;\n"; 
echo "				GO(\"ipPing\").innerHTML = \"\";\n"; 
echo "				show();\n"; 
echo "				return;\n"; 
echo "                        },\n"; 
echo "                        error:function(xhr)\n"; 
echo "                        {\n"; 
echo "                                location.reload();\n"; 
echo "                        }\n"; 
echo "                }\n"; 
echo "        );\n"; 
echo "}\n"; 
echo "\n"; 
echo "function InitDisplay()\n"; 
echo "{\n"; 
echo "	top.loading = 0;\n"; 
echo "	setInterval('ajax_get_signals()',2000);\n"; 
echo "}\n"; 
echo "/*\n"; 
echo "function InitDisplay(response)\n"; 
echo "{\n"; 
echo "\n"; 
echo "\n"; 
echo "//        var token = response.split(\";\");\n"; 
echo "\n"; 
echo "//        LAN_MASK = token[1];\n"; 
echo "//        tr_display(\"LAN_IP\");\n"; 
echo "//        obj_readonly(\"LAN_MASK\",\"ip\");\n"; 
echo "\n"; 
echo "        InitValue(document.forms[0]);\n"; 
echo "	//setInterval('aaa()',2000);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function InitValue(passForm) {\n"; 
echo "\n"; 
echo "        top.loading = 0;\n"; 
echo "        setInterval('ajax_get_signals()',2000);\n"; 
echo "}\n"; 
echo "*/\n"; 
echo "-->\n"; 
echo "</script>\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body onload=\"init_obj();InitDisplay();\">\n"; 
echo "<div id=\"main_div\">\n"; 
echo "        <div id=\"container\">\n"; 
echo " 		<!--<tr><td style=\"vertical-align:top;width:50%;\">-->\n"; 
echo "		<FIELDSET id=\"field_ping\">\n"; 
echo "                                <legend>Ping Test</legend>\n"; 
echo "                                <table>\n"; 
echo "				<tr>\n"; 
echo "				<td><b>IP Address</b></td>\n"; 
echo "				<td width=\"20\"></td>\n"; 
echo "				<td><input name=\"ip\" id=\"ip\" size=\"35\" maxlength=\"35\" ></td>\n"; 
echo "\n"; 
echo "					<td width=\"20\"></td>\n"; 
echo "					<td id=\"submit_btn\" class=\"td_btn\" onclick=\"ajax_get_dpingFile()\">Ping</td>\n"; 
echo "				</tr>\n"; 
echo "                                </table>\n"; 
echo "		<!--<br/>-->\n"; 
echo "		<!--<table> style=\"width:120px;height:25px;text-align:center\">-->\n"; 
echo "		<div id=\"ipPing\" style=\"font-family:Courier New,Fixedsys,Arial;font-size:10pt;\"></div><!--width:550px;border-style:dotted;\"</div>-->\n"; 
echo "		<!--</table>-->\n"; 
echo "                </FIELDSET>\n"; 
echo "                        <!--</td></tr>-->\n"; 
echo "	</div>\n"; 
echo "</dir>\n"; 
echo "</body>\n"; 
echo "</html>\n"; 
echo "\n";
?>