<?php
echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "<title></title>\n"; 
echo "<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "<script type=\"text/javascript\" src=\"comm.js\"></script>\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "<!--\n"; 
echo "\n"; 
echo "var SNMPD_ENABLE,SYSLOCATION,SYSCONTACT,ROCOMMUNITY,RWCOMMUNITY;\n"; 
echo "\n"; 
echo "function Validate(passForm) {\n"; 
echo "\n"; 
echo "\n"; 
echo "	passForm.SNMPD_ENABLE.disabled = false;\n"; 
echo "\n"; 
echo "	passForm.sid.value = sid;\n"; 
echo "	passForm.btnSubmit.value = \"1\";\n"; 
echo "	passForm.submit();\n"; 
echo "	return;\n"; 
echo "}\n"; 
echo "\n"; 
echo "\n"; 
echo "function InitDisplay(response)\n"; 
echo "{\n"; 
echo "\n"; 
echo "	var token = response.split(\";\");\n"; 
echo "\n"; 
echo "	SNMPD_ENABLE = token[0];\n"; 
echo "	SYSLOCATION = token[1];\n"; 
echo "	SYSCONTACT = token[2];\n"; 
echo "	ROCOMMUNITY = token[3];\n"; 
echo "	RWCOMMUNITY = token[4];\n"; 
echo "\n"; 
echo "\n"; 
echo "	tr_display(\"SNMPD_ENABLE\");\n"; 
echo "	tr_display(\"SYSLOCATION\");\n"; 
echo "	tr_display(\"SYSCONTACT\");\n"; 
echo "	tr_display(\"ROCOMMUNITY\");\n"; 
echo "	tr_display(\"RWCOMMUNITY\");\n"; 
echo "\n"; 
echo "\n"; 
echo "	obj_readonly(\"SNMPD_ENABLE\");\n"; 
echo "	obj_readonly(\"SYSLOCATION\");\n"; 
echo "	obj_readonly(\"SYSCONTACT\");\n"; 
echo "	obj_readonly(\"ROCOMMUNITY\");\n"; 
echo "	obj_readonly(\"RWCOMMUNITY\");\n"; 
echo "\n"; 
echo "\n"; 
echo "	InitValue(document.forms[0]);\n"; 
echo "}\n"; 
echo "\n"; 
echo "\n"; 
echo "function InitValue(passForm) {\n"; 
echo "\n"; 
echo "\n"; 
echo "	passForm.SNMPD_ENABLE.value = SNMPD_ENABLE;\n"; 
echo "	passForm.SYSLOCATION.value = SYSLOCATION;\n"; 
echo "	passForm.SYSCONTACT.value = SYSCONTACT;\n"; 
echo "	passForm.ROCOMMUNITY.value = ROCOMMUNITY;\n"; 
echo "	passForm.RWCOMMUNITY.value = RWCOMMUNITY;\n"; 
echo "\n"; 
echo "	change_tbl(passForm);\n"; 
echo "\n"; 
echo "\n"; 
echo "	top.loading = 0;\n"; 
echo "	setInterval('ajax_get_signals()',2000);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function change_tbl(passForm) {\n"; 
echo "	if (passForm.SNMPD_ENABLE.value==\"1\") {\n"; 
echo "		try {\n"; 
echo "			document.getElementById(\"SNMPsettingGroup\").style.display = \"table-row-group\";\n"; 
echo "		} catch (e) {\n"; 
echo "			document.getElementById(\"SNMPsettingGroup\").style.display = \"block\";\n"; 
echo "		}\n"; 
echo "	} else {\n"; 
echo "		document.getElementById(\"SNMPsettingGroup\").style.display = \"none\";\n"; 
echo "	}\n"; 
echo "}\n"; 
echo "//-->\n"; 
echo "</script>\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body onload=\"init_obj();setTimeout('ajax_get_key()',500);\">\n"; 
echo "<div id=\"main_div\">\n"; 
echo "	<div id=\"container\">\n"; 
echo "		<FIELDSET>\n"; 
echo "		<legend>SNMP Server Configuration</legend>\n"; 
echo "		<form method=\"POST\" action=\"ajax.php?action=manage_snmp\">\n"; 
echo "			<input type=\"hidden\" name=\"sid\" id=\"sid\">\n"; 
echo "			<table>\n"; 
echo "				<tbody>\n"; 
echo "					<tr id=\"TR_SNMPD_ENABLE\" style=\"display:none\"><td>SNMP server</td>\n"; 
echo "					<td><select name=\"SNMPD_ENABLE\" id=\"SNMPD_ENABLE\" onChange=\"change_tbl(this.form)\">\n"; 
echo "						<option value=\"0\">disable</option>\n"; 
echo "						<option value=\"1\">enable</option>\n"; 
echo "					</select></td></tr>\n"; 
echo "				</tbody>\n"; 
echo "				<tbody id=\"SNMPsettingGroup\">\n"; 
echo "					<tr id=\"TR_ROCOMMUNITY\" style=\"display:none\"><td>SNMP read-only community</td><td>\n"; 
echo "					<input type=\"text\" name=\"ROCOMMUNITY\" id=\"ROCOMMUNITY\" size=\"24\" maxlength=\"32\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_RWCOMMUNITY\" style=\"display:none\"><td>SNMP read-write community</td><td>\n"; 
echo "					<input type=\"text\" name=\"RWCOMMUNITY\" id=\"RWCOMMUNITY\" size=\"24\" maxlength=\"32\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_SYSCONTACT\" style=\"display:none\"><td>Contact</td><td>\n"; 
echo "					<input type=\"text\" name=\"SYSCONTACT\" id=\"SYSCONTACT\" size=\"24\" maxlength=\"64\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_SYSLOCATION\" style=\"display:none\"><td>Location</td><td>\n"; 
echo "					<input type=\"text\" name=\"SYSLOCATION\" id=\"SYSLOCATION\" size=\"24\" maxlength=\"64\">\n"; 
echo "					</td></tr>\n"; 
echo "				</tbody>\n"; 
echo "			</table>\n"; 
echo "			<input type=\"hidden\" name=\"btnSubmit\">\n"; 
echo "		</form>\n"; 
echo "		</FIELDSET>\n"; 
echo "	</div>\n"; 
echo "	<div>\n"; 
echo "		<table style=\"width:600px;height:25px;text-align:center\">\n"; 
echo "			<tr>\n"; 
echo "				<td width=\"210\"></td>\n"; 
echo "				<td id=\"clear_btn\" class=\"td_btn\" onclick=\"location.reload()\">Undo</td>\n"; 
echo "				<td width=\"30\"></td>\n"; 
echo "				<td id=\"submit_btn\" class=\"td_btn\" onclick=\"Validate(document.forms[0])\">Apply</td>\n"; 
echo "				<td width=\"210\"></td>\n"; 
echo "			</tr>\n"; 
echo "		</table>\n"; 
echo "	</div>\n"; 
echo "</div>\n"; 
echo "</body>\n"; 
echo "</html>\n"; 
echo "\n";
?>