<?php
echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "<title></title>\n"; 
echo "<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "<script type=\"text/javascript\" src=\"comm.js\"></script>\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "<!--\n"; 
echo "\n"; 
echo "var UPNP_ENABLE_UPNP,UPNP_ENABLE_NATPMP;\n"; 
echo "\n"; 
echo "\n"; 
echo "function InitDisplay(response)\n"; 
echo "{\n"; 
echo "	var token = response.split(\";\");\n"; 
echo "\n"; 
echo "	UPNP_ENABLE_UPNP = token[0];\n"; 
echo "	UPNP_ENABLE_NATPMP = token[1];\n"; 
echo "\n"; 
echo "	tr_display(\"UPNP_ENABLE_UPNP\");\n"; 
echo "	tr_display(\"UPNP_ENABLE_NATPMP\");\n"; 
echo "\n"; 
echo "	obj_readonly(\"UPNP_ENABLE_UPNP\");\n"; 
echo "	obj_readonly(\"UPNP_ENABLE_NATPMP\");\n"; 
echo "\n"; 
echo "	InitValue(document.forms[0]);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function InitValue(passForm)\n"; 
echo "{\n"; 
echo "	passForm.UPNP_ENABLE_UPNP.checked = (UPNP_ENABLE_UPNP==\"1\")? true : false;\n"; 
echo "	passForm.UPNP_ENABLE_NATPMP.checked = (UPNP_ENABLE_NATPMP==\"1\")? true : false;\n"; 
echo "\n"; 
echo "	top.loading = 0;\n"; 
echo "	setInterval('ajax_get_signals()',2000);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function Validate(passForm)\n"; 
echo "{\n"; 
echo "	passForm.sid.value = sid;\n"; 
echo "	passForm.btnSubmit.value = \"1\";\n"; 
echo "	passForm.submit();\n"; 
echo "}\n"; 
echo "//-->\n"; 
echo "</script>\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body onload=\"init_obj();setTimeout('ajax_get_key()',500);\">\n"; 
echo "<div id=\"main_div\">\n"; 
echo "	<div id=\"container\">\n"; 
echo "		<form name=\"form1\" method=\"POST\" action=\"ajax.php?action=net_upnp\">\n"; 
echo "		<input type=\"hidden\" name=\"sid\" id=\"sid\">\n"; 
echo "		<table class=\"pf_tbl\" cellpadding=\"5\">\n"; 
echo "			<tr>\n"; 
echo "				<th>Settings</th>\n"; 
echo "				<th>Enable</th>\n"; 
echo "			</tr>\n"; 
echo "			<tr id=\"TR_UPNP_ENABLE_UPNP\" style=\"display:none;\">\n"; 
echo "				<td>ENABLE UPNP</td>\n"; 
echo "				<td><input type=\"checkbox\" id=\"UPNP_ENABLE_UPNP\" name=\"UPNP_ENABLE_UPNP\"></td>\n"; 
echo "			</tr>\n"; 
echo "			<tr id=\"TR_UPNP_ENABLE_NATPMP\" style=\"display:none;\">\n"; 
echo "				<td>ENABLE NATPMP</td>\n"; 
echo "				<td><input type=\"checkbox\" id=\"UPNP_ENABLE_NATPMP\" name=\"UPNP_ENABLE_NATPMP\"></td>\n"; 
echo "			</tr>\n"; 
echo "		</table>\n"; 
echo "		<input type=\"hidden\" name=\"btnSubmit\">\n"; 
echo "		</form>\n"; 
echo "	</div>\n"; 
echo "	<div>\n"; 
echo "		<table style=\"width:600px;height:25px;text-align:center\">\n"; 
echo "			<tr>\n"; 
echo "				<td width=\"210\"></td>\n"; 
echo "				<td id=\"clear_btn\" class=\"td_btn\" onclick=\"location.reload()\">Undo</td>\n"; 
echo "				<td width=\"30\"></td>\n"; 
echo "				<td id=\"submit_btn\" class=\"td_btn\" onclick=\"Validate(document.forms[0]);\">Apply</td>\n"; 
echo "				<td width=\"210\"></td>\n"; 
echo "			</tr>\n"; 
echo "		</table>\n"; 
echo "	</div>\n"; 
echo "</div>\n"; 
echo "</body>\n"; 
echo "</html>\n"; 
echo "\n";
?>