<?php
echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "<title></title>\n"; 
echo "<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "<script type=\"text/javascript\" src=\"comm.js\"></script>\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "<!--\n"; 
echo "\n"; 
echo "var DHCPD_ENABLE,DHCPD_START_IP,DHCPD_END_IP,DHCPD_LEASE_TIME;\n"; 
echo "var Array_DHCPD_DNS,Array_DHCPD_DNS_1,Array_DHCPD_DNS_2,Array_DHCPD_DNS_3;\n"; 
echo "var DNS_1,DNS_2,DNS_3;\n"; 
echo "var DNS_IP_1,DNS_IP_2,DNS_IP_3;\n"; 
echo "\n"; 
echo "\n"; 
echo "var pftData_Array,pftData_raw;\n"; 
echo "var pftData = new Array();\n"; 
echo "\n"; 
echo "Array.prototype.remove = function(from, to) {\n"; 
echo "	var rest = this.slice((to || from) + 1 || this.length);\n"; 
echo "	this.length = from < 0 ? this.length + from : from;\n"; 
echo "	return this.push.apply(this, rest);\n"; 
echo "};\n"; 
echo "\n"; 
echo "function pft_obj()\n"; 
echo "{\n"; 
echo "	this.value = pftData;\n"; 
echo "}\n"; 
echo "\n"; 
echo "var pft;\n"; 
echo "\n"; 
echo "function updateAllRow()\n"; 
echo "{\n"; 
echo "	for(var i=0;i<pft.length;i++)\n"; 
echo "	{\n"; 
echo "		pft[i].Enable = (GO(\"Enb_\"+i).checked)?\"1\":\"0\";\n"; 
echo "		pft[i].MAC = GO(\"MAC_\"+i).value;\n"; 
echo "		pft[i].IP = GO(\"IP_\"+i).value;\n"; 
echo "	}\n"; 
echo "}\n"; 
echo "\n"; 
echo "function fp_insert()\n"; 
echo "{\n"; 
echo "	if (pft.length >= 30) return;\n"; 
echo "	var newobj = {\"Enable\":\"\",\"MAC\":\"\",\"IP\":\"\"};\n"; 
echo "\n"; 
echo "\n"; 
echo "	updateAllRow();\n"; 
echo "	pft.push(newobj);\n"; 
echo "	removeAllRow();\n"; 
echo "	for(var i=0;i<pft.length;i++)\n"; 
echo "		addRowToTable(pft[i]);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function addRowToTable(obj)\n"; 
echo "{\n"; 
echo "	var tbl = document.getElementById('pf');\n"; 
echo "	var lastRow = tbl.rows.length;\n"; 
echo "	var iteration = lastRow-1;\n"; 
echo "	var row = tbl.insertRow(lastRow);\n"; 
echo "\n"; 
echo "	//No\n"; 
echo "	var cellno = row.insertCell(0);\n"; 
echo "	var textNode = document.createTextNode(iteration+1);\n"; 
echo "	cellno.appendChild(textNode);\n"; 
echo "\n"; 
echo "	//Enable\n"; 
echo "	var cellenable = row.insertCell(1);\n"; 
echo "	var el = document.createElement('input');\n"; 
echo "	el.type = 'checkbox';\n"; 
echo "	el.id = 'Enb_' + iteration;\n"; 
echo "	el.name = 'Enb_' + iteration;\n"; 
echo "	el.defaultChecked = (obj.Enable == \"1\")?true:false;\n"; 
echo "	el.value = (obj.Enable)?\"1\":\"0\";\n"; 
echo "	el.onclick = function(){this.value = (this.checked)?\"1\":\"0\"};\n"; 
echo "	el.disabled = (!pri_a(uitems[inner_url][\"DHCPD_STATIC_LEASE\"]))?true:false;\n"; 
echo "	cellenable.appendChild(el);\n"; 
echo "\n"; 
echo "	//MAC\n"; 
echo "	var cellMAC = row.insertCell(2);\n"; 
echo "	var el = document.createElement('input');\n"; 
echo "	el.type = 'text';\n"; 
echo "	el.id = 'MAC_' + iteration;\n"; 
echo "	el.name = 'MAC_' + iteration;\n"; 
echo "	el.size = 20;\n"; 
echo "	el.maxLength = 17;\n"; 
echo "	el.value = obj.MAC;\n"; 
echo "	el.disabled = (!pri_a(uitems[inner_url][\"DHCPD_STATIC_LEASE\"]))?true:false;\n"; 
echo "	cellMAC.appendChild(el);\n"; 
echo "\n"; 
echo "	//Server IP\n"; 
echo "	var celllanip = row.insertCell(3);\n"; 
echo "	var el = document.createElement('input');\n"; 
echo "	el.type = 'text';\n"; 
echo "	el.id = 'IP_' + iteration;\n"; 
echo "	el.name = 'IP_' + iteration;\n"; 
echo "	el.size = 13;\n"; 
echo "	el.maxLength = 15;\n"; 
echo "	el.value = obj.IP;\n"; 
echo "	el.disabled = (!pri_a(uitems[inner_url][\"DHCPD_STATIC_LEASE\"]))?true:false;\n"; 
echo "	celllanip.appendChild(el);\n"; 
echo "\n"; 
echo "	//Delete\n"; 
echo "	var cellenable = row.insertCell(4);\n"; 
echo "	var el = document.createElement('input');\n"; 
echo "	el.value = \"Delete\";\n"; 
echo "	el.type = 'button';\n"; 
echo "	eval(\"el.onclick = function(){removeRowFromTable(\"+ iteration +\")}\");\n"; 
echo "	el.disabled = (!pri_a(uitems[inner_url][\"DHCPD_STATIC_LEASE\"]))?true:false;\n"; 
echo "	cellenable.appendChild(el);\n"; 
echo "}\n"; 
echo "function removeRowFromTable(index)\n"; 
echo "{\n"; 
echo "	updateAllRow();\n"; 
echo "	removeAllRow();\n"; 
echo "	pft.remove(index);\n"; 
echo "\n"; 
echo "	for(var i=0;i<pft.length;i++)\n"; 
echo "		addRowToTable(pft[i], i);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function removeAllRow()\n"; 
echo "{\n"; 
echo "	var tbl = GO('pf');\n"; 
echo "	var lastRow = tbl.rows.length;  \n"; 
echo "	for(var i=1;i<lastRow;i++)\n"; 
echo "		tbl.deleteRow(lastRow - i);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function Validate(passForm) {\n"; 
echo "	passForm.DHCPD_ENABLE.disabled = false;\n"; 
echo "	if (passForm.DHCPD_ENABLE.value == \"1\") {\n"; 
echo "		if(!AssembleIPAddress(passForm, \"DHCPD_START_IP\")) return;\n"; 
echo "		if(!AssembleIPAddress(passForm, \"DHCPD_END_IP\")) return;\n"; 
echo "\n"; 
echo "		var DHCPD_DNS;\n"; 
echo "		DHCPD_DNS = passForm.dns_type_1.value + \",\"\n"; 
echo "		if(passForm.dns_type_1.value == \"2\")\n"; 
echo "		{\n"; 
echo "			if(!AssembleIPAddress(passForm, \"DNS_IP_1\")) return;\n"; 
echo "			DHCPD_DNS += passForm.DNS_IP_1.value;\n"; 
echo "		}\n"; 
echo "		else\n"; 
echo "			DHCPD_DNS += DNS_IP_1;\n"; 
echo "\n"; 
echo "		DHCPD_DNS += \" \";\n"; 
echo "\n"; 
echo "		DHCPD_DNS += passForm.dns_type_2.value + \",\"\n"; 
echo "		if(passForm.dns_type_2.value == \"2\")\n"; 
echo "		{\n"; 
echo "			if(!AssembleIPAddress(passForm, \"DNS_IP_2\")) return;\n"; 
echo "			DHCPD_DNS += passForm.DNS_IP_2.value;\n"; 
echo "		}\n"; 
echo "		else\n"; 
echo "			DHCPD_DNS += DNS_IP_2;\n"; 
echo "\n"; 
echo "		DHCPD_DNS += \" \";\n"; 
echo "\n"; 
echo "		DHCPD_DNS += passForm.dns_type_3.value + \",\"\n"; 
echo "		if(passForm.dns_type_3.value == \"2\")\n"; 
echo "		{\n"; 
echo "			if(!AssembleIPAddress(passForm, \"DNS_IP_3\")) return;\n"; 
echo "			DHCPD_DNS += passForm.DNS_IP_3.value;\n"; 
echo "		}\n"; 
echo "		else\n"; 
echo "			DHCPD_DNS += DNS_IP_3;\n"; 
echo "\n"; 
echo "		\n"; 
echo "		if(!CheckValue(passForm.DHCPD_LEASE_TIME, \"1\", \"99999999\")) return;\n"; 
echo "\n"; 
echo "		passForm.DHCPD_DNS.value = DHCPD_DNS;\n"; 
echo "\n"; 
echo "	} else {\n"; 
echo "		InitValue(passForm);\n"; 
echo "		passForm.DHCPD_ENABLE.value = \"0\";\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	var tmpDHCPD_STATIC_LEASE=\"\";\n"; 
echo "	for(i=0; i<pft.length; i++) {\n"; 
echo "		var MAC = GO(\"MAC_\"+i).value;\n"; 
echo "		if(!CheckMacAddress(MAC))\n"; 
echo "		{\n"; 
echo "			alert(\"Invalid MAC address\");\n"; 
echo "			return;\n"; 
echo "		}\n"; 
echo "\n"; 
echo "\n"; 
echo "		var ServerIp = GO(\"IP_\"+i).value;\n"; 
echo "		if(!v_IP(ServerIp)) return;\n"; 
echo "\n"; 
echo "\n"; 
echo "		if(i > 0)\n"; 
echo "			tmpDHCPD_STATIC_LEASE+= \" \";\n"; 
echo "		tmpDHCPD_STATIC_LEASE+= ((GO(\"Enb_\"+i).checked)?\"1\":\"0\");\n"; 
echo "		tmpDHCPD_STATIC_LEASE+= \",\"+GO(\"MAC_\"+i).value;\n"; 
echo "		tmpDHCPD_STATIC_LEASE+= \",\"+GO(\"IP_\"+i).value;\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	passForm.DHCPD_STATIC_LEASE.value = tmpDHCPD_STATIC_LEASE;\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "	passForm.sid.value = sid;\n"; 
echo "	passForm.btnSubmit.value = \"1\";\n"; 
echo "	passForm.submit();\n"; 
echo "	return;\n"; 
echo "}\n"; 
echo "\n"; 
echo "\n"; 
echo "function InitDisplay(response)\n"; 
echo "{\n"; 
echo "\n"; 
echo "	var token = response.split(\";\");\n"; 
echo "\n"; 
echo "	DHCPD_ENABLE = token[0];\n"; 
echo "	DHCPD_START_IP = token[1];\n"; 
echo "	DHCPD_END_IP = token[2];\n"; 
echo "	DHCPD_LEASE_TIME = token[3];\n"; 
echo "	Array_DHCPD_DNS = token[4].split(\" \");\n"; 
echo "	Array_DHCPD_DNS_1 = Array_DHCPD_DNS[0].split(\",\");\n"; 
echo "	Array_DHCPD_DNS_2 = Array_DHCPD_DNS[1].split(\",\");\n"; 
echo "	Array_DHCPD_DNS_3 = Array_DHCPD_DNS[2].split(\",\");\n"; 
echo "	DNS_1 = Array_DHCPD_DNS_1[0];\n"; 
echo "	DNS_IP_1 = Array_DHCPD_DNS_1[1];\n"; 
echo "	DNS_2 = Array_DHCPD_DNS_2[0];\n"; 
echo "	DNS_IP_2 = Array_DHCPD_DNS_2[1];\n"; 
echo "	DNS_3 = Array_DHCPD_DNS_3[0];\n"; 
echo "	DNS_IP_3 = Array_DHCPD_DNS_3[1];\n"; 
echo "\n"; 
echo "\n"; 
echo "	pftData_raw = token[5];\n"; 
echo "	if(pftData_raw != \"\")\n"; 
echo "	{\n"; 
echo "		pftData_Array = pftData_raw.split(\" \");\n"; 
echo "		pftData = new Array();\n"; 
echo "		var i;\n"; 
echo "		for(i=0;i<pftData_Array.length;i++)\n"; 
echo "		{\n"; 
echo "			var tmpArray = pftData_Array[i].split(\",\");\n"; 
echo "			var newobj = {\"Enable\":tmpArray[0],\"MAC\":tmpArray[1],\"IP\":tmpArray[2]};\n"; 
echo "			pftData.push(newobj);\n"; 
echo "\n"; 
echo "		}\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	tr_display(\"DHCPD_STATIC_LEASE\");\n"; 
echo "\n"; 
echo "	tr_display(\"DHCPD_ENABLE\");\n"; 
echo "	tr_display(\"DHCPD_START_IP\");\n"; 
echo "	tr_display(\"DHCPD_END_IP\");\n"; 
echo "	tr_display(\"DHCPD_LEASE_TIME\");\n"; 
echo "\n"; 
echo "	if(pri_d(uitems[inner_url][\"DHCPD_DNS\"]))\n"; 
echo "	{\n"; 
echo "		GO(\"TR_dns_type_1\").style.display = \"\";\n"; 
echo "		GO(\"TR_dns_type_2\").style.display = \"\";\n"; 
echo "		GO(\"TR_dns_type_3\").style.display = \"\";\n"; 
echo "	}\n"; 
echo "\n"; 
echo "\n"; 
echo "	obj_readonly(\"DHCPD_ENABLE\");\n"; 
echo "	obj_readonly(\"DHCPD_START_IP\",\"ip\");\n"; 
echo "	obj_readonly(\"DHCPD_END_IP\",\"ip\");\n"; 
echo "	obj_readonly(\"DHCPD_LEASE_TIME\");\n"; 
echo "\n"; 
echo "\n"; 
echo "	if(!pri_a(uitems[inner_url][\"DHCPD_DNS\"]))\n"; 
echo "	{\n"; 
echo "		GO(\"dns_type_1\").disabled = true;\n"; 
echo "		GO(\"DNS_IP_1_01\").disabled = true;\n"; 
echo "		GO(\"DNS_IP_1_02\").disabled = true;\n"; 
echo "		GO(\"DNS_IP_1_03\").disabled = true;\n"; 
echo "		GO(\"DNS_IP_1_04\").disabled = true;\n"; 
echo "\n"; 
echo "		GO(\"dns_type_2\").disabled = true;\n"; 
echo "		GO(\"DNS_IP_2_01\").disabled = true;\n"; 
echo "		GO(\"DNS_IP_2_02\").disabled = true;\n"; 
echo "		GO(\"DNS_IP_2_03\").disabled = true;\n"; 
echo "		GO(\"DNS_IP_2_04\").disabled = true;\n"; 
echo "\n"; 
echo "		GO(\"dns_type_3\").disabled = true;\n"; 
echo "		GO(\"DNS_IP_3_01\").disabled = true;\n"; 
echo "		GO(\"DNS_IP_3_02\").disabled = true;\n"; 
echo "		GO(\"DNS_IP_3_03\").disabled = true;\n"; 
echo "		GO(\"DNS_IP_3_04\").disabled = true;\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	InitValue(document.forms[0]);\n"; 
echo "}\n"; 
echo "\n"; 
echo "\n"; 
echo "function InitValue(passForm) {\n"; 
echo "\n"; 
echo "	passForm.DHCPD_ENABLE.value = DHCPD_ENABLE;\n"; 
echo "	SplitIPAddress(DHCPD_START_IP, \"DHCPD_START_IP\");\n"; 
echo "	SplitIPAddress(DHCPD_END_IP, \"DHCPD_END_IP\");\n"; 
echo "	SplitIPAddress(DNS_IP_1, \"DNS_IP_1\");\n"; 
echo "	SplitIPAddress(DNS_IP_2, \"DNS_IP_2\");\n"; 
echo "	SplitIPAddress(DNS_IP_3, \"DNS_IP_3\");\n"; 
echo "	passForm.DHCPD_LEASE_TIME.value = DHCPD_LEASE_TIME;\n"; 
echo "\n"; 
echo "	passForm.dns_type_1.value = DNS_1;\n"; 
echo "	passForm.dns_type_2.value = DNS_2;\n"; 
echo "	passForm.dns_type_3.value = DNS_3;\n"; 
echo "\n"; 
echo "\n"; 
echo "	if(DNS_1 == \"2\")\n"; 
echo "		GO(\"dns_1\").style.visibility = \"visible\";\n"; 
echo "	if(DNS_2 == \"2\")\n"; 
echo "		GO(\"dns_2\").style.visibility = \"visible\";\n"; 
echo "	if(DNS_3 == \"2\")\n"; 
echo "		GO(\"dns_3\").style.visibility = \"visible\";\n"; 
echo "\n"; 
echo "\n"; 
echo "	change_tbl(passForm);\n"; 
echo "\n"; 
echo "\n"; 
echo "	removeAllRow();\n"; 
echo "	pft = new pft_obj().value;\n"; 
echo "\n"; 
echo "	for(var i=0;i<pft.length;i++)\n"; 
echo "		addRowToTable(pft[i]);\n"; 
echo "\n"; 
echo "	if(!pri_a(uitems[inner_url][\"DHCPD_STATIC_LEASE\"]))\n"; 
echo "	{\n"; 
echo "		passForm.Insert.disabled = true;\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	top.loading = 0;\n"; 
echo "	setInterval('ajax_get_signals()',2000);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function change_tbl(passForm) {\n"; 
echo "	if (passForm.DHCPD_ENABLE.value==\"1\") {\n"; 
echo "		try {\n"; 
echo "			GO(\"DHCPsettingGroup\").style.display = \"table-row-group\";\n"; 
echo "		} catch (e) {\n"; 
echo "			GO(\"DHCPsettingGroup\").style.display = \"block\";\n"; 
echo "		}\n"; 
echo "	} else {\n"; 
echo "		GO(\"DHCPsettingGroup\").style.display = \"none\";\n"; 
echo "	}\n"; 
echo "}\n"; 
echo "\n"; 
echo "function do_change(val,type)\n"; 
echo "{\n"; 
echo "	GO(\"dns_\"+type).style.visibility = \"hidden\";\n"; 
echo "	if(val == \"2\")\n"; 
echo "	{\n"; 
echo "		GO(\"dns_\"+type).style.visibility = \"visible\";\n"; 
echo "	}\n"; 
echo "\n"; 
echo "}\n"; 
echo "//-->\n"; 
echo "</script>\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body onload=\"init_obj();setTimeout('ajax_get_key()',500);\">\n"; 
echo "<div id=\"main_div\">\n"; 
echo "	<div id=\"container\">\n"; 
echo "		<form method=\"POST\" action=\"ajax.php?action=net_dhcp\">\n"; 
echo "		<FIELDSET>\n"; 
echo "		<legend>DHCP Server Configuration</legend>\n"; 
echo "			<input type=\"hidden\" name=\"sid\" id=\"sid\">\n"; 
echo "			<input type=\"hidden\" name=\"DHCPD_STATIC_LEASE\" id=\"DHCPD_STATIC_LEASE\">\n"; 
echo "\n"; 
echo "			<table>\n"; 
echo "				<tbody>\n"; 
echo "				<tr id=\"TR_DHCPD_ENABLE\" style=\"display:none\"><td>DHCP server</td>\n"; 
echo "					<td><select name=\"DHCPD_ENABLE\" id=\"DHCPD_ENABLE\" onChange=\"change_tbl(this.form)\">\n"; 
echo "						<option value=\"0\">disable</option>\n"; 
echo "						<option value=\"1\">enable</option>\n"; 
echo "					</select></td></tr>\n"; 
echo "				</tbody>\n"; 
echo "				<tbody id=\"DHCPsettingGroup\">\n"; 
echo "				<tr id=\"TR_DHCPD_START_IP\" style=\"display:none\"><td>DHCP start IP address</td><td>\n"; 
echo "					<input type=\"text\" id=\"DHCPD_START_IP_01\" name=\"DHCPD_START_IP_01\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "					<input type=\"text\" id=\"DHCPD_START_IP_02\" name=\"DHCPD_START_IP_02\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "					<input type=\"text\" id=\"DHCPD_START_IP_03\" name=\"DHCPD_START_IP_03\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "					<input type=\"text\" id=\"DHCPD_START_IP_04\" name=\"DHCPD_START_IP_04\" size=\"3\" maxlength=\"3\">\n"; 
echo "					<input type=\"hidden\" name=\"DHCPD_START_IP\">\n"; 
echo "					</td></tr>\n"; 
echo "				<tr id=\"TR_DHCPD_END_IP\" style=\"display:none\"><td>DHCP end IP address</td><td>\n"; 
echo "					<input type=\"text\" id=\"DHCPD_END_IP_01\" name=\"DHCPD_END_IP_01\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "					<input type=\"text\" id=\"DHCPD_END_IP_02\" name=\"DHCPD_END_IP_02\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "					<input type=\"text\" id=\"DHCPD_END_IP_03\" name=\"DHCPD_END_IP_03\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "					<input type=\"text\" id=\"DHCPD_END_IP_04\" name=\"DHCPD_END_IP_04\" size=\"3\" maxlength=\"3\">\n"; 
echo "					<input type=\"hidden\" name=\"DHCPD_END_IP\">\n"; 
echo "					</td></tr>\n"; 
echo "				<tr id=\"TR_dns_type_1\" style=\"display:none\"><td>First DNS Server</td><td>\n"; 
echo "					<select id=\"dns_type_1\" name=\"dns_type_1\" onchange=\"do_change(this.value,'1')\">\n"; 
echo "						<option value=\"0\">None</option>\n"; 
echo "						<option value=\"1\">From ISP</option>\n"; 
echo "						<option value=\"2\">User Define</option>		\n"; 
echo "					</select>\n"; 
echo "					<span id=\"dns_1\" name=\"dns_1\" style=\"visibility:hidden\">\n"; 
echo "						<input type=\"text\" id=\"DNS_IP_1_01\" name=\"DNS_IP_1_01\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "						<input type=\"text\" id=\"DNS_IP_1_02\" name=\"DNS_IP_1_02\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "						<input type=\"text\" id=\"DNS_IP_1_03\" name=\"DNS_IP_1_03\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "						<input type=\"text\" id=\"DNS_IP_1_04\" name=\"DNS_IP_1_04\" size=\"3\" maxlength=\"3\">\n"; 
echo "						<input type=\"hidden\" name=\"DNS_IP_1\">\n"; 
echo "					</div>\n"; 
echo "					</td></tr>\n"; 
echo "				<tr id=\"TR_dns_type_2\" style=\"display:none\"><td>Second DNS Server</td><td>\n"; 
echo "					<select id=\"dns_type_2\" name=\"dns_type_2\" onchange=\"do_change(this.value,'2')\">\n"; 
echo "						<option value=\"0\">None</option>\n"; 
echo "						<option value=\"1\">From ISP</option>\n"; 
echo "						<option value=\"2\">User Define</option>		\n"; 
echo "					</select>\n"; 
echo "					<span id=\"dns_2\" name=\"dns_2\" style=\"visibility:hidden\">\n"; 
echo "						<input type=\"text\" id=\"DNS_IP_2_01\" name=\"DNS_IP_2_01\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "						<input type=\"text\" id=\"DNS_IP_2_02\" name=\"DNS_IP_2_02\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "						<input type=\"text\" id=\"DNS_IP_2_03\" name=\"DNS_IP_2_03\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "						<input type=\"text\" id=\"DNS_IP_2_04\" name=\"DNS_IP_2_04\" size=\"3\" maxlength=\"3\">\n"; 
echo "						<input type=\"hidden\" name=\"DNS_IP_2\">\n"; 
echo "					</div>\n"; 
echo "					</td></tr>\n"; 
echo "				<tr id=\"TR_dns_type_3\" style=\"display:none\"><td>Third DNS Server</td><td>\n"; 
echo "					<select id=\"dns_type_3\" name=\"dns_type_3\" onchange=\"do_change(this.value,'3')\">\n"; 
echo "						<option value=\"0\">None</option>\n"; 
echo "						<option value=\"1\">From ISP</option>\n"; 
echo "						<option value=\"2\">User Define</option>		\n"; 
echo "					</select>\n"; 
echo "					<span id=\"dns_3\" name=\"dns_3\" style=\"visibility:hidden\">\n"; 
echo "						<input type=\"text\" id=\"DNS_IP_3_01\" name=\"DNS_IP_3_01\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "						<input type=\"text\" id=\"DNS_IP_3_02\" name=\"DNS_IP_3_02\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "						<input type=\"text\" id=\"DNS_IP_3_03\" name=\"DNS_IP_3_03\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "						<input type=\"text\" id=\"DNS_IP_3_04\" name=\"DNS_IP_3_04\" size=\"3\" maxlength=\"3\">\n"; 
echo "						<input type=\"hidden\" name=\"DNS_IP_3\">\n"; 
echo "					</span>\n"; 
echo "					</td></tr>\n"; 
echo "				<tr id=\"TR_DHCPD_LEASE_TIME\" style=\"display:none\"><td>Max lease time (minutes)</td><td>\n"; 
echo "						<input type=\"text\" id=\"DHCPD_LEASE_TIME\" name=\"DHCPD_LEASE_TIME\" size=\"15\" maxlength=\"8\">\n"; 
echo "					</td></tr>\n"; 
echo "				</tbody>\n"; 
echo "			</table>\n"; 
echo "			<input type=\"hidden\" name=\"btnSubmit\">\n"; 
echo "			<input type=\"hidden\" name=\"DHCPD_DNS\">\n"; 
echo "\n"; 
echo "		</FIELDSET>\n"; 
echo "\n"; 
echo "		<FIELDSET id=\"DHCPhostField\">\n"; 
echo "		<legend>Permanent Host Configuration</legend>\n"; 
echo "			<table align=center>\n"; 
echo "			<tr id=\"TR_DHCPD_STATIC_LEASE\" style=\"display:none\"><td>\n"; 
echo "			<table id=\"pf\" class=\"pf_tbl\" cellpadding=\"5\">\n"; 
echo "				<tr><th>No.</th><th>Enable</th><th>MAC Address</th><th>IP</th><th>Delete</th></tr>\n"; 
echo "			</table>\n"; 
echo "			<input type=\"button\" id=\"Insert\" name=\"Insert\" value=\"Insert\" onclick=\"fp_insert()\">\n"; 
echo "			</td></tr>\n"; 
echo "			</table>\n"; 
echo "		</FIELDSET>\n"; 
echo "		</form>\n"; 
echo "	</div>\n"; 
echo "	<div>\n"; 
echo "		<table style=\"width:600px;height:25px;text-align:center\">\n"; 
echo "			<tr>\n"; 
echo "				<td width=\"210\"></td>\n"; 
echo "				<td id=\"clear_btn\" class=\"td_btn\" onclick=\"location.reload()\">Undo</td>\n"; 
echo "				<td width=\"30\"></td>\n"; 
echo "				<td id=\"submit_btn\" class=\"td_btn\" onclick=\"Validate(document.forms[0])\">Apply</td>\n"; 
echo "				<td width=\"210\"></td>\n"; 
echo "			</tr>\n"; 
echo "		</table>\n"; 
echo "	</div>\n"; 
echo "</div>\n"; 
echo "</body>\n"; 
echo "</html>\n";
?>