<?php
echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "<title></title>\n"; 
echo "<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "<script type=\"text/javascript\" src=\"comm.js\"></script>\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "<!--\n"; 
echo "var VOIP_SERVER_REGISTRAR_ADDR,VOIP_SERVER_REGISTRAR_PORT,VOIP_SERVER_REGISTRAR_EXPIRY,VOIP_SERVER_PROXY_ADDR,VOIP_SERVER_PROXY_PORT,\n"; 
echo "VOIP_SERVER_OUTBOUND_ADDR,VOIP_SERVER_OUTBOUND_PORT,VOIP_SERVER_STUN_ADDR,VOIP_SERVER_STUN_PORT,VOIP_FXS_1_USERNAME,\n"; 
echo "VOIP_FXS_1_DISPLAYNAME,VOIP_FXS_1_AUTHNAME,VOIP_FXS_1_PASSWORD,VOIP_FXS_1_AUTO_DECLINE,VOIP_FXS_1_DND, VOIP_FXS_1_HIDE_USER_ID,VOIP_FXS_1_DTMF,VOIP_FXS_1_PREFER_1ST_CODEC,VOIP_FXS_1_PREFER_2ND_CODEC, VOIP_FXS_1_PREFER_3RD_CODEC,VOIP_FXS_1_PREFER_4TH_CODEC,VOIP_FXS_1_PREFER_5TH_CODEC,VOIP_FXS_1_PREFER_6TH_CODEC, VOIP_FXS_1_PREFER_7TH_CODEC,VOIP_FXS_1_PREFER_8TH_CODEC,VOIP_FXS_1_PREFER_9TH_CODEC,VOIP_COMM_SIP_DOMAIN,\n"; 
echo "VOIP_PROF1_LINE1_ENABLE,VOIP_FXS_1_VAD,VOIP_FXS_1_CALLERID_TYPE,VOIP_FXS_1_CALLERID_DISP,VOIP_FXS_1_CALLERID_POWER,\n"; 
echo "VOIP_AUTO_PROVISION_ENABLE,VOIP_AUTO_PROVISION_FTP_ADDRESS,VOIP_AUTO_PROVISION_FTP_TIMEOUT,\n"; 
echo "VOIP_AUTO_PROVISION_FTP_RETRY,VOIP_AUTO_PROVISION_FTP_FILE_NAME,VOIP_AUTO_PROVISION_FTP_USER_NAME,\n"; 
echo "VOIP_AUTO_PROVISION_FTP_USER_PASSWORD,VOIP_FXS_1_FLASH_DET_UPLV,VOIP_FXS_1_FLASH_DET_LOWLV,\n"; 
echo "VOIP_FXS_1_VOGAIN_TX_LV,VOIP_FXS_1_VOGAIN_RX_LV,VOIP_FXS_1_TONE_TYPE,VOIP_FXS_1_RING_IMPEDENCE,\n"; 
echo "VOIP_FXS_2_USERNAME,VOIP_FXS_2_DISPLAYNAME,VOIP_FXS_2_AUTHNAME,VOIP_FXS_2_PASSWORD,\n"; 
echo "VOIP_FXS_2_AUTO_DECLINE,VOIP_FXS_2_DND,VOIP_FXS_2_HIDE_USER_ID,VOIP_FXS_2_DTMF,\n"; 
echo "VOIP_FXS_2_PREFER_1ST_CODEC,VOIP_FXS_2_PREFER_2ND_CODEC,VOIP_FXS_2_PREFER_3RD_CODEC,\n"; 
echo "VOIP_FXS_2_PREFER_4TH_CODEC,VOIP_FXS_2_PREFER_5TH_CODEC,VOIP_FXS_2_PREFER_6TH_CODEC, VOIP_FXS_2_PREFER_7TH_CODEC,VOIP_FXS_2_PREFER_8TH_CODEC,VOIP_FXS_2_PREFER_9TH_CODEC,\n"; 
echo "VOIP_PROF1_LINE2_ENABLE,VOIP_FXS_2_VAD,VOIP_FXS_2_CALLERID_TYPE,VOIP_FXS_2_CALLERID_DISP,\n"; 
echo "VOIP_FXS_2_CALLERID_POWER,VOIP_FXS_2_FLASH_DET_UPLV,VOIP_FXS_2_FLASH_DET_LOWLV,\n"; 
echo "VOIP_FXS_2_VOGAIN_TX_LV,VOIP_FXS_2_VOGAIN_RX_LV,VOIP_FXS_2_TONE_TYPE,VOIP_FXS_2_RING_IMPEDENCE;\n"; 
echo "\n"; 
echo "function checkPort(obj)\n"; 
echo "{\n"; 
echo "	var d = parseInt(obj.value,10);\n"; 
echo "	if( !(d<65536 && d>=0) || isNaN(d))\n"; 
echo "	{\n"; 
echo "		alert(\"Port Number must be located between 0 ~ 65535\");\n"; 
echo "		obj.select();\n"; 
echo "		return false;\n"; 
echo "	}\n"; 
echo "	return true;\n"; 
echo "}\n"; 
echo "\n"; 
echo "function Validate (passForm) {\n"; 
echo "\n"; 
echo "	if(!checkPort(passForm.VOIP_SERVER_REGISTRAR_PORT) || !checkPort(passForm.VOIP_SERVER_PROXY_PORT) || !checkPort(passForm.VOIP_SERVER_OUTBOUND_PORT) || !checkPort(passForm.VOIP_SERVER_STUN_PORT))\n"; 
echo "		return	;\n"; 
echo "\n"; 
echo "	if(!CheckValue(passForm.VOIP_SERVER_REGISTRAR_EXPIRY,60,65535))\n"; 
echo "		return;\n"; 
echo "\n"; 
echo "	if( passForm.VOIP_FXS_1_PASSWORD.value != passForm.CVOIP_FXS_1_PASSWORD.value)\n"; 
echo "	{\n"; 
echo "		alert(\"Password Confirm failed\");\n"; 
echo "		assForm.VOIP_FXS_1_PASSWORD.select();\n"; 
echo "		return;\n"; 
echo "	}\n"; 
echo "	if(!CheckValue(passForm.VOIP_FXS_1_FLASH_DET_UPLV,100,2000))\n"; 
echo "		return;\n"; 
echo "\n"; 
echo "	if(!CheckValue(passForm.VOIP_FXS_1_FLASH_DET_LOWLV,100,2000))\n"; 
echo "		return;\n"; 
echo "\n"; 
echo "\n"; 
echo "	if( passForm.VOIP_FXS_2_PASSWORD.value != passForm.CVOIP_FXS_2_PASSWORD.value)\n"; 
echo "	{\n"; 
echo "		alert(\"Password Confirm failed\");\n"; 
echo "		assForm.VOIP_FXS_2_PASSWORD.select();\n"; 
echo "		return;\n"; 
echo "	}\n"; 
echo "	if(!CheckValue(passForm.VOIP_FXS_2_FLASH_DET_UPLV,100,2000))\n"; 
echo "		return;\n"; 
echo "\n"; 
echo "	if(!CheckValue(passForm.VOIP_FXS_2_FLASH_DET_LOWLV,100,2000))\n"; 
echo "		return;\n"; 
echo "\n"; 
echo "	if(!CheckValue(passForm.VOIP_AUTO_PROVISION_FTP_TIMEOUT,10,60))\n"; 
echo "		return;\n"; 
echo "\n"; 
echo "	if(!CheckValue(passForm.VOIP_AUTO_PROVISION_FTP_RETRY,1,5))\n"; 
echo "		return;\n"; 
echo "\n"; 
echo "	passForm.sid.value = sid;\n"; 
echo "	passForm.submit();\n"; 
echo "}\n"; 
echo "\n"; 
echo "function InitDisplay(response)\n"; 
echo "{\n"; 
echo "	var token = response.split(\";\");\n"; 
echo "\n"; 
echo "	VOIP_SERVER_REGISTRAR_ADDR = token[0];\n"; 
echo "	VOIP_SERVER_REGISTRAR_PORT = token[1];\n"; 
echo "	VOIP_SERVER_PROXY_ADDR = token[2];\n"; 
echo "	VOIP_SERVER_PROXY_PORT = token[3];\n"; 
echo "	VOIP_SERVER_OUTBOUND_ADDR = token[4];\n"; 
echo "	VOIP_SERVER_OUTBOUND_PORT = token[5];\n"; 
echo "	VOIP_SERVER_STUN_ADDR = token[6];\n"; 
echo "	VOIP_SERVER_STUN_PORT = token[7];\n"; 
echo "	VOIP_FXS_1_USERNAME = token[8];\n"; 
echo "	VOIP_FXS_1_DISPLAYNAME = token[9];\n"; 
echo "	VOIP_FXS_1_AUTHNAME = token[10];\n"; 
echo "	VOIP_FXS_1_PASSWORD = token[11];\n"; 
echo "	VOIP_FXS_1_AUTO_DECLINE = token[12];\n"; 
echo "	VOIP_FXS_1_DND = token[13];\n"; 
echo "	VOIP_FXS_1_HIDE_USER_ID = token[14];\n"; 
echo "	VOIP_FXS_1_DTMF = token[15];\n"; 
echo "	VOIP_FXS_1_PREFER_1ST_CODEC = token[16];\n"; 
echo "	VOIP_FXS_1_PREFER_2ND_CODEC = token[17];\n"; 
echo "	VOIP_FXS_1_PREFER_3RD_CODEC = token[18];\n"; 
echo "	VOIP_FXS_1_PREFER_4TH_CODEC  = token[19];\n"; 
echo "	VOIP_FXS_1_PREFER_5TH_CODEC  = token[20];\n"; 
echo "	VOIP_FXS_1_PREFER_6TH_CODEC  = token[21];\n"; 
echo "	VOIP_FXS_1_PREFER_7TH_CODEC  = token[22];\n"; 
echo "	VOIP_FXS_1_PREFER_8TH_CODEC  = token[23];\n"; 
echo "	VOIP_FXS_1_PREFER_9TH_CODEC  = token[24];\n"; 
echo "	VOIP_COMM_SIP_DOMAIN = token[25];\n"; 
echo "	VOIP_PROF1_LINE1_ENABLE = token[26];\n"; 
echo "	VOIP_FXS_1_VAD = token[27];\n"; 
echo "	VOIP_FXS_1_CALLERID_TYPE = token[28];\n"; 
echo "	VOIP_FXS_1_CALLERID_DISP = token[29];\n"; 
echo "	VOIP_FXS_1_CALLERID_POWER = token[30];\n"; 
echo "\n"; 
echo "	VOIP_AUTO_PROVISION_ENABLE = token[31];\n"; 
echo "	VOIP_AUTO_PROVISION_FTP_ADDRESS = token[32];\n"; 
echo "	VOIP_AUTO_PROVISION_FTP_TIMEOUT = token[33];\n"; 
echo "	VOIP_AUTO_PROVISION_FTP_RETRY = token[34];\n"; 
echo "	VOIP_AUTO_PROVISION_FTP_FILE_NAME = token[35];\n"; 
echo "	VOIP_AUTO_PROVISION_FTP_USER_NAME = token[36];\n"; 
echo "	VOIP_AUTO_PROVISION_FTP_USER_PASSWORD = token[37];\n"; 
echo "\n"; 
echo "	VOIP_FXS_1_FLASH_DET_UPLV = token[38];\n"; 
echo "	VOIP_FXS_1_FLASH_DET_LOWLV = token[39];\n"; 
echo "	VOIP_FXS_1_VOGAIN_TX_LV = token[40];\n"; 
echo "	VOIP_FXS_1_VOGAIN_RX_LV = token[41];\n"; 
echo "	VOIP_FXS_1_TONE_TYPE = token[42];\n"; 
echo "	VOIP_FXS_1_RING_IMPEDENCE = token[43];\n"; 
echo "\n"; 
echo "	VOIP_FXS_2_USERNAME = token[44];\n"; 
echo "	VOIP_FXS_2_DISPLAYNAME = token[45];\n"; 
echo "	VOIP_FXS_2_AUTHNAME = token[46];\n"; 
echo "	VOIP_FXS_2_PASSWORD = token[47];\n"; 
echo "	VOIP_FXS_2_AUTO_DECLINE = token[48];\n"; 
echo "	VOIP_FXS_2_DND = token[49];\n"; 
echo "	VOIP_FXS_2_HIDE_USER_ID = token[50];\n"; 
echo "	VOIP_FXS_2_DTMF = token[51];\n"; 
echo "	VOIP_FXS_2_PREFER_1ST_CODEC = token[52];\n"; 
echo "	VOIP_FXS_2_PREFER_2ND_CODEC = token[53];\n"; 
echo "	VOIP_FXS_2_PREFER_3RD_CODEC = token[54];\n"; 
echo "	VOIP_FXS_2_PREFER_4TH_CODEC = token[55];\n"; 
echo "	VOIP_FXS_2_PREFER_5TH_CODEC = token[56];\n"; 
echo "	VOIP_FXS_2_PREFER_6TH_CODEC = token[57];\n"; 
echo "	VOIP_FXS_2_PREFER_7TH_CODEC = token[58];\n"; 
echo "	VOIP_FXS_2_PREFER_8TH_CODEC = token[59];\n"; 
echo "	VOIP_FXS_2_PREFER_9TH_CODEC = token[60];\n"; 
echo "	VOIP_PROF1_LINE2_ENABLE = token[61];\n"; 
echo "	VOIP_FXS_2_VAD = token[62];\n"; 
echo "	VOIP_FXS_2_CALLERID_TYPE = token[63];\n"; 
echo "	VOIP_FXS_2_CALLERID_DISP = token[64];\n"; 
echo "	VOIP_FXS_2_CALLERID_POWER = token[65];\n"; 
echo "	VOIP_FXS_2_FLASH_DET_UPLV = token[66];\n"; 
echo "	VOIP_FXS_2_FLASH_DET_LOWLV = token[67];\n"; 
echo "	VOIP_FXS_2_VOGAIN_TX_LV = token[68];\n"; 
echo "	VOIP_FXS_2_VOGAIN_RX_LV = token[69];\n"; 
echo "	VOIP_FXS_2_TONE_TYPE = token[70];\n"; 
echo "	VOIP_FXS_2_RING_IMPEDENCE = token[71];\n"; 
echo "	\n"; 
echo "	VOIP_SERVER_REGISTRAR_EXPIRY = token[72];\n"; 
echo "\n"; 
echo "	tr_display(\"VOIP_SERVER_REGISTRAR_ADDR\");\n"; 
echo "	tr_display(\"VOIP_SERVER_REGISTRAR_PORT\");\n"; 
echo "	tr_display(\"VOIP_SERVER_REGISTRAR_EXPIRY\");\n"; 
echo "	tr_display(\"VOIP_SERVER_PROXY_ADDR\");\n"; 
echo "	tr_display(\"VOIP_SERVER_PROXY_PORT\");\n"; 
echo "	tr_display(\"VOIP_SERVER_OUTBOUND_ADDR\");\n"; 
echo "	tr_display(\"VOIP_SERVER_OUTBOUND_PORT\");\n"; 
echo "	tr_display(\"VOIP_SERVER_STUN_ADDR\");\n"; 
echo "	tr_display(\"VOIP_SERVER_STUN_PORT\");\n"; 
echo "	tr_display(\"VOIP_FXS_1_USERNAME\");\n"; 
echo "	tr_display(\"VOIP_FXS_1_DISPLAYNAME\");\n"; 
echo "	tr_display(\"VOIP_FXS_1_AUTHNAME\");\n"; 
echo "	tr_display(\"VOIP_FXS_1_PASSWORD\",1);\n"; 
echo "	tr_display(\"VOIP_FXS_1_AUTO_DECLINE\");\n"; 
echo "	tr_display(\"VOIP_FXS_1_DND\");\n"; 
echo "	tr_display(\"VOIP_FXS_1_HIDE_USER_ID\");\n"; 
echo "	tr_display(\"VOIP_FXS_1_DTMF\");\n"; 
echo "	tr_display(\"VOIP_FXS_1_PREFER_1ST_CODEC\");\n"; 
echo "	tr_display(\"VOIP_FXS_1_PREFER_2ND_CODEC\");\n"; 
echo "	tr_display(\"VOIP_FXS_1_PREFER_3RD_CODEC\");\n"; 
echo "	tr_display(\"VOIP_FXS_1_PREFER_4TH_CODEC\");\n"; 
echo "	tr_display(\"VOIP_FXS_1_PREFER_5TH_CODEC\");\n"; 
echo "	tr_display(\"VOIP_FXS_1_PREFER_6TH_CODEC\");\n"; 
echo "	tr_display(\"VOIP_FXS_1_PREFER_7TH_CODEC\");\n"; 
echo "	tr_display(\"VOIP_FXS_1_PREFER_8TH_CODEC\");\n"; 
echo "	tr_display(\"VOIP_FXS_1_PREFER_9TH_CODEC\");\n"; 
echo "	tr_display(\"VOIP_COMM_SIP_DOMAIN\");\n"; 
echo "	tr_display(\"VOIP_PROF1_LINE1_ENABLE\");\n"; 
echo "	tr_display(\"VOIP_FXS_1_VAD\");\n"; 
echo "	tr_display(\"VOIP_FXS_1_CALLERID_TYPE\");\n"; 
echo "	tr_display(\"VOIP_FXS_1_CALLERID_DISP\");\n"; 
echo "	tr_display(\"VOIP_FXS_1_CALLERID_POWER\");\n"; 
echo "	tr_display(\"VOIP_AUTO_PROVISION_ENABLE\");\n"; 
echo "	tr_display(\"VOIP_AUTO_PROVISION_FTP_ADDRESS\");\n"; 
echo "	tr_display(\"VOIP_AUTO_PROVISION_FTP_TIMEOUT\");\n"; 
echo "	tr_display(\"VOIP_AUTO_PROVISION_FTP_RETRY\");\n"; 
echo "	tr_display(\"VOIP_AUTO_PROVISION_FTP_FILE_NAME\");\n"; 
echo "	tr_display(\"VOIP_AUTO_PROVISION_FTP_USER_NAME\");\n"; 
echo "	tr_display(\"VOIP_AUTO_PROVISION_FTP_USER_PASSWORD\");\n"; 
echo "	tr_display(\"VOIP_FXS_1_FLASH_DET_UPLV\");\n"; 
echo "	tr_display(\"VOIP_FXS_1_FLASH_DET_LOWLV\");\n"; 
echo "	tr_display(\"VOIP_FXS_1_VOGAIN_TX_LV\");\n"; 
echo "	tr_display(\"VOIP_FXS_1_VOGAIN_RX_LV\");\n"; 
echo "	tr_display(\"VOIP_FXS_1_TONE_TYPE\");\n"; 
echo "	tr_display(\"VOIP_FXS_1_RING_IMPEDENCE\");\n"; 
echo "\n"; 
echo "\n"; 
echo "	tr_display(\"VOIP_FXS_2_USERNAME\");\n"; 
echo "	tr_display(\"VOIP_FXS_2_DISPLAYNAME\");\n"; 
echo "	tr_display(\"VOIP_FXS_2_AUTHNAME\");\n"; 
echo "	tr_display(\"VOIP_FXS_2_PASSWORD\",1);\n"; 
echo "	tr_display(\"VOIP_FXS_2_AUTO_DECLINE\");\n"; 
echo "	tr_display(\"VOIP_FXS_2_DND\");\n"; 
echo "	tr_display(\"VOIP_FXS_2_HIDE_USER_ID\");\n"; 
echo "	tr_display(\"VOIP_FXS_2_DTMF\");\n"; 
echo "	tr_display(\"VOIP_FXS_2_PREFER_1ST_CODEC\");\n"; 
echo "	tr_display(\"VOIP_FXS_2_PREFER_2ND_CODEC\");\n"; 
echo "	tr_display(\"VOIP_FXS_2_PREFER_3RD_CODEC\");\n"; 
echo "	tr_display(\"VOIP_FXS_2_PREFER_4TH_CODEC\");\n"; 
echo "	tr_display(\"VOIP_FXS_2_PREFER_5TH_CODEC\");\n"; 
echo "	tr_display(\"VOIP_FXS_2_PREFER_6TH_CODEC\");\n"; 
echo "	tr_display(\"VOIP_FXS_2_PREFER_7TH_CODEC\");\n"; 
echo "	tr_display(\"VOIP_FXS_2_PREFER_8TH_CODEC\");\n"; 
echo "	tr_display(\"VOIP_FXS_2_PREFER_9TH_CODEC\");\n"; 
echo "	tr_display(\"VOIP_PROF1_LINE2_ENABLE\");\n"; 
echo "	tr_display(\"VOIP_FXS_2_VAD\");\n"; 
echo "	tr_display(\"VOIP_FXS_2_CALLERID_TYPE\");\n"; 
echo "	tr_display(\"VOIP_FXS_2_CALLERID_DISP\");\n"; 
echo "	tr_display(\"VOIP_FXS_2_CALLERID_POWER\");\n"; 
echo "	tr_display(\"VOIP_FXS_2_FLASH_DET_UPLV\");\n"; 
echo "	tr_display(\"VOIP_FXS_2_FLASH_DET_LOWLV\");\n"; 
echo "	tr_display(\"VOIP_FXS_2_VOGAIN_TX_LV\");\n"; 
echo "	tr_display(\"VOIP_FXS_2_VOGAIN_RX_LV\");\n"; 
echo "	tr_display(\"VOIP_FXS_2_TONE_TYPE\");\n"; 
echo "	tr_display(\"VOIP_FXS_2_RING_IMPEDENCE\");\n"; 
echo "\n"; 
echo "\n"; 
echo "	tr_display(\"TD_Register\");\n"; 
echo "	tr_display(\"TD_Proxy\");\n"; 
echo "	tr_display(\"TD_Outbound\");\n"; 
echo "	tr_display(\"TD_Nat\");\n"; 
echo "	tr_display(\"TD_Basic\");\n"; 
echo "	tr_display(\"TD_Advance\");\n"; 
echo "	tr_display(\"TD_Codec\");\n"; 
echo "	tr_display(\"TD_Caller\");\n"; 
echo "	tr_display(\"TD_FXS\");\n"; 
echo "	tr_display(\"TD_Provision\");\n"; 
echo "\n"; 
echo "\n"; 
echo "	obj_readonly(\"VOIP_SERVER_REGISTRAR_ADDR\");\n"; 
echo "	obj_readonly(\"VOIP_SERVER_REGISTRAR_PORT\");\n"; 
echo "	obj_readonly(\"VOIP_SERVER_REGISTRAR_EXPIRY\");\n"; 
echo "	obj_readonly(\"VOIP_SERVER_PROXY_ADDR\");\n"; 
echo "	obj_readonly(\"VOIP_SERVER_PROXY_PORT\");\n"; 
echo "	obj_readonly(\"VOIP_SERVER_OUTBOUND_ADDR\");\n"; 
echo "	obj_readonly(\"VOIP_SERVER_OUTBOUND_PORT\");\n"; 
echo "	obj_readonly(\"VOIP_SERVER_STUN_ADDR\");\n"; 
echo "	obj_readonly(\"VOIP_SERVER_STUN_PORT\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_1_USERNAME\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_1_DISPLAYNAME\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_1_AUTHNAME\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_1_PASSWORD\",\"pass\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_1_AUTO_DECLINE\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_1_DND\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_1_HIDE_USER_ID\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_1_DTMF\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_1_PREFER_1ST_CODEC\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_1_PREFER_2ND_CODEC\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_1_PREFER_3RD_CODEC\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_1_PREFER_4TH_CODEC\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_1_PREFER_5TH_CODEC\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_1_PREFER_6TH_CODEC\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_1_PREFER_7TH_CODEC\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_1_PREFER_8TH_CODEC\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_1_PREFER_9TH_CODEC\");\n"; 
echo "	obj_readonly(\"VOIP_COMM_SIP_DOMAIN\");\n"; 
echo "	obj_readonly(\"VOIP_PROF1_LINE1_ENABLE\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_1_VAD\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_1_CALLERID_TYPE\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_1_CALLERID_DISP\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_1_CALLERID_POWER\");\n"; 
echo "	obj_readonly(\"VOIP_AUTO_PROVISION_ENABLE\");\n"; 
echo "	obj_readonly(\"VOIP_AUTO_PROVISION_FTP_ADDRESS\");\n"; 
echo "	obj_readonly(\"VOIP_AUTO_PROVISION_FTP_TIMEOUT\");\n"; 
echo "	obj_readonly(\"VOIP_AUTO_PROVISION_FTP_RETRY\");\n"; 
echo "	obj_readonly(\"VOIP_AUTO_PROVISION_FTP_FILE_NAME\");\n"; 
echo "	obj_readonly(\"VOIP_AUTO_PROVISION_FTP_USER_NAME\");\n"; 
echo "	obj_readonly(\"VOIP_AUTO_PROVISION_FTP_USER_PASSWORD\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_1_FLASH_DET_UPLV\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_1_FLASH_DET_LOWLV\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_1_VOGAIN_TX_LV\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_1_VOGAIN_RX_LV\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_1_TONE_TYPE\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_1_RING_IMPEDENCE\");\n"; 
echo "\n"; 
echo "	obj_readonly(\"VOIP_FXS_2_USERNAME\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_2_DISPLAYNAME\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_2_AUTHNAME\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_2_PASSWORD\",\"pass\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_2_AUTO_DECLINE\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_2_DND\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_2_HIDE_USER_ID\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_2_DTMF\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_2_PREFER_1ST_CODEC\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_2_PREFER_2ND_CODEC\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_2_PREFER_3RD_CODEC\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_2_PREFER_4TH_CODEC\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_2_PREFER_5TH_CODEC\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_2_PREFER_6TH_CODEC\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_2_PREFER_7TH_CODEC\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_2_PREFER_8TH_CODEC\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_2_PREFER_9TH_CODEC\");\n"; 
echo "	obj_readonly(\"VOIP_PROF1_LINE2_ENABLE\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_2_VAD\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_2_CALLERID_TYPE\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_2_CALLERID_DISP\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_2_CALLERID_POWER\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_2_FLASH_DET_UPLV\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_2_FLASH_DET_LOWLV\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_2_VOGAIN_TX_LV\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_2_VOGAIN_RX_LV\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_2_TONE_TYPE\");\n"; 
echo "	obj_readonly(\"VOIP_FXS_2_RING_IMPEDENCE\");\n"; 
echo "\n"; 
echo "	InitValue(document.forms[0]);\n"; 
echo "}\n"; 
echo "function InitValue(passForm) {\n"; 
echo "\n"; 
echo "	passForm.VOIP_SERVER_REGISTRAR_ADDR.value=VOIP_SERVER_REGISTRAR_ADDR;\n"; 
echo "	passForm.VOIP_SERVER_REGISTRAR_PORT.value=VOIP_SERVER_REGISTRAR_PORT;\n"; 
echo "	passForm.VOIP_SERVER_REGISTRAR_EXPIRY.value=VOIP_SERVER_REGISTRAR_EXPIRY;\n"; 
echo "\n"; 
echo "	passForm.VOIP_SERVER_PROXY_ADDR.value=VOIP_SERVER_PROXY_ADDR;\n"; 
echo "	passForm.VOIP_SERVER_PROXY_PORT.value=VOIP_SERVER_PROXY_PORT;\n"; 
echo "\n"; 
echo "	passForm.VOIP_SERVER_OUTBOUND_ADDR.value=VOIP_SERVER_OUTBOUND_ADDR;\n"; 
echo "	passForm.VOIP_SERVER_OUTBOUND_PORT.value=VOIP_SERVER_OUTBOUND_PORT;\n"; 
echo "\n"; 
echo "	passForm.VOIP_SERVER_STUN_ADDR.value=VOIP_SERVER_STUN_ADDR;\n"; 
echo "	passForm.VOIP_SERVER_STUN_PORT.value=VOIP_SERVER_STUN_PORT;\n"; 
echo "\n"; 
echo "	passForm.VOIP_FXS_1_USERNAME.value = VOIP_FXS_1_USERNAME;\n"; 
echo "	passForm.VOIP_FXS_1_DISPLAYNAME.value = VOIP_FXS_1_DISPLAYNAME;\n"; 
echo "	passForm.VOIP_FXS_1_AUTHNAME.value = VOIP_FXS_1_AUTHNAME;\n"; 
echo "	passForm.VOIP_FXS_1_PASSWORD.value = VOIP_FXS_1_PASSWORD;\n"; 
echo "	passForm.CVOIP_FXS_1_PASSWORD.value = VOIP_FXS_1_PASSWORD;\n"; 
echo "\n"; 
echo "	passForm.VOIP_FXS_1_AUTO_DECLINE.checked = (VOIP_FXS_1_AUTO_DECLINE == '1')? true : false;\n"; 
echo "	passForm.VOIP_FXS_1_DND.checked = (VOIP_FXS_1_DND == '1')? true : false;\n"; 
echo "	passForm.VOIP_FXS_1_HIDE_USER_ID.checked = (VOIP_FXS_1_HIDE_USER_ID == '1')? true : false;\n"; 
echo "	passForm.VOIP_FXS_1_DTMF.value = VOIP_FXS_1_DTMF;\n"; 
echo "\n"; 
echo "	passForm.VOIP_FXS_1_PREFER_1ST_CODEC.value = VOIP_FXS_1_PREFER_1ST_CODEC;\n"; 
echo "	passForm.VOIP_FXS_1_PREFER_2ND_CODEC.value = VOIP_FXS_1_PREFER_2ND_CODEC;\n"; 
echo "	passForm.VOIP_FXS_1_PREFER_3RD_CODEC.value = VOIP_FXS_1_PREFER_3RD_CODEC;\n"; 
echo "	passForm.VOIP_FXS_1_PREFER_4TH_CODEC.value = VOIP_FXS_1_PREFER_4TH_CODEC;\n"; 
echo "	passForm.VOIP_FXS_1_PREFER_5TH_CODEC.value = VOIP_FXS_1_PREFER_5TH_CODEC;\n"; 
echo "	passForm.VOIP_FXS_1_PREFER_6TH_CODEC.value = VOIP_FXS_1_PREFER_6TH_CODEC;\n"; 
echo "	passForm.VOIP_FXS_1_PREFER_7TH_CODEC.value = VOIP_FXS_1_PREFER_7TH_CODEC;\n"; 
echo "	passForm.VOIP_FXS_1_PREFER_8TH_CODEC.value = VOIP_FXS_1_PREFER_8TH_CODEC;\n"; 
echo "	passForm.VOIP_FXS_1_PREFER_9TH_CODEC.value = VOIP_FXS_1_PREFER_9TH_CODEC;\n"; 
echo "\n"; 
echo "	passForm.VOIP_COMM_SIP_DOMAIN.value = VOIP_COMM_SIP_DOMAIN;\n"; 
echo "\n"; 
echo "	passForm.VOIP_PROF1_LINE1_ENABLE.checked = (VOIP_PROF1_LINE1_ENABLE == '1')? true : false;\n"; 
echo "\n"; 
echo "	passForm.VOIP_FXS_1_VAD.value = VOIP_FXS_1_VAD;\n"; 
echo "\n"; 
echo "	passForm.VOIP_FXS_1_CALLERID_TYPE.value = VOIP_FXS_1_CALLERID_TYPE;\n"; 
echo "	passForm.VOIP_FXS_1_CALLERID_DISP.value = VOIP_FXS_1_CALLERID_DISP;\n"; 
echo "	passForm.VOIP_FXS_1_CALLERID_POWER.value = VOIP_FXS_1_CALLERID_POWER;\n"; 
echo "\n"; 
echo "	passForm.VOIP_AUTO_PROVISION_ENABLE.checked = (VOIP_AUTO_PROVISION_ENABLE == '1')? true : false;\n"; 
echo "	passForm.VOIP_AUTO_PROVISION_FTP_ADDRESS.value = VOIP_AUTO_PROVISION_FTP_ADDRESS;\n"; 
echo "	passForm.VOIP_AUTO_PROVISION_FTP_TIMEOUT.value = VOIP_AUTO_PROVISION_FTP_TIMEOUT;\n"; 
echo "	passForm.VOIP_AUTO_PROVISION_FTP_RETRY.value = VOIP_AUTO_PROVISION_FTP_RETRY;\n"; 
echo "	passForm.VOIP_AUTO_PROVISION_FTP_FILE_NAME.value = VOIP_AUTO_PROVISION_FTP_FILE_NAME;\n"; 
echo "	passForm.VOIP_AUTO_PROVISION_FTP_USER_NAME.value = VOIP_AUTO_PROVISION_FTP_USER_NAME;\n"; 
echo "	passForm.VOIP_AUTO_PROVISION_FTP_USER_PASSWORD.value = VOIP_AUTO_PROVISION_FTP_USER_PASSWORD;\n"; 
echo "\n"; 
echo "\n"; 
echo "	passForm.VOIP_FXS_1_FLASH_DET_UPLV.value = VOIP_FXS_1_FLASH_DET_UPLV;\n"; 
echo "	passForm.VOIP_FXS_1_FLASH_DET_LOWLV.value = VOIP_FXS_1_FLASH_DET_LOWLV;\n"; 
echo "	passForm.VOIP_FXS_1_VOGAIN_TX_LV.value = VOIP_FXS_1_VOGAIN_TX_LV;\n"; 
echo "	passForm.VOIP_FXS_1_VOGAIN_RX_LV.value = VOIP_FXS_1_VOGAIN_RX_LV;\n"; 
echo "	passForm.VOIP_FXS_1_TONE_TYPE.value = VOIP_FXS_1_TONE_TYPE;\n"; 
echo "	passForm.VOIP_FXS_1_RING_IMPEDENCE.value = VOIP_FXS_1_RING_IMPEDENCE;\n"; 
echo "\n"; 
echo "\n"; 
echo "	passForm.VOIP_FXS_2_USERNAME.value = VOIP_FXS_2_USERNAME;\n"; 
echo "	passForm.VOIP_FXS_2_DISPLAYNAME.value = VOIP_FXS_2_DISPLAYNAME;\n"; 
echo "	passForm.VOIP_FXS_2_AUTHNAME.value = VOIP_FXS_2_AUTHNAME;\n"; 
echo "	passForm.VOIP_FXS_2_PASSWORD.value = VOIP_FXS_2_PASSWORD;\n"; 
echo "	passForm.CVOIP_FXS_2_PASSWORD.value = VOIP_FXS_2_PASSWORD;\n"; 
echo "	passForm.VOIP_FXS_2_AUTO_DECLINE.checked = (VOIP_FXS_2_AUTO_DECLINE == '1')? true : false;\n"; 
echo "	passForm.VOIP_FXS_2_DND.checked = (VOIP_FXS_2_DND == '1')? true : false;\n"; 
echo "	passForm.VOIP_FXS_2_HIDE_USER_ID.checked = (VOIP_FXS_2_HIDE_USER_ID == '1')? true : false;\n"; 
echo "	passForm.VOIP_FXS_2_DTMF.value = VOIP_FXS_2_DTMF;\n"; 
echo "	passForm.VOIP_FXS_2_PREFER_1ST_CODEC.value = VOIP_FXS_2_PREFER_1ST_CODEC;\n"; 
echo "	passForm.VOIP_FXS_2_PREFER_2ND_CODEC.value = VOIP_FXS_2_PREFER_2ND_CODEC;\n"; 
echo "	passForm.VOIP_FXS_2_PREFER_3RD_CODEC.value = VOIP_FXS_2_PREFER_3RD_CODEC;\n"; 
echo "	passForm.VOIP_FXS_2_PREFER_4TH_CODEC.value = VOIP_FXS_2_PREFER_4TH_CODEC;\n"; 
echo "	passForm.VOIP_FXS_2_PREFER_5TH_CODEC.value = VOIP_FXS_2_PREFER_5TH_CODEC;\n"; 
echo "	passForm.VOIP_FXS_2_PREFER_6TH_CODEC.value = VOIP_FXS_2_PREFER_6TH_CODEC;\n"; 
echo "	passForm.VOIP_FXS_2_PREFER_7TH_CODEC.value = VOIP_FXS_2_PREFER_7TH_CODEC;\n"; 
echo "	passForm.VOIP_FXS_2_PREFER_8TH_CODEC.value = VOIP_FXS_2_PREFER_8TH_CODEC;\n"; 
echo "	passForm.VOIP_FXS_2_PREFER_9TH_CODEC.value = VOIP_FXS_2_PREFER_9TH_CODEC;\n"; 
echo "	passForm.VOIP_PROF1_LINE2_ENABLE.checked = (VOIP_PROF1_LINE2_ENABLE == '1')? true : false;\n"; 
echo "	passForm.VOIP_FXS_2_VAD.value = VOIP_FXS_2_VAD;\n"; 
echo "	passForm.VOIP_FXS_2_CALLERID_TYPE.value = VOIP_FXS_2_CALLERID_TYPE;\n"; 
echo "	passForm.VOIP_FXS_2_CALLERID_DISP.value = VOIP_FXS_2_CALLERID_DISP;\n"; 
echo "	passForm.VOIP_FXS_2_CALLERID_POWER.value = VOIP_FXS_2_CALLERID_POWER;\n"; 
echo "	passForm.VOIP_FXS_2_FLASH_DET_UPLV.value = VOIP_FXS_2_FLASH_DET_UPLV;\n"; 
echo "	passForm.VOIP_FXS_2_FLASH_DET_LOWLV.value = VOIP_FXS_2_FLASH_DET_LOWLV;\n"; 
echo "	passForm.VOIP_FXS_2_VOGAIN_TX_LV.value = VOIP_FXS_2_VOGAIN_TX_LV;\n"; 
echo "	passForm.VOIP_FXS_2_VOGAIN_RX_LV.value = VOIP_FXS_2_VOGAIN_RX_LV;\n"; 
echo "	passForm.VOIP_FXS_2_TONE_TYPE.value = VOIP_FXS_2_TONE_TYPE;\n"; 
echo "	passForm.VOIP_FXS_2_RING_IMPEDENCE.value = VOIP_FXS_2_RING_IMPEDENCE;\n"; 
echo "\n"; 
echo "	top.loading = 0;\n"; 
echo "	setInterval('ajax_get_signals()',2000);\n"; 
echo "}\n"; 
echo "//-->\n"; 
echo "</script>\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body onload=\"init_obj();setTimeout('ajax_get_key()',500);\">\n"; 
echo "<div id=\"main_div\">\n"; 
echo "	<div id=\"container\">\n"; 
echo "		<form method=\"POST\" action=\"ajax.php?action=net_voip\">\n"; 
echo "			<input type=\"hidden\" name=\"sid\" id=\"sid\">\n"; 
echo "			<table>\n"; 
echo "			<tr><td id=\"TR_TD_Register\" style=\"display:none\">\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>SIP Server-Registrar Server</legend>\n"; 
echo "				<table>\n"; 
echo "					<tr id=\"TR_VOIP_SERVER_REGISTRAR_ADDR\" style=\"display:none\"><td>IP Address</td><td>\n"; 
echo "						<input type=\"text\" id=\"VOIP_SERVER_REGISTRAR_ADDR\" name=\"VOIP_SERVER_REGISTRAR_ADDR\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_SERVER_REGISTRAR_PORT\" style=\"display:none\"><td>Port Number</td><td>\n"; 
echo "						<input type=\"text\" id=\"VOIP_SERVER_REGISTRAR_PORT\" name=\"VOIP_SERVER_REGISTRAR_PORT\" size=\"5\" maxlength=\"5\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_SERVER_REGISTRAR_EXPIRY\" style=\"display:none\"><td>Register Period Time</td><td>\n"; 
echo "						<input type=\"text\" id=\"VOIP_SERVER_REGISTRAR_EXPIRY\" name=\"VOIP_SERVER_REGISTRAR_EXPIRY\" size=\"5\" maxlength=\"5\">  seconds\n"; 
echo "					</td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td><td id=\"TR_TD_Proxy\" style=\"display:none\">\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>SIP Server-Proxy Server</legend>\n"; 
echo "				<table>\n"; 
echo "					<tr id=\"TR_VOIP_SERVER_PROXY_ADDR\" style=\"display:none\"><td>IP Address</td><td>\n"; 
echo "						<input type=\"text\" id=\"VOIP_SERVER_PROXY_ADDR\" name=\"VOIP_SERVER_PROXY_ADDR\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_SERVER_PROXY_PORT\" style=\"display:none\"><td>Port Number</td><td>\n"; 
echo "						<input type=\"text\" id=\"VOIP_SERVER_PROXY_PORT\" name=\"VOIP_SERVER_PROXY_PORT\" size=\"5\" maxlength=\"5\">\n"; 
echo "					</td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td></tr>\n"; 
echo "			<tr><td id=\"TR_TD_Outbound\" style=\"display:none\">\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>SIP Server-Outbound Server</legend>\n"; 
echo "				<table>\n"; 
echo "					<tr id=\"TR_VOIP_SERVER_OUTBOUND_ADDR\" style=\"display:none\"><td>IP Address</td><td>\n"; 
echo "						<input type=\"text\" id=\"VOIP_SERVER_OUTBOUND_ADDR\" name=\"VOIP_SERVER_OUTBOUND_ADDR\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_SERVER_OUTBOUND_PORT\" style=\"display:none\"><td>Port Number</td><td>\n"; 
echo "						<input type=\"text\" id=\"VOIP_SERVER_OUTBOUND_PORT\" name=\"VOIP_SERVER_OUTBOUND_PORT\" size=\"5\" maxlength=\"5\">\n"; 
echo "					</td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td><td id=\"TR_TD_Nat\" style=\"display:none\">\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>SIP Server-NAT Traversal</legend>\n"; 
echo "				<table>\n"; 
echo "					<tr id=\"TR_VOIP_SERVER_STUN_ADDR\" style=\"display:none\"><td>STUN Server</td><td>\n"; 
echo "						<input type=\"text\" id=\"VOIP_SERVER_STUN_ADDR\" name=\"VOIP_SERVER_STUN_ADDR\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_SERVER_STUN_PORT\" style=\"display:none\"><td>Port Number</td><td>\n"; 
echo "						<input type=\"text\" id=\"VOIP_SERVER_STUN_PORT\" name=\"VOIP_SERVER_STUN_PORT\" size=\"5\" maxlength=\"5\">\n"; 
echo "					</td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td></tr>\n"; 
echo "			<tr id=\"TR_TD_Basic\" style=\"display:none\"><td>\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>Line 1 Basic Setting</legend>\n"; 
echo "				<table>\n"; 
echo "					<tr id=\"TR_VOIP_PROF1_LINE1_ENABLE\" style=\"display:none\"><td>Registration Account</td><td>\n"; 
echo "						<input type=\"checkbox\" id=\"VOIP_PROF1_LINE1_ENABLE\" name=\"VOIP_PROF1_LINE1_ENABLE\">\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "					<tr id=\"TR_VOIP_COMM_SIP_DOMAIN\" style=\"display:none\"><td>User Domain</td><td>\n"; 
echo "						<input type=\"text\" id=\"VOIP_COMM_SIP_DOMAIN\" name=\"VOIP_COMM_SIP_DOMAIN\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_1_USERNAME\" style=\"display:none\"><td>Number</td><td>\n"; 
echo "						<input type=\"text\" id=\"VOIP_FXS_1_USERNAME\" name=\"VOIP_FXS_1_USERNAME\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_1_DISPLAYNAME\" style=\"display:none\"><td>Display Name</td><td>\n"; 
echo "						<input type=\"text\" id=\"VOIP_FXS_1_DISPLAYNAME\" name=\"VOIP_FXS_1_DISPLAYNAME\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_1_AUTHNAME\" style=\"display:none\"><td>Authentication Name</td><td>\n"; 
echo "						<input type=\"text\" id=\"VOIP_FXS_1_AUTHNAME\" name=\"VOIP_FXS_1_AUTHNAME\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_1_PASSWORD\" style=\"display:none\"><td>Password</td><td>\n"; 
echo "						<input type=\"password\" id=\"VOIP_FXS_1_PASSWORD\" name=\"VOIP_FXS_1_PASSWORD\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_CVOIP_FXS_1_PASSWORD\" style=\"display:none\"><td>Password Confirm</td><td>\n"; 
echo "						<input type=\"password\" id=\"CVOIP_FXS_1_PASSWORD\" name=\"CVOIP_FXS_1_PASSWORD\">\n"; 
echo "					</td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td><td>\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>Line 2 Basic Setting</legend>\n"; 
echo "				<table>\n"; 
echo "					<tr id=\"TR_VOIP_PROF1_LINE2_ENABLE\" style=\"display:none\"><td>Registration Account</td><td>\n"; 
echo "						<input type=\"checkbox\" id=\"VOIP_PROF1_LINE2_ENABLE\" name=\"VOIP_PROF1_LINE2_ENABLE\">\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "					<tr id=\"TR_VOIP_FXS_2_USERNAME\" style=\"display:none\"><td>Number</td><td>\n"; 
echo "						<input type=\"text\" id=\"VOIP_FXS_2_USERNAME\" name=\"VOIP_FXS_2_USERNAME\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_2_DISPLAYNAME\" style=\"display:none\"><td>Display Name</td><td>\n"; 
echo "						<input type=\"text\" id=\"VOIP_FXS_2_DISPLAYNAME\" name=\"VOIP_FXS_2_DISPLAYNAME\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_2_AUTHNAME\" style=\"display:none\"><td>Authentication Name</td><td>\n"; 
echo "						<input type=\"text\" id=\"VOIP_FXS_2_AUTHNAME\" name=\"VOIP_FXS_2_AUTHNAME\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_2_PASSWORD\" style=\"display:none\"><td>Password</td><td>\n"; 
echo "						<input type=\"password\" id=\"VOIP_FXS_2_PASSWORD\" name=\"VOIP_FXS_2_PASSWORD\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_CVOIP_FXS_2_PASSWORD\" style=\"display:none\"><td>Password Confirm</td><td>\n"; 
echo "						<input type=\"password\" id=\"CVOIP_FXS_2_PASSWORD\" name=\"CVOIP_FXS_2_PASSWORD\">\n"; 
echo "					</td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td></tr>\n"; 
echo "			</table>\n"; 
echo "			<table id=\"TR_TD_Advance\" style=\"display:none\">\n"; 
echo "			<tr><td>\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>Line 1 Advance Setting</legend>\n"; 
echo "				<table>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_1_AUTO_DECLINE\" style=\"display:none\"><td>Auto Decline Anonymous</td><td>\n"; 
echo "						<input type=\"checkbox\" id=\"VOIP_FXS_1_AUTO_DECLINE\" name=\"VOIP_FXS_1_AUTO_DECLINE\">\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "					<tr id=\"TR_VOIP_FXS_1_DND\" style=\"display:none\"><td>Do Not Disturb(DND)</td><td>\n"; 
echo "						<input type=\"checkbox\" id=\"VOIP_FXS_1_DND\" name=\"VOIP_FXS_1_DND\">\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "					<tr id=\"TR_VOIP_FXS_1_HIDE_USER_ID\" style=\"display:none\"><td>Hide User ID</td><td>\n"; 
echo "						<input type=\"checkbox\" id=\"VOIP_FXS_1_HIDE_USER_ID\" name=\"VOIP_FXS_1_HIDE_USER_ID\">\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "					<tr id=\"TR_VOIP_FXS_1_DTMF\" style=\"display:none\"><td>Send DTMF</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_1_DTMF\" name=\"VOIP_FXS_1_DTMF\">\n"; 
echo "							<option value=\"0\">Out-of-band(RFC 2833)</option>\n"; 
echo "							<option value=\"1\">In Band</option>\n"; 
echo "							<option value=\"2\">SIP INFO</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "					<tr id=\"TR_VOIP_FXS_1_VAD\" style=\"display:none\"><td colspan=2>Voice Active Detector<br/>\n"; 
echo "						<select id=\"VOIP_FXS_1_VAD\" name=\"VOIP_FXS_1_VAD\">\n"; 
echo "							<option value=\"0\">Disable</option>\n"; 
echo "							<option value=\"1\">Silence Suppression - NO CNG</option>\n"; 
echo "							<option value=\"2\">Silence Suppression - Only G.711 AnnexII Type</option>\n"; 
echo "							<option value=\"3\">Silence Suppression - Codec Specific CN</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td></tr>\n"; 
echo "			<tr><td>\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>Line 2 Advance Setting</legend>\n"; 
echo "				<table>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_2_AUTO_DECLINE\" style=\"display:none\"><td>Auto Decline Anonymous</td><td>\n"; 
echo "						<input type=\"checkbox\" id=\"VOIP_FXS_2_AUTO_DECLINE\" name=\"VOIP_FXS_2_AUTO_DECLINE\">\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "					<tr id=\"TR_VOIP_FXS_2_DND\" style=\"display:none\"><td>Do Not Disturb(DND)</td><td>\n"; 
echo "						<input type=\"checkbox\" id=\"VOIP_FXS_2_DND\" name=\"VOIP_FXS_2_DND\">\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "					<tr id=\"TR_VOIP_FXS_2_HIDE_USER_ID\" style=\"display:none\"><td>Hide User ID</td><td>\n"; 
echo "						<input type=\"checkbox\" id=\"VOIP_FXS_2_HIDE_USER_ID\" name=\"VOIP_FXS_2_HIDE_USER_ID\">\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "					<tr id=\"TR_VOIP_FXS_2_DTMF\" style=\"display:none\"><td>Send DTMF</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_2_DTMF\" name=\"VOIP_FXS_2_DTMF\">\n"; 
echo "							<option value=\"0\">Out-of-band(RFC 2833)</option>\n"; 
echo "							<option value=\"1\">In Band</option>\n"; 
echo "							<option value=\"2\">SIP INFO</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "					<tr id=\"TR_VOIP_FXS_2_VAD\" style=\"display:none\"><td colspan=2>Voice Active Detector<br/>\n"; 
echo "						<select id=\"VOIP_FXS_2_VAD\" name=\"VOIP_FXS_2_VAD\">\n"; 
echo "							<option value=\"0\">Disable</option>\n"; 
echo "							<option value=\"1\">Silence Suppression - NO CNG</option>\n"; 
echo "							<option value=\"2\">Silence Suppression - Only G.711 AnnexII Type</option>\n"; 
echo "							<option value=\"3\">Silence Suppression - Codec Specific CN</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td></tr>\n"; 
echo "			</table>\n"; 
echo "			<table id=\"TR_TD_Codec\" style=\"display:none\">\n"; 
echo "			<tr><td>\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>Line 1 Codec Setting</legend>\n"; 
echo "				<table>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_1_PREFER_1ST_CODEC\" style=\"display:none\"><td>1st Codec</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_1_PREFER_1ST_CODEC\" name=\"VOIP_FXS_1_PREFER_1ST_CODEC\">\n"; 
echo "							<option value=\"1\">G.729</option>\n"; 
echo "							<option value=\"2\">G.723.1</option>\n"; 
echo "							<option value=\"4\">G.726 16K</option>\n"; 
echo "							<option value=\"5\">G.726 24K</option>\n"; 
echo "							<option value=\"6\">G.726 32K</option>\n"; 
echo "							<option value=\"7\">G.726 40K</option>\n"; 
echo "							<option value=\"8\">G.711 aLaw</option>\n"; 
echo "							<option value=\"9\">G.711 muLaw</option>\n"; 
echo "							<option value=\"11\">iLBC</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_1_PREFER_2ND_CODEC\" style=\"display:none\"><td>2nd Codec</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_1_PREFER_2ND_CODEC\" name=\"VOIP_FXS_1_PREFER_2ND_CODEC\">\n"; 
echo "							<option value=\"3\">NONE</option>\n"; 
echo "							<option value=\"1\">G.729</option>\n"; 
echo "							<option value=\"2\">G.723.1</option>\n"; 
echo "							<option value=\"4\">G.726 16K</option>\n"; 
echo "							<option value=\"5\">G.726 24K</option>\n"; 
echo "							<option value=\"6\">G.726 32K</option>\n"; 
echo "							<option value=\"7\">G.726 40K</option>\n"; 
echo "							<option value=\"8\">G.711 aLaw</option>\n"; 
echo "							<option value=\"9\">G.711 muLaw</option>\n"; 
echo "							<option value=\"11\">iLBC</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_1_PREFER_3RD_CODEC\" style=\"display:none\"><td>3rd Codec</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_1_PREFER_3RD_CODEC\" name=\"VOIP_FXS_1_PREFER_3RD_CODEC\">\n"; 
echo "							<option value=\"3\">NONE</option>\n"; 
echo "							<option value=\"1\">G.729</option>\n"; 
echo "							<option value=\"2\">G.723.1</option>\n"; 
echo "							<option value=\"4\">G.726 16K</option>\n"; 
echo "							<option value=\"5\">G.726 24K</option>\n"; 
echo "							<option value=\"6\">G.726 32K</option>\n"; 
echo "							<option value=\"7\">G.726 40K</option>\n"; 
echo "							<option value=\"8\">G.711 aLaw</option>\n"; 
echo "							<option value=\"9\">G.711 muLaw</option>\n"; 
echo "							<option value=\"11\">iLBC</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_1_PREFER_4TH_CODEC\" style=\"display:none\"><td>4th Codec</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_1_PREFER_4TH_CODEC\" name=\"VOIP_FXS_1_PREFER_4TH_CODEC\">\n"; 
echo "							<option value=\"3\">NONE</option>\n"; 
echo "							<option value=\"1\">G.729</option>\n"; 
echo "							<option value=\"2\">G.723.1</option>\n"; 
echo "							<option value=\"4\">G.726 16K</option>\n"; 
echo "							<option value=\"5\">G.726 24K</option>\n"; 
echo "							<option value=\"6\">G.726 32K</option>\n"; 
echo "							<option value=\"7\">G.726 40K</option>\n"; 
echo "							<option value=\"8\">G.711 aLaw</option>\n"; 
echo "							<option value=\"9\">G.711 muLaw</option>\n"; 
echo "							<option value=\"11\">iLBC</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_1_PREFER_5TH_CODEC\" style=\"display:none\"><td>5th Codec</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_1_PREFER_5TH_CODEC\" name=\"VOIP_FXS_1_PREFER_5TH_CODEC\">\n"; 
echo "							<option value=\"3\">NONE</option>\n"; 
echo "							<option value=\"1\">G.729</option>\n"; 
echo "							<option value=\"2\">G.723.1</option>\n"; 
echo "							<option value=\"4\">G.726 16K</option>\n"; 
echo "							<option value=\"5\">G.726 24K</option>\n"; 
echo "							<option value=\"6\">G.726 32K</option>\n"; 
echo "							<option value=\"7\">G.726 40K</option>\n"; 
echo "							<option value=\"8\">G.711 aLaw</option>\n"; 
echo "							<option value=\"9\">G.711 muLaw</option>\n"; 
echo "							<option value=\"11\">iLBC</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_1_PREFER_6TH_CODEC\" style=\"display:none\"><td>6th Codec</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_1_PREFER_6TH_CODEC\" name=\"VOIP_FXS_1_PREFER_6TH_CODEC\">\n"; 
echo "							<option value=\"3\">NONE</option>\n"; 
echo "							<option value=\"1\">G.729</option>\n"; 
echo "							<option value=\"2\">G.723.1</option>\n"; 
echo "							<option value=\"4\">G.726 16K</option>\n"; 
echo "							<option value=\"5\">G.726 24K</option>\n"; 
echo "							<option value=\"6\">G.726 32K</option>\n"; 
echo "							<option value=\"7\">G.726 40K</option>\n"; 
echo "							<option value=\"8\">G.711 aLaw</option>\n"; 
echo "							<option value=\"9\">G.711 muLaw</option>\n"; 
echo "							<option value=\"11\">iLBC</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_1_PREFER_7TH_CODEC\" style=\"display:none\"><td>7th Codec</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_1_PREFER_7TH_CODEC\" name=\"VOIP_FXS_1_PREFER_7TH_CODEC\">\n"; 
echo "							<option value=\"3\">NONE</option>\n"; 
echo "							<option value=\"1\">G.729</option>\n"; 
echo "							<option value=\"2\">G.723.1</option>\n"; 
echo "							<option value=\"4\">G.726 16K</option>\n"; 
echo "							<option value=\"5\">G.726 24K</option>\n"; 
echo "							<option value=\"6\">G.726 32K</option>\n"; 
echo "							<option value=\"7\">G.726 40K</option>\n"; 
echo "							<option value=\"8\">G.711 aLaw</option>\n"; 
echo "							<option value=\"9\">G.711 muLaw</option>\n"; 
echo "							<option value=\"11\">iLBC</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_1_PREFER_8TH_CODEC\" style=\"display:none\"><td>8th Codec</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_1_PREFER_8TH_CODEC\" name=\"VOIP_FXS_1_PREFER_8TH_CODEC\">\n"; 
echo "							<option value=\"3\">NONE</option>\n"; 
echo "							<option value=\"1\">G.729</option>\n"; 
echo "							<option value=\"2\">G.723.1</option>\n"; 
echo "							<option value=\"4\">G.726 16K</option>\n"; 
echo "							<option value=\"5\">G.726 24K</option>\n"; 
echo "							<option value=\"6\">G.726 32K</option>\n"; 
echo "							<option value=\"7\">G.726 40K</option>\n"; 
echo "							<option value=\"8\">G.711 aLaw</option>\n"; 
echo "							<option value=\"9\">G.711 muLaw</option>\n"; 
echo "							<option value=\"11\">iLBC</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_1_PREFER_9TH_CODEC\" style=\"display:none\"><td>9th Codec</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_1_PREFER_9TH_CODEC\" name=\"VOIP_FXS_1_PREFER_9TH_CODEC\">\n"; 
echo "							<option value=\"3\">NONE</option>\n"; 
echo "							<option value=\"1\">G.729</option>\n"; 
echo "							<option value=\"2\">G.723.1</option>\n"; 
echo "							<option value=\"4\">G.726 16K</option>\n"; 
echo "							<option value=\"5\">G.726 24K</option>\n"; 
echo "							<option value=\"6\">G.726 32K</option>\n"; 
echo "							<option value=\"7\">G.726 40K</option>\n"; 
echo "							<option value=\"8\">G.711 aLaw</option>\n"; 
echo "							<option value=\"9\">G.711 muLaw</option>\n"; 
echo "							<option value=\"11\">iLBC</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td><td>\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>Line 2 Codec Setting</legend>\n"; 
echo "				<table>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_2_PREFER_1ST_CODEC\" style=\"display:none\"><td>1st Codec</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_2_PREFER_1ST_CODEC\" name=\"VOIP_FXS_2_PREFER_1ST_CODEC\">\n"; 
echo "							<option value=\"1\">G.729</option>\n"; 
echo "							<option value=\"2\">G.723.1</option>\n"; 
echo "							<option value=\"4\">G.726 16K</option>\n"; 
echo "							<option value=\"5\">G.726 24K</option>\n"; 
echo "							<option value=\"6\">G.726 32K</option>\n"; 
echo "							<option value=\"7\">G.726 40K</option>\n"; 
echo "							<option value=\"8\">G.711 aLaw</option>\n"; 
echo "							<option value=\"9\">G.711 muLaw</option>\n"; 
echo "							<option value=\"11\">iLBC</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_2_PREFER_2ND_CODEC\" style=\"display:none\"><td>2nd Codec</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_2_PREFER_2ND_CODEC\" name=\"VOIP_FXS_2_PREFER_2ND_CODEC\">\n"; 
echo "							<option value=\"3\">NONE</option>\n"; 
echo "							<option value=\"1\">G.729</option>\n"; 
echo "							<option value=\"2\">G.723.1</option>\n"; 
echo "							<option value=\"4\">G.726 16K</option>\n"; 
echo "							<option value=\"5\">G.726 24K</option>\n"; 
echo "							<option value=\"6\">G.726 32K</option>\n"; 
echo "							<option value=\"7\">G.726 40K</option>\n"; 
echo "							<option value=\"8\">G.711 aLaw</option>\n"; 
echo "							<option value=\"9\">G.711 muLaw</option>\n"; 
echo "							<option value=\"11\">iLBC</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_2_PREFER_3RD_CODEC\" style=\"display:none\"><td>3rd Codec</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_2_PREFER_3RD_CODEC\" name=\"VOIP_FXS_2_PREFER_3RD_CODEC\">\n"; 
echo "							<option value=\"3\">NONE</option>\n"; 
echo "							<option value=\"1\">G.729</option>\n"; 
echo "							<option value=\"2\">G.723.1</option>\n"; 
echo "							<option value=\"4\">G.726 16K</option>\n"; 
echo "							<option value=\"5\">G.726 24K</option>\n"; 
echo "							<option value=\"6\">G.726 32K</option>\n"; 
echo "							<option value=\"7\">G.726 40K</option>\n"; 
echo "							<option value=\"8\">G.711 aLaw</option>\n"; 
echo "							<option value=\"9\">G.711 muLaw</option>\n"; 
echo "							<option value=\"11\">iLBC</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_2_PREFER_4TH_CODEC\" style=\"display:none\"><td>4th Codec</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_2_PREFER_4TH_CODEC\" name=\"VOIP_FXS_2_PREFER_4TH_CODEC\">\n"; 
echo "							<option value=\"3\">NONE</option>\n"; 
echo "							<option value=\"1\">G.729</option>\n"; 
echo "							<option value=\"2\">G.723.1</option>\n"; 
echo "							<option value=\"4\">G.726 16K</option>\n"; 
echo "							<option value=\"5\">G.726 24K</option>\n"; 
echo "							<option value=\"6\">G.726 32K</option>\n"; 
echo "							<option value=\"7\">G.726 40K</option>\n"; 
echo "							<option value=\"8\">G.711 aLaw</option>\n"; 
echo "							<option value=\"9\">G.711 muLaw</option>\n"; 
echo "							<option value=\"11\">iLBC</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_2_PREFER_5TH_CODEC\" style=\"display:none\"><td>5th Codec</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_2_PREFER_5TH_CODEC\" name=\"VOIP_FXS_2_PREFER_5TH_CODEC\">\n"; 
echo "							<option value=\"3\">NONE</option>\n"; 
echo "							<option value=\"1\">G.729</option>\n"; 
echo "							<option value=\"2\">G.723.1</option>\n"; 
echo "							<option value=\"4\">G.726 16K</option>\n"; 
echo "							<option value=\"5\">G.726 24K</option>\n"; 
echo "							<option value=\"6\">G.726 32K</option>\n"; 
echo "							<option value=\"7\">G.726 40K</option>\n"; 
echo "							<option value=\"8\">G.711 aLaw</option>\n"; 
echo "							<option value=\"9\">G.711 muLaw</option>\n"; 
echo "							<option value=\"11\">iLBC</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_2_PREFER_6TH_CODEC\" style=\"display:none\"><td>6th Codec</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_2_PREFER_6TH_CODEC\" name=\"VOIP_FXS_2_PREFER_6TH_CODEC\">\n"; 
echo "							<option value=\"3\">NONE</option>\n"; 
echo "							<option value=\"1\">G.729</option>\n"; 
echo "							<option value=\"2\">G.723.1</option>\n"; 
echo "							<option value=\"4\">G.726 16K</option>\n"; 
echo "							<option value=\"5\">G.726 24K</option>\n"; 
echo "							<option value=\"6\">G.726 32K</option>\n"; 
echo "							<option value=\"7\">G.726 40K</option>\n"; 
echo "							<option value=\"8\">G.711 aLaw</option>\n"; 
echo "							<option value=\"9\">G.711 muLaw</option>\n"; 
echo "							<option value=\"11\">iLBC</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_2_PREFER_7TH_CODEC\" style=\"display:none\"><td>7th Codec</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_2_PREFER_7TH_CODEC\" name=\"VOIP_FXS_2_PREFER_7TH_CODEC\">\n"; 
echo "							<option value=\"3\">NONE</option>\n"; 
echo "							<option value=\"1\">G.729</option>\n"; 
echo "							<option value=\"2\">G.723.1</option>\n"; 
echo "							<option value=\"4\">G.726 16K</option>\n"; 
echo "							<option value=\"5\">G.726 24K</option>\n"; 
echo "							<option value=\"6\">G.726 32K</option>\n"; 
echo "							<option value=\"7\">G.726 40K</option>\n"; 
echo "							<option value=\"8\">G.711 aLaw</option>\n"; 
echo "							<option value=\"9\">G.711 muLaw</option>\n"; 
echo "							<option value=\"11\">iLBC</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_2_PREFER_8TH_CODEC\" style=\"display:none\"><td>8th Codec</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_2_PREFER_8TH_CODEC\" name=\"VOIP_FXS_2_PREFER_8TH_CODEC\">\n"; 
echo "							<option value=\"3\">NONE</option>\n"; 
echo "							<option value=\"1\">G.729</option>\n"; 
echo "							<option value=\"2\">G.723.1</option>\n"; 
echo "							<option value=\"4\">G.726 16K</option>\n"; 
echo "							<option value=\"5\">G.726 24K</option>\n"; 
echo "							<option value=\"6\">G.726 32K</option>\n"; 
echo "							<option value=\"7\">G.726 40K</option>\n"; 
echo "							<option value=\"8\">G.711 aLaw</option>\n"; 
echo "							<option value=\"9\">G.711 muLaw</option>\n"; 
echo "							<option value=\"11\">iLBC</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_2_PREFER_9TH_CODEC\" style=\"display:none\"><td>9th Codec</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_2_PREFER_9TH_CODEC\" name=\"VOIP_FXS_2_PREFER_9TH_CODEC\">\n"; 
echo "							<option value=\"3\">NONE</option>\n"; 
echo "							<option value=\"1\">G.729</option>\n"; 
echo "							<option value=\"2\">G.723.1</option>\n"; 
echo "							<option value=\"4\">G.726 16K</option>\n"; 
echo "							<option value=\"5\">G.726 24K</option>\n"; 
echo "							<option value=\"6\">G.726 32K</option>\n"; 
echo "							<option value=\"7\">G.726 40K</option>\n"; 
echo "							<option value=\"8\">G.711 aLaw</option>\n"; 
echo "							<option value=\"9\">G.711 muLaw</option>\n"; 
echo "							<option value=\"11\">iLBC</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td></tr>\n"; 
echo "			</table>\n"; 
echo "			<table width=\"600px\" id=\"TR_TD_Caller\" style=\"display:none\">\n"; 
echo "			<tr><td>\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>Line 1 Caller ID</legend>\n"; 
echo "				<table>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_1_CALLERID_TYPE\" style=\"display:none\"><td>Caller ID Type</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_1_CALLERID_TYPE\" name=\"VOIP_FXS_1_CALLERID_TYPE\">\n"; 
echo "							<option value=\"0\">Disable</option>\n"; 
echo "							<option value=\"2\">FSK Bellcore</option>\n"; 
echo "							<option value=\"3\">Japan CLIP</option>\n"; 
echo "							<option value=\"4\">FSK ETSI</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "					<tr id=\"TR_VOIP_FXS_1_CALLERID_DISP\" style=\"display:none\"><td>Caller ID Display</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_1_CALLERID_DISP\" name=\"VOIP_FXS_1_CALLERID_DISP\">\n"; 
echo "							<option value=\"0\">Before Ring</option>\n"; 
echo "							<option value=\"1\">After Ring</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "					<tr id=\"TR_VOIP_FXS_1_CALLERID_POWER\" style=\"display:none\"><td>Caller ID Power Level</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_1_CALLERID_POWER\" name=\"VOIP_FXS_1_CALLERID_POWER\">\n"; 
echo "							<option value=\"0\">0</option>\n"; 
echo "							<option value=\"1\">1</option>\n"; 
echo "							<option value=\"2\">2</option>\n"; 
echo "							<option value=\"3\">3</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td><td>\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>Line 2 Caller ID</legend>\n"; 
echo "				<table>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_2_CALLERID_TYPE\" style=\"display:none\"><td>Caller ID Type</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_2_CALLERID_TYPE\" name=\"VOIP_FXS_2_CALLERID_TYPE\">\n"; 
echo "							<option value=\"0\">Disable</option>\n"; 
echo "							<option value=\"2\">FSK Bellcore</option>\n"; 
echo "							<option value=\"3\">Japan CLIP</option>\n"; 
echo "							<option value=\"4\">FSK ETSI</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "					<tr id=\"TR_VOIP_FXS_2_CALLERID_DISP\" style=\"display:none\"><td>Caller ID Display</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_2_CALLERID_DISP\" name=\"VOIP_FXS_2_CALLERID_DISP\">\n"; 
echo "							<option value=\"0\">Before Ring</option>\n"; 
echo "							<option value=\"1\">After Ring</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "					<tr id=\"TR_VOIP_FXS_2_CALLERID_POWER\" style=\"display:none\"><td>Caller ID Power Level</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_2_CALLERID_POWER\" name=\"VOIP_FXS_2_CALLERID_POWER\">\n"; 
echo "							<option value=\"0\">0</option>\n"; 
echo "							<option value=\"1\">1</option>\n"; 
echo "							<option value=\"2\">2</option>\n"; 
echo "							<option value=\"3\">3</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td></tr>\n"; 
echo "			</table>\n"; 
echo "			<table id=\"TR_TD_FXS\" style=\"display:none\">\n"; 
echo "			<tr><td>\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>Line 1 FXS</legend>\n"; 
echo "				<table>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_1_FLASH_DET_UPLV\" style=\"display:none\"><td>Hook Flash Detect Upper Bound</td><td>\n"; 
echo "						<input type=\"text\" id=\"VOIP_FXS_1_FLASH_DET_UPLV\" name=\"VOIP_FXS_1_FLASH_DET_UPLV\" size=\"4\" maxlength=\"4\">msecs (100~2000 msecs, default:300)\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_1_FLASH_DET_LOWLV\" style=\"display:none\"><td>Hook Flash Detect Lower Bound</td><td>\n"; 
echo "						<input type=\"text\" id=\"VOIP_FXS_1_FLASH_DET_LOWLV\" name=\"VOIP_FXS_1_FLASH_DET_LOWLV\" size=\"4\" maxlength=\"4\">msecs (100~2000 msecs, default:100)\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "					<tr id=\"TR_VOIP_FXS_1_VOGAIN_TX_LV\" style=\"display:none\"><td>Voice Tx Level</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_1_VOGAIN_TX_LV\" name=\"VOIP_FXS_1_VOGAIN_TX_LV\">\n"; 
echo "							<option value=\"0\">-9</option>\n"; 
echo "							<option value=\"1\">-8</option>\n"; 
echo "							<option value=\"2\">-7</option>\n"; 
echo "							<option value=\"3\">-6</option>\n"; 
echo "							<option value=\"4\">-5</option>\n"; 
echo "							<option value=\"5\">-4</option>\n"; 
echo "							<option value=\"6\">-3</option>\n"; 
echo "							<option value=\"7\">-2</option>\n"; 
echo "							<option value=\"8\">-1</option>\n"; 
echo "							<option value=\"9\">0</option>\n"; 
echo "							<option value=\"10\">1</option>\n"; 
echo "							<option value=\"11\">2</option>\n"; 
echo "							<option value=\"12\">3</option>\n"; 
echo "							<option value=\"13\">4</option>\n"; 
echo "							<option value=\"14\">5</option>\n"; 
echo "							<option value=\"15\">6</option>\n"; 
echo "							<option value=\"16\">7</option>\n"; 
echo "							<option value=\"17\">8</option>\n"; 
echo "							<option value=\"18\">9</option>\n"; 
echo "						</select>(default:5)\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "					<tr id=\"TR_VOIP_FXS_1_VOGAIN_RX_LV\" style=\"display:none\"><td>Voice Rx Level</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_1_VOGAIN_RX_LV\" name=\"VOIP_FXS_1_VOGAIN_RX_LV\">\n"; 
echo "							<option value=\"0\">-9</option>\n"; 
echo "							<option value=\"1\">-8</option>\n"; 
echo "							<option value=\"2\">-7</option>\n"; 
echo "							<option value=\"3\">-6</option>\n"; 
echo "							<option value=\"4\">-5</option>\n"; 
echo "							<option value=\"5\">-4</option>\n"; 
echo "							<option value=\"6\">-3</option>\n"; 
echo "							<option value=\"7\">-2</option>\n"; 
echo "							<option value=\"8\">-1</option>\n"; 
echo "							<option value=\"9\">0</option>\n"; 
echo "							<option value=\"10\">1</option>\n"; 
echo "							<option value=\"11\">2</option>\n"; 
echo "							<option value=\"12\">3</option>\n"; 
echo "							<option value=\"13\">4</option>\n"; 
echo "							<option value=\"14\">5</option>\n"; 
echo "							<option value=\"15\">6</option>\n"; 
echo "							<option value=\"16\">7</option>\n"; 
echo "							<option value=\"17\">8</option>\n"; 
echo "							<option value=\"18\">9</option>\n"; 
echo "						</select>(default:5)\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_1_TONE_TYPE\" style=\"display:none\"><td>Tone Setting</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_1_TONE_TYPE\" name=\"VOIP_FXS_1_TONE_TYPE\">\n"; 
echo "							<option value=\"0\">US</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_1_RING_IMPEDENCE\" style=\"display:none\"><td>Ring Impedance</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_1_RING_IMPEDENCE\" name=\"VOIP_FXS_1_RING_IMPEDENCE\">\n"; 
echo "							<option value=\"1\">600ohms</option>\n"; 
echo "							<option value=\"2\">900ohms</option>\n"; 
echo "							<option value=\"3\">Japan (600ohms + 1uF)</option>\n"; 
echo "							<option value=\"4\">900ohms + 2.16uF</option>\n"; 
echo "							<option value=\"5\">CTR21 270ohms+(750ohms||150nF)</option>\n"; 
echo "							<option value=\"6\">Australia/New Zealand220ohms+(820ohms||120nF)</option>\n"; 
echo "							<option value=\"7\">Slovakia/Slovenia/South Africa220ohms+(820ohms||115nF)</option>\n"; 
echo "							<option value=\"8\">China 200ohms+(680ohms||100nF)</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td></tr>\n"; 
echo "			<tr><td>\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>Line 2 FXS</legend>\n"; 
echo "				<table>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_2_FLASH_DET_UPLV\" style=\"display:none\"><td>Hook Flash Detect Upper Bound</td><td>\n"; 
echo "						<input type=\"text\" id=\"VOIP_FXS_2_FLASH_DET_UPLV\" name=\"VOIP_FXS_2_FLASH_DET_UPLV\" size=\"4\" maxlength=\"4\">msecs (100~2000 msecs, default:300)\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_2_FLASH_DET_LOWLV\" style=\"display:none\"><td>Hook Flash Detect Lower Bound</td><td>\n"; 
echo "						<input type=\"text\" id=\"VOIP_FXS_2_FLASH_DET_LOWLV\" name=\"VOIP_FXS_2_FLASH_DET_LOWLV\" size=\"4\" maxlength=\"4\">msecs (100~2000 msecs, default:100)\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "					<tr id=\"TR_VOIP_FXS_2_VOGAIN_TX_LV\" style=\"display:none\"><td>Voice Tx Level</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_2_VOGAIN_TX_LV\" name=\"VOIP_FXS_2_VOGAIN_TX_LV\">\n"; 
echo "							<option value=\"0\">-9</option>\n"; 
echo "							<option value=\"1\">-8</option>\n"; 
echo "							<option value=\"2\">-7</option>\n"; 
echo "							<option value=\"3\">-6</option>\n"; 
echo "							<option value=\"4\">-5</option>\n"; 
echo "							<option value=\"5\">-4</option>\n"; 
echo "							<option value=\"6\">-3</option>\n"; 
echo "							<option value=\"7\">-2</option>\n"; 
echo "							<option value=\"8\">-1</option>\n"; 
echo "							<option value=\"9\">0</option>\n"; 
echo "							<option value=\"10\">1</option>\n"; 
echo "							<option value=\"11\">2</option>\n"; 
echo "							<option value=\"12\">3</option>\n"; 
echo "							<option value=\"13\">4</option>\n"; 
echo "							<option value=\"14\">5</option>\n"; 
echo "							<option value=\"15\">6</option>\n"; 
echo "							<option value=\"16\">7</option>\n"; 
echo "							<option value=\"17\">8</option>\n"; 
echo "							<option value=\"18\">9</option>\n"; 
echo "						</select>(default:5)\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "					<tr id=\"TR_VOIP_FXS_2_VOGAIN_RX_LV\" style=\"display:none\"><td>Voice Rx Level</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_2_VOGAIN_RX_LV\" name=\"VOIP_FXS_2_VOGAIN_RX_LV\">\n"; 
echo "							<option value=\"0\">-9</option>\n"; 
echo "							<option value=\"1\">-8</option>\n"; 
echo "							<option value=\"2\">-7</option>\n"; 
echo "							<option value=\"3\">-6</option>\n"; 
echo "							<option value=\"4\">-5</option>\n"; 
echo "							<option value=\"5\">-4</option>\n"; 
echo "							<option value=\"6\">-3</option>\n"; 
echo "							<option value=\"7\">-2</option>\n"; 
echo "							<option value=\"8\">-1</option>\n"; 
echo "							<option value=\"9\">0</option>\n"; 
echo "							<option value=\"10\">1</option>\n"; 
echo "							<option value=\"11\">2</option>\n"; 
echo "							<option value=\"12\">3</option>\n"; 
echo "							<option value=\"13\">4</option>\n"; 
echo "							<option value=\"14\">5</option>\n"; 
echo "							<option value=\"15\">6</option>\n"; 
echo "							<option value=\"16\">7</option>\n"; 
echo "							<option value=\"17\">8</option>\n"; 
echo "							<option value=\"18\">9</option>\n"; 
echo "						</select>(default:5)\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_2_TONE_TYPE\" style=\"display:none\"><td>Tone Setting</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_2_TONE_TYPE\" name=\"VOIP_FXS_2_TONE_TYPE\">\n"; 
echo "							<option value=\"0\">US</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_VOIP_FXS_2_RING_IMPEDENCE\" style=\"display:none\"><td>Ring Impedance</td><td>\n"; 
echo "						<select id=\"VOIP_FXS_2_RING_IMPEDENCE\" name=\"VOIP_FXS_2_RING_IMPEDENCE\">\n"; 
echo "							<option value=\"1\">600ohms</option>\n"; 
echo "							<option value=\"2\">900ohms</option>\n"; 
echo "							<option value=\"3\">Japan (600ohms + 1uF)</option>\n"; 
echo "							<option value=\"4\">900ohms + 2.16uF</option>\n"; 
echo "							<option value=\"5\">CTR21 270ohms+(750ohms||150nF)</option>\n"; 
echo "							<option value=\"6\">Australia/New Zealand220ohms+(820ohms||120nF)</option>\n"; 
echo "							<option value=\"7\">Slovakia/Slovenia/South Africa220ohms+(820ohms||115nF)</option>\n"; 
echo "							<option value=\"8\">China 200ohms+(680ohms||100nF)</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td></tr>\n"; 
echo "			</table>\n"; 
echo "\n"; 
echo "			<FIELDSET id=\"TR_TD_Provision\" style=\"display:none\">\n"; 
echo "				<legend>Provision</legend>\n"; 
echo "				<table>\n"; 
echo "					<tr id=\"TR_VOIP_AUTO_PROVISION_ENABLE\" style=\"display:none\"><td>Enable</td><td>\n"; 
echo "						<input type=\"checkbox\" id=\"VOIP_AUTO_PROVISION_ENABLE\" name=\"VOIP_AUTO_PROVISION_ENABLE\">\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "					<tr id=\"TR_VOIP_AUTO_PROVISION_FTP_ADDRESS\" style=\"display:none\"><td>FTP Server</td><td>\n"; 
echo "						<input type=\"text\" id=\"VOIP_AUTO_PROVISION_FTP_ADDRESS\" name=\"VOIP_AUTO_PROVISION_FTP_ADDRESS\">\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "					<tr id=\"TR_VOIP_AUTO_PROVISION_FTP_FILE_NAME\" style=\"display:none\"><td>File Path</td><td>\n"; 
echo "						<input type=\"text\" id=\"VOIP_AUTO_PROVISION_FTP_FILE_NAME\" name=\"VOIP_AUTO_PROVISION_FTP_FILE_NAME\">\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "					<tr id=\"TR_VOIP_AUTO_PROVISION_FTP_USER_NAME\" style=\"display:none\"><td>Logining User Name</td><td>\n"; 
echo "						<input type=\"text\" id=\"VOIP_AUTO_PROVISION_FTP_USER_NAME\" name=\"VOIP_AUTO_PROVISION_FTP_USER_NAME\">\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "					<tr id=\"TR_VOIP_AUTO_PROVISION_FTP_USER_PASSWORD\" style=\"display:none\"><td>Logining Password</td><td>\n"; 
echo "						<input type=\"password\" id=\"VOIP_AUTO_PROVISION_FTP_USER_PASSWORD\" name=\"VOIP_AUTO_PROVISION_FTP_USER_PASSWORD\">\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "					<tr id=\"TR_VOIP_AUTO_PROVISION_FTP_TIMEOUT\" style=\"display:none\"><td>Connection Timeout</td><td>\n"; 
echo "						<input type=\"text\" id=\"VOIP_AUTO_PROVISION_FTP_TIMEOUT\" name=\"VOIP_AUTO_PROVISION_FTP_TIMEOUT\" size=\"2\" maxlength=\"2\">seconds (10~60, default:10)\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "					<tr id=\"TR_VOIP_AUTO_PROVISION_FTP_RETRY\" style=\"display:none\"><td>Retry Count</td><td>\n"; 
echo "						<input type=\"text\" id=\"VOIP_AUTO_PROVISION_FTP_RETRY\" name=\"VOIP_AUTO_PROVISION_FTP_RETRY\" size=\"1\" maxlength=\"1\">(1~5, default:3)\n"; 
echo "					</td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "		</form>\n"; 
echo "	</div>\n"; 
echo "	<div>\n"; 
echo "		<table style=\"width:600px;height:25px;text-align:center\">\n"; 
echo "			<tr>\n"; 
echo "				<td width=\"210\"></td>\n"; 
echo "				<td id=\"clear_btn\" class=\"td_btn\" onclick=\"location.reload()\">Undo</td>\n"; 
echo "				<td width=\"30\"></td>\n"; 
echo "				<td id=\"submit_btn\" class=\"td_btn\" onclick=\"Validate(document.forms[0])\">Apply</td>\n"; 
echo "				<td width=\"210\"></td>\n"; 
echo "			</tr>\n"; 
echo "		</table>\n"; 
echo "	</div>\n"; 
echo "</div>\n"; 
echo "</body>\n"; 
echo "</html>\n";
?>