<?php
echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "<title></title>\n"; 
echo "<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "<script type=\"text/javascript\" src=\"comm.js\"></script>\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "<!--\n"; 
echo "\n"; 
echo "var NETFILTER_ALG_FTP,NETFILTER_ALG_H323,NETFILTER_ALG_PPTP,NETFILTER_ALG_SIP_SET_BSID;\n"; 
echo "\n"; 
echo "\n"; 
echo "function InitDisplay(response)\n"; 
echo "{\n"; 
echo "	var token = response.split(\";\");\n"; 
echo "\n"; 
echo "	NETFILTER_ALG_FTP = token[0];\n"; 
echo "	NETFILTER_ALG_H323 = token[1];\n"; 
echo "	NETFILTER_ALG_PPTP = token[2];\n"; 
echo "	NETFILTER_ALG_SIP_SET_BSID = token[3];\n"; 
echo "\n"; 
echo "\n"; 
echo "	tr_display(\"NETFILTER_ALG_FTP\");\n"; 
echo "	tr_display(\"NETFILTER_ALG_H323\");\n"; 
echo "	tr_display(\"NETFILTER_ALG_PPTP\");\n"; 
echo "	tr_display(\"NETFILTER_ALG_SIP_SET_BSID\");\n"; 
echo "\n"; 
echo "	obj_readonly(\"NETFILTER_ALG_FTP\");\n"; 
echo "	obj_readonly(\"NETFILTER_ALG_H323\");\n"; 
echo "	obj_readonly(\"NETFILTER_ALG_PPTP\");\n"; 
echo "	obj_readonly(\"NETFILTER_ALG_SIP_SET_BSID\");\n"; 
echo "\n"; 
echo "\n"; 
echo "	InitValue(document.forms[0]);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function InitValue(passForm)\n"; 
echo "{\n"; 
echo "	passForm.NETFILTER_ALG_FTP.checked = (NETFILTER_ALG_FTP==\"1\")? true : false;\n"; 
echo "	passForm.NETFILTER_ALG_H323.checked = (NETFILTER_ALG_H323==\"1\")? true : false;\n"; 
echo "	passForm.NETFILTER_ALG_PPTP.checked = (NETFILTER_ALG_PPTP==\"1\")? true : false;\n"; 
echo "	passForm.NETFILTER_ALG_SIP_SET_BSID.checked = (NETFILTER_ALG_SIP_SET_BSID==\"1\")? true : false;\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "	top.loading = 0;\n"; 
echo "	setInterval('ajax_get_signals()',2000);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function Validate(passForm)\n"; 
echo "{\n"; 
echo "	passForm.sid.value = sid;\n"; 
echo "	passForm.btnSubmit.value = \"1\";\n"; 
echo "	passForm.submit();\n"; 
echo "}\n"; 
echo "//-->\n"; 
echo "</script>\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body onload=\"init_obj();setTimeout('ajax_get_key()',500);\">\n"; 
echo "<div id=\"main_div\">\n"; 
echo "	<div id=\"container\">\n"; 
echo "		<form name=\"form1\" method=\"POST\" action=\"ajax.php?action=net_alg\">\n"; 
echo "		<input type=\"hidden\" name=\"sid\" id=\"sid\">\n"; 
echo "		<table class=\"pf_tbl\" cellpadding=\"5\">\n"; 
echo "			<tr>\n"; 
echo "				<th>Application Layer Gateway</th>\n"; 
echo "				<th>Enable</th>\n"; 
echo "			</tr>\n"; 
echo "			<tr id=\"TR_NETFILTER_ALG_FTP\" style=\"display:none;\">\n"; 
echo "				<td>FTP ALG</td>\n"; 
echo "				<td><input type=\"checkbox\" id=\"NETFILTER_ALG_FTP\" name=\"NETFILTER_ALG_FTP\"></td>\n"; 
echo "			</tr>\n"; 
echo "			<tr id=\"TR_NETFILTER_ALG_H323\" style=\"display:none;\">\n"; 
echo "				<td>H.323 ALG</td>\n"; 
echo "				<td><input type=\"checkbox\" id=\"NETFILTER_ALG_H323\" name=\"NETFILTER_ALG_H323\"></td>\n"; 
echo "			</tr>\n"; 
echo "			<tr id=\"TR_NETFILTER_ALG_PPTP\" style=\"display:none;\">\n"; 
echo "				<td>PPTP ALG</td>\n"; 
echo "				<td><input type=\"checkbox\" id=\"NETFILTER_ALG_PPTP\" name=\"NETFILTER_ALG_PPTP\"></td>\n"; 
echo "			</tr>\n"; 
echo "			<tr id=\"TR_NETFILTER_ALG_SIP_SET_BSID\" style=\"display:none;\">\n"; 
echo "				<td>BSID SIP ALG</td>\n"; 
echo "				<td><input type=\"checkbox\" id=\"NETFILTER_ALG_SIP_SET_BSID\" name=\"NETFILTER_ALG_SIP_SET_BSID\"></td>\n"; 
echo "			</tr>\n"; 
echo "		</table>\n"; 
echo "		<input type=\"hidden\" name=\"btnSubmit\">\n"; 
echo "		</form>\n"; 
echo "	</div>\n"; 
echo "	<div>\n"; 
echo "		<table style=\"width:600px;height:25px;text-align:center\">\n"; 
echo "			<tr>\n"; 
echo "				<td width=\"210\"></td>\n"; 
echo "				<td id=\"clear_btn\" class=\"td_btn\" onclick=\"location.reload()\">Undo</td>\n"; 
echo "				<td width=\"30\"></td>\n"; 
echo "				<td id=\"submit_btn\" class=\"td_btn\" onclick=\"Validate(document.forms[0]);\">Apply</td>\n"; 
echo "				<td width=\"210\"></td>\n"; 
echo "			</tr>\n"; 
echo "		</table>\n"; 
echo "	</div>\n"; 
echo "</div>\n"; 
echo "</body>\n"; 
echo "</html>\n";
?>