<?php
echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "<title></title>\n"; 
echo "<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "<script type=\"text/javascript\" src=\"comm.js\"></script>\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "<!--\n"; 
echo "var WAN_OP_MODE,WAN_TYPE,WAN_IP,WAN_MASK,WAN_GATEWAY,WAN_MTU,LAN_IP,LAN_MASK,LAN_MTU;\n"; 
echo "var Array_WAN_DNS,Array_WAN_DNS_1,Array_WAN_DNS_2,Array_WAN_DNS_3;\n"; 
echo "var DNS_1,DNS_2,DNS_3;\n"; 
echo "var DNS_IP_1,DNS_IP_2,DNS_IP_3;\n"; 
echo "\n"; 
echo "\n"; 
echo "function Validate (passForm) {\n"; 
echo "		if(passForm.WAN_TYPE.value == \"1\")\n"; 
echo "		{\n"; 
echo "			if(!AssembleIPAddress(passForm,\"WAN_IP\"))\n"; 
echo "				return false;\n"; 
echo "\n"; 
echo "			if(!AssembleNetmaskAddress(passForm.WAN_MASK_01, passForm.WAN_MASK_02, passForm.WAN_MASK_03, passForm.WAN_MASK_04, passForm.WAN_MASK))\n"; 
echo "			{\n"; 
echo "				passForm.WAN_MASK_04.select();\n"; 
echo "				return false;\n"; 
echo "			}\n"; 
echo "\n"; 
echo "			if(!AssembleIPAddress(passForm,\"WAN_GATEWAY\")) return false;\n"; 
echo "		}\n"; 
echo "\n"; 
echo "		if(!AssembleIPAddress(passForm,\"LAN_IP\"))\n"; 
echo "			return false;\n"; 
echo "\n"; 
echo "		if(!AssembleNetmaskAddress(passForm.LAN_MASK_01, passForm.LAN_MASK_02, passForm.LAN_MASK_03, passForm.LAN_MASK_04, passForm.LAN_MASK)) {\n"; 
echo "			passForm.LAN_MASK_04.select();\n"; 
echo "			return false;\n"; 
echo "		}\n"; 
echo "\n"; 
echo "		if(!CheckValue(passForm.LAN_MTU, 68, 1500))\n"; 
echo "			return false;\n"; 
echo "\n"; 
echo "\n"; 
echo "		if(!CheckValue(passForm.WAN_MTU, 68, 1500))\n"; 
echo "			return false;\n"; 
echo "\n"; 
echo "		var WAN_DNS;\n"; 
echo "		WAN_DNS = passForm.dns_type_1.value + \",\"\n"; 
echo "		if(passForm.dns_type_1.value == \"2\")\n"; 
echo "		{\n"; 
echo "			if(!AssembleIPAddress(passForm, \"DNS_IP_1\")) return;\n"; 
echo "			WAN_DNS += passForm.DNS_IP_1.value;\n"; 
echo "		}\n"; 
echo "		else\n"; 
echo "			WAN_DNS += DNS_IP_1;\n"; 
echo "\n"; 
echo "		WAN_DNS += \" \";\n"; 
echo "\n"; 
echo "		WAN_DNS += passForm.dns_type_2.value + \",\"\n"; 
echo "		if(passForm.dns_type_2.value == \"2\")\n"; 
echo "		{\n"; 
echo "			if(!AssembleIPAddress(passForm, \"DNS_IP_2\")) return;\n"; 
echo "			WAN_DNS += passForm.DNS_IP_2.value;\n"; 
echo "		}\n"; 
echo "		else\n"; 
echo "			WAN_DNS += DNS_IP_2;\n"; 
echo "\n"; 
echo "		WAN_DNS += \" \";\n"; 
echo "\n"; 
echo "		WAN_DNS += passForm.dns_type_3.value + \",\"\n"; 
echo "		if(passForm.dns_type_3.value == \"2\")\n"; 
echo "		{\n"; 
echo "			if(!AssembleIPAddress(passForm, \"DNS_IP_3\")) return;\n"; 
echo "			WAN_DNS += passForm.DNS_IP_3.value;\n"; 
echo "		}\n"; 
echo "		else\n"; 
echo "			WAN_DNS += DNS_IP_3;\n"; 
echo "\n"; 
echo "\n"; 
echo "		passForm.WAN_DNS.value = WAN_DNS;\n"; 
echo "\n"; 
echo "	passForm.sid.value = sid;\n"; 
echo "	passForm.btnSubmit.value = \"1\";\n"; 
echo "	passForm.submit();\n"; 
echo "}\n"; 
echo "function InitDisplay(response)\n"; 
echo "{\n"; 
echo "	var token = response.split(\";\");\n"; 
echo "\n"; 
echo "	WAN_OP_MODE = token[0];\n"; 
echo "	WAN_TYPE = token[1];\n"; 
echo "	WAN_IP = token[2];\n"; 
echo "	WAN_MASK = token[3];\n"; 
echo "	WAN_GATEWAY = token[4];\n"; 
echo "	LAN_IP = token[5];\n"; 
echo "	LAN_MASK = token[6];\n"; 
echo "	LAN_MTU= token[7];\n"; 
echo "	WAN_MTU= token[8];\n"; 
echo "\n"; 
echo "	Array_WAN_DNS = token[9].split(\" \");\n"; 
echo "	Array_WAN_DNS_1 = Array_WAN_DNS[0].split(\",\");\n"; 
echo "	Array_WAN_DNS_2 = Array_WAN_DNS[1].split(\",\");\n"; 
echo "	Array_WAN_DNS_3 = Array_WAN_DNS[2].split(\",\");\n"; 
echo "	DNS_1 = Array_WAN_DNS_1[0];\n"; 
echo "	DNS_IP_1 = Array_WAN_DNS_1[1];\n"; 
echo "	DNS_2 = Array_WAN_DNS_2[0];\n"; 
echo "	DNS_IP_2 = Array_WAN_DNS_2[1];\n"; 
echo "	DNS_3 = Array_WAN_DNS_3[0];\n"; 
echo "	DNS_IP_3 = Array_WAN_DNS_3[1];\n"; 
echo "\n"; 
echo "	tr_display(\"WAN_OP_MODE\");\n"; 
echo "	tr_display(\"WAN_TYPE\");\n"; 
echo "	tr_display(\"WAN_IP\");\n"; 
echo "	tr_display(\"WAN_MASK\");\n"; 
echo "	tr_display(\"WAN_GATEWAY\");\n"; 
echo "	tr_display(\"LAN_IP\");\n"; 
echo "	tr_display(\"LAN_MASK\");\n"; 
echo "	tr_display(\"LAN_MTU\");\n"; 
echo "	tr_display(\"WAN_MTU\");\n"; 
echo "\n"; 
echo "	if(pri_d(uitems[inner_url][\"WAN_DNS\"]))\n"; 
echo "	{\n"; 
echo "		GO(\"TR_dns_type_1\").style.display = \"\";\n"; 
echo "		GO(\"TR_dns_type_2\").style.display = \"\";\n"; 
echo "		GO(\"TR_dns_type_3\").style.display = \"\";\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	obj_readonly(\"WAN_OP_MODE\");\n"; 
echo "	obj_readonly(\"WAN_TYPE\");\n"; 
echo "	obj_readonly(\"WAN_IP\",\"ip\");\n"; 
echo "	obj_readonly(\"WAN_MASK\",\"ip\");\n"; 
echo "	obj_readonly(\"WAN_GATEWAY\",\"ip\");\n"; 
echo "	obj_readonly(\"LAN_IP\",\"ip\");\n"; 
echo "	obj_readonly(\"LAN_MASK\",\"ip\");\n"; 
echo "	obj_readonly(\"LAN_MTU\");\n"; 
echo "	obj_readonly(\"WAN_MTU\");\n"; 
echo "\n"; 
echo "\n"; 
echo "	if(!pri_a(uitems[inner_url][\"WAN_DNS\"]))\n"; 
echo "	{\n"; 
echo "		GO(\"dns_type_1\").disabled = true;\n"; 
echo "		GO(\"DNS_IP_1_01\").disabled = true;\n"; 
echo "		GO(\"DNS_IP_1_02\").disabled = true;\n"; 
echo "		GO(\"DNS_IP_1_03\").disabled = true;\n"; 
echo "		GO(\"DNS_IP_1_04\").disabled = true;\n"; 
echo "\n"; 
echo "		GO(\"dns_type_2\").disabled = true;\n"; 
echo "		GO(\"DNS_IP_2_01\").disabled = true;\n"; 
echo "		GO(\"DNS_IP_2_02\").disabled = true;\n"; 
echo "		GO(\"DNS_IP_2_03\").disabled = true;\n"; 
echo "		GO(\"DNS_IP_2_04\").disabled = true;\n"; 
echo "\n"; 
echo "		GO(\"dns_type_3\").disabled = true;\n"; 
echo "		GO(\"DNS_IP_3_01\").disabled = true;\n"; 
echo "		GO(\"DNS_IP_3_02\").disabled = true;\n"; 
echo "		GO(\"DNS_IP_3_03\").disabled = true;\n"; 
echo "		GO(\"DNS_IP_3_04\").disabled = true;\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	InitValue(document.forms[0]);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function InitValue(passForm) \n"; 
echo "{\n"; 
echo "	passForm.WAN_OP_MODE.value = WAN_OP_MODE;\n"; 
echo "	passForm.WAN_TYPE.value = WAN_TYPE;\n"; 
echo "	SplitIPAddress(WAN_IP,\"WAN_IP\");\n"; 
echo "	SplitIPAddress(WAN_MASK,\"WAN_MASK\");\n"; 
echo "	SplitIPAddress(WAN_GATEWAY,\"WAN_GATEWAY\");\n"; 
echo "	SplitIPAddress(LAN_IP,\"LAN_IP\");\n"; 
echo "	SplitIPAddress(LAN_MASK,\"LAN_MASK\");\n"; 
echo "	SplitIPAddress(DNS_IP_1, \"DNS_IP_1\");\n"; 
echo "	SplitIPAddress(DNS_IP_2, \"DNS_IP_2\");\n"; 
echo "	SplitIPAddress(DNS_IP_3, \"DNS_IP_3\");\n"; 
echo "\n"; 
echo "	passForm.LAN_MTU.value = LAN_MTU;\n"; 
echo "	passForm.WAN_MTU.value = WAN_MTU;\n"; 
echo "\n"; 
echo "\n"; 
echo "	passForm.dns_type_1.value = DNS_1;\n"; 
echo "	passForm.dns_type_2.value = DNS_2;\n"; 
echo "	passForm.dns_type_3.value = DNS_3;\n"; 
echo "\n"; 
echo "\n"; 
echo "	if(DNS_1 == \"2\")\n"; 
echo "		GO(\"dns_1\").style.visibility = \"visible\";\n"; 
echo "	if(DNS_2 == \"2\")\n"; 
echo "		GO(\"dns_2\").style.visibility = \"visible\";\n"; 
echo "	if(DNS_3 == \"2\")\n"; 
echo "		GO(\"dns_3\").style.visibility = \"visible\";\n"; 
echo "\n"; 
echo "	change_tbl(passForm);\n"; 
echo "\n"; 
echo "	top.loading = 0;\n"; 
echo "	setInterval('ajax_get_signals()',2000);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function change_tbl(passForm)\n"; 
echo "{\n"; 
echo "	if(pri_a(uitems[inner_url][\"WAN_IP\"]))\n"; 
echo "	{\n"; 
echo "		passForm.WAN_IP_01.disabled = false;\n"; 
echo "		passForm.WAN_IP_02.disabled = false;\n"; 
echo "		passForm.WAN_IP_03.disabled = false;\n"; 
echo "		passForm.WAN_IP_04.disabled = false;\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	if(pri_a(uitems[inner_url][\"WAN_MASK\"]))\n"; 
echo "	{\n"; 
echo "		passForm.WAN_MASK_01.disabled = false;\n"; 
echo "		passForm.WAN_MASK_02.disabled = false;\n"; 
echo "		passForm.WAN_MASK_03.disabled = false;\n"; 
echo "		passForm.WAN_MASK_04.disabled = false;\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	if(pri_a(uitems[inner_url][\"WAN_GATEWAY\"]))\n"; 
echo "	{\n"; 
echo "		passForm.WAN_GATEWAY_01.disabled = false;\n"; 
echo "		passForm.WAN_GATEWAY_02.disabled = false;\n"; 
echo "		passForm.WAN_GATEWAY_03.disabled = false;\n"; 
echo "		passForm.WAN_GATEWAY_04.disabled = false;\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	if(passForm.WAN_TYPE.value == \"2\")\n"; 
echo "	{\n"; 
echo "		if(pri_a(uitems[inner_url][\"WAN_IP\"]))\n"; 
echo "		{\n"; 
echo "			passForm.WAN_IP_01.disabled = true;\n"; 
echo "			passForm.WAN_IP_02.disabled = true;\n"; 
echo "			passForm.WAN_IP_03.disabled = true;\n"; 
echo "			passForm.WAN_IP_04.disabled = true;\n"; 
echo "		}\n"; 
echo "		if(pri_a(uitems[inner_url][\"WAN_MASK\"]))\n"; 
echo "		{\n"; 
echo "			passForm.WAN_MASK_01.disabled = true;\n"; 
echo "			passForm.WAN_MASK_02.disabled = true;\n"; 
echo "			passForm.WAN_MASK_03.disabled = true;\n"; 
echo "			passForm.WAN_MASK_04.disabled = true;\n"; 
echo "		}\n"; 
echo "		if(pri_a(uitems[inner_url][\"WAN_GATEWAY\"]))\n"; 
echo "		{\n"; 
echo "			passForm.WAN_GATEWAY_01.disabled = true;\n"; 
echo "			passForm.WAN_GATEWAY_02.disabled = true;\n"; 
echo "			passForm.WAN_GATEWAY_03.disabled = true;\n"; 
echo "			passForm.WAN_GATEWAY_04.disabled = true;\n"; 
echo "		}\n"; 
echo "	}\n"; 
echo "}\n"; 
echo "\n"; 
echo "\n"; 
echo "function do_change(val,type)\n"; 
echo "{\n"; 
echo "	GO(\"dns_\"+type).style.visibility = \"hidden\";\n"; 
echo "	if(val == \"2\")\n"; 
echo "	{\n"; 
echo "		GO(\"dns_\"+type).style.visibility = \"visible\";\n"; 
echo "	}\n"; 
echo "\n"; 
echo "}\n"; 
echo "//-->\n"; 
echo "</script>\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body onload=\"init_obj();setTimeout('ajax_get_key()',500);\">\n"; 
echo "<div id=\"main_div\">\n"; 
echo "	<div id=\"container\">\n"; 
echo "		<br/>\n"; 
echo "		<form method=\"POST\" action=\"ajax.php?action=net_bridge_nat_mode\">\n"; 
echo "			<input type=\"hidden\" name=\"sid\" id=\"sid\">\n"; 
echo "			<FIELDSET>\n"; 
echo "			<legend>LAN Setting</legend>\n"; 
echo "			<table>\n"; 
echo "				<tr id=\"TR_LAN_IP\" style=\"display:none\"><td>LAN IP address</td><td>\n"; 
echo "					<input type=\"text\" id=\"LAN_IP_01\" name=\"LAN_IP_01\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "					<input type=\"text\" id=\"LAN_IP_02\" name=\"LAN_IP_02\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "					<input type=\"text\" id=\"LAN_IP_03\" name=\"LAN_IP_03\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "					<input type=\"text\" id=\"LAN_IP_04\" name=\"LAN_IP_04\" size=\"3\" maxlength=\"3\">\n"; 
echo "					<input type=\"hidden\" id=\"LAN_IP\" name=\"LAN_IP\">\n"; 
echo "				</td></tr>\n"; 
echo "				<tr id=\"TR_LAN_MASK\" style=\"display:none\"><td>LAN netmask</td><td>\n"; 
echo "					<input type=\"text\" id=\"LAN_MASK_01\" name=\"LAN_MASK_01\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "					<input type=\"text\" id=\"LAN_MASK_02\" name=\"LAN_MASK_02\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "					<input type=\"text\" id=\"LAN_MASK_03\" name=\"LAN_MASK_03\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "					<input type=\"text\" id=\"LAN_MASK_04\" name=\"LAN_MASK_04\" size=\"3\" maxlength=\"3\">\n"; 
echo "					<input type=\"hidden\" id=\"LAN_MASK\" name=\"LAN_MASK\">\n"; 
echo "				</td></tr>\n"; 
echo "				<tr id=\"TR_LAN_MTU\" style=\"display:none\"><td>MTU</td><td>\n"; 
echo "					<input type=\"text\" id=\"LAN_MTU\" name=\"LAN_MTU\" size=\"15\" maxlength=\"4\">\n"; 
echo "				</td></tr>\n"; 
echo "			</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			<FIELDSET>\n"; 
echo "			<legend>WAN Setting</legend>\n"; 
echo "\n"; 
echo "			<table>\n"; 
echo "				<tr id=\"TR_WAN_OP_MODE\" style=\"display:none\"><td>Operation Mode</td><td>\n"; 
echo "					<select name=\"WAN_OP_MODE\" id=\"WAN_OP_MODE\">\n"; 
echo "						<option value=\"0\">Bridge</option>\n"; 
echo "						<option value=\"2\">NAT</option>\n"; 
echo "					</select>\n"; 
echo "				</td></tr>\n"; 
echo "				<tr id=\"TR_WAN_TYPE\" style=\"display:none\"><td>WAN IP type</td><td>\n"; 
echo "					<select name=\"WAN_TYPE\" id=\"WAN_TYPE\" onchange=\"change_tbl(document.forms[0])\">\n"; 
echo "						<option value=\"1\">Static</option>\n"; 
echo "						<option value=\"2\">DHCP</option>\n"; 
echo "					</select>\n"; 
echo "				</td></tr>\n"; 
echo "				<tr id=\"TR_WAN_IP\" style=\"display:none\"><td>WAN IP address</td><td>\n"; 
echo "					<input type=\"text\" id=\"WAN_IP_01\" name=\"WAN_IP_01\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "					<input type=\"text\" id=\"WAN_IP_02\" name=\"WAN_IP_02\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "					<input type=\"text\" id=\"WAN_IP_03\" name=\"WAN_IP_03\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "					<input type=\"text\" id=\"WAN_IP_04\" name=\"WAN_IP_04\" size=\"3\" maxlength=\"3\">\n"; 
echo "					<input type=\"hidden\" id=\"WAN_IP\" name=\"WAN_IP\">\n"; 
echo "				</td></tr>\n"; 
echo "				<tr id=\"TR_WAN_MASK\" style=\"display:none\"><td>WAN netmask</td><td>\n"; 
echo "					<input type=\"text\" id=\"WAN_MASK_01\" name=\"WAN_MASK_01\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "					<input type=\"text\" id=\"WAN_MASK_02\" name=\"WAN_MASK_02\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "					<input type=\"text\" id=\"WAN_MASK_03\" name=\"WAN_MASK_03\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "					<input type=\"text\" id=\"WAN_MASK_04\" name=\"WAN_MASK_04\" size=\"3\" maxlength=\"3\">\n"; 
echo "					<input type=\"hidden\" id=\"WAN_MASK\" name=\"WAN_MASK\">\n"; 
echo "				</td></tr>\n"; 
echo "				<tr id=\"TR_WAN_GATEWAY\" style=\"display:none\"><td>WAN gateway</td><td>\n"; 
echo "					<input type=\"text\" id=\"WAN_GATEWAY_01\" name=\"WAN_GATEWAY_01\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "					<input type=\"text\" id=\"WAN_GATEWAY_02\" name=\"WAN_GATEWAY_02\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "					<input type=\"text\" id=\"WAN_GATEWAY_03\" name=\"WAN_GATEWAY_03\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "					<input type=\"text\" id=\"WAN_GATEWAY_04\" name=\"WAN_GATEWAY_04\" size=\"3\" maxlength=\"3\">\n"; 
echo "					<input type=\"hidden\" id=\"WAN_GATEWAY\" name=\"WAN_GATEWAY\">\n"; 
echo "				</td></tr>\n"; 
echo "				<tr id=\"TR_WAN_MTU\" style=\"display:none\"><td>MTU</td><td>\n"; 
echo "					<input type=\"text\" id=\"WAN_MTU\" name=\"WAN_MTU\" size=\"15\" maxlength=\"4\">\n"; 
echo "				</td></tr>\n"; 
echo "\n"; 
echo "				<tr id=\"TR_dns_type_1\" style=\"display:none\"><td>First DNS Server</td><td>\n"; 
echo "					<select id=\"dns_type_1\" name=\"dns_type_1\" onchange=\"do_change(this.value,'1')\">\n"; 
echo "						<option value=\"0\">None</option>\n"; 
echo "						<option value=\"1\">From ISP</option>\n"; 
echo "						<option value=\"2\">User Define</option>		\n"; 
echo "					</select>\n"; 
echo "					<span id=\"dns_1\" name=\"dns_1\" style=\"visibility:hidden\">\n"; 
echo "						<input type=\"text\" id=\"DNS_IP_1_01\" name=\"DNS_IP_1_01\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "						<input type=\"text\" id=\"DNS_IP_1_02\" name=\"DNS_IP_1_02\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "						<input type=\"text\" id=\"DNS_IP_1_03\" name=\"DNS_IP_1_03\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "						<input type=\"text\" id=\"DNS_IP_1_04\" name=\"DNS_IP_1_04\" size=\"3\" maxlength=\"3\">\n"; 
echo "						<input type=\"hidden\" name=\"DNS_IP_1\">\n"; 
echo "					</div>\n"; 
echo "				</td></tr>\n"; 
echo "				<tr id=\"TR_dns_type_2\" style=\"display:none\"><td>Second DNS Server</td><td>\n"; 
echo "					<select id=\"dns_type_2\" name=\"dns_type_2\" onchange=\"do_change(this.value,'2')\">\n"; 
echo "						<option value=\"0\">None</option>\n"; 
echo "						<option value=\"1\">From ISP</option>\n"; 
echo "						<option value=\"2\">User Define</option>		\n"; 
echo "					</select>\n"; 
echo "					<span id=\"dns_2\" name=\"dns_2\" style=\"visibility:hidden\">\n"; 
echo "						<input type=\"text\" id=\"DNS_IP_2_01\" name=\"DNS_IP_2_01\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "						<input type=\"text\" id=\"DNS_IP_2_02\" name=\"DNS_IP_2_02\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "						<input type=\"text\" id=\"DNS_IP_2_03\" name=\"DNS_IP_2_03\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "						<input type=\"text\" id=\"DNS_IP_2_04\" name=\"DNS_IP_2_04\" size=\"3\" maxlength=\"3\">\n"; 
echo "						<input type=\"hidden\" name=\"DNS_IP_2\">\n"; 
echo "					</div>\n"; 
echo "				</td></tr>\n"; 
echo "				<tr id=\"TR_dns_type_3\" style=\"display:none\"><td>Third DNS Server</td><td>\n"; 
echo "					<select id=\"dns_type_3\" name=\"dns_type_3\" onchange=\"do_change(this.value,'3')\">\n"; 
echo "						<option value=\"0\">None</option>\n"; 
echo "						<option value=\"1\">From ISP</option>\n"; 
echo "						<option value=\"2\">User Define</option>		\n"; 
echo "					</select>\n"; 
echo "					<span id=\"dns_3\" name=\"dns_3\" style=\"visibility:hidden\">\n"; 
echo "						<input type=\"text\" id=\"DNS_IP_3_01\" name=\"DNS_IP_3_01\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "						<input type=\"text\" id=\"DNS_IP_3_02\" name=\"DNS_IP_3_02\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "						<input type=\"text\" id=\"DNS_IP_3_03\" name=\"DNS_IP_3_03\" size=\"3\" maxlength=\"3\">&nbsp;.&nbsp;\n"; 
echo "						<input type=\"text\" id=\"DNS_IP_3_04\" name=\"DNS_IP_3_04\" size=\"3\" maxlength=\"3\">\n"; 
echo "						<input type=\"hidden\" name=\"DNS_IP_3\">\n"; 
echo "					</span>\n"; 
echo "				</td></tr>\n"; 
echo "			</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			<input type=\"hidden\" name=\"btnSubmit\">\n"; 
echo "			<input type=\"hidden\" name=\"WAN_DNS\">\n"; 
echo "		</form>\n"; 
echo "	</div>\n"; 
echo "	<div>\n"; 
echo "		<table style=\"width:600px;height:25px;text-align:center\">\n"; 
echo "			<tr>\n"; 
echo "				<td width=\"210\"></td>\n"; 
echo "				<td id=\"clear_btn\" class=\"td_btn\" onclick=\"location.reload()\">Undo</td>\n"; 
echo "				<td width=\"30\"></td>\n"; 
echo "				<td id=\"submit_btn\" class=\"td_btn\" onclick=\"Validate(document.forms[0])\">Apply</td>\n"; 
echo "				<td width=\"210\"></td>\n"; 
echo "			</tr>\n"; 
echo "		</table>\n"; 
echo "	</div>\n"; 
echo "\n"; 
echo "</div>\n"; 
echo "</body>\n"; 
echo "</html>\n";
?>