<?php
echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "<title>WIFI</title>\n"; 
echo "<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "<script type=\"text/javascript\" src=\"comm.js\"></script>\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "<!--\n"; 
echo "var RekeyInterval,WPAPSK1,Key1Str1,Key2Str1,Key3Str1,Key4Str1,RADIUS_Server,RADIUS_Port\n"; 
echo ",RADIUS_Key,SSID1,WdsEnable,AccessPolicy0,BeaconPeriod,BssidNum,OldBssidNum,WPAPSK2,Key1Str2,Key2Str2\n"; 
echo ",Key3Str2,Key4Str2,SSID2,AccessPolicy1,AuthMode,AuthMode_1,AuthMode_2,EncrypType,EncrypType_1,EncrypType_2,\n"; 
echo "IEEE8021X,IEEE8021X_1,IEEE8021X_2,DefaultKeyID,DefaultKeyID_1,DefaultKeyID_2,HideSSID,HideSSID_1,HideSSID_2,\n"; 
echo "WdsList,AccessControlList0,AccessControlList1,WLAN_USE_DEFAULT,WLAN_AUTO_SSIDWEP,WLAN_WscConfMode;\n"; 
echo "\n"; 
echo "\n"; 
echo "var AuthMode_1Array = new Array();\n"; 
echo "var EncrypType_1Array = new Array();\n"; 
echo "var DefaultKeyID_1Array = new Array();\n"; 
echo "var AuthMode_2Array = new Array();\n"; 
echo "var EncrypType_2Array = new Array();\n"; 
echo "var DefaultKeyID_2Array = new Array();\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "function Validate (passForm) {\n"; 
echo "\n"; 
echo "	var smode_1 = GO(\"security_mode_1\").value;\n"; 
echo "	var KeyType1=0;\n"; 
echo "	var KeyType2=0;\n"; 
echo "	GO(\"KeyType\").value = KeyType1 + \";\" + KeyType2;\n"; 
echo "	passForm.SSID1.value = trim(passForm.SSID1.value);\n"; 
echo "\n"; 
echo "	if(smode_1 == \"WEP\")\n"; 
echo "	{\n"; 
echo "		if(!isHexOrAscii(passForm.KeyStr_1))\n"; 
echo "			return ;\n"; 
echo "\n"; 
echo "		if(passForm.KeyStr_1.value.length == 5 || passForm.KeyStr_1.value.length == 13)\n"; 
echo "			KeyType1 = 1;\n"; 
echo "		GO(\"KeyType\").value = KeyType1 + \";\" + KeyType2;\n"; 
echo "\n"; 
echo "	}\n"; 
echo "	else if(smode_1 == \"WPA\")\n"; 
echo "	{\n"; 
echo "		if(!isInteger(passForm.RekeyInterval))\n"; 
echo "			return ;\n"; 
echo "\n"; 
echo "		if(!ValidPortNum(passForm.RADIUS_Port))\n"; 
echo "		{\n"; 
echo "			alert(\"Invalid Port Number\");\n"; 
echo "			passForm.RADIUS_Port.select();\n"; 
echo "			return;\n"; 
echo "		}\n"; 
echo "		passForm.RADIUS_Server.value = trim(passForm.RADIUS_Server.value);\n"; 
echo "		passForm.RADIUS_Key.value = trim(passForm.RADIUS_Key.value);\n"; 
echo "\n"; 
echo "	}\n"; 
echo "	else if(smode_1 == \"WPAPSK\")\n"; 
echo "	{\n"; 
echo "		if(!isInteger(passForm.RekeyInterval))\n"; 
echo "			return ;\n"; 
echo "		if(!isLenValide8to64(passForm.WPAPSK1))\n"; 
echo "			return ;\n"; 
echo "	}\n"; 
echo "	else if(smode_1 == \"WPA2\")\n"; 
echo "	{\n"; 
echo "		if(!isInteger(passForm.RekeyInterval))\n"; 
echo "			return ;\n"; 
echo "		if(!ValidPortNum(passForm.RADIUS_Port))\n"; 
echo "		{\n"; 
echo "			alert(\"Invalid Port Number\");\n"; 
echo "			passForm.RADIUS_Port.select();\n"; 
echo "			return;\n"; 
echo "		}\n"; 
echo "		passForm.RADIUS_Server.value = trim(passForm.RADIUS_Server.value);\n"; 
echo "		passForm.RADIUS_Key.value = trim(passForm.RADIUS_Key.value);\n"; 
echo "	}\n"; 
echo "	else if(smode_1 == \"WPA2PSK\")\n"; 
echo "	{\n"; 
echo "		if(!isInteger(passForm.RekeyInterval))\n"; 
echo "			return ;\n"; 
echo "		if(!isLenValide8to64(passForm.WPAPSK1))\n"; 
echo "			return ;\n"; 
echo "	}\n"; 
echo "	else if(smode_1 == \"802.1X\")\n"; 
echo "	{\n"; 
echo "		if(!ValidPortNum(passForm.RADIUS_Port))\n"; 
echo "		{\n"; 
echo "			alert(\"Invalid Port Number\");\n"; 
echo "			passForm.RADIUS_Port.select();\n"; 
echo "			return;\n"; 
echo "		}\n"; 
echo "		passForm.RADIUS_Server.value = trim(passForm.RADIUS_Server.value);\n"; 
echo "		passForm.RADIUS_Key.value = trim(passForm.RADIUS_Key.value);\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	if(GO(\"WdsEnable\").value != \"0\")\n"; 
echo "	{\n"; 
echo "		var tmpWdsList = \"\";\n"; 
echo "		for(var i=1;i<=4;i++)\n"; 
echo "		{\n"; 
echo "			var checkflag = macsCheck(GO(\"WdsList\"+i));\n"; 
echo "			if(checkflag == 2)\n"; 
echo "				tmpWdsList += GO(\"WdsList\"+i).value + \";\" ;\n"; 
echo "			else if(checkflag == 1)\n"; 
echo "			{\n"; 
echo "				GO(\"WdsList\"+i).select();\n"; 
echo "				return;\n"; 
echo "			}	\n"; 
echo "		}\n"; 
echo "		if(tmpWdsList.length != 0)\n"; 
echo "			tmpWdsList = tmpWdsList.substr(0,tmpWdsList.length-1);\n"; 
echo "\n"; 
echo "		GO(\"WdsList\").value = tmpWdsList;\n"; 
echo "	}\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "	if(GO(\"AccessPolicy0\").value != \"0\")\n"; 
echo "	{\n"; 
echo "		var tmpAccessPolicy0 = \"\";\n"; 
echo "		for(var i=1;i<=8;i++)\n"; 
echo "		{\n"; 
echo "			var checkflag = macsCheck(GO(\"AccessControlList0\"+i));\n"; 
echo "			if(checkflag == 2)\n"; 
echo "				tmpAccessPolicy0 += GO(\"AccessControlList0\"+i).value + \";\" ;\n"; 
echo "			else if(checkflag == 1)\n"; 
echo "			{\n"; 
echo "				GO(\"AccessControlList0\"+i).select();\n"; 
echo "				return;\n"; 
echo "			}	\n"; 
echo "		}\n"; 
echo "		if(tmpAccessPolicy0.length != 0)\n"; 
echo "			tmpAccessPolicy0 = tmpAccessPolicy0.substr(0,tmpAccessPolicy0.length-1);\n"; 
echo "\n"; 
echo "		GO(\"AccessControlList0\").value = tmpAccessPolicy0;\n"; 
echo "	}\n"; 
echo "\n"; 
echo "\n"; 
echo "	GO(\"AuthMode\").value = GO(\"AuthMode_1\").value + \";\" + ((BssidNum == \"1\")?AuthMode_2:GO(\"AuthMode_2\").value);\n"; 
echo "\n"; 
echo "	GO(\"EncrypType\").value = GO(\"EncrypType_1\").value + \";\" + ((BssidNum == \"1\")?EncrypType_2:GO(\"EncrypType_2\").value);\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "	if(BssidNum == \"1\")\n"; 
echo "	{\n"; 
echo "		GO(\"DefaultKeyID\").value = ((GO(\"security_mode_1\").value == \"Disable\" || GO(\"security_mode_1\").value == \"802.1X\")?\"0\":GO(\"DefaultKeyID_1\").value) + \";\" + DefaultKeyID_2;\n"; 
echo "	}\n"; 
echo "	else\n"; 
echo "	{\n"; 
echo "		GO(\"DefaultKeyID\").value = ((GO(\"security_mode_1\").value == \"Disable\" || GO(\"security_mode_1\").value == \"802.1X\")?\"0\":GO(\"DefaultKeyID_1\").value) + \";\" + ((GO(\"security_mode_2\").value == \"Disable\" || GO(\"security_mode_1\").value == \"802.1X\")?\"0\":GO(\"DefaultKeyID_2\").value);\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	GO(\"HideSSID\").value = GO(\"HideSSID_1\").value + \";\" + ((BssidNum == \"1\")?HideSSID_2:GO(\"HideSSID_2\").value);\n"; 
echo "\n"; 
echo "	if(BssidNum == \"1\")\n"; 
echo "	{\n"; 
echo "		GO(\"IEEE8021X\").value = ((GO(\"security_mode_1\").value == \"802.1X\")?\"1\":\"0\") + \";\" + IEEE8021X_2;\n"; 
echo "	}\n"; 
echo "	else\n"; 
echo "	{\n"; 
echo "		GO(\"IEEE8021X\").value = ((GO(\"security_mode_1\").value == \"802.1X\")?\"1\":\"0\") + \";\" + ((GO(\"security_mode_2\").value == \"802.1X\")?\"1\":\"0\");\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	GO(\"SSID1\").disabled = false;\n"; 
echo "	GO(\"security_mode_1\").disabled = false;\n"; 
echo "	GO(\"AuthMode_1\").disabled = false;\n"; 
echo "	GO(\"EncrypType_1\").disabled = false;\n"; 
echo "	GO(\"WPAPSK1\").disabled = false;\n"; 
echo "	GO(\"DefaultKeyID_1\").disabled = false;\n"; 
echo "	GO(\"KeyStr_1\").disabled = false;\n"; 
echo "/*SSID2*/\n"; 
echo "	if(BssidNum == \"1\")\n"; 
echo "	{\n"; 
echo "		passForm.submit();\n"; 
echo "		return;\n"; 
echo "	}\n"; 
echo "	var smode_2 = GO(\"security_mode_2\").value;\n"; 
echo "\n"; 
echo "	passForm.SSID2.value = trim(passForm.SSID2.value);\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "	if(smode_2 == \"WEP\")\n"; 
echo "	{\n"; 
echo "		if(!isHexOrAscii(passForm.KeyStr_2))\n"; 
echo "			return ;\n"; 
echo "                if(passForm.KeyStr_2.value.length == 5 || passForm.KeyStr_2.value.length == 13)\n"; 
echo "                        KeyType2 = 1;\n"; 
echo "                GO(\"KeyType\").value = KeyType1 + \";\" + KeyType2;\n"; 
echo "\n"; 
echo "	}\n"; 
echo "	else if(smode_2 == \"WPA\")\n"; 
echo "	{\n"; 
echo "		if(!isInteger(passForm.RekeyInterval))\n"; 
echo "			return ;\n"; 
echo "\n"; 
echo "		if(!ValidPortNum(passForm.RADIUS_Port))\n"; 
echo "		{\n"; 
echo "			alert(\"Invalid Port Number\");\n"; 
echo "			passForm.RADIUS_Port.select();\n"; 
echo "			return;\n"; 
echo "		}\n"; 
echo "		passForm.RADIUS_Server.value = trim(passForm.RADIUS_Server.value);\n"; 
echo "		passForm.RADIUS_Key.value = trim(passForm.RADIUS_Key.value);\n"; 
echo "\n"; 
echo "	}\n"; 
echo "	else if(smode_2 == \"WPAPSK\")\n"; 
echo "	{\n"; 
echo "		if(!isInteger(passForm.RekeyInterval))\n"; 
echo "			return ;\n"; 
echo "		if(!isLenValide8to64(passForm.WPAPSK2))\n"; 
echo "			return ;\n"; 
echo "	}\n"; 
echo "	else if(smode_2 == \"WPA2\")\n"; 
echo "	{\n"; 
echo "		if(!isInteger(passForm.RekeyInterval))\n"; 
echo "			return ;\n"; 
echo "		if(!ValidPortNum(passForm.RADIUS_Port))\n"; 
echo "		{\n"; 
echo "			alert(\"Invalid Port Number\");\n"; 
echo "			passForm.RADIUS_Port.select();\n"; 
echo "			return;\n"; 
echo "		}\n"; 
echo "		passForm.RADIUS_Server.value = trim(passForm.RADIUS_Server.value);\n"; 
echo "		passForm.RADIUS_Key.value = trim(passForm.RADIUS_Key.value);\n"; 
echo "	}\n"; 
echo "	else if(smode_2 == \"WPA2PSK\")\n"; 
echo "	{\n"; 
echo "		if(!isInteger(passForm.RekeyInterval))\n"; 
echo "			return ;\n"; 
echo "		if(!isLenValide8to64(passForm.WPAPSK2))\n"; 
echo "			return ;\n"; 
echo "	}\n"; 
echo "	else if(smode_2 == \"802.1X\")\n"; 
echo "	{\n"; 
echo "		if(!ValidPortNum(passForm.RADIUS_Port))\n"; 
echo "		{\n"; 
echo "			alert(\"Invalid Port Number\");\n"; 
echo "			passForm.RADIUS_Port.select();\n"; 
echo "			return;\n"; 
echo "		}\n"; 
echo "		passForm.RADIUS_Server.value = trim(passForm.RADIUS_Server.value);\n"; 
echo "		passForm.RADIUS_Key.value = trim(passForm.RADIUS_Key.value);\n"; 
echo "	}\n"; 
echo "\n"; 
echo "\n"; 
echo "	if(GO(\"AccessPolicy1\").value != \"0\")\n"; 
echo "	{\n"; 
echo "		var tmpAccessPolicy1 = \"\";\n"; 
echo "		for(var i=1;i<=8;i++)\n"; 
echo "		{\n"; 
echo "			var checkflag = macsCheck(GO(\"AccessControlList1\"+i));\n"; 
echo "			if(checkflag == 2)\n"; 
echo "				tmpAccessPolicy1 += GO(\"AccessControlList1\"+i).value + \";\" ;\n"; 
echo "			else if(checkflag == 1)\n"; 
echo "			{\n"; 
echo "				GO(\"AccessControlList1\"+i).select();\n"; 
echo "				return;\n"; 
echo "			}	\n"; 
echo "		}\n"; 
echo "		if(tmpAccessPolicy1.length != 0)\n"; 
echo "			tmpAccessPolicy1 = tmpAccessPolicy1.substr(0,tmpAccessPolicy1.length-1);\n"; 
echo "\n"; 
echo "		GO(\"AccessControlList1\").value = tmpAccessPolicy1;\n"; 
echo "	}\n"; 
echo "	passForm.submit();\n"; 
echo "}\n"; 
echo "function ValidPortNum(obj) {\n"; 
echo "	var port = obj.value;\n"; 
echo "        var d = parseInt(port, 10);\n"; 
echo "\n"; 
echo "        return (CheckPositiveNum(port) && d <= 65535 && d > 0);\n"; 
echo "}\n"; 
echo "function CheckPositiveNum(str) {\n"; 
echo "        var expr = new RegExp(\"^[1-9]+\\d*$\");\n"; 
echo "\n"; 
echo "        if(!str || str.match(expr)==null)\n"; 
echo "                return false;\n"; 
echo "\n"; 
echo "        return true;\n"; 
echo "}\n"; 
echo "function ignoreSpaces(string) {\n"; 
echo "  var temp = \"\";\n"; 
echo "\n"; 
echo "  string = '' + string;\n"; 
echo "  splitstring = string.split(\" \");\n"; 
echo "  for(i = 0; i < splitstring.length; i++)\n"; 
echo "    temp += splitstring[i];\n"; 
echo "  return temp;\n"; 
echo "}\n"; 
echo "\n"; 
echo "function macsCheck(oldmac)\n"; 
echo "{\n"; 
echo "	var mac = ignoreSpaces(oldmac.value);\n"; 
echo "  	oldmac.value = mac;\n"; 
echo "\n"; 
echo "\n"; 
echo "  	if (mac == null || mac == \"\" || mac == \"00:00:00:00:00:00\")\n"; 
echo "  		return 0;\n"; 
echo "  \n"; 
echo "	var m = new Array();\n"; 
echo "	if 	(mac.indexOf(\":\")==-1)\n"; 
echo "	{\n"; 
echo "		if (mac.length != 12)\n"; 
echo "  		{\n"; 
echo "			alert(\"Invalid MAC address format\");\n"; 
echo "	    		return 1;\n"; 
echo "    		}\n"; 
echo "    	for (var i=0; i<6; i++)\n"; 
echo "    		m[i] = mac.substring(i*2, (i+1)*2);\n"; 
echo "	}\n"; 
echo "	else\n"; 
echo "	{\n"; 
echo "  		m = mac.split(\":\");\n"; 
echo "  		if (mac.length != 17 || m.length != 6) \n"; 
echo "  		{\n"; 
echo "			alert(\"Invalid MAC address format\");\n"; 
echo "	    		return 1;\n"; 
echo "    		}\n"; 
echo "  	}\n"; 
echo "    if ((parseInt(m[0],16) & 1) || ((parseInt(m[0],16) & parseInt(m[1],16) & parseInt(m[2],16) & parseInt(m[3],16) & parseInt(m[4],16) & parseInt(m[5],16)) == 0xff) || ((parseInt(m[0],16) | parseInt(m[1],16) | parseInt(m[2],16) | parseInt(m[3],16) | parseInt(m[4],16) | parseInt(m[5],16)) == 0x00))\n"; 
echo "    {\n"; 
echo "		alert(\"Not a MAC address !\");\n"; 
echo "		return 1;\n"; 
echo "    }\n"; 
echo "    \n"; 
echo "	for (var i=0; i<m.length; i++) \n"; 
echo "	{\n"; 
echo "		nameVal = m[i];\n"; 
echo "		len = nameVal.length;\n"; 
echo "\n"; 
echo "		if (len < 1 || len > 2) \n"; 
echo "		{\n"; 
echo "			alert(\"The WAN MAC Address is not correct!!\");\n"; 
echo "			return 1;\n"; 
echo "		}\n"; 
echo "\n"; 
echo "		for(iln = 0; iln < len; iln++) \n"; 
echo "		{\n"; 
echo "			ch = nameVal.charAt(iln).toLowerCase();\n"; 
echo "			if (ch >= '0' && ch <= '9' || ch >= 'a' && ch <= 'f') \n"; 
echo "			{\n"; 
echo "				//Valid Value\n"; 
echo "			}\n"; 
echo "			else \n"; 
echo "			{\n"; 
echo "				alert (\"Invalid hex value \" + nameVal + \" found in MAC address \" + oldmac.value);\n"; 
echo "				return 1;\n"; 
echo "			}\n"; 
echo "		}	\n"; 
echo "	}\n"; 
echo "	//add :\n"; 
echo "	if 	(mac.indexOf(\":\")==-1)\n"; 
echo "	{\n"; 
echo "		oldmac.value = \"\";\n"; 
echo "	    for (var i=0; i<6; i++)\n"; 
echo "    	{\n"; 
echo "    		if (i!=5)\n"; 
echo "    			oldmac.value += (mac.substring(i*2, (i+1)*2) + \":\");\n"; 
echo "    		else\n"; 
echo "    			oldmac.value += mac.substring(i*2, (i+1)*2);\n"; 
echo "    	}\n"; 
echo "	}\n"; 
echo "	return 2;\n"; 
echo "}\n"; 
echo "function isHexOrAscii(obj)\n"; 
echo "{\n"; 
echo "	var s = obj.value;\n"; 
echo "	if(isFieldEmpty(obj))\n"; 
echo "		return false;\n"; 
echo "\n"; 
echo "	if(s.length != 5 && s.length != 10 && s.length != 13 && s.length != 26)\n"; 
echo "	{\n"; 
echo "		alert(\"The Length of Value is Wrong\");\n"; 
echo "		obj.select();	\n"; 
echo "		return false;\n"; 
echo "	}\n"; 
echo "	//check ascii\n"; 
echo "	if(s.length == 5 || s.length == 13)\n"; 
echo "	{\n"; 
echo "		\n"; 
echo "		for(var i=0;i<s.length;i++)\n"; 
echo "		{\n"; 
echo "			var asciiNum = s.charCodeAt(i);\n"; 
echo "			if( (asciiNum == 20) || (asciiNum>64 && asciiNum<91) || (asciiNum>96 && asciiNum<123) || (asciiNum>47 && asciiNum<58) )\n"; 
echo "			{}\n"; 
echo "			else\n"; 
echo "			{\n"; 
echo "				alert(\"The Value must be constructed by Ascii Codes\");\n"; 
echo "				obj.select();	\n"; 
echo "				return false;			\n"; 
echo "			}\n"; 
echo "		}\n"; 
echo "	}\n"; 
echo "	//checkhex\n"; 
echo "	if(s.length == 10 || s.length == 26)\n"; 
echo "	{\n"; 
echo "		for(var i=0;i<s.length;i++)\n"; 
echo "		{\n"; 
echo "\n"; 
echo "			var ch = s.charAt(i).toLowerCase();\n"; 
echo "	  		if ( ch >= '0' && ch <= '9' || ch >= 'a' && ch <= 'f' )\n"; 
echo "			{}\n"; 
echo "			else \n"; 
echo "			{\n"; 
echo "				alert(\"The Value must be constructed by Hex Codes\");\n"; 
echo "				obj.select();\n"; 
echo "				return false;\n"; 
echo "			}\n"; 
echo "		}\n"; 
echo "	}\n"; 
echo "\n"; 
echo "\n"; 
echo "	return true;\n"; 
echo "\n"; 
echo "}\n"; 
echo "function isLenValide8to64(obj)\n"; 
echo "{\n"; 
echo "	var s = obj.value;\n"; 
echo "	if(isFieldEmpty(obj))\n"; 
echo "		return false;\n"; 
echo "\n"; 
echo "	if(s.length < 8 || s.length >64)\n"; 
echo "	{\n"; 
echo "		alert(\"The Length of Value must be located within 8 to 64\");\n"; 
echo "		obj.select();\n"; 
echo "		return false;\n"; 
echo "	}\n"; 
echo "	return true;\n"; 
echo "}\n"; 
echo "function isInteger(obj)\n"; 
echo "{   var i;\n"; 
echo "    var s = obj.value;\n"; 
echo "	if(isFieldEmpty(obj))\n"; 
echo "		return false;\n"; 
echo "    for (i = 0; i < s.length; i++)\n"; 
echo "    {   \n"; 
echo "        // Check that current character is number.\n"; 
echo "        var c = s.charAt(i);\n"; 
echo "        if (((c < \"0\") || (c > \"9\"))){ \n"; 
echo "		alert(\"The Value must be Integer\");\n"; 
echo "		obj.select();\n"; 
echo "		return false;}\n"; 
echo "    }\n"; 
echo "    // All characters are numbers.\n"; 
echo "    return true;\n"; 
echo "}\n"; 
echo "function InitValue(passForm) {\n"; 
echo "	GO(\"WLAN_USE_DEFAULT\").value = WLAN_USE_DEFAULT;\n"; 
echo "	GO(\"RekeyInterval\").value = RekeyInterval;\n"; 
echo "	GO(\"RADIUS_Server\").value = RADIUS_Server;\n"; 
echo "	GO(\"RADIUS_Port\").value = RADIUS_Port;\n"; 
echo "	GO(\"RADIUS_Key\").value = RADIUS_Key;\n"; 
echo "\n"; 
echo "\n"; 
echo "	GO(\"WPAPSK1\").value = WPAPSK1;\n"; 
echo "\n"; 
echo "	if(AuthMode_1 == \"OPEN\" && EncrypType_1 == \"NONE\" && IEEE8021X_1 == \"0\")\n"; 
echo "	{\n"; 
echo "		AuthMode_1Array = [\"OPEN\"];\n"; 
echo "		EncrypType_1Array = [\"NONE\"];\n"; 
echo "		GO(\"security_mode_1\").value = \"Disable\";\n"; 
echo "	}\n"; 
echo "	else if( (AuthMode_1 == \"OPEN\" || AuthMode_1 == \"SHARED\") && EncrypType_1 == \"WEP\" && IEEE8021X_1 == \"0\")\n"; 
echo "	{\n"; 
echo "		AuthMode_1Array = [\"OPEN\",\"SHARED\"];\n"; 
echo "		EncrypType_1Array = [\"WEP\"];\n"; 
echo "		GO(\"security_mode_1\").value = \"WEP\";\n"; 
echo "		DefaultKeyID_1Array = [\"1\",\"2\",\"3\",\"4\"];\n"; 
echo "		do_change4(DefaultKeyID_1,\"1\");\n"; 
echo "		\n"; 
echo "	}\n"; 
echo "	else if( AuthMode_1 == \"WPA\" && (EncrypType_1 == \"TKIP\" || EncrypType_1 == \"AES\" || EncrypType_1 == \"TKIPAES\") && IEEE8021X_1 == \"0\")\n"; 
echo "	{\n"; 
echo "		AuthMode_1Array = [\"WPA\"];\n"; 
echo "		EncrypType_1Array = [\"TKIP\",\"AES\",\"TKIPAES\"];\n"; 
echo "		DefaultKeyID_1Array = [\"2\"];\n"; 
echo "		GO(\"security_mode_1\").value = \"WPA\";\n"; 
echo "	}\n"; 
echo "	else if( AuthMode_1 == \"WPAPSK\" && (EncrypType_1 == \"TKIP\" || EncrypType_1 == \"AES\" || EncrypType_1 == \"TKIPAES\") && IEEE8021X_1 == \"0\")\n"; 
echo "	{\n"; 
echo "		AuthMode_1Array = [\"WPAPSK\"];\n"; 
echo "		EncrypType_1Array = [\"TKIP\",\"AES\",\"TKIPAES\"];\n"; 
echo "		DefaultKeyID_1Array = [\"2\"];\n"; 
echo "		GO(\"security_mode_1\").value = \"WPAPSK\";\n"; 
echo "	}\n"; 
echo "	else if( AuthMode_1 == \"WPA2\" && (EncrypType_1 == \"TKIP\" || EncrypType_1 == \"AES\" || EncrypType_1 == \"TKIPAES\") && IEEE8021X_1 == \"0\")\n"; 
echo "	{\n"; 
echo "		AuthMode_1Array = [\"WPA2\"];\n"; 
echo "		EncrypType_1Array = [\"TKIP\",\"AES\",\"TKIPAES\"];\n"; 
echo "		DefaultKeyID_1Array = [\"2\"];\n"; 
echo "		GO(\"security_mode_1\").value = \"WPA2\";\n"; 
echo "	}\n"; 
echo "	else if( AuthMode_1 == \"WPA2PSK\" && (EncrypType_1 == \"TKIP\" || EncrypType_1 == \"AES\" || EncrypType_1 == \"TKIPAES\") && IEEE8021X_1 == \"0\")\n"; 
echo "	{\n"; 
echo "		AuthMode_1Array = [\"WPA2PSK\"];\n"; 
echo "		EncrypType_1Array = [\"TKIP\",\"AES\",\"TKIPAES\"];\n"; 
echo "		DefaultKeyID_1Array = [\"2\"];\n"; 
echo "		GO(\"security_mode_1\").value = \"WPA2PSK\";\n"; 
echo "	}\n"; 
echo "	else if(AuthMode_1 == \"OPEN\" && EncrypType_1 == \"WEP\" && IEEE8021X_1 == \"1\")\n"; 
echo "	{\n"; 
echo "		AuthMode_1Array = [\"OPEN\"];\n"; 
echo "		EncrypType_1Array = [\"WEP\"];\n"; 
echo "		GO(\"security_mode_1\").value = \"802.1X\";\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	for(var i=0;i<AuthMode_1Array.length;i++)\n"; 
echo "	{\n"; 
echo "		var oOption = document.createElement(\"option\");\n"; 
echo "		oOption.value = AuthMode_1Array[i];\n"; 
echo "		oOption.text = AuthMode_1Array[i];\n"; 
echo "		GO(\"AuthMode_1\").options.add(oOption);\n"; 
echo "	}\n"; 
echo "	GO(\"AuthMode_1\").value = AuthMode_1;\n"; 
echo "	for(var i=0;i<EncrypType_1Array.length;i++)\n"; 
echo "	{\n"; 
echo "		var oOption = document.createElement(\"option\");\n"; 
echo "		oOption.value = EncrypType_1Array[i];\n"; 
echo "		oOption.text = EncrypType_1Array[i];\n"; 
echo "		GO(\"EncrypType_1\").options.add(oOption);\n"; 
echo "	}\n"; 
echo "	GO(\"EncrypType_1\").value = EncrypType_1;\n"; 
echo "\n"; 
echo "\n"; 
echo "	var smode_1 = GO(\"security_mode_1\").value;\n"; 
echo "	\n"; 
echo "	if( (smode_1 != \"Disable\") && (smode_1 != \"802.1X\") )\n"; 
echo "	{\n"; 
echo "		for(var i=0;i<DefaultKeyID_1Array.length;i++)\n"; 
echo "		{\n"; 
echo "			var oOption = document.createElement(\"option\");\n"; 
echo "			oOption.value = DefaultKeyID_1Array[i];\n"; 
echo "			oOption.text = DefaultKeyID_1Array[i];\n"; 
echo "			GO(\"DefaultKeyID_1\").options.add(oOption);\n"; 
echo "		}\n"; 
echo "		GO(\"DefaultKeyID_1\").value = DefaultKeyID_1;\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	if(smode_1 == \"WEP\")\n"; 
echo "	{\n"; 
echo "		GO(\"trDefaultKeyID_1\").style.display = \"\";\n"; 
echo "		GO(\"trKeyStr_1\").style.display = \"\";\n"; 
echo "	}\n"; 
echo "	else if(smode_1 == \"WPA\")\n"; 
echo "	{\n"; 
echo "		GO(\"trRekeyInterval\").style.display = \"\";\n"; 
echo "		GO(\"trRADIUS_Server\").style.display = \"\";\n"; 
echo "		GO(\"trRADIUS_Port\").style.display = \"\";\n"; 
echo "		GO(\"trRADIUS_Key\").style.display = \"\";\n"; 
echo "	}\n"; 
echo "	else if(smode_1 == \"WPAPSK\")\n"; 
echo "	{\n"; 
echo "		GO(\"trRekeyInterval\").style.display = \"\";\n"; 
echo "		GO(\"trWPAPSK1\").style.display = \"\";\n"; 
echo "	}\n"; 
echo "	else if(smode_1 == \"WPA2\")\n"; 
echo "	{\n"; 
echo "		GO(\"trRekeyInterval\").style.display = \"\";\n"; 
echo "		GO(\"trRADIUS_Server\").style.display = \"\";\n"; 
echo "		GO(\"trRADIUS_Port\").style.display = \"\";\n"; 
echo "		GO(\"trRADIUS_Key\").style.display = \"\";\n"; 
echo "	}\n"; 
echo "	else if(smode_1 == \"WPA2PSK\")\n"; 
echo "	{\n"; 
echo "		GO(\"trRekeyInterval\").style.display = \"\";\n"; 
echo "		GO(\"trWPAPSK1\").style.display = \"\";\n"; 
echo "	}\n"; 
echo "	else if(smode_1 == \"802.1X\")\n"; 
echo "	{\n"; 
echo "		GO(\"trRADIUS_Server\").style.display = \"\";\n"; 
echo "		GO(\"trRADIUS_Port\").style.display = \"\";\n"; 
echo "		GO(\"trRADIUS_Key\").style.display = \"\";\n"; 
echo "	}\n"; 
echo "\n"; 
echo "\n"; 
echo "	GO(\"SSID1\").value = SSID1;\n"; 
echo "	GO(\"HideSSID_1\").value = HideSSID_1;\n"; 
echo "	GO(\"WdsEnable\").value = WdsEnable;\n"; 
echo "	if(WdsEnable != \"0\")\n"; 
echo "	{\n"; 
echo "		GO(\"trWdsList\").style.display = \"\";\n"; 
echo "	}\n"; 
echo "	if(WdsList.length != 0)\n"; 
echo "	{\n"; 
echo "		var WdsListArray = WdsList.split(\";\");\n"; 
echo "		if(WdsListArray.length == 1)\n"; 
echo "			GO(\"WdsList1\").value = WdsListArray;\n"; 
echo "		else\n"; 
echo "		{\n"; 
echo "			for(var i=1;i<=WdsListArray.length;i++)\n"; 
echo "			{\n"; 
echo "				GO(\"WdsList\"+i).value = WdsListArray[i-1];\n"; 
echo "			}\n"; 
echo "		}\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	GO(\"AccessPolicy0\").value = AccessPolicy0;\n"; 
echo "	if(AccessPolicy0 != \"0\")\n"; 
echo "	{\n"; 
echo "		GO(\"trAccessControlList0\").style.display = \"\";\n"; 
echo "	}\n"; 
echo "	if(AccessControlList0.length != 0)\n"; 
echo "	{\n"; 
echo "		var AccessControlList0Array = AccessControlList0.split(\";\");\n"; 
echo "		if(AccessControlList0Array.length == 1)\n"; 
echo "			GO(\"AccessControlList01\").value = AccessControlList0Array;\n"; 
echo "		else\n"; 
echo "		{\n"; 
echo "			for(var i=1;i<=AccessControlList0Array.length;i++)\n"; 
echo "			{\n"; 
echo "				GO(\"AccessControlList0\"+i).value = AccessControlList0Array[i-1];\n"; 
echo "			}\n"; 
echo "		}\n"; 
echo "	}\n"; 
echo "	\n"; 
echo "	if(smode_1 == \"WEP\")\n"; 
echo "		GO(\"alertMode\").innerHTML = \"WEP - \" + AuthMode_1;\n"; 
echo "	else\n"; 
echo "		GO(\"alertMode\").innerHTML = smode_1;\n"; 
echo "\n"; 
echo "/*SSID2*/\n"; 
echo "\n"; 
echo "	if(BssidNum == \"2\")\n"; 
echo "		GO(\"FIELDSSID2\").style.display = \"\";	\n"; 
echo "\n"; 
echo "	GO(\"WPAPSK2\").value = WPAPSK2;\n"; 
echo "\n"; 
echo "	if(AuthMode_2 == \"OPEN\" && EncrypType_2 == \"NONE\" && IEEE8021X_2 == \"0\")\n"; 
echo "	{\n"; 
echo "		AuthMode_2Array = [\"OPEN\"];\n"; 
echo "		EncrypType_2Array = [\"NONE\"];\n"; 
echo "		GO(\"security_mode_2\").value = \"Disable\";\n"; 
echo "	}\n"; 
echo "	else if( (AuthMode_2 == \"OPEN\" || AuthMode_2 == \"SHARED\") && EncrypType_2 == \"WEP\" && IEEE8021X_2 == \"0\")\n"; 
echo "	{\n"; 
echo "		AuthMode_2Array = [\"OPEN\",\"SHARED\"];\n"; 
echo "		EncrypType_2Array = [\"WEP\"];\n"; 
echo "		GO(\"security_mode_2\").value = \"WEP\";\n"; 
echo "		DefaultKeyID_2Array = [\"1\",\"2\",\"3\",\"4\"];\n"; 
echo "		do_change4(DefaultKeyID_2,\"2\");\n"; 
echo "		\n"; 
echo "	}\n"; 
echo "	else if( AuthMode_2 == \"WPA\" && (EncrypType_2 == \"TKIP\" || EncrypType_2 == \"AES\" || EncrypType_2 == \"TKIPAES\") && IEEE8021X_2 == \"0\")\n"; 
echo "	{\n"; 
echo "		AuthMode_2Array = [\"WPA\"];\n"; 
echo "		EncrypType_2Array = [\"TKIP\",\"AES\",\"TKIPAES\"];\n"; 
echo "		DefaultKeyID_2Array = [\"2\"];\n"; 
echo "		GO(\"security_mode_2\").value = \"WPA\";\n"; 
echo "	}\n"; 
echo "	else if( AuthMode_2 == \"WPAPSK\" && (EncrypType_2 == \"TKIP\" || EncrypType_2 == \"AES\" || EncrypType_2 == \"TKIPAES\") && IEEE8021X_2 == \"0\")\n"; 
echo "	{\n"; 
echo "		AuthMode_2Array = [\"WPAPSK\"];\n"; 
echo "		EncrypType_2Array = [\"TKIP\",\"AES\",\"TKIPAES\"];\n"; 
echo "		DefaultKeyID_2Array = [\"2\"];\n"; 
echo "		GO(\"security_mode_2\").value = \"WPAPSK\";\n"; 
echo "	}\n"; 
echo "	else if( AuthMode_2 == \"WPA2\" && (EncrypType_2 == \"TKIP\" || EncrypType_2 == \"AES\" || EncrypType_2 == \"TKIPAES\") && IEEE8021X_2 == \"0\")\n"; 
echo "	{\n"; 
echo "		AuthMode_2Array = [\"WPA2\"];\n"; 
echo "		EncrypType_2Array = [\"TKIP\",\"AES\",\"TKIPAES\"];\n"; 
echo "		DefaultKeyID_2Array = [\"2\"];\n"; 
echo "		GO(\"security_mode_2\").value = \"WPA2\";\n"; 
echo "	}\n"; 
echo "	else if( AuthMode_2 == \"WPA2PSK\" && (EncrypType_2 == \"TKIP\" || EncrypType_2 == \"AES\" || EncrypType_2 == \"TKIPAES\") && IEEE8021X_2 == \"0\")\n"; 
echo "	{\n"; 
echo "		AuthMode_2Array = [\"WPA2PSK\"];\n"; 
echo "		EncrypType_2Array = [\"TKIP\",\"AES\",\"TKIPAES\"];\n"; 
echo "		DefaultKeyID_2Array = [\"2\"];\n"; 
echo "		GO(\"security_mode_2\").value = \"WPA2PSK\";\n"; 
echo "	}\n"; 
echo "	else if(AuthMode_2 == \"OPEN\" && EncrypType_2 == \"WEP\" && IEEE8021X_2 == \"1\")\n"; 
echo "	{\n"; 
echo "		AuthMode_2Array = [\"OPEN\"];\n"; 
echo "		EncrypType_2Array = [\"WEP\"];\n"; 
echo "		GO(\"security_mode_2\").value = \"802.1X\";\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	for(var i=0;i<AuthMode_2Array.length;i++)\n"; 
echo "	{\n"; 
echo "		var oOption = document.createElement(\"option\");\n"; 
echo "		oOption.value = AuthMode_2Array[i];\n"; 
echo "		oOption.text = AuthMode_2Array[i];\n"; 
echo "		GO(\"AuthMode_2\").options.add(oOption);\n"; 
echo "	}\n"; 
echo "	GO(\"AuthMode_2\").value = AuthMode_2;\n"; 
echo "	for(var i=0;i<EncrypType_2Array.length;i++)\n"; 
echo "	{\n"; 
echo "		var oOption = document.createElement(\"option\");\n"; 
echo "		oOption.value = EncrypType_2Array[i];\n"; 
echo "		oOption.text = EncrypType_2Array[i];\n"; 
echo "		GO(\"EncrypType_2\").options.add(oOption);\n"; 
echo "	}\n"; 
echo "	GO(\"EncrypType_2\").value = EncrypType_2;\n"; 
echo "\n"; 
echo "\n"; 
echo "	var smode_2 = GO(\"security_mode_2\").value;\n"; 
echo "	\n"; 
echo "	if( (smode_2 != \"Disable\") && (smode_2 != \"802.1X\") )\n"; 
echo "	{\n"; 
echo "		for(var i=0;i<DefaultKeyID_2Array.length;i++)\n"; 
echo "		{\n"; 
echo "			var oOption = document.createElement(\"option\");\n"; 
echo "			oOption.value = DefaultKeyID_2Array[i];\n"; 
echo "			oOption.text = DefaultKeyID_2Array[i];\n"; 
echo "			GO(\"DefaultKeyID_2\").options.add(oOption);\n"; 
echo "		}\n"; 
echo "		GO(\"DefaultKeyID_2\").value = DefaultKeyID_2;\n"; 
echo "	}\n"; 
echo "	\n"; 
echo "\n"; 
echo "	if(BssidNum == \"2\")\n"; 
echo "	{\n"; 
echo "		if(smode_2 == \"WEP\")\n"; 
echo "		{\n"; 
echo "			GO(\"trDefaultKeyID_2\").style.display = \"\";\n"; 
echo "			GO(\"trKeyStr_2\").style.display = \"\";\n"; 
echo "		}\n"; 
echo "		else if(smode_2 == \"WPA\")\n"; 
echo "		{\n"; 
echo "			GO(\"trRekeyInterval\").style.display = \"\";\n"; 
echo "			GO(\"trRADIUS_Server\").style.display = \"\";\n"; 
echo "			GO(\"trRADIUS_Port\").style.display = \"\";\n"; 
echo "			GO(\"trRADIUS_Key\").style.display = \"\";\n"; 
echo "		}\n"; 
echo "		else if(smode_2 == \"WPAPSK\")\n"; 
echo "		{\n"; 
echo "			GO(\"trRekeyInterval\").style.display = \"\";\n"; 
echo "			GO(\"trWPAPSK2\").style.display = \"\";\n"; 
echo "		}\n"; 
echo "		else if(smode_2 == \"WPA2\")\n"; 
echo "		{\n"; 
echo "			GO(\"trRekeyInterval\").style.display = \"\";\n"; 
echo "			GO(\"trRADIUS_Server\").style.display = \"\";\n"; 
echo "			GO(\"trRADIUS_Port\").style.display = \"\";\n"; 
echo "			GO(\"trRADIUS_Key\").style.display = \"\";\n"; 
echo "		}\n"; 
echo "		else if(smode_2 == \"WPA2PSK\")\n"; 
echo "		{\n"; 
echo "			GO(\"trRekeyInterval\").style.display = \"\";\n"; 
echo "			GO(\"trWPAPSK2\").style.display = \"\";\n"; 
echo "		}\n"; 
echo "		else if(smode_2 == \"802.1X\")\n"; 
echo "		{\n"; 
echo "			GO(\"trRADIUS_Server\").style.display = \"\";\n"; 
echo "			GO(\"trRADIUS_Port\").style.display = \"\";\n"; 
echo "			GO(\"trRADIUS_Key\").style.display = \"\";\n"; 
echo "		}\n"; 
echo "\n"; 
echo "	}\n"; 
echo "\n"; 
echo "\n"; 
echo "	GO(\"SSID2\").value = SSID2;\n"; 
echo "	GO(\"HideSSID_2\").value = HideSSID_2;\n"; 
echo "\n"; 
echo "	GO(\"AccessPolicy1\").value = AccessPolicy1;\n"; 
echo "\n"; 
echo "	if(AccessPolicy1 != \"0\")\n"; 
echo "	{\n"; 
echo "		GO(\"trAccessControlList1\").style.display = \"\";\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	if(AccessControlList1.length != 0)\n"; 
echo "	{\n"; 
echo "		var AccessControlList1Array = AccessControlList1.split(\";\");\n"; 
echo "		if(AccessControlList1Array.length == 1)\n"; 
echo "			GO(\"AccessControlList11\").value = AccessControlList1Array;\n"; 
echo "		else\n"; 
echo "		{\n"; 
echo "			for(var i=1;i<=AccessControlList1Array.length;i++)\n"; 
echo "			{\n"; 
echo "				GO(\"AccessControlList1\"+i).value = AccessControlList1Array[i-1];\n"; 
echo "			}\n"; 
echo "		}\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	do_change5(WLAN_USE_DEFAULT);\n"; 
echo "\n"; 
echo "	top.loading = 0;\n"; 
echo "	setInterval('ajax_get_signals()',2000);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function do_change(type)\n"; 
echo "{\n"; 
echo "	//clear all\n"; 
echo "	for(var i=0;i<4;i++)\n"; 
echo "	{\n"; 
echo "\n"; 
echo "		GO(\"AuthMode_\"+type).remove(0);\n"; 
echo "		GO(\"EncrypType_\"+type).remove(0);\n"; 
echo "		GO(\"DefaultKeyID_\"+type).remove(0);\n"; 
echo "	}\n"; 
echo "	//none all\n"; 
echo "	\n"; 
echo "	GO(\"trRekeyInterval\").style.display = \"none\";\n"; 
echo "	GO(\"trWPAPSK\"+type).style.display = \"none\";\n"; 
echo "	GO(\"trDefaultKeyID_\"+type).style.display = \"none\";\n"; 
echo "	GO(\"trKeyStr_\"+type).style.display = \"none\";\n"; 
echo "	GO(\"trRADIUS_Server\").style.display = \"none\";\n"; 
echo "	GO(\"trRADIUS_Port\").style.display = \"none\";\n"; 
echo "	GO(\"trRADIUS_Key\").style.display = \"none\";\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "	var smode = GO(\"security_mode_\"+type).value;\n"; 
echo "	if(smode == \"Disable\")\n"; 
echo "	{\n"; 
echo "		if(type == \"1\")\n"; 
echo "		{\n"; 
echo "			AuthMode_1Array = [\"OPEN\"];\n"; 
echo "			EncrypType_1Array = [\"NONE\"];\n"; 
echo "		}\n"; 
echo "		else\n"; 
echo "		{\n"; 
echo "			AuthMode_2Array = [\"OPEN\"];\n"; 
echo "			EncrypType_2Array = [\"NONE\"];\n"; 
echo "		}\n"; 
echo "	}\n"; 
echo "	else if(smode == \"WEP\")\n"; 
echo "	{\n"; 
echo "		if(type == \"1\")\n"; 
echo "		{\n"; 
echo "			AuthMode_1Array = [\"OPEN\",\"SHARED\"];\n"; 
echo "			EncrypType_1Array = [\"WEP\"];\n"; 
echo "			DefaultKeyID_1Array = [\"1\",\"2\",\"3\",\"4\"];\n"; 
echo "		}\n"; 
echo "		else\n"; 
echo "		{\n"; 
echo "			AuthMode_2Array = [\"OPEN\",\"SHARED\"];\n"; 
echo "			EncrypType_2Array = [\"WEP\"];\n"; 
echo "			DefaultKeyID_2Array = [\"1\",\"2\",\"3\",\"4\"];\n"; 
echo "		}\n"; 
echo "\n"; 
echo "		do_change4(\"1\",type);\n"; 
echo "\n"; 
echo "	}\n"; 
echo "	else if(smode == \"WPA\")\n"; 
echo "	{\n"; 
echo "		if(type == \"1\")\n"; 
echo "		{\n"; 
echo "			AuthMode_1Array = [\"WPA\"];\n"; 
echo "			EncrypType_1Array = [\"TKIP\",\"AES\",\"TKIPAES\"];\n"; 
echo "			DefaultKeyID_1Array = [\"2\"];\n"; 
echo "		}\n"; 
echo "		else\n"; 
echo "		{\n"; 
echo "			AuthMode_2Array = [\"WPA\"];\n"; 
echo "			EncrypType_2Array = [\"TKIP\",\"AES\",\"TKIPAES\"];\n"; 
echo "			DefaultKeyID_2Array = [\"2\"];\n"; 
echo "		}\n"; 
echo "		GO(\"security_mode_\"+type).value = \"WPA\";\n"; 
echo "	}\n"; 
echo "	else if(smode == \"WPAPSK\")\n"; 
echo "	{\n"; 
echo "		if(type == \"1\")\n"; 
echo "		{\n"; 
echo "			AuthMode_1Array = [\"WPAPSK\"];\n"; 
echo "			EncrypType_1Array = [\"TKIP\",\"AES\",\"TKIPAES\"];\n"; 
echo "			DefaultKeyID_1Array = [\"2\"];\n"; 
echo "		}\n"; 
echo "		else\n"; 
echo "		{\n"; 
echo "			AuthMode_2Array = [\"WPAPSK\"];\n"; 
echo "			EncrypType_2Array = [\"TKIP\",\"AES\",\"TKIPAES\"];			\n"; 
echo "			DefaultKeyID_2Array = [\"2\"];\n"; 
echo "		}\n"; 
echo "		GO(\"security_mode_\"+type).value = \"WPAPSK\";\n"; 
echo "	}\n"; 
echo "	else if(smode == \"WPA2\")\n"; 
echo "	{\n"; 
echo "		if(type == \"1\")\n"; 
echo "		{\n"; 
echo "			AuthMode_1Array = [\"WPA2\"];\n"; 
echo "			EncrypType_1Array = [\"TKIP\",\"AES\",\"TKIPAES\"];\n"; 
echo "			DefaultKeyID_1Array = [\"2\"];\n"; 
echo "		}\n"; 
echo "		else\n"; 
echo "		{\n"; 
echo "			AuthMode_2Array = [\"WPA2\"];\n"; 
echo "			EncrypType_2Array = [\"TKIP\",\"AES\",\"TKIPAES\"];\n"; 
echo "			DefaultKeyID_2Array = [\"2\"];\n"; 
echo "		}\n"; 
echo "		GO(\"security_mode_\"+type).value = \"WPA2\";\n"; 
echo "	}\n"; 
echo "	else if(smode == \"WPA2PSK\")\n"; 
echo "	{\n"; 
echo "		if(type == \"1\")\n"; 
echo "		{\n"; 
echo "			AuthMode_1Array = [\"WPA2PSK\"];\n"; 
echo "			EncrypType_1Array = [\"TKIP\",\"AES\",\"TKIPAES\"];\n"; 
echo "			DefaultKeyID_1Array = [\"2\"];\n"; 
echo "		}\n"; 
echo "		else\n"; 
echo "		{\n"; 
echo "			AuthMode_2Array = [\"WPA2PSK\"];\n"; 
echo "			EncrypType_2Array = [\"TKIP\",\"AES\",\"TKIPAES\"];\n"; 
echo "			DefaultKeyID_2Array = [\"2\"];\n"; 
echo "		}\n"; 
echo "		GO(\"security_mode_\"+type).value = \"WPA2PSK\";\n"; 
echo "	}\n"; 
echo "	else if(smode == \"802.1X\")\n"; 
echo "	{\n"; 
echo "		if(type == \"1\")\n"; 
echo "		{\n"; 
echo "			AuthMode_1Array = [\"OPEN\"];\n"; 
echo "			EncrypType_1Array = [\"WEP\"];\n"; 
echo "		}\n"; 
echo "		else\n"; 
echo "		{\n"; 
echo "			AuthMode_2Array = [\"OPEN\"];\n"; 
echo "			EncrypType_2Array = [\"WEP\"];\n"; 
echo "		}\n"; 
echo "		GO(\"security_mode_\"+type).value = \"802.1X\";\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	var counti = 1;\n"; 
echo "	if(BssidNum == \"2\")\n"; 
echo "		counti = 2;\n"; 
echo "	for(var i=1;i<=counti;i++)\n"; 
echo "	{\n"; 
echo "		var smode = GO(\"security_mode_\"+i).value;\n"; 
echo "		if(smode == \"Disable\")\n"; 
echo "		{\n"; 
echo "		}\n"; 
echo "		else if(smode == \"WEP\")\n"; 
echo "		{\n"; 
echo "			GO(\"trDefaultKeyID_\"+i).style.display = \"\";\n"; 
echo "			GO(\"trKeyStr_\"+i).style.display = \"\";\n"; 
echo "		}\n"; 
echo "		else if(smode == \"WPA\")\n"; 
echo "		{\n"; 
echo "			GO(\"trRekeyInterval\").style.display = \"\";\n"; 
echo "			GO(\"trRADIUS_Server\").style.display = \"\";\n"; 
echo "			GO(\"trRADIUS_Port\").style.display = \"\";\n"; 
echo "			GO(\"trRADIUS_Key\").style.display = \"\";\n"; 
echo "		}\n"; 
echo "		else if(smode == \"WPAPSK\")\n"; 
echo "		{\n"; 
echo "			GO(\"trRekeyInterval\").style.display = \"\";\n"; 
echo "			GO(\"trWPAPSK\"+i).style.display = \"\";\n"; 
echo "		}\n"; 
echo "		else if(smode == \"WPA2\")\n"; 
echo "		{\n"; 
echo "			GO(\"trRekeyInterval\").style.display = \"\";\n"; 
echo "			GO(\"trRADIUS_Server\").style.display = \"\";\n"; 
echo "			GO(\"trRADIUS_Port\").style.display = \"\";\n"; 
echo "			GO(\"trRADIUS_Key\").style.display = \"\";\n"; 
echo "		}\n"; 
echo "		else if(smode == \"WPA2PSK\")\n"; 
echo "		{\n"; 
echo "			GO(\"trRekeyInterval\").style.display = \"\";\n"; 
echo "			GO(\"trWPAPSK\"+i).style.display = \"\";\n"; 
echo "		}\n"; 
echo "		else if(smode == \"802.1X\")\n"; 
echo "		{\n"; 
echo "			GO(\"trRADIUS_Server\").style.display = \"\";\n"; 
echo "			GO(\"trRADIUS_Port\").style.display = \"\";\n"; 
echo "			GO(\"trRADIUS_Key\").style.display = \"\";\n"; 
echo "		}\n"; 
echo "	}\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "	if(type == \"1\")\n"; 
echo "	{\n"; 
echo "		for(var i=0;i<AuthMode_1Array.length;i++)\n"; 
echo "		{\n"; 
echo "			var oOption = document.createElement(\"option\");\n"; 
echo "			oOption.value = AuthMode_1Array[i];\n"; 
echo "			oOption.text = AuthMode_1Array[i];\n"; 
echo "			GO(\"AuthMode_1\").options.add(oOption);\n"; 
echo "		}\n"; 
echo "		for(var i=0;i<EncrypType_1Array.length;i++)\n"; 
echo "		{\n"; 
echo "			var oOption = document.createElement(\"option\");\n"; 
echo "			oOption.value = EncrypType_1Array[i];\n"; 
echo "			oOption.text = EncrypType_1Array[i];\n"; 
echo "			GO(\"EncrypType_1\").options.add(oOption);\n"; 
echo "		}\n"; 
echo "		for(var i=0;i<DefaultKeyID_1Array.length;i++)\n"; 
echo "		{\n"; 
echo "			var oOption = document.createElement(\"option\");\n"; 
echo "			oOption.value = DefaultKeyID_1Array[i];\n"; 
echo "			oOption.text = DefaultKeyID_1Array[i];\n"; 
echo "			GO(\"DefaultKeyID_1\").options.add(oOption);\n"; 
echo "		}\n"; 
echo "	}\n"; 
echo "	else\n"; 
echo "	{\n"; 
echo "		for(var i=0;i<AuthMode_2Array.length;i++)\n"; 
echo "		{\n"; 
echo "			var oOption = document.createElement(\"option\");\n"; 
echo "			oOption.value = AuthMode_2Array[i];\n"; 
echo "			oOption.text = AuthMode_2Array[i];\n"; 
echo "			GO(\"AuthMode_2\").options.add(oOption);\n"; 
echo "		}\n"; 
echo "		for(var i=0;i<EncrypType_2Array.length;i++)\n"; 
echo "		{\n"; 
echo "			var oOption = document.createElement(\"option\");\n"; 
echo "			oOption.value = EncrypType_2Array[i];\n"; 
echo "			oOption.text = EncrypType_2Array[i];\n"; 
echo "			GO(\"EncrypType_2\").options.add(oOption);\n"; 
echo "		}\n"; 
echo "		for(var i=0;i<DefaultKeyID_2Array.length;i++)\n"; 
echo "		{\n"; 
echo "			var oOption = document.createElement(\"option\");\n"; 
echo "			oOption.value = DefaultKeyID_2Array[i];\n"; 
echo "			oOption.text = DefaultKeyID_2Array[i];\n"; 
echo "			GO(\"DefaultKeyID_2\").options.add(oOption);\n"; 
echo "		}\n"; 
echo "	}\n"; 
echo "	return;\n"; 
echo "\n"; 
echo "}\n"; 
echo "function do_change2(val)\n"; 
echo "{\n"; 
echo "	if(val == \"0\")\n"; 
echo "		GO(\"trWdsList\").style.display = \"none\";\n"; 
echo "	else\n"; 
echo "		GO(\"trWdsList\").style.display = \"\";\n"; 
echo "\n"; 
echo "}\n"; 
echo "\n"; 
echo "function do_change3(val,type)\n"; 
echo "{\n"; 
echo "	if(val == \"0\")\n"; 
echo "		GO(\"trAccessControlList\"+type).style.display = \"none\";\n"; 
echo "	else\n"; 
echo "		GO(\"trAccessControlList\"+type).style.display = \"\";\n"; 
echo "\n"; 
echo "}\n"; 
echo "function do_change4(val,type)\n"; 
echo "{\n"; 
echo "	eval(\"GO('KeyStr_\"+type+\"').value = Key\"+ val +\"Str\"+type);\n"; 
echo "}\n"; 
echo "function do_change5(val)\n"; 
echo "{\n"; 
echo "	GO(\"SSID1\").disabled = true;\n"; 
echo "	GO(\"security_mode_1\").disabled = true;\n"; 
echo "	GO(\"AuthMode_1\").disabled = true;\n"; 
echo "	GO(\"EncrypType_1\").disabled = true;\n"; 
echo "	GO(\"WPAPSK1\").disabled = true;\n"; 
echo "	GO(\"DefaultKeyID_1\").disabled = true;\n"; 
echo "	GO(\"KeyStr_1\").disabled = true;\n"; 
echo "	if(val == \"1\")\n"; 
echo "	{\n"; 
echo "		if(BssidNum == \"2\")\n"; 
echo "		{\n"; 
echo "			GO(\"FIELDSSID2\").style.display = \"none\";\n"; 
echo "			GO(\"FIELD_Common Radius Setting\").style.display = \"none\";\n"; 
echo "		}\n"; 
echo "\n"; 
echo "		var token2 = WLAN_AUTO_SSIDWEP.split(\",\");\n"; 
echo "		GO(\"SSID1\").value = token2[0];\n"; 
echo "		GO(\"security_mode_1\").value = \"WEP\";\n"; 
echo "		do_change(\"1\");\n"; 
echo "		GO(\"KeyStr_1\").value = token2[1];\n"; 
echo "		BssidNum = \"1\";\n"; 
echo "		\n"; 
echo "	}\n"; 
echo "	else if(val == \"0\")\n"; 
echo "	{\n"; 
echo "		BssidNum = OldBssidNum;\n"; 
echo "		if(BssidNum == \"2\")\n"; 
echo "		{\n"; 
echo "			GO(\"FIELDSSID2\").style.display = \"\";\n"; 
echo "			GO(\"FIELD_Common Radius Setting\").style.display = \"\";\n"; 
echo "		}\n"; 
echo "\n"; 
echo "		GO(\"SSID1\").value = SSID1;\n"; 
echo "		GO(\"WPAPSK1\").value = WPAPSK1;\n"; 
echo "\n"; 
echo "		GO(\"SSID1\").disabled = false;\n"; 
echo "		GO(\"security_mode_1\").disabled = false;\n"; 
echo "		GO(\"AuthMode_1\").disabled = false;\n"; 
echo "		GO(\"EncrypType_1\").disabled = false;\n"; 
echo "		GO(\"WPAPSK1\").disabled = false;\n"; 
echo "		GO(\"DefaultKeyID_1\").disabled = false;\n"; 
echo "		GO(\"KeyStr_1\").disabled = false;\n"; 
echo "	}\n"; 
echo "}\n"; 
echo "\n"; 
echo "function do_change6()\n"; 
echo "{\n"; 
echo "	GO(\"btnStartSetup\").disabled = false;\n"; 
echo "\n"; 
echo "        if(GO(\"WIFI_PIN_MODE\").checked==true)\n"; 
echo "                GO(\"TR_PinCode\").style.display = \"\";\n"; 
echo "        else\n"; 
echo "                GO(\"TR_PinCode\").style.display = \"none\";\n"; 
echo "}\n"; 
echo "\n"; 
echo "function do_change7(val)\n"; 
echo "{\n"; 
echo "	if (val==\"0\")\n"; 
echo "	{\n"; 
echo "		GO(\"WPS_ENABLE\").checked = false;\n"; 
echo "		GO(\"WIFI_PBC_MODE\").disabled = true;\n"; 
echo "		GO(\"btnStartSetup\").disabled = true;\n"; 
echo "		GO(\"WIFI_PIN_MODE\").disabled = true;\n"; 
echo "		GO(\"WIFI_PIN_CODE\").disabled = true;\n"; 
echo "	}\n"; 
echo "	else\n"; 
echo "	{\n"; 
echo "		GO(\"WPS_ENABLE\").checked = true;\n"; 
echo "		GO(\"WIFI_PBC_MODE\").disabled = false;\n"; 
echo "		GO(\"btnStartSetup\").disabled = false;\n"; 
echo "		GO(\"WIFI_PIN_MODE\").disabled = false;\n"; 
echo "		GO(\"WIFI_PIN_CODE\").disabled = false;\n"; 
echo "	}\n"; 
echo "\n"; 
echo "}\n"; 
echo "\n"; 
echo "function InitDisplay(response)\n"; 
echo "{\n"; 
echo "	var token = response.split(\"#\");//#\n"; 
echo "	RekeyInterval = token[0];\n"; 
echo "	WPAPSK1 = token[1];\n"; 
echo "	Key1Str1 = token[2];\n"; 
echo "	Key2Str1 = token[3];\n"; 
echo "	Key3Str1 = token[4];\n"; 
echo "	Key4Str1 = token[5];\n"; 
echo "	RADIUS_Server = token[6];\n"; 
echo "	RADIUS_Port = token[7];\n"; 
echo "	RADIUS_Key = token[8];\n"; 
echo "	SSID1 = token[9];\n"; 
echo "	WdsEnable = token[10];\n"; 
echo "	AccessPolicy0 = token[11];\n"; 
echo "	BeaconPeriod = token[12];\n"; 
echo "	BssidNum = token[13];\n"; 
echo "	OldBssidNum = token[13];\n"; 
echo "	WPAPSK2 = token[14];\n"; 
echo "	Key1Str2 = token[15];\n"; 
echo "	Key2Str2 = token[16];\n"; 
echo "	Key3Str2 = token[17];\n"; 
echo "	Key4Str2 = token[18];\n"; 
echo "	SSID2 = token[19];\n"; 
echo "	AccessPolicy1 = token[20];\n"; 
echo "	\n"; 
echo "	AuthMode = token[21].split(\";\");\n"; 
echo "	AuthMode_1 = AuthMode[0];\n"; 
echo "	AuthMode_2 = (AuthMode.length == 2)?AuthMode[1]:\"\";\n"; 
echo "\n"; 
echo "	EncrypType = token[22].split(\";\");\n"; 
echo "	EncrypType_1 = EncrypType[0];\n"; 
echo "	EncrypType_2 = (EncrypType.length == 2)?EncrypType[1]:\"\";\n"; 
echo "	\n"; 
echo "\n"; 
echo "	IEEE8021X = token[23].split(\";\");\n"; 
echo "	IEEE8021X_1 = IEEE8021X[0];\n"; 
echo "	IEEE8021X_2 = (IEEE8021X.length == 2)?IEEE8021X[1]:\"\";\n"; 
echo "	\n"; 
echo "	DefaultKeyID = token[24].split(\";\");\n"; 
echo "	DefaultKeyID_1 = DefaultKeyID[0];\n"; 
echo "	DefaultKeyID_2 = (DefaultKeyID.length == 2)?DefaultKeyID[1]:\"\";\n"; 
echo "	\n"; 
echo "	HideSSID = token[25].split(\";\");\n"; 
echo "	HideSSID_1 = HideSSID[0];\n"; 
echo "	HideSSID_2 = (HideSSID.length == 2)?HideSSID[1]:\"\";\n"; 
echo "	\n"; 
echo "	WdsList = token[26];\n"; 
echo "	AccessControlList0 = token[27];\n"; 
echo "	AccessControlList1 = token[28];\n"; 
echo "	WLAN_WscConfMode = token[29];\n"; 
echo "	WLAN_USE_DEFAULT = token[30];\n"; 
echo "	WLAN_AUTO_SSIDWEP = token[31];\n"; 
echo "\n"; 
echo "\n"; 
echo "	do_change7(WLAN_WscConfMode);\n"; 
echo "\n"; 
echo "	if (EncrypType_1==\"WEP\" || AuthMode_1==\"SHARED\" || AuthMode_1==\"WPA\" || AuthMode_1==\"WPA2\" || IEEE8021X_1==\"1\")\n"; 
echo "	{\n"; 
echo "		GO(\"TR_EnableWPS\").style.display = \"none\";\n"; 
echo "		GO(\"TR_PbcMode\").style.display = \"none\";\n"; 
echo "		GO(\"TR_PinMode\").style.display = \"none\";\n"; 
echo "		GO(\"TR_PinCode\").style.display = \"none\";\n"; 
echo "		GO(\"WPS_alert\").style.display = \"\";\n"; 
echo "	}\n"; 
echo "	\n"; 
echo "	InitValue(document.forms[0]);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function EnableWPS()\n"; 
echo "{\n"; 
echo "        var WPS_ENABLE = document.getElementById(\"WPS_ENABLE\").checked;\n"; 
echo "\n"; 
echo "        top.$.ajax(\n"; 
echo "                {\n"; 
echo "                        url:\"ajax.php\",\n"; 
echo "                        data:{\n"; 
echo "                                action:\"tag_enableWPS\",\n"; 
echo "				WPS_ENABLE:WPS_ENABLE,\n"; 
echo "                                cache:false,\n"; 
echo "                                time:(new Date()).getTime()\n"; 
echo "                        },\n"; 
echo "                        beforeSend:function(xhr){\n"; 
echo "                                GO(\"WPS_ENABLE\").disabled = true;\n"; 
echo "                                //clearInterval(signal_ID);\n"; 
echo "                        },\n"; 
echo "                        success:function(response){\n"; 
echo "				WLAN_WscConfMode=response;\n"; 
echo "				do_change7(WLAN_WscConfMode);\n"; 
echo "				GO(\"WPS_ENABLE\").disabled = false;\n"; 
echo "                        },\n"; 
echo "                        timeout:2000,\n"; 
echo "                        error:function(xhr)\n"; 
echo "                        {\n"; 
echo "                                location.reload();\n"; 
echo "                        }\n"; 
echo "                }\n"; 
echo "        );\n"; 
echo "}\n"; 
echo "\n"; 
echo "function startWPS()\n"; 
echo "{\n"; 
echo "        var WIFI_PBC_MODE = document.getElementById(\"WIFI_PBC_MODE\").checked;\n"; 
echo "	var WIFI_PIN_MODE = document.getElementById(\"WIFI_PIN_MODE\").checked;\n"; 
echo "	var WIFI_PIN_CODE = document.getElementById(\"WIFI_PIN_CODE\").value;\n"; 
echo "\n"; 
echo "	GO(\"popMessage\").innerHTML = \"\";\n"; 
echo "\n"; 
echo "        top.$.ajax(\n"; 
echo "                {\n"; 
echo "                        url:\"ajax.php\",\n"; 
echo "                        data:{\n"; 
echo "                                action:\"tag_startWPS\",\n"; 
echo "				WPS_PBC_MODE:WIFI_PBC_MODE,\n"; 
echo "				WPS_PIN_MODE:WIFI_PIN_MODE,\n"; 
echo "                                WPS_PIN_CODE:WIFI_PIN_CODE,\n"; 
echo "                                cache:false,\n"; 
echo "                                time:(new Date()).getTime()\n"; 
echo "                        },\n"; 
echo "                        beforeSend:function(xhr){\n"; 
echo "                                GO(\"btnStartSetup\").disabled = true;\n"; 
echo "                                //clearInterval(signal_ID);\n"; 
echo "                        },\n"; 
echo "                        success:function(response){\n"; 
echo "				if(response == \"1\")\n"; 
echo "					GO(\"popMessage\").innerHTML = \"Start wifi PBC\";\n"; 
echo "				else if(response == \"2\")\n"; 
echo "                                	GO(\"popMessage\").innerHTML = \"Start wifi PIN\";\n"; 
echo "				else if(response == \"0\")\n"; 
echo "					alert(\"PIN Code fail !\");\n"; 
echo "				GO(\"btnStartSetup\").disabled = false;\n"; 
echo "                        },\n"; 
echo "                        timeout:2000,\n"; 
echo "                        error:function(xhr)\n"; 
echo "                        {\n"; 
echo "                                location.reload();\n"; 
echo "                        }\n"; 
echo "                }\n"; 
echo "        );\n"; 
echo "}\n"; 
echo "\n"; 
echo "//-->\n"; 
echo "</script>\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body onload=\"init_obj();setTimeout('ajax_get_key()',500);\">\n"; 
echo "\n"; 
echo "<div id=\"main_div\">\n"; 
echo "\n"; 
echo "	<div id=\"container\">\n"; 
echo "		<form method=\"POST\" action=\"ajax.php?action=net_wifi_bssid\">\n"; 
echo "			<input type=\"hidden\" name=\"step\">\n"; 
echo "			<input type=\"hidden\" name=\"HideSSID\" id=\"HideSSID\">\n"; 
echo "			<input type=\"hidden\" name=\"AuthMode\" id=\"AuthMode\">\n"; 
echo "			<input type=\"hidden\" name=\"EncrypType\" id=\"EncrypType\">\n"; 
echo "			<input type=\"hidden\" name=\"DefaultKeyID\" id=\"DefaultKeyID\">\n"; 
echo "			<input type=\"hidden\" name=\"IEEE8021X\" id=\"IEEE8021X\">\n"; 
echo "			<input type=\"hidden\" name=\"KeyType\" id=\"KeyType\">\n"; 
echo "\n"; 
echo "\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>Use Default</legend>\n"; 
echo "					<select name=\"WLAN_USE_DEFAULT\" id=\"WLAN_USE_DEFAULT\" onchange=\"do_change5(this.value)\">\n"; 
echo "						<option value=\"1\">Auto Defined</option>\n"; 
echo "						<option value=\"0\">User Defined</option>\n"; 
echo "					</select>\n"; 
echo "			</FIELDSET>\n"; 
echo "\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend style=\"cursor:pointer;\" onclick=\"var tbl=GO('tbl_1');tbl.style.display=(tbl.style.display == 'none')?'':'none'\">SSID1</legend>\n"; 
echo "			<div  id=\"tbl_1\">\n"; 
echo "			<table><tr>\n"; 
echo "			<td valign=top>\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend style=\"background:#feed00;\">Common Setting</legend>\n"; 
echo "				<table>\n"; 
echo "					<tr><td>SSID</td><td>\n"; 
echo "						<input type=\"text\" style=\"font-family:fixedsys\" name=\"SSID1\" id=\"SSID1\" size=\"10\" onkeypress=\"return goodchars(event,'1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz@_')\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr><td>HideSSID</td><td>\n"; 
echo "						<select name=\"HideSSID_1\" id=\"HideSSID_1\">\n"; 
echo "							<option value=\"0\">Disable</option>\n"; 
echo "							<option value=\"1\">Enable</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td>\n"; 
echo "			<td valign=top>\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend style=\"background:#feed00;\">Security Setting</legend>\n"; 
echo "				<table>\n"; 
echo "					<tr><td>Security Mode</td><td>\n"; 
echo "						<select name=\"security_mode_1\" id=\"security_mode_1\" onchange=\"do_change('1')\">\n"; 
echo "							<option value=\"Disable\">Disable</option>\n"; 
echo "							<option value=\"WEP\">WEP</option>\n"; 
echo "							<option value=\"WPA\">WPA</option>\n"; 
echo "							<option value=\"WPAPSK\">WPA-PSK</option>\n"; 
echo "							<option value=\"WPA2\">WPA2</option>\n"; 
echo "							<option value=\"WPA2PSK\">WPA2-PSK</option>\n"; 
echo "							<option value=\"802.1X\">802.1X</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr><td>Auth Mode</td><td>\n"; 
echo "						<select name=\"AuthMode_1\" id=\"AuthMode_1\">\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr><td>Encryp Type</td><td>\n"; 
echo "						<select name=\"EncrypType_1\" id=\"EncrypType_1\">\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"trWPAPSK1\" style=\"display:none;\"><td>WPAPSK</td><td>\n"; 
echo "						<input type=\"text\" style=\"font-family:fixedsys\" name=\"WPAPSK1\" id=\"WPAPSK1\" size=\"10\" onkeypress=\"return goodchars(event,'1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz@_')\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"trDefaultKeyID_1\" style=\"display:none;\"><td>Key Index</td><td>\n"; 
echo "						<select name=\"DefaultKeyID_1\" id=\"DefaultKeyID_1\" onchange=\"do_change4(this.value,'1')\">\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"trKeyStr_1\" style=\"display:none;\"><td>WEP Key</td><td>\n"; 
echo "						<input type=\"text\" style=\"font-family:fixedsys\" name=\"KeyStr_1\" id=\"KeyStr_1\" size=\"26\" onkeypress=\"return goodchars(event,'1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz@_')\">\n"; 
echo "					</td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td>\n"; 
echo "			</tr>\n"; 
echo "			</table>\n"; 
echo "\n"; 
echo "			<FIELDSET style=\"display:none;\">\n"; 
echo "				<legend style=\"background:#feed00;\">WDS-setting</legend>\n"; 
echo "				<table>\n"; 
echo "					<tr><td>WDS Mode</td><td>\n"; 
echo "						<select name=\"WdsEnable\" id=\"WdsEnable\" onchange=\"do_change2(this.value)\">\n"; 
echo "							<option value=\"0\">Disable</option>\n"; 
echo "							<option value=\"1\">Restrict mode(as Repeater mode)</option>\n"; 
echo "							<option value=\"2\">Bridge mode(STA cannot connet with it)</option>\n"; 
echo "							<option value=\"3\">Repeater mode</option>\n"; 
echo "							<option value=\"4\">Lazy mode</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"trWdsList\" style=\"display:none;\"><td>WDS LIST</td>\n"; 
echo "						<td>\n"; 
echo "						<input type=\"text\" name=\"WdsList1\" id=\"WdsList1\" value=\"00:00:00:00:00:00\">\n"; 
echo "						<input type=\"text\" name=\"WdsList2\" id=\"WdsList2\" value=\"00:00:00:00:00:00\">\n"; 
echo "						<br/>\n"; 
echo "						<input type=\"text\" name=\"WdsList3\" id=\"WdsList3\" value=\"00:00:00:00:00:00\">\n"; 
echo "						<input type=\"text\" name=\"WdsList4\" id=\"WdsList4\" value=\"00:00:00:00:00:00\">\n"; 
echo "						<input type=\"hidden\" name=\"WdsList\" id=\"WdsList\" value=\"\">\n"; 
echo "						</td>\n"; 
echo "					</tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend style=\"background:#feed00;\">ACL-setting</legend>\n"; 
echo "				<table>\n"; 
echo "					<tr><td>Access Control</td><td>\n"; 
echo "						<select name=\"AccessPolicy0\" id=\"AccessPolicy0\" onchange=\"do_change3(this.value,'0')\">\n"; 
echo "							<option value=\"0\">Disable</option>\n"; 
echo "							<option value=\"1\">Allow only following MAC addresses to connect to wireless network</option>\n"; 
echo "							<option value=\"2\">Prevent following MAC addresses from connecting to wireless network</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"trAccessControlList0\" style=\"display:none;\"><td>Access Control List</td><td>\n"; 
echo "						<input type=\"text\" name=\"AccessControlList01\" id=\"AccessControlList01\" size=\"17\" maxlength=\"17\" value=\"00:00:00:00:00:00\">\n"; 
echo "						<input type=\"text\" name=\"AccessControlList02\" id=\"AccessControlList02\" size=\"17\" maxlength=\"17\" value=\"00:00:00:00:00:00\">\n"; 
echo "						<br/>\n"; 
echo "						<input type=\"text\" name=\"AccessControlList03\" id=\"AccessControlList03\" size=\"17\" maxlength=\"17\" value=\"00:00:00:00:00:00\">\n"; 
echo "						<input type=\"text\" name=\"AccessControlList04\" id=\"AccessControlList04\" size=\"17\" maxlength=\"17\" value=\"00:00:00:00:00:00\">\n"; 
echo "						<br/>\n"; 
echo "						<input type=\"text\" name=\"AccessControlList05\" id=\"AccessControlList05\" size=\"17\" maxlength=\"17\" value=\"00:00:00:00:00:00\">\n"; 
echo "						<input type=\"text\" name=\"AccessControlList06\" id=\"AccessControlList06\" size=\"17\" maxlength=\"17\" value=\"00:00:00:00:00:00\">\n"; 
echo "						<br/>\n"; 
echo "						<input type=\"text\" name=\"AccessControlList07\" id=\"AccessControlList07\" size=\"17\" maxlength=\"17\" value=\"00:00:00:00:00:00\">\n"; 
echo "						<input type=\"text\" name=\"AccessControlList08\" id=\"AccessControlList08\" size=\"17\" maxlength=\"17\" value=\"00:00:00:00:00:00\">\n"; 
echo "						<input type=\"hidden\" name=\"AccessControlList0\" id=\"AccessControlList0\" value=\"\">\n"; 
echo "					</td></tr>					\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "\n"; 
echo "			<!--<tr><td valign=top>-->\n"; 
echo "                        <FIELDSET>\n"; 
echo "                                <legend>Wifi Protected Setup</legend>\n"; 
echo "                                <table>\n"; 
echo "					<tr id=\"WPS_alert\" style=\"display:none\"><td >WPS doesn't support current SSID1 Security Mode : <b> <span id=\"alertMode\"></span></b>\n"; 
echo "					<br><br>WPS ONLY support Security Mode :<b> Disable </b>,<b> WPA-PSK </b> and <b> WPA2-PSK</b>. </td></tr>\n"; 
echo "					<tr id=\"TR_EnableWPS\" style=\"display:\"><td>Enable WPS</td>\n"; 
echo "						<td><input type=\"checkbox\" id=\"WPS_ENABLE\" name=\"WPS_ENABLE\" onclick=\"EnableWPS()\"></td></tr>\n"; 
echo "                                        <tr id=\"TR_PbcMode\" style=\"display:\"><td>PBC Mode</td>\n"; 
echo "                                                <td width=\"105\"><input type=\"radio\" name=\"mode\" id=\"WIFI_PBC_MODE\" value=\"WIFI_PBC_MODE\" onclick=\"do_change6()\"></td>\n"; 
echo "                                                <td><input type=\"button\" id=\"btnStartSetup\" value=\"Start\" disabled onclick=\"startWPS()\"></td>\n"; 
echo "						<td rowspan=2 style=\"width:200px;text-align:center\"><div id=\"popMessage\" style=\"font-family:Courier New,Fixedsys,Arial; font-size:12pt;\"></div></td>\n"; 
echo "                                        </tr>\n"; 
echo "                                        <tr id=\"TR_PinMode\" style=\"display:\"><td>PIN Mode</td>\n"; 
echo "                                                <td><input type=\"radio\" name=\"mode\" id=\"WIFI_PIN_MODE\" value=\"WIFI_PIN_MODE\" onclick=\"do_change6()\"></td>\n"; 
echo "                                        </tr>\n"; 
echo "                                        <tr id=\"TR_PinCode\" style=\"display:\"><td>PIN Code</td>\n"; 
echo "                                                <td colspan=2><input type=\"text\" id=\"WIFI_PIN_CODE\" name=\"WIFI_PIN_CODE\"></td></tr>\n"; 
echo "                                </table>\n"; 
echo "                        </FIELDSET>\n"; 
echo "<!-- \n"; 
echo "                       <br/><br/><br/>\n"; 
echo "                        </td>\n"; 
echo "                        </tr>\n"; 
echo "\n"; 
echo "                        </table>\n"; 
echo "-->\n"; 
echo "\n"; 
echo "			</div>\n"; 
echo "			</FIELDSET>\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "			<FIELDSET id=\"FIELDSSID2\" style=\"display:none;\">\n"; 
echo "				<legend style=\"cursor:pointer;\" onclick=\"var tbl=GO('tbl_2');tbl.style.display=(tbl.style.display == 'none')?'':'none'\">SSID2</legend>\n"; 
echo "			<div  id=\"tbl_2\">\n"; 
echo "\n"; 
echo "\n"; 
echo "			<table><tr>\n"; 
echo "			<td valign=top>\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend style=\"background:#feed00;\">Common Setting</legend>\n"; 
echo "				<table>\n"; 
echo "					<tr><td>SSID</td><td>\n"; 
echo "						<input type=\"text\" name=\"SSID2\" id=\"SSID2\"  style=\"font-family:fixedsys\" size=\"10\" onkeypress=\"return goodchars(event,'1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz@_')\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr><td>HideSSID</td><td>\n"; 
echo "						<select name=\"HideSSID_2\" id=\"HideSSID_2\">\n"; 
echo "							<option value=\"0\">Disable</option>\n"; 
echo "							<option value=\"1\">Enable</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td>\n"; 
echo "			<td valign=top>\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend style=\"background:#feed00;\">Security Setting</legend>\n"; 
echo "				<table>\n"; 
echo "					<tr><td>Security Mode</td><td>\n"; 
echo "						<select name=\"security_mode_2\" id=\"security_mode_2\" onchange=\"do_change('2')\">\n"; 
echo "							<option value=\"Disable\">Disable</option>\n"; 
echo "							<option value=\"WEP\">WEP</option>\n"; 
echo "							<option value=\"WPA\">WPA</option>\n"; 
echo "							<option value=\"WPAPSK\">WPA-PSK</option>\n"; 
echo "							<option value=\"WPA2\">WPA2</option>\n"; 
echo "							<option value=\"WPA2PSK\">WPA2-PSK</option>\n"; 
echo "							<option value=\"802.1X\">802.1X</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr><td>Auth Mode</td><td>\n"; 
echo "						<select name=\"AuthMode_2\" id=\"AuthMode_2\">\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr><td>Encryp Type</td><td>\n"; 
echo "						<select name=\"EncrypType_2\" id=\"EncrypType_2\">\n"; 
echo "						</select>\n"; 
echo "					</td></tr>	\n"; 
echo "					<tr id=\"trWPAPSK2\" style=\"display:none;\"><td>WPAPSK</td><td>\n"; 
echo "						<input type=\"text\" name=\"WPAPSK2\" id=\"WPAPSK2\" style=\"font-family:fixedsys\" size=\"10\" onkeypress=\"return goodchars(event,'1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz@_')\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"trDefaultKeyID_2\" style=\"display:none;\"><td>Key Index</td><td>\n"; 
echo "						<select name=\"DefaultKeyID_2\" id=\"DefaultKeyID_2\" onchange=\"do_change4(this.value,'2')\">\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"trKeyStr_2\" style=\"display:none;\"><td>WEP Key</td><td>\n"; 
echo "						<input type=\"text\" name=\"KeyStr_2\" id=\"KeyStr_2\" style=\"font-family:fixedsys\" size=\"26\" onkeypress=\"return goodchars(event,'1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz@_')\">\n"; 
echo "					</td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td>\n"; 
echo "			</tr>\n"; 
echo "			</table>\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend style=\"background:#feed00;\">ACL-setting</legend>\n"; 
echo "				<table>\n"; 
echo "					<tr><td>Access Control</td><td>\n"; 
echo "						<select name=\"AccessPolicy1\" id=\"AccessPolicy1\" onchange=\"do_change3(this.value,'1')\">\n"; 
echo "							<option value=\"0\">Disable</option>\n"; 
echo "							<option value=\"1\">Allow only following MAC addresses to connect to wireless network</option>\n"; 
echo "							<option value=\"2\">Prevent following MAC addresses from connecting to wireless network</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"trAccessControlList1\" style=\"display:none;\"><td>Access Control List</td><td>\n"; 
echo "						<input type=\"text\" name=\"AccessControlList11\" id=\"AccessControlList11\" size=\"17\" maxlength=\"17\" value=\"00:00:00:00:00:00\">\n"; 
echo "						<input type=\"text\" name=\"AccessControlList12\" id=\"AccessControlList12\" size=\"17\" maxlength=\"17\" value=\"00:00:00:00:00:00\">\n"; 
echo "						<br/>\n"; 
echo "						<input type=\"text\" name=\"AccessControlList13\" id=\"AccessControlList13\" size=\"17\" maxlength=\"17\" value=\"00:00:00:00:00:00\">\n"; 
echo "						<input type=\"text\" name=\"AccessControlList14\" id=\"AccessControlList14\" size=\"17\" maxlength=\"17\" value=\"00:00:00:00:00:00\">\n"; 
echo "						<br/>\n"; 
echo "						<input type=\"text\" name=\"AccessControlList15\" id=\"AccessControlList15\" size=\"17\" maxlength=\"17\" value=\"00:00:00:00:00:00\">\n"; 
echo "						<input type=\"text\" name=\"AccessControlList16\" id=\"AccessControlList16\" size=\"17\" maxlength=\"17\" value=\"00:00:00:00:00:00\">\n"; 
echo "						<br/>\n"; 
echo "						<input type=\"text\" name=\"AccessControlList17\" id=\"AccessControlList17\" size=\"17\" maxlength=\"17\" value=\"00:00:00:00:00:00\">\n"; 
echo "						<input type=\"text\" name=\"AccessControlList18\" id=\"AccessControlList18\" size=\"17\" maxlength=\"17\" value=\"00:00:00:00:00:00\">\n"; 
echo "						<input type=\"hidden\" name=\"AccessControlList1\" id=\"AccessControlList1\" value=\"\">\n"; 
echo "					</td></tr>					\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</div>\n"; 
echo "			</FIELDSET>\n"; 
echo "\n"; 
echo "\n"; 
echo "			<FIELDSET id=\"FIELD_Common Radius Setting\">\n"; 
echo "				<legend>Common Radius Setting</legend>\n"; 
echo "				<table>\n"; 
echo "					<tr id=\"trRekeyInterval\" style=\"display:none;\"><td>Rekey Interval</td><td>\n"; 
echo "						<input type=\"text\" name=\"RekeyInterval\" id=\"RekeyInterval\">(Default:3600)\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"trRADIUS_Server\" style=\"display:none;\"><td>RADIUS Server IP</td><td>\n"; 
echo "						<input type=\"text\" name=\"RADIUS_Server\" id=\"RADIUS_Server\" onkeypress=\"return nogoodchars(event,' \\/;')\">\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"trRADIUS_Port\" style=\"display:none;\"><td>RADIUS Server Port</td><td>\n"; 
echo "						<input type=\"text\" name=\"RADIUS_Port\" id=\"RADIUS_Port\">(Default Port:1812)\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"trRADIUS_Key\" style=\"display:none;\"><td>Shared Key</td><td>\n"; 
echo "						<input type=\"text\" name=\"RADIUS_Key\" id=\"RADIUS_Key\" onkeypress=\"return goodchars(event,'1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz@_')\">\n"; 
echo "					</td></tr>\n"; 
echo "\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "		</form>\n"; 
echo "	</div>\n"; 
echo "	<div>\n"; 
echo "		<table style=\"width:600px;height:25px;text-align:center\">\n"; 
echo "			<tr>\n"; 
echo "				<td width=\"150\"></td>\n"; 
echo "				<td id=\"clear_btn\" class=\"td_btn\" onclick=\"location.reload();\">Undo</td>\n"; 
echo "				<td width=\"30\"></td>\n"; 
echo "				<td id=\"submit_btn\" class=\"td_btn\" onclick=\"document.forms[0].step.value=1;Validate(document.forms[0])\">Prev</td>\n"; 
echo "				<td width=\"30\"></td>\n"; 
echo "				<td id=\"submit_btn\" class=\"td_btn\" onclick=\"document.forms[0].step.value=0;Validate(document.forms[0])\">Apply</td>\n"; 
echo "				<td width=\"150\"></td>\n"; 
echo "			</tr>\n"; 
echo "		</table>\n"; 
echo "	</div>\n"; 
echo "</div>\n"; 
echo "</body>\n"; 
echo "</html>\n";
?>