<?php
echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "<title>WIFI</title>\n"; 
echo "<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "<script type=\"text/javascript\" src=\"comm.js\"></script>\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "<!--\n"; 
echo "var WirelessMode,Channel,TxPower,TxBurst,BeaconPeriod,BssidNum,NoForwardingBTNBSSID,ssState,AutoChannelSelect,wifi,SYS_MODEL,WLAN_USE_DEFAULT,WLAN_CountryCode;\n"; 
echo "\n"; 
echo "var signal_ID;\n"; 
echo "\n"; 
echo "function Validate (passForm) {\n"; 
echo "\n"; 
echo "	if(isFieldEmpty(passForm.BeaconPeriod)) return;\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "	passForm.Channel.disabled = false;\n"; 
echo "	passForm.BssidNum.disabled = false;\n"; 
echo "	passForm.WLAN_USE_DEFAULT.disabled = false;\n"; 
echo "	passForm.sid.value = sid;\n"; 
echo "	passForm.submit();\n"; 
echo "}\n"; 
echo "function InitDisplay(response)\n"; 
echo "{\n"; 
echo "	var token = response.split(\"#\");//#\n"; 
echo "\n"; 
echo "	WirelessMode = token[0];\n"; 
echo "	Channel = token[1];\n"; 
echo "	TxPower = token[2];\n"; 
echo "	TxBurst= token[3];\n"; 
echo "	BeaconPeriod = token[4];\n"; 
echo "	BssidNum = token[5];\n"; 
echo "	NoForwardingBTNBSSID = token[6];\n"; 
echo "	ssState = token[7];\n"; 
echo "	AutoChannelSelect = token[8];\n"; 
echo "	WLAN_CountryCode = token[9];\n"; 
echo "	wifi = token[10];\n"; 
echo "	SYS_MODEL = token[11];\n"; 
echo "	WLAN_USE_DEFAULT = token[12];\n"; 
echo "	\n"; 
echo "	tr_display(\"START_STOP_WIFI\");\n"; 
echo "	tr_display(\"WirelessMode\");\n"; 
echo "	tr_display(\"Channel\");\n"; 
echo "	tr_display(\"TxPower\");\n"; 
echo "	tr_display(\"TxBurst\");\n"; 
echo "	tr_display(\"BeaconPeriod\");\n"; 
echo "	tr_display(\"BssidNum\");\n"; 
echo "	tr_display(\"NoForwardingBTNBSSID\");\n"; 
echo "\n"; 
echo "	obj_readonly(\"WirelessMode\");\n"; 
echo "	obj_readonly(\"Channel\");\n"; 
echo "	obj_readonly(\"TxPower\");\n"; 
echo "	obj_readonly(\"TxBurst\");\n"; 
echo "	obj_readonly(\"BeaconPeriod\");\n"; 
echo "	obj_readonly(\"BssidNum\");\n"; 
echo "	obj_readonly(\"NoForwardingBTNBSSID\");\n"; 
echo "\n"; 
echo "	InitValue(document.forms[0]);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function InitValue(passForm) {\n"; 
echo "	if(wifi == 1)\n"; 
echo "	{\n"; 
echo "		GO(\"clear_btn\").style.display = \"\";\n"; 
echo "		GO(\"next_btn\").style.display = \"\";\n"; 
echo "		GO(\"submit_btn\").style.display = \"\";\n"; 
echo "	}\n"; 
echo "	else\n"; 
echo "	{\n"; 
echo "		hideAllSelect();\n"; 
echo "		GO(\"wifi_mask\").style.display = \"\";\n"; 
echo "		GO(\"wifi_alert\").style.display = \"\";\n"; 
echo "		top.loading = 0;\n"; 
echo "		return;\n"; 
echo "	}\n"; 
echo "\n"; 
echo "\n"; 
echo "	if(pri_a(uitems[inner_url][\"START_STOP_WIFI\"]))\n"; 
echo "	{\n"; 
echo "		if (ssState == \"0\")\n"; 
echo "			GO(\"btnStartSs\").disabled = false;\n"; 
echo "		else\n"; 
echo "			GO(\"btnStopSs\").disabled = false;\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	GO(\"WirelessMode\").value = WirelessMode;\n"; 
echo "\n"; 
echo "	//create channel option\n"; 
echo "\n"; 
echo "	var oOption = document.createElement(\"option\");\n"; 
echo "	oOption.value = \"Auto\";\n"; 
echo "	oOption.text = \"Auto\";\n"; 
echo "	GO(\"Channel\").options.add(oOption);\n"; 
echo "\n"; 
echo "	var ChannelMin = WLAN_CountryCode.charAt(0);\n"; 
echo "	var Channel_range = WLAN_CountryCode.charAt(1);\n"; 
echo "\n"; 
echo "	switch(Channel_range.toUpperCase())\n"; 
echo "	{\n"; 
echo "  		case \"A\":\n"; 
echo "   			Channel_range = 10;\n"; 
echo "   			break;\n"; 
echo "  		case \"B\":\n"; 
echo "			Channel_range = 11;\n"; 
echo "                	break;\n"; 
echo "                case \"C\":\n"; 
echo "			Channel_range = 12;\n"; 
echo "                	break;\n"; 
echo "                case \"D\":\n"; 
echo "			Channel_range = 13;\n"; 
echo "                	break;\n"; 
echo "                case \"E\":\n"; 
echo "			Channel_range = 14;\n"; 
echo "                	break;\n"; 
echo "		case \"F\":\n"; 
echo "                        Channel_range = 15;\n"; 
echo "                        break;\n"; 
echo "	 }\n"; 
echo "\n"; 
echo "	var ChannelMax = parseInt(ChannelMin) + parseInt(Channel_range) - 1;\n"; 
echo "	\n"; 
echo "	if(SYS_MODEL == \"WIXM-171\")\n"; 
echo "	{\n"; 
echo "		ChannelMin = 9;\n"; 
echo "		ChannelMax = 13;\n"; 
echo "	}\n"; 
echo "	else if(SYS_MODEL == \"WIXM-173\")\n"; 
echo "	{\n"; 
echo "		ChannelMin = 1;\n"; 
echo "		ChannelMax = 3;\n"; 
echo "	}\n"; 
echo "	else if(SYS_MODEL == \"WIXM-174\")\n"; 
echo "	{\n"; 
echo "		ChannelMin = 1;\n"; 
echo "		ChannelMax = 13;\n"; 
echo "	}\n"; 
echo "/*\n"; 
echo "	else if(SYS_MODEL == \"WIXFMR-107\")\n"; 
echo "	{\n"; 
echo "		ChannelMin = 9;\n"; 
echo "                ChannelMax = 13;\n"; 
echo "	}\n"; 
echo "*/	\n"; 
echo "	for(var i=ChannelMin;i<=ChannelMax;i++)\n"; 
echo "	{\n"; 
echo "		var oOption = document.createElement(\"option\");\n"; 
echo "		oOption.value = i;\n"; 
echo "		oOption.text = i;\n"; 
echo "		GO(\"Channel\").options.add(oOption);\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	if(AutoChannelSelect == \"1\")\n"; 
echo "		GO(\"Channel\").value = \"Auto\";\n"; 
echo "	else\n"; 
echo "		GO(\"Channel\").value = Channel;\n"; 
echo "\n"; 
echo "	GO(\"TxPower\").value = TxPower;\n"; 
echo "	GO(\"TxBurst\").value = TxBurst;\n"; 
echo "	GO(\"BeaconPeriod\").value = BeaconPeriod;\n"; 
echo "\n"; 
echo "	GO(\"BssidNum\").value = BssidNum;\n"; 
echo "	GO(\"NoForwardingBTNBSSID\").value = NoForwardingBTNBSSID;\n"; 
echo "\n"; 
echo "	do_change(BssidNum);\n"; 
echo "	GO(\"WLAN_USE_DEFAULT\").value = WLAN_USE_DEFAULT;\n"; 
echo "	do_change2(WLAN_USE_DEFAULT);\n"; 
echo "	top.loading = 0;\n"; 
echo "	signal_ID = setInterval('ajax_get_signals()',2000);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function do_change(val)\n"; 
echo "{\n"; 
echo "	if(pri_d(uitems[inner_url][\"NoForwardingBTNBSSID\"]))\n"; 
echo "	{\n"; 
echo "		if(val == \"1\")\n"; 
echo "			GO(\"TR_NoForwardingBTNBSSID\").style.display = \"none\";\n"; 
echo "		else\n"; 
echo "			GO(\"TR_NoForwardingBTNBSSID\").style.display = \"\";\n"; 
echo "	}\n"; 
echo "}\n"; 
echo "\n"; 
echo "function do_change2(val)\n"; 
echo "{\n"; 
echo "	GO(\"BssidNum\").disabled = true;\n"; 
echo "	GO(\"NoForwardingBTNBSSID\").disabled = true;\n"; 
echo "	if(val == \"1\")\n"; 
echo "	{\n"; 
echo "		GO(\"BssidNum\").value = 1;\n"; 
echo "		do_change(\"1\");\n"; 
echo "	}\n"; 
echo "	else if(val == \"0\")\n"; 
echo "	{\n"; 
echo "		if(pri_d(uitems[inner_url][\"BssidNum\"]))\n"; 
echo "			GO(\"BssidNum\").disabled = false;\n"; 
echo "		if(pri_d(uitems[inner_url][\"NoForwardingBTNBSSID\"]))\n"; 
echo "			GO(\"NoForwardingBTNBSSID\").disabled = false;\n"; 
echo "	}\n"; 
echo "\n"; 
echo "\n"; 
echo "}\n"; 
echo "\n"; 
echo "\n"; 
echo "function startSs()\n"; 
echo "{\n"; 
echo "\n"; 
echo "	top.$.ajax(\n"; 
echo "		{\n"; 
echo "			url:\"ajax.php\",\n"; 
echo "			data:{\n"; 
echo "				action:\"tag_startWifi\",\n"; 
echo "				cache:false,\n"; 
echo "				time:(new Date()).getTime()\n"; 
echo "			},\n"; 
echo "			beforeSend:function(xhr){\n"; 
echo "				GO(\"btnStartSs\").disabled = true;\n"; 
echo "				clearInterval(signal_ID);\n"; 
echo "			},\n"; 
echo "			success:function(response){\n"; 
echo "				GO(\"btnStopSs\").disabled = false;\n"; 
echo "				try{ajax_get_signals()}catch(e){}\n"; 
echo "				signal_ID = setInterval('ajax_get_signals()',2000);\n"; 
echo "			},\n"; 
echo "			timeout:2000,\n"; 
echo "			error:function(xhr)\n"; 
echo "			{\n"; 
echo "				location.reload();\n"; 
echo "			}\n"; 
echo "		}\n"; 
echo "	);\n"; 
echo "}\n"; 
echo "\n"; 
echo "\n"; 
echo "function stopSs()\n"; 
echo "{\n"; 
echo "	top.$.ajax(\n"; 
echo "		{\n"; 
echo "			url:\"ajax.php\",\n"; 
echo "			data:{\n"; 
echo "				action:\"tag_stopWifi\",\n"; 
echo "				cache:false,\n"; 
echo "				time:(new Date()).getTime()\n"; 
echo "			},\n"; 
echo "			beforeSend:function(xhr){\n"; 
echo "				GO(\"btnStopSs\").disabled = true;\n"; 
echo "				clearInterval(signal_ID);\n"; 
echo "			},\n"; 
echo "			success:function(response){\n"; 
echo "				GO(\"btnStartSs\").disabled = false;\n"; 
echo "				try{ajax_get_signals()}catch(e){}\n"; 
echo "				signal_ID = setInterval('ajax_get_signals()',2000);\n"; 
echo "			},\n"; 
echo "			timeout:2000,\n"; 
echo "			error:function(xhr)\n"; 
echo "			{\n"; 
echo "				location.reload();\n"; 
echo "			}\n"; 
echo "		}\n"; 
echo "	);\n"; 
echo "\n"; 
echo "}\n"; 
echo "\n"; 
echo "//-->\n"; 
echo "</script>\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body onload=\"init_obj();setTimeout('ajax_get_key()',500);\">\n"; 
echo "\n"; 
echo "	<div id=\"wifi_mask\" style=\"display:none;position:absolute;top:0px;width:780px;height:574px;background-color:gray;visibility: visible;filter:alpha(opacity=40);-moz-opacity:0.4;opacity:0.4;z-index:3000;text-align:center;\"></div>\n"; 
echo "\n"; 
echo "	<div id=\"wifi_alert\" style=\"display:none;position:absolute;top:100px;left:20px;width:600px;height:150px;color:white;visibility: visible;z-index:3000;text-align:center;\"><font size=\"8\">Insert WiFi dongle to enable</font></div>\n"; 
echo "\n"; 
echo "<div id=\"main_div\">\n"; 
echo "	<div id=\"container\">\n"; 
echo "		<form method=\"POST\" action=\"ajax.php?action=net_wifi_setting\">\n"; 
echo "			<input type=\"hidden\" name=\"sid\" id=\"sid\">\n"; 
echo "			<input type=\"hidden\" name=\"step\">\n"; 
echo "		<table width=\"90%\"><tr>\n"; 
echo "		<td width=\"50%\">\n"; 
echo "		<FIELDSET>\n"; 
echo "			<legend>Start/Stop WiFi</legend>\n"; 
echo "				<table><tr id=\"TR_START_STOP_WIFI\" style=\"display:none\"><td>\n"; 
echo "				<input type=\"button\" id=\"btnStartSs\" value=\"Start\" disabled onclick=\"startSs()\">\n"; 
echo "				<input type=\"button\" id=\"btnStopSs\" value=\"Stop\" disabled onclick=\"stopSs()\">\n"; 
echo "				</td></tr></table>\n"; 
echo "		</FIELDSET>\n"; 
echo "		</td>\n"; 
echo "		<td width=\"50%\">\n"; 
echo "		<FIELDSET>\n"; 
echo "			<legend>Use Default</legend>\n"; 
echo "				<table><tr><td>\n"; 
echo "				<select name=\"WLAN_USE_DEFAULT\" id=\"WLAN_USE_DEFAULT\" onchange=\"do_change2(this.value)\">\n"; 
echo "					<option value=\"1\">Auto Defined</option>\n"; 
echo "					<option value=\"0\">User Defined</option>\n"; 
echo "				</select>\n"; 
echo "				</td></tr></table>\n"; 
echo "		</FIELDSET>\n"; 
echo "		</td></tr>\n"; 
echo "		</table>\n"; 
echo "\n"; 
echo "\n"; 
echo "			<table><tr><td valign=top rowspan=2>\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>Wifi-Setting</legend>\n"; 
echo "				<table>\n"; 
echo "\n"; 
echo "					<tr id=\"TR_WirelessMode\" style=\"display:none\"><td>Wireless Mode</td><td>\n"; 
echo "						<select name=\"WirelessMode\" id=\"WirelessMode\">\n"; 
echo "							<option value=\"9\">B/G/N mixed</option>\n"; 
echo "							<option value=\"7\">G/N mixed</option>\n"; 
echo "							<option value=\"0\">B/G mixed</option>\n"; 
echo "							<option value=\"6\">N only</option>\n"; 
echo "							<option value=\"4\">G only</option>\n"; 
echo "							<option value=\"1\">B only</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_Channel\" style=\"display:none\"><td>Channel</td><td>\n"; 
echo "						<select name=\"Channel\" id=\"Channel\">\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_TxPower\" style=\"display:none\"><td>Tx Power</td><td>\n"; 
echo "						<select name=\"TxPower\" id=\"TxPower\">\n"; 
echo "							<option value=\"100\">100%</option>\n"; 
echo "							<option value=\"75\">75%</option>\n"; 
echo "							<option value=\"50\">50%</option>\n"; 
echo "							<option value=\"25\">25%</option>\n"; 
echo "							<option value=\"1\">1%</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_TxBurst\" style=\"display:none\"><td>Tx Burst</td><td>\n"; 
echo "						<select name=\"TxBurst\" id=\"TxBurst\">\n"; 
echo "							<option value=\"1\">Enable</option>\n"; 
echo "							<option value=\"0\">Disable</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					<tr id=\"TR_BeaconPeriod\" style=\"display:none\"><td>Beacon Period</td><td>\n"; 
echo "						<input type=\"text\" name=\"BeaconPeriod\" id=\"BeaconPeriod\" size=\"5\" maxlength=\"10\" onkeypress=\"return goodchars(event,' 0123456789')\">(Default:100)\n"; 
echo "					</td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td>\n"; 
echo "			<td valign=top>\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>Multiple SSID</legend>\n"; 
echo "				<table>\n"; 
echo "					<tr id=\"TR_BssidNum\" style=\"display:none\"><td>multiple BSSID Number</td><td>\n"; 
echo "						<select name=\"BssidNum\" id=\"BssidNum\" onchange=\"do_change(this.value)\">\n"; 
echo "							<option value=\"1\">1</option>\n"; 
echo "							<option value=\"2\">2</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "					\n"; 
echo "					<tr id=\"TR_NoForwardingBTNBSSID\" style=\"display:none;\"><td>No Forwarding<br/>between BSSID</td>\n"; 
echo "					<td>				\n"; 
echo "						<select name=\"NoForwardingBTNBSSID\" id=\"NoForwardingBTNBSSID\">\n"; 
echo "							<option value=\"1\">Enable</option>\n"; 
echo "							<option value=\"0\">Disable</option>\n"; 
echo "						</select>\n"; 
echo "					</td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			<br/><br/><br/>\n"; 
echo "			</td>\n"; 
echo "			</tr>\n"; 
echo "			</table>\n"; 
echo "		</form>\n"; 
echo "	</div>\n"; 
echo "	<div>\n"; 
echo "		<table style=\"width:600px;height:25px;text-align:center\">\n"; 
echo "			<tr>\n"; 
echo "				<td width=\"150\"></td>\n"; 
echo "				<td id=\"clear_btn\" class=\"td_btn\" style=\"display:none\" onclick=\"location.reload()\">Undo</td>\n"; 
echo "				<td width=\"30\"></td>\n"; 
echo "				<td id=\"next_btn\" class=\"td_btn\" style=\"display:none\" onclick=\"document.forms[0].step.value=1;Validate(document.forms[0])\">Next</td>\n"; 
echo "				<td width=\"30\"></td>\n"; 
echo "				<td id=\"submit_btn\" class=\"td_btn\" style=\"display:none\" onclick=\"document.forms[0].step.value=0;Validate(document.forms[0])\">Apply</td>\n"; 
echo "				<td width=\"150\"></td>\n"; 
echo "			</tr>\n"; 
echo "		</table>\n"; 
echo "	</div>\n"; 
echo "</div>\n"; 
echo "</body>\n"; 
echo "</html>\n";
?>