<?php
echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "<title></title>\n"; 
echo "<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "<script type=\"text/javascript\" src=\"comm.js\"></script>\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "<!--\n"; 
echo "var pftData_Array,pftData_raw;\n"; 
echo "var pftData = new Array();\n"; 
echo "\n"; 
echo "Array.prototype.remove = function(from, to) {\n"; 
echo "	var rest = this.slice((to || from) + 1 || this.length);\n"; 
echo "	this.length = from < 0 ? this.length + from : from;\n"; 
echo "	return this.push.apply(this, rest);\n"; 
echo "};\n"; 
echo "\n"; 
echo "function pft_obj()\n"; 
echo "{\n"; 
echo "	this.value = pftData;\n"; 
echo "}\n"; 
echo "\n"; 
echo "var pft;\n"; 
echo "\n"; 
echo "function updateAllRow()\n"; 
echo "{\n"; 
echo "	for(var i=0;i<pft.length;i++)\n"; 
echo "	{\n"; 
echo "		pft[i].Enable = (GO(\"Enb_\"+i).checked)?\"Y\":\"N\";\n"; 
echo "		pft[i].Name = GO(\"Name_\"+i).value;\n"; 
echo "		pft[i].Protocol = GO(\"Type_\"+i).value;\n"; 
echo "		pft[i].WANPort_Begin = GO(\"WPtb_\"+i).value;\n"; 
echo "		pft[i].WANPort_End = GO(\"WPte_\"+i).value;\n"; 
echo "		pft[i].LANPort_Begin = GO(\"LPtb_\"+i).value;\n"; 
echo "		pft[i].LANPort_End = GO(\"LPte_\"+i).value;\n"; 
echo "		pft[i].ServerIp = GO(\"ServerIp_\"+i).value;\n"; 
echo "	}\n"; 
echo "}\n"; 
echo "\n"; 
echo "function fp_insert()\n"; 
echo "{\n"; 
echo "	if (pft.length >= 30) return;\n"; 
echo "	var newobj = {\"Enable\":\"\",\"Name\":\"\",\"Protocol\":\"\",\"WANPort_Begin\":\"\",\"WANPort_End\":\"\",\"LANPort_Begin\":\"\",\"LANPort_End\":\"\",\"ServerIp\":\"\"};\n"; 
echo "\n"; 
echo "\n"; 
echo "	updateAllRow();\n"; 
echo "	pft.push(newobj);\n"; 
echo "	removeAllRow();\n"; 
echo "	for(var i=0;i<pft.length;i++)\n"; 
echo "		addRowToTable(pft[i]);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function addRowToTable(obj)\n"; 
echo "{\n"; 
echo "\n"; 
echo "	var tbl = GO('pf');\n"; 
echo "	var lastRow = tbl.rows.length;\n"; 
echo "	var iteration = lastRow-2;\n"; 
echo "	var row = tbl.insertRow(lastRow);\n"; 
echo "\n"; 
echo "	//No\n"; 
echo "	var cellno = row.insertCell(0);\n"; 
echo "	var textNode = document.createTextNode(iteration+1);\n"; 
echo "	cellno.appendChild(textNode);\n"; 
echo "\n"; 
echo "\n"; 
echo "	//Enable\n"; 
echo "	var cellenable = row.insertCell(1);\n"; 
echo "	var el = document.createElement('input');\n"; 
echo "	el.type = 'checkbox';\n"; 
echo "	el.id = 'Enb_' + iteration;\n"; 
echo "	el.name = 'Enb_' + iteration;\n"; 
echo "	el.defaultChecked = (obj.Enable == \"Y\")?true:false;\n"; 
echo "	el.value = (obj.Enable)?\"Y\":\"N\";\n"; 
echo "	el.onclick = function(){this.value = (this.checked)?\"Y\":\"N\"};\n"; 
echo "	el.disabled = (!pri_a(uitems[inner_url][\"NETFILTER_NAT_FORWARD\"]))?true:false;\n"; 
echo "	cellenable.appendChild(el);\n"; 
echo "\n"; 
echo "	//Name\n"; 
echo "	var cellwanpb = row.insertCell(2);\n"; 
echo "	var el = document.createElement('input');\n"; 
echo "	el.type = 'text';\n"; 
echo "	el.id = 'Name_' + iteration;\n"; 
echo "	el.name = 'Name_' + iteration;\n"; 
echo "	el.size = 8;\n"; 
echo "	el.maxLength = 25;\n"; 
echo "	el.value = obj.Name;\n"; 
echo "	el.disabled = (!pri_a(uitems[inner_url][\"NETFILTER_NAT_FORWARD\"]))?true:false;\n"; 
echo "	cellwanpb.appendChild(el);\n"; 
echo "\n"; 
echo "	//Protocol\n"; 
echo "	var cellprotocol = row.insertCell(3);\n"; 
echo "	var sel = document.createElement('select');\n"; 
echo "	sel.id = 'Type_' + iteration;\n"; 
echo "	sel.name = 'Type_' + iteration;\n"; 
echo "	sel.options[0] = new Option('TCP', '0');\n"; 
echo "	sel.options[1] = new Option('UDP', '1');\n"; 
echo "	sel.options[2] = new Option('TCP/UDP', '2');\n"; 
echo "	sel.value = obj.Protocol;\n"; 
echo "	sel.disabled = (!pri_a(uitems[inner_url][\"NETFILTER_NAT_FORWARD\"]))?true:false;\n"; 
echo "	cellprotocol.appendChild(sel);\n"; 
echo "\n"; 
echo "\n"; 
echo "	//WAN Port Begin\n"; 
echo "	var cellwanpb = row.insertCell(4);\n"; 
echo "	var el = document.createElement('input');\n"; 
echo "	el.type = 'text';\n"; 
echo "	el.id = 'WPtb_' + iteration;\n"; 
echo "	el.name = 'WPtb_' + iteration;\n"; 
echo "	el.size = 4;\n"; 
echo "	el.maxLength = 5;\n"; 
echo "	el.value = obj.WANPort_Begin;\n"; 
echo "	el.disabled = (!pri_a(uitems[inner_url][\"NETFILTER_NAT_FORWARD\"]))?true:false;\n"; 
echo "	cellwanpb.appendChild(el);\n"; 
echo "\n"; 
echo "	//WAN Port End\n"; 
echo "	var cellwanpe = row.insertCell(5);\n"; 
echo "	var el = document.createElement('input');\n"; 
echo "	el.type = 'text';\n"; 
echo "	el.id = 'WPte_' + iteration;\n"; 
echo "	el.name = 'WPte_' + iteration;\n"; 
echo "	el.size = 4;\n"; 
echo "	el.maxLength = 5;\n"; 
echo "	el.value = obj.WANPort_End;\n"; 
echo "	el.disabled = (!pri_a(uitems[inner_url][\"NETFILTER_NAT_FORWARD\"]))?true:false;\n"; 
echo "	cellwanpe.appendChild(el);\n"; 
echo "\n"; 
echo "	//LAN Port Begin\n"; 
echo "	var cellwanpb = row.insertCell(6);\n"; 
echo "	var el = document.createElement('input');\n"; 
echo "	el.type = 'text';\n"; 
echo "	el.id = 'LPtb_' + iteration;\n"; 
echo "	el.name = 'LPtb_' + iteration;\n"; 
echo "	el.size = 4;\n"; 
echo "	el.maxLength = 5;\n"; 
echo "	el.value = obj.LANPort_Begin;\n"; 
echo "	el.disabled = (!pri_a(uitems[inner_url][\"NETFILTER_NAT_FORWARD\"]))?true:false;\n"; 
echo "	cellwanpb.appendChild(el);\n"; 
echo "\n"; 
echo "	//LAN Port End\n"; 
echo "	var cellwanpe = row.insertCell(7);\n"; 
echo "	var el = document.createElement('input');\n"; 
echo "	el.type = 'text';\n"; 
echo "	el.id = 'LPte_' + iteration;\n"; 
echo "	el.name = 'LPte_' + iteration;\n"; 
echo "	el.size = 4;\n"; 
echo "	el.maxLength = 5;\n"; 
echo "	el.value = obj.LANPort_End;\n"; 
echo "	el.disabled = (!pri_a(uitems[inner_url][\"NETFILTER_NAT_FORWARD\"]))?true:false;\n"; 
echo "	cellwanpe.appendChild(el);\n"; 
echo "\n"; 
echo "\n"; 
echo "	//Server IP\n"; 
echo "	var celllanip = row.insertCell(8);\n"; 
echo "	var el = document.createElement('input');\n"; 
echo "	el.type = 'text';\n"; 
echo "	el.id = 'ServerIp_' + iteration;\n"; 
echo "	el.name = 'ServerIp_' + iteration;\n"; 
echo "	el.size = 13;\n"; 
echo "	el.maxLength = 15;\n"; 
echo "	el.value = obj.ServerIp;\n"; 
echo "	el.disabled = (!pri_a(uitems[inner_url][\"NETFILTER_NAT_FORWARD\"]))?true:false;\n"; 
echo "	celllanip.appendChild(el);\n"; 
echo "\n"; 
echo "\n"; 
echo "	//Delete\n"; 
echo "	var cellenable = row.insertCell(9);\n"; 
echo "	var el = document.createElement('input');\n"; 
echo "	el.value = \"Del\";\n"; 
echo "	el.type = 'button';\n"; 
echo "	eval(\"el.onclick = function(){removeRowFromTable(\"+ iteration +\")}\");\n"; 
echo "	el.disabled = (!pri_a(uitems[inner_url][\"NETFILTER_NAT_FORWARD\"]))?true:false;\n"; 
echo "	cellenable.appendChild(el);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function removeRowFromTable(index)\n"; 
echo "{\n"; 
echo "	updateAllRow();\n"; 
echo "	removeAllRow();\n"; 
echo "	pft.remove(index);\n"; 
echo "\n"; 
echo "	for(var i=0;i<pft.length;i++)\n"; 
echo "		addRowToTable(pft[i]);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function removeAllRow()\n"; 
echo "{\n"; 
echo "	var tbl = GO('pf');\n"; 
echo "	var lastRow = tbl.rows.length;  \n"; 
echo "	for(var i=1;i<lastRow-1 ;i++)\n"; 
echo "		tbl.deleteRow(lastRow - i);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function InitDisplay(response)\n"; 
echo "{\n"; 
echo "	pftData_raw = response;\n"; 
echo "	pftData_Array = pftData_raw.split(\"@\");\n"; 
echo "	pftData = new Array();\n"; 
echo "	var i;\n"; 
echo "	for(i=1;i<pftData_Array.length;i++)\n"; 
echo "	{\n"; 
echo "		var tmpArray = pftData_Array[i].split(\",\");\n"; 
echo "		var tmpWanPort = tmpArray[4].split(\"-\");\n"; 
echo "		var tmpLanPort = tmpArray[5].split(\"-\");\n"; 
echo "		var newobj = {\"Enable\":tmpArray[1],\n"; 
echo "		\"Name\":tmpArray[2],\"Protocol\":tmpArray[3],\n"; 
echo "		\"WANPort_Begin\":tmpWanPort[0],\n"; 
echo "		\"WANPort_End\":tmpWanPort[1],\n"; 
echo "		\"LANPort_Begin\":tmpLanPort[0],\n"; 
echo "		\"LANPort_End\":tmpLanPort[1],\"ServerIp\":tmpArray[6]};\n"; 
echo "		pftData.push(newobj);\n"; 
echo "\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	tr_display(\"NETFILTER_NAT_FORWARD\");\n"; 
echo "\n"; 
echo "\n"; 
echo "	InitValue(document.forms[0]);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function InitValue(passForm)\n"; 
echo "{\n"; 
echo "	removeAllRow();\n"; 
echo "	pft = new pft_obj().value;\n"; 
echo "\n"; 
echo "	for(var i=0;i<pft.length;i++)\n"; 
echo "		addRowToTable(pft[i]);\n"; 
echo "\n"; 
echo "	if(!pri_a(uitems[inner_url][\"NETFILTER_NAT_FORWARD\"]))\n"; 
echo "	{\n"; 
echo "		passForm.Insert.disabled = true;\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	top.loading = 0;\n"; 
echo "\n"; 
echo "	setInterval('ajax_get_signals()',2000);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function Validate(passForm)\n"; 
echo "{\n"; 
echo "	var tmpNETFILTER_NAT_FORWARD=\"\";\n"; 
echo "	for(i=0; i<pft.length; i++) {\n"; 
echo "\n"; 
echo "		var WPtb = GO(\"WPtb_\"+i);\n"; 
echo "		var WPte = GO(\"WPte_\"+i);\n"; 
echo "		if (!CheckValue(WPte, 1, 65535) || !CheckValue(WPtb, 1, 65535)) return;\n"; 
echo "		if (WPte.value > 0 && !CheckValue(WPte, WPtb.value, 65535)) return;\n"; 
echo "\n"; 
echo "		var LPtb = GO(\"LPtb_\"+i);\n"; 
echo "		var LPte = GO(\"LPte_\"+i);\n"; 
echo "		if (!CheckValue(LPte, 1, 65535) || !CheckValue(LPtb, 1, 65535)) return;\n"; 
echo "		if (LPte.value > 0 && !CheckValue(LPte, LPtb.value, 65535)) return;\n"; 
echo "\n"; 
echo "		if (WPte.value - WPtb.value != LPte.value - LPtb.value) {\n"; 
echo "			alert(\"Local port range is not equal to WAN port range.\");\n"; 
echo "			LPtb.select();\n"; 
echo "			return;\n"; 
echo "		}\n"; 
echo "\n"; 
echo "		var ServerIp = GO(\"ServerIp_\"+i).value;\n"; 
echo "		if(!v_IP(ServerIp)) return;\n"; 
echo "\n"; 
echo "\n"; 
echo "		tmpNETFILTER_NAT_FORWARD+= \"@\"+(i+1);\n"; 
echo "		tmpNETFILTER_NAT_FORWARD+= \",\"+((GO(\"Enb_\"+i).checked)?\"Y\":\"N\");\n"; 
echo "		tmpNETFILTER_NAT_FORWARD+= \",\"+GO(\"Name_\"+i).value;\n"; 
echo "		tmpNETFILTER_NAT_FORWARD+= \",\"+GO(\"Type_\"+i).value;\n"; 
echo "		tmpNETFILTER_NAT_FORWARD+= \",\"+GO(\"WPtb_\"+i).value + \"-\" + GO(\"WPte_\"+i).value;\n"; 
echo "		tmpNETFILTER_NAT_FORWARD+= \",\"+GO(\"LPtb_\"+i).value + \"-\" + GO(\"LPte_\"+i).value;\n"; 
echo "		tmpNETFILTER_NAT_FORWARD+= \",\"+GO(\"ServerIp_\"+i).value;\n"; 
echo "\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	passForm.NETFILTER_NAT_FORWARD.value = tmpNETFILTER_NAT_FORWARD;\n"; 
echo "\n"; 
echo "	passForm.sid.value = sid;\n"; 
echo "	passForm.btnSubmit.value = \"1\";\n"; 
echo "	passForm.submit();\n"; 
echo "}\n"; 
echo "//-->\n"; 
echo "</script>\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body onload=\"init_obj();setTimeout('ajax_get_key()',500);\">\n"; 
echo "<div id=\"main_div\">\n"; 
echo "	<div id=\"container\">\n"; 
echo "		<form name=\"form1\" method=\"POST\" action=\"ajax.php?action=net_port_forwarding\" style=\"text-align:center\">\n"; 
echo "			<input type=\"hidden\" name=\"sid\" id=\"sid\">\n"; 
echo "			<input type=\"hidden\" name=\"NETFILTER_NAT_FORWARD\" id=\"NETFILTER_NAT_FORWARD\">\n"; 
echo "			<table align=center>\n"; 
echo "			<tr id=\"TR_NETFILTER_NAT_FORWARD\" style=\"display:none\"><td>\n"; 
echo "\n"; 
echo "\n"; 
echo "			<table id=\"pf\" class=\"pf_tbl\" cellpadding=\"5\">\n"; 
echo "			<tr>\n"; 
echo "				<td rowspan=\"2\"><b>No.</b></td>\n"; 
echo "				<td rowspan=\"2\"><b>Enable</b></td>\n"; 
echo "				<td rowspan=\"2\"><b>Name</b></td>\n"; 
echo "				<td rowspan=\"2\"><b>Protocol</b></td>\n"; 
echo "				<td colspan=\"2\"><b>WAN Port</b></td>\n"; 
echo "				<td colspan=\"2\"><b>LAN Port</b></td>\n"; 
echo "				<td rowspan=\"2\"><b>Server IP</b></td>\n"; 
echo "				<td rowspan=\"2\"><b>Delete</b></td>\n"; 
echo "			</tr>\n"; 
echo "			<tr>\n"; 
echo "				<td>Begin</td>\n"; 
echo "				<td>End</td>\n"; 
echo "				<td>Begin</td>\n"; 
echo "				<td>End</td>\n"; 
echo "			</tr>\n"; 
echo "			</table>\n"; 
echo "\n"; 
echo "			<input type=\"button\" id=\"Insert\" name=\"Insert\" value=\"Insert\" onclick=\"fp_insert()\">\n"; 
echo "			</td></tr>\n"; 
echo "			</table>\n"; 
echo "			<input type=\"hidden\" name=\"btnSubmit\">\n"; 
echo "		</form>\n"; 
echo "	</div>\n"; 
echo "	<div>\n"; 
echo "		<table style=\"width:600px;height:25px;text-align:center\">\n"; 
echo "			<tr>\n"; 
echo "				<td width=\"210\"></td>\n"; 
echo "				<td id=\"clear_btn\" class=\"td_btn\" onclick=\"location.reload()\">Undo</td>\n"; 
echo "				<td width=\"30\"></td>\n"; 
echo "				<td id=\"submit_btn\" class=\"td_btn\" onclick=\"Validate(document.forms[0])\">Apply</td>\n"; 
echo "				<td width=\"210\"></td>\n"; 
echo "			</tr>\n"; 
echo "		</table>\n"; 
echo "	</div>\n"; 
echo "</div>\n"; 
echo "</body>\n"; 
echo "</html>\n";
?>