<?php
echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "<title></title>\n"; 
echo "<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "<script type=\"text/javascript\" src=\"comm.js\"></script>\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "<!--\n"; 
echo "var NETFILTER_DMZ_HOST,NETFILTER_FW_IPFILTER,MGMT_WEB_WAN,MGMT_TELNET_WAN;\n"; 
echo "var pftData_raw,pftData_Array;\n"; 
echo "var pftData = new Array();\n"; 
echo "\n"; 
echo "Array.prototype.remove = function(from, to) {\n"; 
echo "	var rest = this.slice((to || from) + 1 || this.length);\n"; 
echo "	this.length = from < 0 ? this.length + from : from;\n"; 
echo "	return this.push.apply(this, rest);\n"; 
echo "};\n"; 
echo "\n"; 
echo "function pft_obj()\n"; 
echo "{\n"; 
echo "	this.value = pftData;\n"; 
echo "}\n"; 
echo "\n"; 
echo "var pft;\n"; 
echo "\n"; 
echo "function updateAllRow()\n"; 
echo "{\n"; 
echo "	for(var i=0;i<pft.length;i++)\n"; 
echo "	{\n"; 
echo "		pft[i].Enable = (GO(\"Enb_\"+i).checked)?\"Y\":\"N\";\n"; 
echo "		pft[i].SourceIP = GO(\"SrcIP_\"+i).value;\n"; 
echo "		pft[i].SourcePort = GO(\"SrcPort_\"+i).value;\n"; 
echo "		pft[i].DestinationIP = GO(\"DstIP_\"+i).value;\n"; 
echo "		pft[i].DestinationPort = GO(\"DstPort_\"+i).value;\n"; 
echo "		pft[i].Protocol = GO(\"Type_\"+i).value;\n"; 
echo "	}\n"; 
echo "}\n"; 
echo "\n"; 
echo "function fp_insert()\n"; 
echo "{\n"; 
echo "	if (pft.length >= 16) return;\n"; 
echo "\n"; 
echo "	var newobj = {\"Enable\":\"\",\"SourceIP\":\"\",\"SourcePort\":\"\",\"DestinationIP\":\"\",\"DestinationPort\":\"\",\"Protocol\":\"\"};\n"; 
echo "	updateAllRow();\n"; 
echo "	pft.push(newobj);\n"; 
echo "	removeAllRow();\n"; 
echo "	for(var i=0;i<pft.length;i++)\n"; 
echo "		addRowToTable(pft[i], i);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function addRowToTable(obj, iteration)\n"; 
echo "{\n"; 
echo "	var tbl = GO('pf');\n"; 
echo "	var lastRow = tbl.rows.length;\n"; 
echo "	var row = tbl.insertRow(lastRow);\n"; 
echo "\n"; 
echo "	//No\n"; 
echo "	var cellno = row.insertCell(0);\n"; 
echo "	var textNode = document.createTextNode(iteration+1);\n"; 
echo "	cellno.appendChild(textNode);\n"; 
echo "\n"; 
echo "	//Enable\n"; 
echo "	var cellenable = row.insertCell(1);\n"; 
echo "	var el = document.createElement('input');\n"; 
echo "	el.type = 'checkbox';\n"; 
echo "	el.id = 'Enb_' + iteration;\n"; 
echo "	el.name = 'Enb_' + iteration;\n"; 
echo "	el.defaultChecked = (obj.Enable == \"Y\")?true:false;\n"; 
echo "	el.value = (obj.Enable)?\"Y\":\"N\";\n"; 
echo "	el.onclick = function(){this.value = (this.checked)?\"Y\":\"N\"};\n"; 
echo "	el.disabled = (!pri_a(uitems[inner_url][\"NETFILTER_FW_IPFILTER\"]))?true:false;\n"; 
echo "	cellenable.appendChild(el);\n"; 
echo "\n"; 
echo "	//SourceIP\n"; 
echo "	var cellSrcIP = row.insertCell(2);\n"; 
echo "	var el = document.createElement('input');\n"; 
echo "	el.type = 'text';\n"; 
echo "	el.id = 'SrcIP_' + iteration;\n"; 
echo "	el.name = 'SrcIP_' + iteration;\n"; 
echo "	el.size = 15;\n"; 
echo "	el.maxLength = 18;\n"; 
echo "	el.value = obj.SourceIP;\n"; 
echo "	el.disabled = (!pri_a(uitems[inner_url][\"NETFILTER_FW_IPFILTER\"]))?true:false;\n"; 
echo "	cellSrcIP.appendChild(el);\n"; 
echo "\n"; 
echo "\n"; 
echo "	//SourcePort\n"; 
echo "	var cellSrcPort = row.insertCell(3);\n"; 
echo "	var el = document.createElement('input');\n"; 
echo "	el.type = 'text';\n"; 
echo "	el.id = 'SrcPort_' + iteration;\n"; 
echo "	el.name = 'SrcPort_' + iteration;\n"; 
echo "	el.size = 4;\n"; 
echo "	el.maxLength = 5;\n"; 
echo "	el.value = obj.SourcePort;\n"; 
echo "	el.disabled = (!pri_a(uitems[inner_url][\"NETFILTER_FW_IPFILTER\"]))?true:false;\n"; 
echo "	cellSrcPort.appendChild(el);\n"; 
echo "\n"; 
echo "\n"; 
echo "	//DestinationIP\n"; 
echo "	var cellDstIP = row.insertCell(4);\n"; 
echo "	var el = document.createElement('input');\n"; 
echo "	el.type = 'text';\n"; 
echo "	el.id = 'DstIP_' + iteration;\n"; 
echo "	el.name = 'DstIP_' + iteration;\n"; 
echo "	el.size = 15;\n"; 
echo "	el.maxLength = 18;\n"; 
echo "	el.value = obj.DestinationIP;\n"; 
echo "	el.disabled = (!pri_a(uitems[inner_url][\"NETFILTER_FW_IPFILTER\"]))?true:false;\n"; 
echo "	cellDstIP.appendChild(el);\n"; 
echo "\n"; 
echo "\n"; 
echo "	//DestinationPort\n"; 
echo "	var cellDstPort = row.insertCell(5);\n"; 
echo "	var el = document.createElement('input');\n"; 
echo "	el.type = 'text';\n"; 
echo "	el.id = 'DstPort_' + iteration;\n"; 
echo "	el.name = 'DstPort_' + iteration;\n"; 
echo "	el.size = 4;\n"; 
echo "	el.maxLength = 5;\n"; 
echo "	el.value = obj.DestinationPort;\n"; 
echo "	el.disabled = (!pri_a(uitems[inner_url][\"NETFILTER_FW_IPFILTER\"]))?true:false;\n"; 
echo "	cellDstPort.appendChild(el);\n"; 
echo "\n"; 
echo "\n"; 
echo "	//Protocol\n"; 
echo "	var cellProtocol = row.insertCell(6);\n"; 
echo "	var sel = document.createElement('select');\n"; 
echo "	sel.id = 'Type_' + iteration;\n"; 
echo "	sel.name = 'Type_' + iteration;\n"; 
echo "	sel.options[0] = new Option('TCP', '0');\n"; 
echo "	sel.options[1] = new Option('UDP', '1');\n"; 
echo "	sel.options[2] = new Option('TCP/UDP', '2');\n"; 
echo "	sel.value = obj.Protocol;\n"; 
echo "	sel.disabled = (!pri_a(uitems[inner_url][\"NETFILTER_FW_IPFILTER\"]))?true:false;\n"; 
echo "	cellProtocol.appendChild(sel);\n"; 
echo "\n"; 
echo "	//Delete\n"; 
echo "	var cellenable = row.insertCell(7);\n"; 
echo "	var el = document.createElement('input');\n"; 
echo "	el.value = \"Del\";\n"; 
echo "	el.type = 'button';\n"; 
echo "	eval(\"el.onclick = function(){removeRowFromTable(\"+ iteration +\")}\");\n"; 
echo "	el.disabled = (!pri_a(uitems[inner_url][\"NETFILTER_FW_IPFILTER\"]))?true:false;\n"; 
echo "	cellenable.appendChild(el);\n"; 
echo "\n"; 
echo "}\n"; 
echo "\n"; 
echo "function removeRowFromTable(index)\n"; 
echo "{\n"; 
echo "	updateAllRow();\n"; 
echo "	removeAllRow();\n"; 
echo "	pft.remove(index);\n"; 
echo "\n"; 
echo "	for(var i=0;i<pft.length;i++)\n"; 
echo "		addRowToTable(pft[i], i);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function removeAllRow()\n"; 
echo "{\n"; 
echo "	var tbl = GO('pf');\n"; 
echo "	var lastRow = tbl.rows.length;  \n"; 
echo "	for(var i=1;i<lastRow;i++)\n"; 
echo "		tbl.deleteRow(lastRow - i);\n"; 
echo "}\n"; 
echo "\n"; 
echo "\n"; 
echo "function InitDisplay(response)\n"; 
echo "{\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "	var token = response.split(\";\");\n"; 
echo "\n"; 
echo "	NETFILTER_DMZ_HOST = token[0];\n"; 
echo "	if(NETFILTER_DMZ_HOST == \"\")\n"; 
echo "		NETFILTER_DMZ_HOST = \"0.0.0.0\";\n"; 
echo "	MGMT_WEB_WAN = token[2];\n"; 
echo "	MGMT_TELNET_WAN = token[3];\n"; 
echo "	pftData_raw = token[1];\n"; 
echo "	pftData_Array = pftData_raw.split(\"@\");\n"; 
echo "\n"; 
echo "	var i;\n"; 
echo "	for(i=1;i<pftData_Array.length;i++)\n"; 
echo "	{\n"; 
echo "		var tmpArray = pftData_Array[i].split(\",\");\n"; 
echo "		var tmpLanPort = tmpArray[4].split(\"-\");\n"; 
echo "		var tmpWanPort = tmpArray[5].split(\"-\");\n"; 
echo "		var newobj = {\"Enable\":tmpArray[1],\n"; 
echo "		\"SourceIP\":tmpArray[2],\"SourcePort\":tmpArray[3],\n"; 
echo "		\"DestinationIP\":tmpArray[4],\n"; 
echo "		\"DestinationPort\":tmpArray[5],\"Protocol\":tmpArray[6]};\n"; 
echo "		pftData.push(newobj);\n"; 
echo "\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	if(pri_d(uitems[inner_url][\"cpe_access_control\"]))\n"; 
echo "	{\n"; 
echo "		GO(\"cpe_access_control\").style.display = \"\";\n"; 
echo "		tr_display(\"MGMT_WEB_WAN\");\n"; 
echo "		tr_display(\"MGMT_TELNET_WAN\");\n"; 
echo "		obj_readonly(\"MGMT_WEB_WAN\");\n"; 
echo "		obj_readonly(\"MGMT_TELNET_WAN\");\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	tr_display(\"NETFILTER_DMZ_HOST\");\n"; 
echo "\n"; 
echo "	tr_display(\"NETFILTER_FW_IPFILTER\");\n"; 
echo "\n"; 
echo "\n"; 
echo "	obj_readonly(\"NETFILTER_DMZ_HOST\");\n"; 
echo "\n"; 
echo "\n"; 
echo "	InitValue(document.forms[0]);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function InitValue(passForm)\n"; 
echo "{\n"; 
echo "	passForm.NETFILTER_DMZ_HOST.value = NETFILTER_DMZ_HOST;\n"; 
echo "	passForm.DMZ_ENABLE.checked = (NETFILTER_DMZ_HOST == \"0.0.0.0\")?false:true;\n"; 
echo "       passForm.MGMT_WEB_WAN.checked = (MGMT_WEB_WAN==\"1\")? true : false;\n"; 
echo "       passForm.MGMT_TELNET_WAN.checked = (MGMT_TELNET_WAN==\"1\")? true : false;\n"; 
echo "	removeAllRow();\n"; 
echo "	pft = new pft_obj().value;\n"; 
echo "\n"; 
echo "	for(var i=0;i<pft.length;i++)\n"; 
echo "		addRowToTable(pft[i], i);\n"; 
echo "\n"; 
echo "	if(!pri_a(uitems[inner_url][\"NETFILTER_DMZ_HOST\"]))\n"; 
echo "	{\n"; 
echo "		passForm.DMZ_ENABLE.disabled = true;\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	if(!pri_a(uitems[inner_url][\"NETFILTER_FW_IPFILTER\"]))\n"; 
echo "	{\n"; 
echo "		passForm.Insert.disabled = true;\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	change_tbl(passForm);\n"; 
echo "\n"; 
echo "	top.loading = 0;\n"; 
echo "	setInterval('ajax_get_signals()',2000);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function Validate(passForm)\n"; 
echo "{\n"; 
echo "	var tmpNETFILTER_FW_IPFILTER=\"\";\n"; 
echo "	for(var i=0; i<pft.length; i++) {\n"; 
echo "\n"; 
echo "		var SrcIP = GO(\"SrcIP_\"+i).value;\n"; 
echo "		if(!v_CIDR(SrcIP)) return;\n"; 
echo "\n"; 
echo "		var SrcPort = GO(\"SrcPort_\"+i);\n"; 
echo "		if (!CheckValue(SrcPort, 0, 65535)) return;\n"; 
echo "\n"; 
echo "		var DstIP = GO(\"DstIP_\"+i).value;\n"; 
echo "		if(!v_CIDR(DstIP)) return;\n"; 
echo "\n"; 
echo "		var DstPort = GO(\"DstPort_\"+i);\n"; 
echo "		if (!CheckValue(DstPort, 0, 65535)) return;\n"; 
echo "\n"; 
echo "\n"; 
echo "		tmpNETFILTER_FW_IPFILTER+= \"@\"+(i+1);\n"; 
echo "		tmpNETFILTER_FW_IPFILTER+= \",\"+((GO(\"Enb_\"+i).checked)?\"Y\":\"N\");\n"; 
echo "		tmpNETFILTER_FW_IPFILTER+= \",\"+GO(\"SrcIP_\"+i).value;\n"; 
echo "		tmpNETFILTER_FW_IPFILTER+= \",\"+GO(\"SrcPort_\"+i).value;\n"; 
echo "		tmpNETFILTER_FW_IPFILTER+= \",\"+GO(\"DstIP_\"+i).value;\n"; 
echo "		tmpNETFILTER_FW_IPFILTER+= \",\"+GO(\"DstPort_\"+i).value;\n"; 
echo "		tmpNETFILTER_FW_IPFILTER+= \",\"+GO(\"Type_\"+i).value;\n"; 
echo "		tmpNETFILTER_FW_IPFILTER+= \",1\";\n"; 
echo "\n"; 
echo "\n"; 
echo "		\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	passForm.NETFILTER_FW_IPFILTER.value = tmpNETFILTER_FW_IPFILTER;\n"; 
echo "\n"; 
echo "	if(passForm.DMZ_ENABLE.checked == false)\n"; 
echo "	{\n"; 
echo "		passForm.NETFILTER_DMZ_HOST.disabled = false;\n"; 
echo "		passForm.NETFILTER_DMZ_HOST.value = \"0.0.0.0\";\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	if(v_IP(GO(\"NETFILTER_DMZ_HOST\").value) == 0)\n"; 
echo "	{\n"; 
echo "		GO(\"NETFILTER_DMZ_HOST\").select();\n"; 
echo "		return;\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	passForm.sid.value = sid;\n"; 
echo "	passForm.btnSubmit.value = \"1\";\n"; 
echo "	passForm.submit();\n"; 
echo "}\n"; 
echo "function change_tbl(passForm)\n"; 
echo "{\n"; 
echo "	if(pri_a(uitems[inner_url][\"NETFILTER_DMZ_HOST\"]))\n"; 
echo "	{\n"; 
echo "		passForm.NETFILTER_DMZ_HOST.disabled = (passForm.DMZ_ENABLE.checked)?false:true;\n"; 
echo "	}\n"; 
echo "}\n"; 
echo "//-->\n"; 
echo "</script>\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body onload=\"init_obj();setTimeout('ajax_get_key()',500);\">\n"; 
echo "<div id=\"main_div\">\n"; 
echo "	<div id=\"container\">\n"; 
echo "		<form name=\"form1\" method=\"POST\" action=\"ajax.php?action=net_firewall\">\n"; 
echo "			<input type=\"hidden\" name=\"sid\" id=\"sid\">\n"; 
echo "			<input type=\"hidden\" name=\"NETFILTER_FW_IPFILTER\" id=\"NETFILTER_FW_IPFILTER\">\n"; 
echo "		<table style=\"width:613px\">\n"; 
echo "		<tr><td style=\"width:50%\">\n"; 
echo "		<FIELDSET id=\"cpe_access_control\" style=\"display:none\">\n"; 
echo "			<legend>CPE Access Control</legend>\n"; 
echo "			<table>\n"; 
echo "			<tr id=\"TR_MGMT_WEB_WAN\" style=\"display:none\"><td>\n"; 
echo "				<input type=\"checkbox\" id=\"MGMT_WEB_WAN\" name=\"MGMT_WEB_WAN\"> Allow Web accessing from WAN<br/>\n"; 
echo "			</td></tr>\n"; 
echo "			<tr id=\"TR_MGMT_TELNET_WAN\" style=\"display:none\"><td>\n"; 
echo "				<input type=\"checkbox\" id=\"MGMT_TELNET_WAN\" name=\"MGMT_TELNET_WAN\"> Allow Telnet accessing from WAN\n"; 
echo "			</td></tr>\n"; 
echo "			</table>\n"; 
echo "		</FIELDSET>\n"; 
echo "		</td><td></td></tr>\n"; 
echo "		<tr><td style=\"width:50%\">\n"; 
echo "		<FIELDSET>\n"; 
echo "			<legend>DMZ</legend>\n"; 
echo "			<table>\n"; 
echo "			<tr id=\"TR_NETFILTER_DMZ_HOST\" style=\"display:none\"><td>\n"; 
echo "			<input type=\"checkbox\" id=\"DMZ_ENABLE\" name=\"DMZ_ENABLE\" onclick=\"change_tbl(document.forms[0])\">DMZ Host:<input type=\"text\" size=\"13\" maxlength=\"15\" id=\"NETFILTER_DMZ_HOST\" name=\"NETFILTER_DMZ_HOST\">\n"; 
echo "			</td></tr>\n"; 
echo "			</table>\n"; 
echo "		</FIELDSET>\n"; 
echo "		</td><td></td></tr>\n"; 
echo "		<tr id=\"TR_NETFILTER_FW_IPFILTER\" style=\"display:none\"><td colspan=\"2\">\n"; 
echo "		<FIELDSET style=\"width:720px;\">\n"; 
echo "			<legend>Firewall Filter</legend>\n"; 
echo "			<table>\n"; 
echo "			<tr><td>\n"; 
echo "\n"; 
echo "			<div id=\"filter\">\n"; 
echo "			<table id=\"pf\" class=\"pf_tbl\" cellpadding=\"5\" style=\"width:560px\">\n"; 
echo "			<tr>\n"; 
echo "				<td><b>No.</b></td>\n"; 
echo "				<td><b>Enable</b></td>\n"; 
echo "				<td><b>SrcIP/Mask</b></td>\n"; 
echo "				<td><b>SrcPort</b></td>\n"; 
echo "				<td><b>DstIP/Mask</b></td>\n"; 
echo "				<td><b>DstPort</b></td>\n"; 
echo "				<td><b>Protocol</b></td>\n"; 
echo "				<td><b>Delete</b></td>\n"; 
echo "			</tr>\n"; 
echo "			</table>\n"; 
echo "			<input type=\"button\" id=\"Insert\" name=\"Insert\" value=\"Insert\" onclick=\"fp_insert()\">\n"; 
echo "			</div>\n"; 
echo "			</td></tr>\n"; 
echo "			</table>\n"; 
echo "		</FIELDSET>\n"; 
echo "		</td></tr>\n"; 
echo "		</table>\n"; 
echo "			<input type=\"hidden\" name=\"btnSubmit\">\n"; 
echo "		</form>\n"; 
echo "	</div>\n"; 
echo "	<div>\n"; 
echo "		<table style=\"width:600px;height:25px;text-align:center\">\n"; 
echo "			<tr>\n"; 
echo "				<td width=\"210\"></td>\n"; 
echo "				<td id=\"clear_btn\" class=\"td_btn\" onclick=\"location.reload()\">Undo</td>\n"; 
echo "				<td width=\"30\"></td>\n"; 
echo "				<td id=\"submit_btn\" class=\"td_btn\" onclick=\"Validate(document.forms[0])\">Apply</td>\n"; 
echo "				<td width=\"210\"></td>\n"; 
echo "			</tr>\n"; 
echo "		</table>\n"; 
echo "	</div>\n"; 
echo "</div>\n"; 
echo "</body>\n"; 
echo "</html>\n";
?>