<?php
echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "<title></title>\n"; 
echo "<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "<script type=\"text/javascript\" src=\"comm.js\"></script>\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "<!--\n"; 
echo "\n"; 
echo "\n"; 
echo "var TZ_DST_ENABLE,TZ_NAME,NTP_ENABLE,NTP_SERVER,sysDate;\n"; 
echo "\n"; 
echo "var tz_set = new Array();\n"; 
echo "tz_set[0]  = \"(GMT-12:00) International Date Line West\";\n"; 
echo "tz_set[1]  = \"(GMT-11:00) Midway Island, Samoa\";\n"; 
echo "tz_set[2]  = \"(GMT-10:00) Hawaii\";\n"; 
echo "tz_set[3]  = \"(GMT-09:00) Alaska\";\n"; 
echo "tz_set[4]  = \"(GMT-08:00) Pacific Time (US and Canada)\";\n"; 
echo "tz_set[5]  = \"(GMT-08:00) Tijuana, Baja California\";\n"; 
echo "tz_set[6]  = \"(GMT-07:00) Arizona\";\n"; 
echo "tz_set[7]  = \"(GMT-07:00) Chihuahua, La Paz, Mazatlan - New\";\n"; 
echo "tz_set[8]  = \"(GMT-07:00) Chihuahua, La Paz, Mazatlan - Old\";\n"; 
echo "tz_set[9]  = \"(GMT-07:00) Mountain Time (US and Canada)\";\n"; 
echo "tz_set[10] = \"(GMT-06:00) Central America\";\n"; 
echo "tz_set[11] = \"(GMT-06:00) Central Time (US and Canada)\";\n"; 
echo "tz_set[12] = \"(GMT-06:00) Guadalajara, Mexico City, Monterrey - New\";\n"; 
echo "tz_set[13] = \"(GMT-06:00) Guadalajara, Mexico City, Monterrey - Old\";\n"; 
echo "tz_set[14] = \"(GMT-06:00) Saskatchewan\";\n"; 
echo "tz_set[15] = \"(GMT-05:00) Bogota, Lima, Quito, Rio Branco\";\n"; 
echo "tz_set[16] = \"(GMT-05:00) Eastern Time (US and Canada)\";\n"; 
echo "tz_set[17] = \"(GMT-05:00) Indiana (East)\";\n"; 
echo "tz_set[18] = \"(GMT-04:30) Caracas\";\n"; 
echo "tz_set[19] = \"(GMT-04:00) Atlantic Time (Canada)\";\n"; 
echo "tz_set[20] = \"(GMT-04:00) Caracas, La Paz\";\n"; 
echo "tz_set[21] = \"(GMT-04:00) Manaus\";\n"; 
echo "tz_set[22] = \"(GMT-04:00) Santiago\";\n"; 
echo "tz_set[23] = \"(GMT-03:30) Newfoundland\";\n"; 
echo "tz_set[24] = \"(GMT-03:00) Brasilia\";\n"; 
echo "tz_set[25] = \"(GMT-03:00) Buenos Aires, Georgetown\";\n"; 
echo "tz_set[26] = \"(GMT-03:00) Greenland\";\n"; 
echo "tz_set[27] = \"(GMT-03:00) Montevideo\";\n"; 
echo "tz_set[28] = \"(GMT-02:00) Mid-Atlantic\";\n"; 
echo "tz_set[29] = \"(GMT-01:00) Azores\";\n"; 
echo "tz_set[30] = \"(GMT-01:00) Cape Verde Is.\";\n"; 
echo "tz_set[31] = \"(GMT) Casablanca, Monrovia, Reykjavik\";\n"; 
echo "tz_set[32] = \"(GMT) Greenwich Mean Time - Dublin, Edinburgh, Lisbon, London\";\n"; 
echo "tz_set[33] = \"(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna\";\n"; 
echo "tz_set[34] = \"(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague\";\n"; 
echo "tz_set[35] = \"(GMT+01:00) Brussels, Copenhagen, Madrid, Paris\";\n"; 
echo "tz_set[36] = \"(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb\";\n"; 
echo "tz_set[37] = \"(GMT+01:00) West Central Africa\";\n"; 
echo "tz_set[38] = \"(GMT+02:00) Amman\";\n"; 
echo "tz_set[39] = \"(GMT+02:00) Athens, Bucharest, Istanbul\";\n"; 
echo "tz_set[40] = \"(GMT+02:00) Beirut\";\n"; 
echo "tz_set[41] = \"(GMT+02:00) Cairo\";\n"; 
echo "tz_set[42] = \"(GMT+02:00) Harare, Pretoria\";\n"; 
echo "tz_set[43] = \"(GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius\";\n"; 
echo "tz_set[44] = \"(GMT+02:00) Jerusalem\";\n"; 
echo "tz_set[45] = \"(GMT+02:00) Minsk\";\n"; 
echo "tz_set[46] = \"(GMT+02:00) Windhoek\";\n"; 
echo "tz_set[47] = \"(GMT+03:00) Baghdad\";\n"; 
echo "tz_set[48] = \"(GMT+03:00) Kuwait, Riyadh\";\n"; 
echo "tz_set[49] = \"(GMT+03:00) Moscow, St. Petersburg, Volgograd\";\n"; 
echo "tz_set[50] = \"(GMT+03:00) Nairobi\";\n"; 
echo "tz_set[51] = \"(GMT+03:00) Tbilisi\";\n"; 
echo "tz_set[52] = \"(GMT+03:30) Tehran\";\n"; 
echo "tz_set[53] = \"(GMT+04:00) Abu Dhabi, Muscat\";\n"; 
echo "tz_set[54] = \"(GMT+04:00) Baku\";\n"; 
echo "tz_set[55] = \"(GMT+04:00) Caucasus Standard Time\";\n"; 
echo "tz_set[56] = \"(GMT+04:00) Yerevan\";\n"; 
echo "tz_set[57] = \"(GMT+04:30) Kabul\";\n"; 
echo "tz_set[58] = \"(GMT+05:00) Yekaterinburg\";\n"; 
echo "tz_set[59] = \"(GMT+05:00) Islamabad, Karachi, Tashkent\";\n"; 
echo "tz_set[60] = \"(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi\";\n"; 
echo "tz_set[61] = \"(GMT+05:30) Sri Jayawardenapura-Kotte\";\n"; 
echo "tz_set[62] = \"(GMT+05:45) Kathmandu\";\n"; 
echo "tz_set[63] = \"(GMT+06:00) Almaty, Novosibirsk\";\n"; 
echo "tz_set[64] = \"(GMT+06:00) Astana, Dhaka\";\n"; 
echo "tz_set[65] = \"(GMT+06:30) Yangon (Rangoon)\";\n"; 
echo "tz_set[66] = \"(GMT+07:00) Bangkok, Hanoi, Jakarta\";\n"; 
echo "tz_set[67] = \"(GMT+07:00) Krasnoyarsk\";\n"; 
echo "tz_set[68] = \"(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi\";\n"; 
echo "tz_set[69] = \"(GMT+08:00) Irkutsk, Ulaan Bataar\";\n"; 
echo "tz_set[70] = \"(GMT+08:00) Kuala Lumpur, Singapore\";\n"; 
echo "tz_set[71] = \"(GMT+08:00) Perth\";\n"; 
echo "tz_set[72] = \"(GMT+08:00) Taipei\";\n"; 
echo "tz_set[73] = \"(GMT+09:00) Osaka, Sapporo, Tokyo\";\n"; 
echo "tz_set[74] = \"(GMT+09:00) Seoul\";\n"; 
echo "tz_set[75] = \"(GMT+09:00) Yakutsk\";\n"; 
echo "tz_set[76] = \"(GMT+09:30) Adelaide\";\n"; 
echo "tz_set[77] = \"(GMT+09:30) Darwin\";\n"; 
echo "tz_set[78] = \"(GMT+10:00) Brisbane\";\n"; 
echo "tz_set[79] = \"(GMT+10:00) Canberra, Melbourne, Sydney\";\n"; 
echo "tz_set[80] = \"(GMT+10:00) Guam, Port Moresby\";\n"; 
echo "tz_set[81] = \"(GMT+10:00) Hobart\";\n"; 
echo "tz_set[82] = \"(GMT+10:00) Vladivostok\";\n"; 
echo "tz_set[83] = \"(GMT+11:00) Magadan, Solomon Is., New Caledonia\";\n"; 
echo "tz_set[84] = \"(GMT+12:00) Auckland, Wellington\";\n"; 
echo "tz_set[85] = \"(GMT+12:00) Fiji, Kamchatka, Marshall Is.\";\n"; 
echo "tz_set[86] = \"(GMT+13:00) Nuku'alofa\";\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "/* Daylight Saving Time, 2008 */\n"; 
echo "/* refer to http://www.timezoneconverter.com/cgi-bin/zoneinfo */\n"; 
echo "\n"; 
echo "/* start : end   */\n"; 
echo "/* MMDDHH:MMDDHH */\n"; 
echo "\n"; 
echo "var TZ_DST_Table = new Array();\n"; 
echo "TZ_DST_Table[0]  = \"000000:000000\";\n"; 
echo "TZ_DST_Table[1]  = \"000000:000000\";\n"; 
echo "TZ_DST_Table[2]  = \"000000:000000\";\n"; 
echo "TZ_DST_Table[3]  = \"030902:110202\";	/* */\n"; 
echo "TZ_DST_Table[4]  = \"030902:110202\";	/* */\n"; 
echo "TZ_DST_Table[5]  = \"040602:102602\";	/* America/Tijuana */\n"; 
echo "TZ_DST_Table[6]  = \"000000:000000\";\n"; 
echo "TZ_DST_Table[7]  = \"040602:102602\";	/* America/Chihuahua */\n"; 
echo "TZ_DST_Table[8]  = \"040602:102602\";	/* America/Mazatlan */\n"; 
echo "TZ_DST_Table[9]  = \"030902:110202\";	/* */\n"; 
echo "TZ_DST_Table[10] = \"000000:000000\";\n"; 
echo "TZ_DST_Table[11] = \"030902:110202\";	/* */\n"; 
echo "TZ_DST_Table[12] = \"040602:102602\";	/* America/Mexico_City */\n"; 
echo "TZ_DST_Table[13] = \"040602:102602\";	/* America/Monterrey */\n"; 
echo "TZ_DST_Table[14] = \"000000:000000\";\n"; 
echo "TZ_DST_Table[15] = \"000000:000000\";\n"; 
echo "TZ_DST_Table[16] = \"030902:110202\";	/* */\n"; 
echo "TZ_DST_Table[17] = \"000000:000000\";\n"; 
echo "TZ_DST_Table[18] = \"000000:000000\";	/* America/Caracas */\n"; 
echo "TZ_DST_Table[19] = \"030902:110202\";	/* America/Halifax */\n"; 
echo "TZ_DST_Table[20] = \"000000:000000\";	/* America/La_Paz */\n"; 
echo "TZ_DST_Table[21] = \"000000:000000\";	/* America/Manaus */\n"; 
echo "TZ_DST_Table[22] = \"101200:033000\";	/* America/Santiago */\n"; 
echo "TZ_DST_Table[23] = \"030900:110200\";	/* America/St_Johns */\n"; 
echo "TZ_DST_Table[24] = \"101200:021700\";	/* America/Sao_Paulo */\n"; 
echo "TZ_DST_Table[25] = \"100500:031600\";	/* America/Argentina/Buenos_Aires */\n"; 
echo "TZ_DST_Table[26] = \"032922:102523\";	/* America/Godthab */\n"; 
echo "TZ_DST_Table[27] = \"100502:030902\";	/* America/Montevideo */\n"; 
echo "TZ_DST_Table[28] = \"030902:110202\";\n"; 
echo "TZ_DST_Table[29] = \"033000:102601\";	/* Atlantic/Azores */\n"; 
echo "TZ_DST_Table[30] = \"000000:000000\";	/* Atlantic/Cape_Verde */\n"; 
echo "TZ_DST_Table[31] = \"060100:092800\";	/* Africa/Casablanca */\n"; 
echo "TZ_DST_Table[32] = \"033001:102602\";	/* Europe/London */\n"; 
echo "TZ_DST_Table[33] = \"033002:102603\";	/* Europe/Amsterdam */\n"; 
echo "TZ_DST_Table[34] = \"033002:102603\";	/* Europe/Belgrade */\n"; 
echo "TZ_DST_Table[35] = \"033002:102603\";	/* Europe/Paris */\n"; 
echo "TZ_DST_Table[36] = \"033002:102603\";	/* Europe/Sarajevo */\n"; 
echo "TZ_DST_Table[37] = \"000000:000000\";\n"; 
echo "TZ_DST_Table[38] = \"032700:103101\";	/* Asia/Amman */\n"; 
echo "TZ_DST_Table[39] = \"033003:102604\";	/* Europe/Athens */\n"; 
echo "TZ_DST_Table[40] = \"033000:102600\";	/* Asia/Beirut */\n"; 
echo "TZ_DST_Table[41] = \"042500:082900\";	/* Africa/Cairo */\n"; 
echo "TZ_DST_Table[42] = \"000000:000000\";	/* Africa/Harare */\n"; 
echo "TZ_DST_Table[43] = \"033003:102604\";	/* Europe/Helsinki */\n"; 
echo "TZ_DST_Table[44] = \"032802:100502\";	/* Asia/Jerusalem */\n"; 
echo "TZ_DST_Table[45] = \"033002:102603\";	/* Europe/Minsk */\n"; 
echo "TZ_DST_Table[46] = \"040602:090702\";	/* Africa/Windhoek */\n"; 
echo "TZ_DST_Table[47] = \"000000:000000\";	/* Asia/Baghdad */\n"; 
echo "TZ_DST_Table[48] = \"000000:000000\";	/* Asia/Kuwait */\n"; 
echo "TZ_DST_Table[49] = \"033002:102603\";	/* Europe/Moscow */\n"; 
echo "TZ_DST_Table[50] = \"000000:000000\";	/* Africa/Nairobi */\n"; 
echo "TZ_DST_Table[51] = \"000000:000000\";	/* Asia/Tbilisi */\n"; 
echo "TZ_DST_Table[52] = \"032100:092100\";	/* Asia/Tehran */\n"; 
echo "TZ_DST_Table[53] = \"000000:000000\";	/* Asia/Muscat */\n"; 
echo "TZ_DST_Table[54] = \"033004:102605\";	/* Asia/Baku */\n"; 
echo "TZ_DST_Table[55] = \"000000:000000\";\n"; 
echo "TZ_DST_Table[56] = \"033002:102603\";	/* Asia/Yerevan */\n"; 
echo "TZ_DST_Table[57] = \"000000:000000\";	/* Asia/Kabul */\n"; 
echo "TZ_DST_Table[58] = \"033002:102603\";	/* Asia/Yekaterinburg */\n"; 
echo "TZ_DST_Table[59] = \"060100:090100\";	/* Asia/Karachi */\n"; 
echo "TZ_DST_Table[60] = \"000000:000000\";	/* Asia/Kolkata */\n"; 
echo "TZ_DST_Table[61] = \"000000:000000\";	/* Asia/Colombo */\n"; 
echo "TZ_DST_Table[62] = \"000000:000000\";	/* Asia/Katmandu */\n"; 
echo "TZ_DST_Table[63] = \"000000:000000\";	/* Asia/Almaty */\n"; 
echo "TZ_DST_Table[64] = \"000000:000000\";	/* Asia/Dhaka */\n"; 
echo "TZ_DST_Table[65] = \"000000:000000\";	/* Asia/Rangoon */\n"; 
echo "TZ_DST_Table[66] = \"000000:000000\";	/* Asia/Bangkok */\n"; 
echo "TZ_DST_Table[67] = \"033002:102603\";	/* Asia/Krasnoyarsk */\n"; 
echo "TZ_DST_Table[68] = \"000000:000000\";	/* Asia/Shanghai */\n"; 
echo "TZ_DST_Table[69] = \"033002:102603\";	/* Asia/Irkutsk */\n"; 
echo "TZ_DST_Table[70] = \"000000:000000\";	/* Asia/Kuala_Lumpur */\n"; 
echo "TZ_DST_Table[71] = \"102602:033003\";	/* Australia/Perth */\n"; 
echo "TZ_DST_Table[72] = \"000000:000000\";	/* Asia/Taipei */\n"; 
echo "TZ_DST_Table[73] = \"000000:000000\";	/* Asia/Tokyo */\n"; 
echo "TZ_DST_Table[74] = \"000000:000000\";	/* Asia/Seoul */\n"; 
echo "TZ_DST_Table[75] = \"033002:102603\";	/* Asia/Yakutsk */\n"; 
echo "TZ_DST_Table[76] = \"100502:040603\";	/* Australia/Adelaide */\n"; 
echo "TZ_DST_Table[77] = \"000000:000000\";	/* Australia/Darwin */\n"; 
echo "TZ_DST_Table[78] = \"000000:000000\";	/* Australia/Brisbane */\n"; 
echo "TZ_DST_Table[79] = \"100502:040603\";	/* Australia/Melbourne */\n"; 
echo "TZ_DST_Table[80] = \"000000:000000\";	/* Pacific/Guam */\n"; 
echo "TZ_DST_Table[81] = \"100502:040603\";	/* Australia/Hobart */\n"; 
echo "TZ_DST_Table[82] = \"033002:102603\";	/* Asia/Vladivostok */\n"; 
echo "TZ_DST_Table[83] = \"033002:102603\";	/* Asia/Magadan */\n"; 
echo "TZ_DST_Table[84] = \"092802:040603\";	/* Pacific/Auckland */\n"; 
echo "TZ_DST_Table[85] = \"000000:000000\";	/* Pacific/Fiji */\n"; 
echo "TZ_DST_Table[86] = \"000000:000000\";	/* Pacific/Tongatapu */\n"; 
echo "\n"; 
echo "function getTZenv(str) {\n"; 
echo "	var strOffset, offset, strEnv;\n"; 
echo "	if (str.charAt(4) == ')') {\n"; 
echo "		strOffset = \"\";\n"; 
echo "		offset = 0;\n"; 
echo "	} else {\n"; 
echo "		strOffset = str.substring(4,10).replace(\":\",\".\");\n"; 
echo "		offset = 0 - (strOffset.substring(0,3) * 60 + strOffset.substring(4,6) * 1);\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	strEnv = \"G\" + strOffset + \"::\" + offset + \":\";\n"; 
echo "	strEnv += ((document.form1.TZ_DST_ENABLE.checked)? TZ_DST_Table[document.form1.TimeZone.selectedIndex] : \"000000:000000\");\n"; 
echo "	return strEnv;\n"; 
echo "}\n"; 
echo "\n"; 
echo "function clockUpdate() {\n"; 
echo "	sysDate.setTime(sysDate.getTime()+1000);\n"; 
echo "	GO(\"idLocalTime\").innerHTML = sysDate.toLocaleString();\n"; 
echo "	setTimeout(\"clockUpdate()\", 1000);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function syncWithPC() {\n"; 
echo "	var pcDate = new Date();\n"; 
echo "	sysDate.setTime(pcDate.getTime());\n"; 
echo "	GO(\"idLocalTime\").innerHTML = sysDate.toLocaleString();\n"; 
echo "}\n"; 
echo "function Validate(passForm) {\n"; 
echo "	var month = (sysDate.getMonth()+1).toString();\n"; 
echo "	var day = sysDate.getDate().toString();\n"; 
echo "	var hour = sysDate.getHours().toString();\n"; 
echo "	var min = sysDate.getMinutes().toString();\n"; 
echo "	var sec = sysDate.getSeconds().toString();\n"; 
echo "\n"; 
echo "\n"; 
echo "	passForm.DT_YEAR.value = sysDate.getFullYear();\n"; 
echo "	passForm.DT_MONTH.value = ((month.length == 1)?\"0\":\"\") + month;\n"; 
echo "	passForm.DT_DAY.value = ((day.length == 1)?\"0\":\"\") + day;\n"; 
echo "	passForm.DT_HOUR.value = ((hour.length == 1)?\"0\":\"\") + hour;\n"; 
echo "	passForm.DT_MIN.value = ((min.length == 1)?\"0\":\"\") + min;\n"; 
echo "	passForm.DT_SEC.value = ((sec.length == 1)?\"0\":\"\") + sec;\n"; 
echo "	passForm.btnSubmit.value = \"Set\";\n"; 
echo "\n"; 
echo "\n"; 
echo "	var tz = passForm.TimeZone.value;\n"; 
echo "	var spindex = tz.indexOf(\")\");\n"; 
echo "	var tz_name = tz.substr(spindex+2,tz.length-spindex);\n"; 
echo "	var tz_stdoffset;\n"; 
echo "	if(tz.substr(4,1) == \"-\")\n"; 
echo "		tz_stdoffset = \"+\" + tz.substr(5,5);\n"; 
echo "	else if(tz.substr(4,1) == \"+\")\n"; 
echo "		tz_stdoffset = \"-\" + tz.substr(5,5);\n"; 
echo "	else\n"; 
echo "		tz_stdoffset = \"+00:00\";\n"; 
echo "\n"; 
echo "\n"; 
echo "	passForm.TZ_NAME.value = tz_name;\n"; 
echo "	passForm.TZ_STDOFFSET.value = tz_stdoffset;\n"; 
echo "\n"; 
echo "\n"; 
echo "	passForm.NTP_ENABLE.disabled = false;\n"; 
echo "\n"; 
echo "\n"; 
echo "	passForm.sid.value = sid;\n"; 
echo "	passForm.submit();\n"; 
echo "}\n"; 
echo "\n"; 
echo "function InitDisplay(response)\n"; 
echo "{\n"; 
echo "	var token = response.split(\";\");\n"; 
echo "\n"; 
echo "	TZ_DST_ENABLE = token[0];\n"; 
echo "	TZ_NAME = token[1];\n"; 
echo "	NTP_ENABLE = token[2];\n"; 
echo "	NTP_SERVER = token[3];\n"; 
echo "	sysDate = new Date(token[4]);\n"; 
echo "\n"; 
echo "	tr_display(\"SYNCWITHPC\");\n"; 
echo "	tr_display(\"NTP_ENABLE\");\n"; 
echo "	tr_display(\"NTP_SERVER\");\n"; 
echo "	tr_display(\"TimeZone\");\n"; 
echo "	tr_display(\"TZ_DST_ENABLE\");\n"; 
echo "\n"; 
echo "	obj_readonly(\"SYNCWITHPC\");\n"; 
echo "	obj_readonly(\"NTP_ENABLE\");\n"; 
echo "	obj_readonly(\"NTP_SERVER\");\n"; 
echo "	obj_readonly(\"TimeZone\");\n"; 
echo "	obj_readonly(\"TZ_DST_ENABLE\");\n"; 
echo "\n"; 
echo "	InitValue(document.forms[0]);\n"; 
echo "}\n"; 
echo "\n"; 
echo "\n"; 
echo "function InitValue(passForm) {\n"; 
echo "	setTimeout(\"clockUpdate()\", 1000);\n"; 
echo "	passForm.TZ_DST_ENABLE.checked = (TZ_DST_ENABLE == \"1\")? true : false;\n"; 
echo "	passForm.NTP_ENABLE.checked = (NTP_ENABLE == \"1\")? true : false;\n"; 
echo "	passForm.NTP_SERVER.value = NTP_SERVER;\n"; 
echo "	change();\n"; 
echo "\n"; 
echo "	InitScreen();\n"; 
echo "\n"; 
echo "	top.loading = 0;\n"; 
echo "	setInterval('ajax_get_signals()',2000);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function InitScreen() {\n"; 
echo "	var i,tz_name;\n"; 
echo "	for(i=0; i<tz_set.length; i++) {\n"; 
echo "\n"; 
echo "		var spindex = tz_set[i].indexOf(\")\");\n"; 
echo "		var tmp_name = tz_set[i].substr(spindex+2,tz_set[i].length-spindex);\n"; 
echo "\n"; 
echo "		if(TZ_NAME == tmp_name)\n"; 
echo "			tz_name = tz_set[i];\n"; 
echo "\n"; 
echo "		GO(\"TimeZone\").options[i] = new Option(tz_set[i], tz_set[i]);\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	GO(\"TimeZone\").value = tz_name;\n"; 
echo "}\n"; 
echo "\n"; 
echo "function change()\n"; 
echo "{\n"; 
echo "	if(pri_a(uitems[inner_url][\"SYNCWITHPC\"]))\n"; 
echo "	{\n"; 
echo "		if(GO(\"NTP_ENABLE\").checked)\n"; 
echo "			GO(\"SYNCWITHPC\").disabled = true;\n"; 
echo "		else\n"; 
echo "			GO(\"SYNCWITHPC\").disabled = false;\n"; 
echo "	}\n"; 
echo "}\n"; 
echo "\n"; 
echo "//-->\n"; 
echo "</script>\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body onload=\"init_obj();setTimeout('ajax_get_key()',500);\">\n"; 
echo "<div id=\"main_div\" class=\"main_div\">\n"; 
echo "	<div id=\"container\">\n"; 
echo "		<form name=\"form1\" method=\"POST\" action=\"ajax.php?action=personal_date\">\n"; 
echo "			<input type=\"hidden\" name=\"sid\" id=\"sid\">\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>System Date</legend>\n"; 
echo "				<table><tr id=\"TR_SYNCWITHPC\" style=\"display:none\"><td>\n"; 
echo "				<span id=\"idLocalTime\"></span>&nbsp;&nbsp;&nbsp;<input type=\"button\" id=\"SYNCWITHPC\" value=\"Synchronize with PC\" onClick=\"syncWithPC()\">\n"; 
echo "				</td></tr>\n"; 
echo "				</table>\n"; 
echo "				<input type=\"hidden\" name=\"DT_YEAR\">\n"; 
echo "				<input type=\"hidden\" name=\"DT_MONTH\">\n"; 
echo "				<input type=\"hidden\" name=\"DT_DAY\">\n"; 
echo "				<input type=\"hidden\" name=\"DT_HOUR\">\n"; 
echo "				<input type=\"hidden\" name=\"DT_MIN\">\n"; 
echo "				<input type=\"hidden\" name=\"DT_SEC\">\n"; 
echo "				<input type=\"hidden\" name=\"btnSubmit\">\n"; 
echo "				<input type=\"hidden\" name=\"TZ_STDOFFSET\">\n"; 
echo "				<input type=\"hidden\" name=\"TZ_NAME\">\n"; 
echo "				\n"; 
echo "				\n"; 
echo "			</FIELDSET>\n"; 
echo "\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>NTP Server</legend>\n"; 
echo "				<table><tr id=\"TR_NTP_ENABLE\" style=\"display:none\"><td>\n"; 
echo "					<input type=\"checkbox\" id=\"NTP_ENABLE\" name=\"NTP_ENABLE\" onclick=\"change()\"> Enable NTP Server\n"; 
echo "				</td></tr>\n"; 
echo "				<tr id=\"TR_NTP_SERVER\" style=\"display:none\"><td>\n"; 
echo "					NTP Server : <input type=\"text\" id=\"NTP_SERVER\" name=\"NTP_SERVER\" size=\"45\" maxlength=\"64\"><br/>\n"; 
echo "				</td></tr></table>\n"; 
echo "			</FIELDSET>\n"; 
echo "\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>Time Zone</legend>\n"; 
echo "				<table><tr id=\"TR_TimeZone\" style=\"display:none\"><td>\n"; 
echo "					<select id=\"TimeZone\" name=\"TimeZone\"></select>\n"; 
echo "				</td></tr></table>\n"; 
echo "			</FIELDSET>\n"; 
echo "\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>Daylight Saving</legend>\n"; 
echo "				<table><tr id=\"TR_TZ_DST_ENABLE\" style=\"display:none\"><td>\n"; 
echo "					<input type=\"checkbox\" id=\"TZ_DST_ENABLE\" name=\"TZ_DST_ENABLE\"> Automatically adjust clock for daylight saving changes.\n"; 
echo "				</td></tr></table>\n"; 
echo "			</FIELDSET>\n"; 
echo "\n"; 
echo "		</form>\n"; 
echo "	</div>\n"; 
echo "	<div>\n"; 
echo "		<table style=\"width:600px;height:25px;text-align:center\">\n"; 
echo "			<tr>\n"; 
echo "				<td width=\"210\"></td>\n"; 
echo "				<td id=\"clear_btn\" class=\"td_btn\" onclick=\"location.reload()\">Undo</td>\n"; 
echo "				<td width=\"30\"></td>\n"; 
echo "				<td id=\"submit_btn\" class=\"td_btn\" onclick=\"Validate(document.forms[0]);\">Apply</td>\n"; 
echo "				<td width=\"210\"></td>\n"; 
echo "			</tr>\n"; 
echo "		</table>\n"; 
echo "	</div>\n"; 
echo "</div>\n"; 
echo "</body>\n"; 
echo "</html>\n";
?>