<?php
echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "<title></title>\n"; 
echo "<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "<script type=\"text/javascript\" src=\"comm.js\"></script>\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "<!--\n"; 
echo "function Validate(passForm)\n"; 
echo "{\n"; 
echo "	passForm.sid.value = sid;\n"; 
echo "	passForm.btnSubmit.value = \"Set\";\n"; 
echo "	passForm.submit();\n"; 
echo "}\n"; 
echo "function InitValue(passForm) {\n"; 
echo "\n"; 
echo "	top.loading = 0;\n"; 
echo "	setInterval('ajax_get_signals()',2000);\n"; 
echo "}\n"; 
echo "\n"; 
echo "//-->\n"; 
echo "</script>\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body onload=\"init_obj();InitValue(document.forms[0]);\">\n"; 
echo "<div id=\"main_div\">\n"; 
echo "	<div id=\"container\">\n"; 
echo "		<form method=\"POST\" action=\"ajax.php?action=personal_account\">\n"; 
echo "			<input type=\"hidden\" name=\"sid\" id=\"sid\">\n"; 
echo "			<br/><br/>\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>Web Login Account</legend>\n"; 
echo "			<table>\n"; 
echo "				<tr><td>old passwd</td><td><input type=\"password\" name=\"old_password\" size=\"31\" maxlength=\"31\"/></td></tr>\n"; 
echo "				<tr><td>new passwd</td><td><input type=\"password\" name=\"new_password\" size=\"31\" maxlength=\"31\"/></td></tr>\n"; 
echo "				\n"; 
echo "				<input type=\"hidden\" name=\"btnSubmit\">\n"; 
echo "			</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "		</form>\n"; 
echo "	</div>\n"; 
echo "	<div>\n"; 
echo "		<table style=\"width:600px; height: 25px;text-align:center;\">\n"; 
echo "			<tr>\n"; 
echo "				<td width=\"210\"></td>\n"; 
echo "				<td id=\"clear_btn\" class=\"td_btn\" onclick=\"location.reload()\">Undo</td>\n"; 
echo "				<td width=\"30\"></td>\n"; 
echo "				<td id=\"submit_btn\" class=\"td_btn\" onclick=\"Validate(document.forms[0]);\">Apply</td>\n"; 
echo "				<td width=\"210\"></td>\n"; 
echo "			</tr>\n"; 
echo "		</table>\n"; 
echo "	</div>\n"; 
echo "</div>\n"; 
echo "</body>\n"; 
echo "</html>\n";
?>