<?php
echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "<title></title>\n"; 
echo "<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "<script type=\"text/javascript\" src=\"comm.js\"></script>\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "<!--\n"; 
echo "function changeStates(dataStr) {\n"; 
echo "	var dataArray = dataStr.split(\";\");\n"; 
echo "\n"; 
echo "	if(dataArray[4] == \"dhcpc\")\n"; 
echo "		dataArray[4] = \"DHCP\";\n"; 
echo "\n"; 
echo "	GO(\"LanIP\").innerHTML = dataArray[1]? dataArray[1] : \"N/A\";\n"; 
echo "	GO(\"LanMask\").innerHTML = dataArray[2]? dataArray[2] : \"N/A\";\n"; 
echo "	GO(\"LanMac\").innerHTML = dataArray[3]? dataArray[3] : \"N/A\";\n"; 
echo "	GO(\"WanType\").innerHTML = dataArray[4]? dataArray[4] : \"N/A\";\n"; 
echo "	GO(\"WanIP\").innerHTML = dataArray[5]? dataArray[5] : \"\";\n"; 
echo "	GO(\"WanMask\").innerHTML = dataArray[6]? dataArray[6] : \"\";\n"; 
echo "	GO(\"WanGateway\").innerHTML = dataArray[7]? dataArray[7] : \"\";\n"; 
echo "	GO(\"WanMac\").innerHTML = dataArray[8]? dataArray[8] : \"N/A\";\n"; 
echo "	GO(\"IspDns\").innerHTML = dataArray[9]? dataArray[9] : \"\";\n"; 
echo "\n"; 
echo "}\n"; 
echo "\n"; 
echo "\n"; 
echo "function ajax_get_states() {\n"; 
echo "	top.$.ajax(\n"; 
echo "		{\n"; 
echo "			url:\"ajax.php\",\n"; 
echo "			data:{\n"; 
echo "				action:\"netState\",\n"; 
echo "				cache:false,\n"; 
echo "				time:(new Date()).getTime()\n"; 
echo "			},\n"; 
echo "			success:function(response){\n"; 
echo "				if(response != \"\")\n"; 
echo "				{\n"; 
echo "					tmptoken = response.split(\";\");\n"; 
echo "					if(tmptoken[0] == \"\")\n"; 
echo "	                        		top.change_signal(\"0\");\n"; 
echo "					else\n"; 
echo "                                        	top.change_signal(tmptoken[0]);\n"; 
echo "						\n"; 
echo "					if(tmptoken[1] != \"\")\n"; 
echo "						changeStates(response);\n"; 
echo "				}\n"; 
echo "				if (top.get_statusTime > 2000)\n"; 
echo "				{\n"; 
echo "					top.get_statusTime=top.get_statusTime - 500;\n"; 
echo "				}\n"; 
echo "			},\n"; 
echo "			timeout:top.get_statusTime,\n"; 
echo "			error:function(xhr)\n"; 
echo "			{\n"; 
echo "				top.get_statusTime=top.get_statusTime + 500;\n"; 
echo "			}\n"; 
echo "		}\n"; 
echo "	);\n"; 
echo "}\n"; 
echo "\n"; 
echo "\n"; 
echo "function InitDisplay()\n"; 
echo "{\n"; 
echo "\n"; 
echo "	if(pri_d(uitems[inner_url][\"field_lan\"]))\n"; 
echo "	{\n"; 
echo "		GO(\"field_lan\").style.display = \"\";\n"; 
echo "		tr_display(\"LanIP\");\n"; 
echo "		tr_display(\"LanMask\");\n"; 
echo "		tr_display(\"LanMac\");\n"; 
echo "\n"; 
echo "	}\n"; 
echo "		\n"; 
echo "	if(pri_d(uitems[inner_url][\"field_wan\"]))\n"; 
echo "	{\n"; 
echo "		GO(\"field_wan\").style.display = \"\";\n"; 
echo "		tr_display(\"WanType\");\n"; 
echo "		tr_display(\"WanIP\");\n"; 
echo "		tr_display(\"WanMask\");\n"; 
echo "		tr_display(\"WanGateway\");\n"; 
echo "		tr_display(\"WanMac\");\n"; 
echo "		tr_display(\"IspDns\");\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	get_states();\n"; 
echo "	//setInterval('ajax_get_states()',top.get_statusTime);\n"; 
echo "	top.loading=0;\n"; 
echo "}\n"; 
echo "\n"; 
echo "function get_states()\n"; 
echo "{\n"; 
echo "	ajax_get_states();\n"; 
echo "        setTimeout('get_states()',top.get_statusTime);\n"; 
echo "}\n"; 
echo "\n"; 
echo "//-->\n"; 
echo "</script>\n"; 
echo "</head>\n"; 
echo "<body onload=\"init_obj();InitDisplay();\">\n"; 
echo "<div id=\"main_div\">\n"; 
echo "	<div id=\"container\" style=\"height:370px\">\n"; 
echo "		<table style=\"width:97%;\">\n"; 
echo "			<tr><td style=\"vertical-align:top;width:50%;\">\n"; 
echo "			<FIELDSET id=\"field_lan\" style=\"display:none;\">\n"; 
echo "				<legend>LAN</legend>\n"; 
echo "				<table>\n"; 
echo "				<tr id=\"TR_LanIP\" style=\"display:none;\"><td>IP:</td><td id=\"LanIP\"></td></tr>\n"; 
echo "				<tr id=\"TR_LanMask\" style=\"display:none;\"><td>Netmask:</td><td id=\"LanMask\"></td></tr>\n"; 
echo "				<tr id=\"TR_LanMac\" style=\"display:none;\"><td>MAC address:</td><td id=\"LanMac\"></td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td>\n"; 
echo "			<td style=\"vertical-align:top;width:50%;\">\n"; 
echo "			<FIELDSET id=\"field_wan\" style=\"display:none;\">\n"; 
echo "				<legend>WAN</legend>\n"; 
echo "				<table>\n"; 
echo "				<tr id=\"TR_WanType\" style=\"display:none;\"><td>Type:</td><td id=\"WanType\"></td></tr>\n"; 
echo "				<tr id=\"TR_WanIP\" style=\"display:none;\"><td>IP:</td><td id=\"WanIP\"></td></tr>\n"; 
echo "				<tr id=\"TR_WanMask\" style=\"display:none;\"><td>Netmask:</td><td id=\"WanMask\"></td></tr>\n"; 
echo "				<tr id=\"TR_WanGateway\" style=\"display:none;\"><td>Gateway:</td><td id=\"WanGateway\"></td></tr>\n"; 
echo "				<tr id=\"TR_WanMac\" style=\"display:none;\"><td>MAC address:</td><td id=\"WanMac\"></td></tr>\n"; 
echo "				<tr id=\"TR_IspDns\" style=\"display:none;\"><td>ISP DNS:</td><td id=\"IspDns\"></td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td></tr>\n"; 
echo "		</table>\n"; 
echo "	</div>\n"; 
echo "</div>\n"; 
echo "</body>\n"; 
echo "</html>\n"; 
echo "\n";
?>