<?php
echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "<title></title>\n"; 
echo "<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "<script type=\"text/javascript\" src=\"comm.js\"></script>\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "<!--\n"; 
echo "var color = new Array(\"\",\"red\",\"red\",\"yellow\",\"yellow\",\"yellow\",\"yellow\",\"green\",\"green\",\"green\",\"green\");\n"; 
echo "\n"; 
echo "var freq_index = 0;\n"; 
echo "var t1;\n"; 
echo "\n"; 
echo "function changeStates(dataStr) {\n"; 
echo "	var dataArray = dataStr.split(\";\");\n"; 
echo "	GO(\"ssBSID\").innerHTML = dataArray[1]? dataArray[1] : \"N/A\";\n"; 
echo "	GO(\"ssFreq\").innerHTML = dataArray[2]? dataArray[2] : \"N/A\";\n"; 
echo "	GO(\"RSSI\").innerHTML = dataArray[3]? dataArray[3] : \"N/A\";\n"; 
echo "	GO(\"CINR\").innerHTML = dataArray[4]? dataArray[4] : \"N/A\";\n"; 
echo "	GO(\"TxPower\").innerHTML = dataArray[5]? dataArray[5] : \"N/A\";\n"; 
echo "	GO(\"ulBytes\").innerHTML = dataArray[6]? dataArray[6] : \"N/A\";\n"; 
echo "	GO(\"dlBytes\").innerHTML = dataArray[7]? dataArray[7] : \"N/A\";\n"; 
echo "	GO(\"uptime\").innerHTML = dataArray[8]? dataArray[8] : \"N/A\";\n"; 
echo "	GO(\"ssBandwidth\").innerHTML = dataArray[9]? dataArray[9] : \"N/A\";\n"; 
echo "	GO(\"devState\").innerHTML = dataArray[10]? dataArray[10] : \"N/A\";\n"; 
echo "	GO(\"macState\").innerHTML = dataArray[11]? dataArray[11] : \"N/A\";\n"; 
echo "	GO(\"ul_mcs\").innerHTML = dataArray[12]? dataArray[12] : \"N/A\";\n"; 
echo "	GO(\"dl_mcs\").innerHTML = dataArray[13]? dataArray[13] : \"N/A\";\n"; 
echo "	GO(\"tx_rate\").innerHTML = dataArray[14]? dataArray[14] : \"N/A\";\n"; 
echo "	GO(\"rx_rate\").innerHTML = dataArray[15]? dataArray[15] : \"N/A\";\n"; 
echo "	GO(\"rft\").innerHTML = dataArray[16]? dataArray[16] : \"N/A\";\n"; 
echo "	GO(\"sf\").innerHTML = dataArray[17]? dataArray[17] : \"N/A\";\n"; 
echo "\n"; 
echo "\n"; 
echo "	for(var j=1;j<=6;j++)\n"; 
echo "		document.getElementById(\"s\"+j).style.backgroundColor = color[0];\n"; 
echo "\n"; 
echo "	var meter=0;\n"; 
echo "	if(dataArray[4])\n"; 
echo "	{\n"; 
echo "		var signalcinr = dataArray[17]? dataArray[17] : \"1\";\n"; 
echo "\n"; 
echo "		var tmptoken = dataArray[4].split(\"/\");\n"; 
echo "		var cinr3 = tmptoken[0];\n"; 
echo "		tmptoken = tmptoken[1].split(\"(\");\n"; 
echo "		var cinr1 = tmptoken[0];\n"; 
echo "\n"; 
echo "		var newcinr;\n"; 
echo "		if(signalcinr == \"1\")\n"; 
echo "			newcinr = cinr1*1;\n"; 
echo "		else\n"; 
echo "			newcinr = cinr3*1;\n"; 
echo "\n"; 
echo "		var newrssi = dataArray[3]*1;\n"; 
echo "		\n"; 
echo "		if(newcinr <= 7)\n"; 
echo "			meter=1;\n"; 
echo "		else if((newcinr > 7 && newcinr <= 8) || (newrssi <= -85 && newcinr>=10))\n"; 
echo "			meter=2;\n"; 
echo "		else if((newcinr > 8 && newcinr <= 9) || (newrssi > -85 && newrssi < -80 && newcinr >= 10))\n"; 
echo "			meter=3;\n"; 
echo "		else if(newcinr > 9 && newcinr <= 11)\n"; 
echo "			meter=4;\n"; 
echo "		else if(newcinr > 11 && newcinr <= 13)\n"; 
echo "			meter=5;\n"; 
echo "		else if(newcinr > 13 && newcinr <= 15)\n"; 
echo "			meter=6;\n"; 
echo "		else if(newcinr > 15 && newcinr <= 18)\n"; 
echo "			meter=7;\n"; 
echo "		else if(newcinr > 18 && newcinr <= 21)\n"; 
echo "			meter=8;\n"; 
echo "		else if(newcinr > 21 && newcinr <= 29)\n"; 
echo "			meter=9;\n"; 
echo "		else if(newcinr > 29)\n"; 
echo "			meter=10;\n"; 
echo "\n"; 
echo "		for(var j=1;j<=color.length-1;j++)\n"; 
echo "			document.getElementById(\"s\"+j).style.backgroundColor = document.getElementById(\"s2\"+j).style.backgroundColor = color[0];\n"; 
echo "\n"; 
echo "		for(var j=1;j<=meter;j++)\n"; 
echo "			document.getElementById(\"s\"+j).style.backgroundColor = document.getElementById(\"s2\"+j).style.backgroundColor = color[meter];\n"; 
echo "	}\n"; 
echo "\n"; 
echo "\n"; 
echo "}\n"; 
echo "\n"; 
echo "function ajax_get_states() {\n"; 
echo "	var tmptoken;\n"; 
echo "\n"; 
echo "	if(t1.length > 0)\n"; 
echo "	{\n"; 
echo "		if(freq_index == t1.length)\n"; 
echo "			freq_index = 0;\n"; 
echo "\n"; 
echo "		top.$.ajax(\n"; 
echo "			{\n"; 
echo "				url:\"ajax.php\",\n"; 
echo "				data:{\n"; 
echo "					action:\"wmxState\",\n"; 
echo "					freq:t1[freq_index].Freq,\n"; 
echo "					bw:t1[freq_index].BW,\n"; 
echo "					cache:false,\n"; 
echo "					time:(new Date()).getTime()\n"; 
echo "				},\n"; 
echo "				success:function(response){\n"; 
echo "					if(response != \"\")\n"; 
echo "					{\n"; 
echo "						tmptoken = response.split(\";\");\n"; 
echo "						if(tmptoken[0] == \"\")\n"; 
echo "		                        		top.change_signal(\"0\");\n"; 
echo "						else\n"; 
echo "	                                        	top.change_signal(tmptoken[0]);\n"; 
echo "							\n"; 
echo "						if(tmptoken[1] != \"\")\n"; 
echo "							changeStates(response);\n"; 
echo "\n"; 
echo "						freq_index++;\n"; 
echo "					}\n"; 
echo "					if (top.get_statusTime > 2000)\n"; 
echo "					{\n"; 
echo "						//alert(top.get_statusTime);\n"; 
echo "						top.get_statusTime=top.get_statusTime - 500;\n"; 
echo "					}\n"; 
echo "				},\n"; 
echo "				timeout:top.get_statusTime,\n"; 
echo "				error:function(xhr)\n"; 
echo "				{\n"; 
echo "					top.get_statusTime=top.get_statusTime + 500;\n"; 
echo "				}\n"; 
echo "			}\n"; 
echo "		);\n"; 
echo "	}\n"; 
echo "	else\n"; 
echo "	{\n"; 
echo "		top.change_signal(\"0\");\n"; 
echo "	}\n"; 
echo "}\n"; 
echo "\n"; 
echo "function InitDisplay(response)\n"; 
echo "{\n"; 
echo "	if(pri_d(uitems[inner_url][\"field_system\"]))\n"; 
echo "	{\n"; 
echo "		GO(\"field_system\").style.display = \"\";\n"; 
echo "		tr_display(\"ssFreq\");\n"; 
echo "		tr_display(\"ssBandwidth\");\n"; 
echo "		tr_display(\"ssBSID\");\n"; 
echo "		tr_display(\"devState\");\n"; 
echo "		tr_display(\"macState\");\n"; 
echo "		tr_display(\"uptime\");\n"; 
echo "	}\n"; 
echo "		\n"; 
echo "	if(pri_d(uitems[inner_url][\"field_phy\"]))\n"; 
echo "	{\n"; 
echo "		GO(\"field_phy\").style.display = \"\";\n"; 
echo "		tr_display(\"RSSI\");\n"; 
echo "		tr_display(\"CINR\");\n"; 
echo "		tr_display(\"TxPower\");\n"; 
echo "		tr_display(\"rft\");\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	if(pri_d(uitems[inner_url][\"field_uplink\"]))\n"; 
echo "	{\n"; 
echo "		GO(\"field_uplink\").style.display = \"\";\n"; 
echo "		tr_display(\"ul_mcs\");\n"; 
echo "		tr_display(\"tx_rate\");\n"; 
echo "		tr_display(\"ulBytes\");\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	if(pri_d(uitems[inner_url][\"field_downlink\"]))\n"; 
echo "	{\n"; 
echo "		GO(\"field_downlink\").style.display = \"\";\n"; 
echo "		tr_display(\"dl_mcs\");	\n"; 
echo "		tr_display(\"rx_rate\");\n"; 
echo "		tr_display(\"dlBytes\");\n"; 
echo "	}\n"; 
echo "	\n"; 
echo "\n"; 
echo "	tr_display(\"SIGNAL_METER\");\n"; 
echo "	tr_display(\"sf\");\n"; 
echo "	eval(\"t1=\"+response);\n"; 
echo "	get_states();\n"; 
echo "	//setInterval('ajax_get_states()',top.get_statusTime);\n"; 
echo "	top.loading=0;\n"; 
echo "\n"; 
echo "}\n"; 
echo "\n"; 
echo "function get_states()\n"; 
echo "{\n"; 
echo "	ajax_get_states();\n"; 
echo "        setTimeout('get_states()',top.get_statusTime);\n"; 
echo "}\n"; 
echo "\n"; 
echo "//-->\n"; 
echo "</script>\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body onload=\"init_obj();setTimeout('ajax_get_key()',500);\">\n"; 
echo "<div id=\"main_div\">\n"; 
echo "	<div id=\"container\" style=\"width:635px;height:380px;margin-top:20px;margin-left:2px;\">\n"; 
echo "		<table style=\"width:97%;\">\n"; 
echo "			<tr id=\"TR_SIGNAL_METER\" style=\"display:none\"><td style=\"vertical-align:top;width:50%;\">\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>WiMAX Signal Strength</legend>\n"; 
echo "				<table width=\"300px\" style=\"border:1px solid black\" cellspacing=\"0\">\n"; 
echo "					<tr>\n"; 
echo "						<td id=\"s1\" height=\"5\" width=\"10%\">&nbsp;</td>\n"; 
echo "						<td id=\"s2\" style=\"border-right:1px solid black;\" height=\"5\" width=\"10%\">&nbsp;</td>\n"; 
echo "						<td id=\"s3\" height=\"5\" width=\"10%\">&nbsp;</td>\n"; 
echo "						<td id=\"s4\" height=\"5\" width=\"10%\">&nbsp;</td>\n"; 
echo "						<td id=\"s5\" height=\"5\" width=\"10%\">&nbsp;</td>\n"; 
echo "						<td id=\"s6\" style=\"border-right:1px solid black;\" height=\"5\" width=\"10%\">&nbsp;</td>\n"; 
echo "						<td id=\"s7\" height=\"5\" width=\"10%\">&nbsp;</td>\n"; 
echo "						<td id=\"s8\" height=\"5\" width=\"10%\">&nbsp;</td>\n"; 
echo "						<td id=\"s9\" height=\"5\" width=\"10%\">&nbsp;</td>\n"; 
echo "						<td id=\"s10\" height=\"5\" width=\"10%\">&nbsp;</td>\n"; 
echo "					</tr>\n"; 
echo "					<tr>\n"; 
echo "						<td id=\"s21\" style=\"border-right:1px solid black;\" height=\"5\">&nbsp;</td>\n"; 
echo "						<td id=\"s22\" style=\"border-right:1px solid black;\" height=\"5\">&nbsp;</td>\n"; 
echo "						<td id=\"s23\" style=\"border-right:1px solid black;\" height=\"5\">&nbsp;</td>\n"; 
echo "						<td id=\"s24\" style=\"border-right:1px solid black;\" height=\"5\">&nbsp;</td>\n"; 
echo "						<td id=\"s25\" style=\"border-right:1px solid black;\" height=\"5\">&nbsp;</td>\n"; 
echo "						<td id=\"s26\" style=\"border-right:1px solid black;\" height=\"5\">&nbsp;</td>\n"; 
echo "						<td id=\"s27\" style=\"border-right:1px solid black;\" height=\"5\">&nbsp;</td>\n"; 
echo "						<td id=\"s28\" style=\"border-right:1px solid black;\" height=\"5\">&nbsp;</td>\n"; 
echo "						<td id=\"s29\" style=\"border-right:1px solid black;\" height=\"5\">&nbsp;</td>\n"; 
echo "						<td id=\"s210\" height=\"5\">&nbsp;</td>\n"; 
echo "					</tr>\n"; 
echo "					<tr>\n"; 
echo "						<th colspan=2 align=left>weak</td>\n"; 
echo "						<th colspan=4 align=left>good</td>\n"; 
echo "						<th colspan=4 align=left>strong</td>\n"; 
echo "					</tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td></tr>\n"; 
echo "			<tr><td style=\"vertical-align:top;width:50%;\">\n"; 
echo "			<FIELDSET id=\"field_system\" style=\"display:none\">\n"; 
echo "				<legend>System Status</legend>\n"; 
echo "				<table>\n"; 
echo "				<tr id=\"TR_ssFreq\" style=\"display:none;\"><td style=\"width:25%\">Frequency:</td>\n"; 
echo "				<td style=\"width:25%\" colspan=\"3\"><span id=\"ssFreq\">n/a</span></td></tr>\n"; 
echo "				<tr id=\"TR_ssBandwidth\" style=\"display:none;\"><td>Bandwidth:</td><td colspan=\"3\"><span id=\"ssBandwidth\">n/a</span></td></tr>\n"; 
echo "				<tr id=\"TR_ssBSID\" style=\"display:none;\"><td>BSID:</td><td colspan=\"3\"><span id=\"ssBSID\">n/a</span></td></tr>\n"; 
echo "				<tr id=\"TR_devState\" style=\"display:none;\"><td>Dev State:</td><td colspan=\"3\"><span id=\"devState\">n/a</span></td></tr>\n"; 
echo "				<tr id=\"TR_macState\" style=\"display:none;\"><td>Mac State:</td><td colspan=\"3\"><span id=\"macState\">n/a</span></td></tr>\n"; 
echo "				<tr id=\"TR_uptime\" style=\"display:none;\"><td>Uptime:</td><td colspan=\"3\"><span id=\"uptime\">n/a</span></td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td><td style=\"vertical-align:top;\">\n"; 
echo "			<FIELDSET id=\"field_phy\" style=\"display:none\">\n"; 
echo "				<legend>Physical Status</legend>\n"; 
echo "				<table>\n"; 
echo "				<tr id=\"TR_RSSI\" style=\"display:none;\"><td style=\"width:25%\">RSSI:</td>\n"; 
echo "				<td style=\"width:25%\">\n"; 
echo "				<span id=\"RSSI\">n/a </span>dBm</td></tr>\n"; 
echo "				<tr id=\"TR_CINR\" style=\"display:none;\"><td style=\"width:15%\">CINR:</td>\n"; 
echo "				<td><span id=\"CINR\">n/a </span>dB</td></tr>\n"; 
echo "				<tr id=\"TR_TxPower\" style=\"display:none;\"><td>TX power:</td><td><span id=\"TxPower\">n/a </span>dBm</td></tr>\n"; 
echo "				<tr id=\"TR_rft\" style=\"display:none;\"><td style=\"width:15%\">RF Temperature:</td>\n"; 
echo "				<td><span id=\"rft\">n/a </span> C</td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td></tr>\n"; 
echo "			<tr><td style=\"vertical-align:top;\">\n"; 
echo "			<FIELDSET id=\"field_uplink\" style=\"display:none\">\n"; 
echo "				<legend>Uplink</legend>\n"; 
echo "				<table>\n"; 
echo "				<tr id=\"TR_ul_mcs\" style=\"display:none;\"><td>Modulation:</td><td><span id=\"ul_mcs\">n/a</span></td></tr>\n"; 
echo "				<tr id=\"TR_tx_rate\" style=\"display:none;\"><td>Data rate:</td><td><span id=\"tx_rate\">n/a </span>B/s</td></tr>\n"; 
echo "				<tr id=\"TR_ulBytes\" style=\"display:none;\"><td>TX bytes:</td><td><span id=\"ulBytes\">n/a</span></td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td><td style=\"vertical-align:top;\">\n"; 
echo "			<FIELDSET id=\"field_downlink\" style=\"display:none\">\n"; 
echo "				<legend>Downlink</legend>\n"; 
echo "				<table>\n"; 
echo "				<tr id=\"TR_dl_mcs\" style=\"display:none;\"><td>Modulation:</td><td><span id=\"dl_mcs\">n/a</span></td></tr>\n"; 
echo "				<tr id=\"TR_rx_rate\" style=\"display:none;\"><td>Data rate:</td><td><span id=\"rx_rate\">n/a </span>B/s</td></tr>\n"; 
echo "				<tr id=\"TR_dlBytes\" style=\"display:none;\"><td>RX bytes:</td><td><span id=\"dlBytes\">n/a</span></td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td></tr>\n"; 
echo "			<tr id=\"TR_sf\" style=\"display:none;\"><td colspan=\"2\">\n"; 
echo "			<FIELDSET style=\"width:93%\">\n"; 
echo "				<legend>Service Flow</legend>\n"; 
echo "				<span><pre id=\"sf\"></pre></span>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td></tr>\n"; 
echo "		</table>\n"; 
echo "	</div>\n"; 
echo "</div>\n"; 
echo "</body>\n"; 
echo "</html>\n"; 
echo "\n";
?>