<?php
echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "<title></title>\n"; 
echo "<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "<script type=\"text/javascript\" src=\"comm.js\"></script>\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "<!--\n"; 
echo "function changeStates(dataStr) {\n"; 
echo "	var dataArray = dataStr.split(\";\");\n"; 
echo "\n"; 
echo "	GO(\"Register_Status_1\").innerHTML = dataArray[1]? dataArray[1] : \"N/A\";\n"; 
echo "	GO(\"Call_Status_1\").innerHTML = dataArray[2]? dataArray[2] : \"N/A\";\n"; 
echo "	GO(\"Sub_Num_1\").innerHTML = dataArray[3]? dataArray[3] : \"N/A\";\n"; 
echo "\n"; 
echo "	GO(\"Register_Status_2\").innerHTML = dataArray[4]? dataArray[4] : \"N/A\";\n"; 
echo "	GO(\"Call_Status_2\").innerHTML = dataArray[5]? dataArray[5] : \"N/A\";\n"; 
echo "	GO(\"Sub_Num_2\").innerHTML = dataArray[6]? dataArray[6] : \"N/A\";\n"; 
echo "\n"; 
echo "}\n"; 
echo "\n"; 
echo "function ajax_get_states() {\n"; 
echo "\n"; 
echo "	top.$.ajax(\n"; 
echo "		{\n"; 
echo "			url:\"ajax.php\",\n"; 
echo "			data:{\n"; 
echo "				action:\"voipState\",\n"; 
echo "				cache:false,\n"; 
echo "				time:(new Date()).getTime()\n"; 
echo "			},\n"; 
echo "			success:function(response){\n"; 
echo "				if(response != \"\")\n"; 
echo "				{\n"; 
echo "					tmptoken = response.split(\";\");\n"; 
echo "					if(tmptoken[0] == \"\")\n"; 
echo "	                        		top.change_signal(\"0\");\n"; 
echo "					else\n"; 
echo "                                        	top.change_signal(tmptoken[0]);\n"; 
echo "						\n"; 
echo "					if(tmptoken[1] != \"\")\n"; 
echo "						changeStates(response);\n"; 
echo "				}\n"; 
echo "				if (top.get_statusTime > 2000)\n"; 
echo "				{\n"; 
echo "					top.get_statusTime=top.get_statusTime - 500;\n"; 
echo "				}\n"; 
echo "			},\n"; 
echo "			timeout:top.get_statusTime,\n"; 
echo "			error:function(xhr)\n"; 
echo "			{\n"; 
echo "				top.get_statusTime=top.get_statusTime + 500;\n"; 
echo "			}\n"; 
echo "		}\n"; 
echo "	);\n"; 
echo "\n"; 
echo "}\n"; 
echo "\n"; 
echo "\n"; 
echo "function InitDisplay()\n"; 
echo "{\n"; 
echo "	tr_display(\"Register_Status_1\");\n"; 
echo "	tr_display(\"Call_Status_1\");\n"; 
echo "	tr_display(\"Sub_Num_1\");\n"; 
echo "\n"; 
echo "	tr_display(\"Register_Status_2\");\n"; 
echo "	tr_display(\"Call_Status_2\");\n"; 
echo "	tr_display(\"Sub_Num_2\");\n"; 
echo "\n"; 
echo "\n"; 
echo "	get_states();\n"; 
echo "	//setInterval('ajax_get_states()',top.get_statusTime);\n"; 
echo "	top.loading=0;\n"; 
echo "}\n"; 
echo "function get_states()\n"; 
echo "{\n"; 
echo "	ajax_get_states();\n"; 
echo "        setTimeout('get_states()',top.get_statusTime);\n"; 
echo "}\n"; 
echo "\n"; 
echo "//-->\n"; 
echo "</script>\n"; 
echo "</head>\n"; 
echo "<body onload=\"init_obj();InitDisplay()\">\n"; 
echo "<div id=\"main_div\">\n"; 
echo "	<div id=\"container\" style=\"width:635px;height:380px;margin-top:20px;margin-left:2px;\">\n"; 
echo "		<table style=\"width:97%;\">\n"; 
echo "			<tr>\n"; 
echo "			<td style=\"vertical-align:top;width:50%;\">\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>Line 1 Status</legend>\n"; 
echo "				<table>\n"; 
echo "				<tr id=\"TR_Register_Status_1\" style=\"display:none;\"><td>Register Status:</td><td><span id=\"Register_Status_1\"></span></td></tr>\n"; 
echo "				<tr id=\"TR_Call_Status_1\" style=\"display:none;\"><td>Call Status:</td><td><span id=\"Call_Status_1\"></span></td></tr>\n"; 
echo "				<tr id=\"TR_Sub_Num_1\" style=\"display:none;\"><td>Subscriber Number:</td><td><span id=\"Sub_Num_1\"></span></td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td>\n"; 
echo "			<td style=\"vertical-align:top;width:50%;\">\n"; 
echo "			<FIELDSET>\n"; 
echo "				<legend>Line 2 Status</legend>\n"; 
echo "				<table>\n"; 
echo "				<tr id=\"TR_Register_Status_2\" style=\"display:none;\"><td>Register Status:</td><td><span id=\"Register_Status_2\"></span></td></tr>\n"; 
echo "				<tr id=\"TR_Call_Status_2\" style=\"display:none;\"><td>Call Status:</td><td><span id=\"Call_Status_2\"></span></td></tr>\n"; 
echo "				<tr id=\"TR_Sub_Num_2\" style=\"display:none;\"><td>Subscriber Number:</td><td><span id=\"Sub_Num_2\"></span></td></tr>\n"; 
echo "				</table>\n"; 
echo "			</FIELDSET>\n"; 
echo "			</td>\n"; 
echo "\n"; 
echo "			</tr>\n"; 
echo "		</table>\n"; 
echo "	</div>\n"; 
echo "</div>\n"; 
echo "</body>\n"; 
echo "</html>\n";
?>