<?php
echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "<title></title>\n"; 
echo "<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "<script type=\"text/javascript\" src=\"comm.js\"></script>\n"; 
echo "\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "<!--\n"; 
echo "\n"; 
echo "var SYS_MODEL,FW_VER,FW_BUILT,FREQ_RANGE,SERIAL;\n"; 
echo "\n"; 
echo "function InitValue()\n"; 
echo "{\n"; 
echo "	GO(\"SYS_MODEL\").innerHTML = SYS_MODEL;\n"; 
echo "	GO(\"FW_VER\").innerHTML = FW_VER;\n"; 
echo "	GO(\"FW_BUILT\").innerHTML = FW_BUILT;\n"; 
echo "	GO(\"FREQ_RANGE\").innerHTML = FREQ_RANGE;\n"; 
echo "	GO(\"SERIAL\").innerHTML = SERIAL;\n"; 
echo "}\n"; 
echo "\n"; 
echo "function InitDisplay(response)\n"; 
echo "{\n"; 
echo "	tr_display(\"SYS_MODEL\");\n"; 
echo "	tr_display(\"FW_VER\");\n"; 
echo "	tr_display(\"FW_BUILT\");\n"; 
echo "	tr_display(\"FREQ_RANGE\");\n"; 
echo "	tr_display(\"SERIAL\");\n"; 
echo "\n"; 
echo "\n"; 
echo "	var token = response.split(\";\");\n"; 
echo "\n"; 
echo "	SYS_MODEL = token[0];\n"; 
echo "	FW_VER = token[1];\n"; 
echo "	FW_BUILT = token[2];\n"; 
echo "	FREQ_RANGE = token[3];\n"; 
echo "	SERIAL = token[4];\n"; 
echo "\n"; 
echo "	InitValue();\n"; 
echo "	top.loading=0;\n"; 
echo "	setInterval('ajax_get_signals()',2000);\n"; 
echo "}\n"; 
echo "\n"; 
echo "//-->\n"; 
echo "</script>\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body onload=\"init_obj();setTimeout('ajax_get_key()',500);\">\n"; 
echo "<div id=\"main_div\">\n"; 
echo "	<div id=\"container\">\n"; 
echo "		<FIELDSET>\n"; 
echo "			<legend>Device Information</legend>\n"; 
echo "			<table>\n"; 
echo "				<tr id=\"TR_SYS_MODEL\" style=\"display:none;\"><td>Hardware model:</td><td id=\"SYS_MODEL\"></td></tr>\n"; 
echo "				<tr id=\"TR_FW_VER\" style=\"display:none;\"><td>Firmware version:</td><td id=\"FW_VER\"></td></tr>\n"; 
echo "				<tr id=\"TR_FW_BUILT\" style=\"display:none;\"><td>Firmware creation date:</td><td id=\"FW_BUILT\"></td></tr>\n"; 
echo "				<tr id=\"TR_FREQ_RANGE\" style=\"display:none;\"><td>Frequency range:</td><td id=\"FREQ_RANGE\"></td></tr>\n"; 
echo "				<tr id=\"TR_SERIAL\" style=\"display:none;\"><td>Serial number:</td><td id=\"SERIAL\"></td></tr>\n"; 
echo "			</table>\n"; 
echo "		</FIELDSET>\n"; 
echo "	</div>\n"; 
echo "</div>\n"; 
echo "</body>\n"; 
echo "</html>\n";
?>