<?php
echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "<title></title>\n"; 
echo "<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "<script type=\"text/javascript\" src=\"comm.js\"></script>\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "<!--\n"; 
echo "var t1;\n"; 
echo "var visible_network_list;\n"; 
echo "var ssState;\n"; 
echo "var signal_ID;\n"; 
echo "\n"; 
echo "var RfcMinFreq = 2300000;\n"; 
echo "var RfcMaxFreq = 2400000;\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "Array.prototype.remove = function(from, to) {\n"; 
echo "	var rest = this.slice((to || from) + 1 || this.length);\n"; 
echo "	this.length = from < 0 ? this.length + from : from;\n"; 
echo "	return this.push.apply(this, rest);\n"; 
echo "};\n"; 
echo "\n"; 
echo "\n"; 
echo "function tab_obj(tableData)\n"; 
echo "{\n"; 
echo "	this.value = tableData;\n"; 
echo "}\n"; 
echo "\n"; 
echo "var tData1, tData2, tbl, tData, passForm;\n"; 
echo "var rdOnly = true;\n"; 
echo "\n"; 
echo "function updateAllRow()\n"; 
echo "{\n"; 
echo "	for(var i=0;i<tData.length;i++)\n"; 
echo "	{\n"; 
echo "		tData[i].Freq = eval(\"passForm.Freq_\"+i+\".value\");\n"; 
echo "		tData[i].BW = eval(\"passForm.BW_\"+i+\".value\");\n"; 
echo "	}\n"; 
echo "}\n"; 
echo "\n"; 
echo "function ins()\n"; 
echo "{\n"; 
echo "	if (tData.length >= 32) return;\n"; 
echo "\n"; 
echo "	var newobj;\n"; 
echo "	if(tData.length == 0)\n"; 
echo "		newobj = {\"Freq\":\"\",\"BW\":\"\"};\n"; 
echo "	else\n"; 
echo "		newobj = {\"Freq\":\"\",\"BW\":\"\"};\n"; 
echo "	updateAllRow();\n"; 
echo "	tData.push(newobj);\n"; 
echo "	removeAllRow();\n"; 
echo "	for(var i=0;i<tData.length;i++)\n"; 
echo "		addRowToTable(tData[i]);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function addRowToTable(obj)\n"; 
echo "{\n"; 
echo "	var lastRow = tbl.rows.length;\n"; 
echo "	var iteration = lastRow-1;\n"; 
echo "	var row = tbl.insertRow(lastRow);\n"; 
echo "\n"; 
echo "	//No\n"; 
echo "	var cellno = row.insertCell(0);\n"; 
echo "	var textNode = document.createTextNode(iteration+1);\n"; 
echo "	cellno.appendChild(textNode);\n"; 
echo "\n"; 
echo "	//Frequency\n"; 
echo "	var cellFreq = row.insertCell(1);\n"; 
echo "	if (rdOnly) {\n"; 
echo "		cellFreq.innerHTML = obj.Freq;\n"; 
echo "	} else {\n"; 
echo "		var el = document.createElement('input');\n"; 
echo "		el.type = 'text';\n"; 
echo "		el.id = 'Freq_' + iteration;\n"; 
echo "		el.name = 'Freq_' + iteration;\n"; 
echo "		el.size = 7;\n"; 
echo "		el.maxLength = 7;\n"; 
echo "		el.readOnly = rdOnly;\n"; 
echo "		el.value = obj.Freq;\n"; 
echo "		cellFreq.appendChild(el);\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	//Bandwidth\n"; 
echo "	var cellBW = row.insertCell(2);\n"; 
echo "	var sel = document.createElement('select');\n"; 
echo "	sel.id = 'BW_' + iteration;\n"; 
echo "	sel.name = 'BW_' + iteration;\n"; 
echo "	sel.options[0] = new Option('10Mhz', 10000);\n"; 
echo "	sel.options[1] = new Option('8.75Mhz', 8750);\n"; 
echo "	sel.options[2] = new Option('7Mhz', 7000);\n"; 
echo "	sel.options[3] = new Option('5Mhz', 5000);\n"; 
echo "\n"; 
echo "	sel.value = obj.BW;\n"; 
echo "	if (rdOnly) {\n"; 
echo "		cellBW.innerHTML = sel.options[sel.selectedIndex].text;\n"; 
echo "		sel.style.display = \"none\";\n"; 
echo "	}\n"; 
echo "	//eval(\"sel.onchange = function(){change_all_bw(\"+iteration+\")}\");\n"; 
echo "	cellBW.appendChild(sel);\n"; 
echo "	\n"; 
echo "\n"; 
echo "\n"; 
echo "	var cellRSSI = row.insertCell(3);\n"; 
echo "	cellRSSI.innerHTML = search_rssi(obj.Freq,obj.BW);\n"; 
echo "\n"; 
echo "\n"; 
echo "	var cellCINR = row.insertCell(4);\n"; 
echo "	cellCINR.innerHTML = search_cinr(obj.Freq,obj.BW);\n"; 
echo "\n"; 
echo "	//Delete\n"; 
echo "\n"; 
echo "	if (!rdOnly) {\n"; 
echo "		var cellDelete = row.insertCell(5);\n"; 
echo "		var el = document.createElement('input');\n"; 
echo "		el.value = \"Delete\";\n"; 
echo "		el.type = 'button';\n"; 
echo "		eval(\"el.onclick = function(){removeRowFromTable(\"+iteration+\")}\");\n"; 
echo "		cellDelete.appendChild(el);\n"; 
echo "	}\n"; 
echo "}\n"; 
echo "\n"; 
echo "function change_all_bw(index)\n"; 
echo "{\n"; 
echo "        var lastRow = tbl.rows.length;\n"; 
echo "        for(var i=1;i<lastRow ;i++)\n"; 
echo "	{\n"; 
echo "		GO(\"BW_\"+(i-1)).value = GO(\"BW_\"+index).value\n"; 
echo "	}\n"; 
echo "}\n"; 
echo "\n"; 
echo "function search_rssi(freq,bw)\n"; 
echo "{\n"; 
echo "	var i,rssi;\n"; 
echo "	for(i=0,rssi=0;i<visible_network_list.length;i++)\n"; 
echo "	{\n"; 
echo "		if(visible_network_list[i].freq == freq && visible_network_list[i].bw == bw )\n"; 
echo "		{\n"; 
echo "			if (visible_network_list[i].rssi >= -150)\n"; 
echo "				rssi = visible_network_list[i].rssi;\n"; 
echo "			else\n"; 
echo "				rssi = \"0\";\n"; 
echo "			break;\n"; 
echo "		}\n"; 
echo "	}\n"; 
echo "	return rssi;\n"; 
echo "}\n"; 
echo "\n"; 
echo "\n"; 
echo "function search_cinr(freq,bw)\n"; 
echo "{\n"; 
echo "	var i,cinr;\n"; 
echo "	for(i=0,cinr=0;i<visible_network_list.length;i++)\n"; 
echo "	{\n"; 
echo "		if(visible_network_list[i].freq == freq && visible_network_list[i].bw == bw )\n"; 
echo "		{\n"; 
echo "			if (visible_network_list[i].rssi >= -150)\n"; 
echo "				cinr = visible_network_list[i].cinr;\n"; 
echo "			else\n"; 
echo "				cinr = \"0\";\n"; 
echo "			break;\n"; 
echo "		}\n"; 
echo "	}\n"; 
echo "	return cinr;\n"; 
echo "}\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "function removeRowFromTable(rowIdx)\n"; 
echo "{\n"; 
echo "	updateAllRow();\n"; 
echo "	removeAllRow();\n"; 
echo "	tData.remove(rowIdx);\n"; 
echo "\n"; 
echo "	for(var i=0;i<tData.length;i++)\n"; 
echo "		addRowToTable(tData[i]);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function removeAllRow()\n"; 
echo "{\n"; 
echo "	var lastRow = tbl.rows.length;  \n"; 
echo "	for(var i=1;i<lastRow ;i++)\n"; 
echo "		tbl.deleteRow(lastRow - i);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function edit()\n"; 
echo "{\n"; 
echo "	GO(\"btnEdit\").style.visibility = \"hidden\";\n"; 
echo "	GO(\"clear_btn\").style.visibility = \"visible\";\n"; 
echo "	GO(\"submit_btn\").style.visibility = \"visible\";\n"; 
echo "	GO(\"ch1_insert\").style.visibility = \"visible\";\n"; 
echo "	var thDel = GO(\"ch1\").rows.item(0).insertCell(5).innerHTML = \"<b>Delete</b>\";\n"; 
echo "\n"; 
echo "	rdOnly = false;\n"; 
echo "	create_table();\n"; 
echo "	if (ie6flag) showAllSelect();\n"; 
echo "}\n"; 
echo "\n"; 
echo "function ajax_get_wimax()\n"; 
echo "{\n"; 
echo "	top.$.ajax(\n"; 
echo "		{\n"; 
echo "			url:\"ajax.php\",\n"; 
echo "			data:{\n"; 
echo "				action:\"tag_get_wimax_scanner\",\n"; 
echo "				cache:false,\n"; 
echo "				time:(new Date()).getTime()\n"; 
echo "			},\n"; 
echo "			success:function(response){\n"; 
echo "				var token = response.split(\";\");\n"; 
echo "				eval(\"t1=\"+token[0]);\n"; 
echo "				eval(\"visible_network_list=\"+token[1]);\n"; 
echo "				ssState = token[2];\n"; 
echo "				InitValue(document.forms[0]);\n"; 
echo "			},\n"; 
echo "			timeout:2000,\n"; 
echo "			error:function(xhr)\n"; 
echo "			{\n"; 
echo "				location.reload();\n"; 
echo "			}\n"; 
echo "		}\n"; 
echo "	);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function startSs()\n"; 
echo "{\n"; 
echo "	top.$.ajax(\n"; 
echo "		{\n"; 
echo "			url:\"ajax.php\",\n"; 
echo "			data:{\n"; 
echo "				action:\"tag_startSs\",\n"; 
echo "				cache:false,\n"; 
echo "				time:(new Date()).getTime()\n"; 
echo "			},\n"; 
echo "			beforeSend:function(xhr){\n"; 
echo "				GO(\"btnStartSs\").disabled = true;\n"; 
echo "				clearInterval(signal_ID);\n"; 
echo "			},\n"; 
echo "			success:function(response){\n"; 
echo "				GO(\"btnStopSs\").disabled = false;\n"; 
echo "				try{ajax_get_signals()}catch(e){}\n"; 
echo "				signal_ID = setInterval('ajax_get_signals()',2000);\n"; 
echo "			},\n"; 
echo "			timeout:2000,\n"; 
echo "			error:function(xhr)\n"; 
echo "			{\n"; 
echo "				location.reload();\n"; 
echo "			}\n"; 
echo "		}\n"; 
echo "	);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function stopSs()\n"; 
echo "{\n"; 
echo "	top.$.ajax(\n"; 
echo "		{\n"; 
echo "			url:\"ajax.php\",\n"; 
echo "			data:{\n"; 
echo "				action:\"tag_stopSs\",\n"; 
echo "				cache:false,\n"; 
echo "				time:(new Date()).getTime()\n"; 
echo "			},\n"; 
echo "			beforeSend:function(xhr){\n"; 
echo "				GO(\"btnStopSs\").disabled = true;\n"; 
echo "				clearInterval(signal_ID);\n"; 
echo "			},\n"; 
echo "			success:function(response){\n"; 
echo "				GO(\"btnStartSs\").disabled = false;\n"; 
echo "				try{ajax_get_signals()}catch(e){}\n"; 
echo "				signal_ID = setInterval('ajax_get_signals()',2000);\n"; 
echo "			},\n"; 
echo "			timeout:2000,\n"; 
echo "			error:function(xhr)\n"; 
echo "			{\n"; 
echo "				location.reload();\n"; 
echo "			}\n"; 
echo "		}\n"; 
echo "	);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function InitDisplay()\n"; 
echo "{\n"; 
echo "	tr_display(\"START_STOP_WIMAX\");\n"; 
echo "	tr_display(\"CHANNEL_TABLE\");\n"; 
echo "	tr_display(\"editScanner\");\n"; 
echo "	try{\n"; 
echo "		setTimeout(\"ajax_get_wimax()\",1000);\n"; 
echo "	}\n"; 
echo "	catch(e)\n"; 
echo "	{\n"; 
echo "		alert(\"SETTIMEOUT ERROR\");\n"; 
echo "	}\n"; 
echo "\n"; 
echo "}\n"; 
echo "\n"; 
echo "function InitValue(Form1)\n"; 
echo "{\n"; 
echo "	passForm = document.forms[0];\n"; 
echo "	if(pri_a(uitems[inner_url][\"START_STOP_WIMAX\"]))\n"; 
echo "	{\n"; 
echo "		if (ssState == \"0\")\n"; 
echo "			GO(\"btnStartSs\").disabled = false;\n"; 
echo "		else\n"; 
echo "			GO(\"btnStopSs\").disabled = false;\n"; 
echo "	}\n"; 
echo "	else\n"; 
echo "	{\n"; 
echo "		GO(\"btnStartSs\").disabled = true;\n"; 
echo "		GO(\"btnStopSs\").disabled = true;\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	if(!pri_a(uitems[inner_url][\"CHANNEL_TABLE\"]))\n"; 
echo "		Form1.btnEdit.disabled = true;\n"; 
echo "\n"; 
echo "	create_table();\n"; 
echo "	GO(\"btnEdit\").disabled = false;\n"; 
echo "\n"; 
echo "	try{ajax_get_signals()}catch(e){}\n"; 
echo "	signal_ID = setInterval('ajax_get_signals()',2000);\n"; 
echo "\n"; 
echo "	top.loading = 0;\n"; 
echo "}\n"; 
echo "\n"; 
echo "function create_table()\n"; 
echo "{\n"; 
echo "	tbl = GO(\"ch1\");\n"; 
echo "	removeAllRow();\n"; 
echo "	//tData1 = new tab_obj(t1).value;\n"; 
echo "	tData1 = t1;\n"; 
echo "	tData = tData1;\n"; 
echo "\n"; 
echo "	for(var i=0;i<tData1.length;i++)\n"; 
echo "		addRowToTable(tData1[i]);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function Validate()\n"; 
echo "{\n"; 
echo "	var Freqlist=\"\";\n"; 
echo "	var Bwlist=\"10000\";\n"; 
echo "	var ListLen=0;\n"; 
echo "	for(var i=0;i<tData.length;i++) {\n"; 
echo "		if(!CheckNum(eval(\"passForm.Freq_\"+i+\".value\")))\n"; 
echo "		{\n"; 
echo "			alert(\"Invalide Number\");\n"; 
echo "			eval(\"passForm.Freq_\"+i+\".select()\");\n"; 
echo "			return ;\n"; 
echo "		}\n"; 
echo "		if(i == 0)\n"; 
echo "		{\n"; 
echo "			Freqlist += eval(\"passForm.Freq_\"+i+\".value\");\n"; 
echo "			Bwlist += \"-\" + eval(\"passForm.BW_\"+i+\".value\");\n"; 
echo "		}else{\n"; 
echo "			Freqlist += \"a\" + eval(\"passForm.Freq_\"+i+\".value\");\n"; 
echo "			Bwlist += \"a\" + eval(\"passForm.BW_\"+i+\".value\");\n"; 
echo "		}\n"; 
echo "	}\n"; 
echo "	if(tData.length) ListLen = tData.length;\n"; 
echo "\n"; 
echo "	if (ssState == \"1\")\n"; 
echo "	{\n"; 
echo "		hideAllSelect();\n"; 
echo "		GO(\"wimax_mask\").style.display = GO(\"wimax_alert\").style.display = \"\";\n"; 
echo "	}\n"; 
echo "	ajax_set_wimax(Freqlist,Bwlist,ListLen);\n"; 
echo "}\n"; 
echo "\n"; 
echo "\n"; 
echo "function ajax_set_wimax(Freqlist,Bwlist,ListLen)\n"; 
echo "{\n"; 
echo "	var Freq = new Array(32);\n"; 
echo "	var BW = new Array(32);\n"; 
echo "\n"; 
echo "	for(var i=0;i<32;i++) {\n"; 
echo "		if(GO(\"Freq_\"+i))\n"; 
echo "			Freq[i] = GO(\"Freq_\"+i).value;\n"; 
echo "		else\n"; 
echo "			Freq[i] = \"\";\n"; 
echo "\n"; 
echo "\n"; 
echo "		if(GO(\"BW_\"+i))\n"; 
echo "			BW[i] = GO(\"BW_\"+i).value;\n"; 
echo "		else\n"; 
echo "			BW[i] = \"\";\n"; 
echo "	}\n"; 
echo "\n"; 
echo "	top.$.ajax(\n"; 
echo "		{\n"; 
echo "			url:\"ajax.php\",\n"; 
echo "			data:{\n"; 
echo "				action:\"ajax_set_wimax_scanner\",\n"; 
echo "				type:\"POST\",\n"; 
echo "				sid:sid,\n"; 
echo "				ListLen:ListLen,\n"; 
echo "				WMX_FREQ_LIST:Freqlist,\n"; 
echo "				WMX_BW_LIST:Bwlist,\n"; 
echo "				Freq_0:Freq[0],BW_0:BW[0],\n"; 
echo "				Freq_1:Freq[1],BW_1:BW[1],\n"; 
echo "				Freq_2:Freq[2],BW_2:BW[2],\n"; 
echo "				Freq_3:Freq[3],BW_3:BW[3],\n"; 
echo "				Freq_4:Freq[4],BW_4:BW[4],\n"; 
echo "				Freq_5:Freq[5],BW_5:BW[5],\n"; 
echo "				Freq_6:Freq[6],BW_6:BW[6],\n"; 
echo "				Freq_7:Freq[7],BW_7:BW[7],\n"; 
echo "				Freq_8:Freq[8],BW_8:BW[8],\n"; 
echo "				Freq_9:Freq[9],BW_9:BW[9],\n"; 
echo "				Freq_10:Freq[10],BW_10:BW[10],\n"; 
echo "				Freq_11:Freq[11],BW_11:BW[11],\n"; 
echo "				Freq_12:Freq[12],BW_12:BW[12],\n"; 
echo "				Freq_13:Freq[13],BW_13:BW[13],\n"; 
echo "				Freq_14:Freq[14],BW_14:BW[14],\n"; 
echo "				Freq_15:Freq[15],BW_15:BW[15],\n"; 
echo "				Freq_16:Freq[16],BW_16:BW[16],\n"; 
echo "				Freq_17:Freq[17],BW_17:BW[17],\n"; 
echo "				Freq_18:Freq[18],BW_18:BW[18],\n"; 
echo "				Freq_19:Freq[19],BW_19:BW[!9],\n"; 
echo "				Freq_20:Freq[20],BW_20:BW[20],\n"; 
echo "				Freq_21:Freq[21],BW_21:BW[21],\n"; 
echo "				Freq_22:Freq[22],BW_22:BW[22],\n"; 
echo "				Freq_23:Freq[23],BW_23:BW[23],\n"; 
echo "				Freq_24:Freq[24],BW_24:BW[24],\n"; 
echo "				Freq_25:Freq[25],BW_25:BW[25],\n"; 
echo "				Freq_26:Freq[26],BW_26:BW[26],\n"; 
echo "				Freq_27:Freq[27],BW_27:BW[27],\n"; 
echo "				Freq_28:Freq[28],BW_28:BW[28],\n"; 
echo "				Freq_29:Freq[29],BW_29:BW[29],\n"; 
echo "				Freq_30:Freq[30],BW_30:BW[30],\n"; 
echo "				Freq_31:Freq[31],BW_31:BW[31],\n"; 
echo "				cache:false,\n"; 
echo "				time:(new Date()).getTime()\n"; 
echo "			},\n"; 
echo "			success:function(response){\n"; 
echo "				location.reload();\n"; 
echo "			},\n"; 
echo "			timeout:2000,\n"; 
echo "			error:function(xhr)\n"; 
echo "			{\n"; 
echo "				location.reload();\n"; 
echo "			}\n"; 
echo "		}\n"; 
echo "	);\n"; 
echo "}\n"; 
echo "\n"; 
echo "-->\n"; 
echo "</script>\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body onload=\"init_obj();InitDisplay();\">\n"; 
echo "\n"; 
echo "	<div id=\"wimax_mask\" style=\"display:none;position:absolute;top:0px;width:780px;height:574px;background-color:gray;visibility: visible;filter:alpha(opacity=40);-moz-opacity:0.4;opacity:0.4;z-index:3000;text-align:center;\"></div>\n"; 
echo "\n"; 
echo "<div id=\"wimax_alert\" style=\"display:none;position:absolute;top:50px;left:100px;width:150px;height:150px;color:white;visibility: visible;z-index:3000;text-align:center;\"><font size=\"8\">WiMAX Reconnecting....</font></div>\n"; 
echo "\n"; 
echo "<div id=\"main_div\">\n"; 
echo "	<div id=\"container\">\n"; 
echo "		<FIELDSET>\n"; 
echo "			<legend>Start/Stop WiMAX</legend>\n"; 
echo "				<table><tr id=\"TR_START_STOP_WIMAX\" style=\"display:none\"><td>\n"; 
echo "				<input type=\"button\" id=\"btnStartSs\" value=\"Start\" disabled onclick=\"startSs()\">\n"; 
echo "				<input type=\"button\" id=\"btnStopSs\" value=\"Stop\" disabled onclick=\"stopSs()\">\n"; 
echo "				</td></tr></table>\n"; 
echo "		</FIELDSET>\n"; 
echo "		<FIELDSET>\n"; 
echo "			<legend>Channel Table</legend>\n"; 
echo "		<form name=\"form1\" method=\"POST\" action=\"ajax.php?action=wimax_scanner\">\n"; 
echo "			<table><tr id=\"TR_CHANNEL_TABLE\" style=\"display:none\"><td>\n"; 
echo "			<table>\n"; 
echo "				<tr id=\"TR_editScanner\" style=\"display:none\"><td colspan=\"2\"><input type=\"button\" name=\"btnEdit\" id=\"btnEdit\" value=\"Edit\" disabled onclick=\"edit()\"></td></tr>\n"; 
echo "				<tr><td colspan=\"2\">\n"; 
echo "\n"; 
echo "		<table id=\"ch1\" class=\"pf_tbl\" cellpadding=\"5\" style=\"margin:0px;width:80%;text-align:center\">\n"; 
echo "		<tr>\n"; 
echo "			<td><b>No.</b></td>\n"; 
echo "			<td><b>Frequency</b></td>\n"; 
echo "			<td><b>Bandwidth</b></td>\n"; 
echo "			<td><b>RSSI(dBm)</b></td>\n"; 
echo "			<td><b>CINR(dB) R3/R1</b></td>\n"; 
echo "		</tr>\n"; 
echo "		</table></table>\n"; 
echo "		</td></tr></table>\n"; 
echo "		<input type=\"button\" id=\"ch1_insert\" value=\"Insert\" style=\"visibility:hidden\" onclick=\"ins()\">\n"; 
echo "		</form>\n"; 
echo "		</FIELDSET>\n"; 
echo "	</div>\n"; 
echo "<div>\n"; 
echo "	<table style=\"width:600px;height:25px;text-align:center\">\n"; 
echo "		<tr>\n"; 
echo "			<td width=\"210\"></td>\n"; 
echo "			<td id=\"clear_btn\" class=\"td_btn\" style=\"visibility:hidden\" onclick=\"location.reload()\">Undo</td>\n"; 
echo "			<td width=\"30\"></td>\n"; 
echo "			<td id=\"submit_btn\" class=\"td_btn\" style=\"visibility:hidden\" onclick=\"Validate()\">Apply</td>\n"; 
echo "			<td width=\"210\"></td>\n"; 
echo "		</tr>\n"; 
echo "	</table>\n"; 
echo "</div>\n"; 
echo "</div>\n"; 
echo "</body>\n"; 
echo "</html>\n";
?>